### ISSUE TITLE
A problem appeared when i run quick-start-Realtime.sh

### ISSUE THREAD

**Issue by ChenJianJunCJJ** [apache/pinot#100]
The whole cluster(zookeeper, kafka, pinot broker, pinot server, pinot controller) can be start. 
"netstat -npl|grep java "shows that port:2191,2123,19092,7000,8000,9000 are open. 
Pinot broker return "null", when i send a query.

```
{
    "traceInfo": {},
    "numDocsScanned": 0,
    "aggregationResults": [],
    "timeUsedMs": 0,
    "segmentStatistics": [],
    "exceptions": [],
    "totalDocs": 0
}
```

Are there some where delay time should be longer?

**Comment by kishoreg** [comment]
Can you run pinot-admin.sh showClusterInfo

**Comment by ChenJianJunCJJ** [comment]
The Cluster Info is:
`Opening socket connection to server localhost/127.0.0.1:2123
Socket connection established to localhost/127.0.0.1:2123, initiating session
Session establishment complete on server localhost/127.0.0.1:2123, sessionid = 0x153ea9f87d50009, negotiated timeout = 30000
zookeeper state changed (SyncConnected)
Connecting to Zookeeper at: localhost:2123
!!com.linkedin.pinot.tools.admin.command.ShowClusterInfoCommand$ClusterInfo
brokerInfoList:
- name: Broker_192.168.170.155_7000
  state: ONLINE
  tags: [DefaultTenant_BROKER]
clusterName: QuickStartCluster
controllerInfo: {leaderName: 192.168.170.155_9000}
serverInfoList:
- name: Server_192.168.170.155_8000
  state: ONLINE
  tags: [DefaultTenant_OFFLINE, DefaultTenant_REALTIME]
tableInfoList:
- segmentInfoList: []
  tableName: meetupRsvp_REALTIME
  tag: meetupRsvp_REALTIME
`
There are another zookeeper too,  it`s address is "localhost:2191".

Thanks!

**Comment by ChenJianJunCJJ** [comment]
I find two zookeeper started. The one`s address is "localhost:2191", another`s "localhost:2123".
Kafka start in "localhost:2191", Pinot cluster start in  "localhost:2123".It sames Kafka and Pinot cluster not in the same zookeeper.It is that OK?

`   
_zookeeperInstance = ZkStarter.startLocalZkServer();// "localhost:2191"

    final KafkaServerStartable kafkaStarter =
        KafkaStarterUtils.startServer(KafkaStarterUtils.DEFAULT_KAFKA_PORT, KafkaStarterUtils.DEFAULT_BROKER_ID,
            KafkaStarterUtils.DEFAULT_ZK_STR, KafkaStarterUtils.getDefaultKafkaConfiguration());
`

but

`
  public void startAll() throws Exception {
    StartZookeeper();//"localhost:2123"
    StartController();
    StartBroker();
    StartServer();
  }
`

**Comment by kishoreg** [comment]
There should be only one zookeeper started at 2123. Can you print the
output of ./quick-start-realtime.sh.

**Comment by ChenJianJunCJJ** [comment]
````````
if [ -z "$JAVA_OPTS" ] ; then
  ALL_JAVA_OPTS="-Xms1G -Xmx1G -Dlog4j.configuration=conf/quickstart-realtime-log4j.properties"
else
  ALL_JAVA_OPTS=$JAVA_OPTS
fi

exec "$JAVACMD" $ALL_JAVA_OPTS \
  -classpath "$CLASSPATH" \
  -Dapp.name="quick-start-realtime" \
  -Dapp.pid="$$" \
  -Dapp.repo="$REPO" \
  -Dapp.home="$BASEDIR" \
  -Dbasedir="$BASEDIR" \
  com.linkedin.pinot.tools.RealtimeQuickStart \
  "$@"
````````````````````````````

**Comment by ChenJianJunCJJ** [comment]
It can`t work also, when i was try to started realtime flow with script. I followed tutorial:[https://github.com/linkedin/pinot/wiki/How-To-Use-Pinot](url)
Here is my step:

`````````````````
bin/pinot-admin.sh StartZookeeper &

bin/pinot-admin.sh StartController &

bin/pinot-admin.sh StartBroker &

bin/pinot-admin.sh StartServer &

bin/pinot-admin.sh AddSchema -schemaFile flights-schema.json –exec

bin/pinot-admin.sh AddTable -filePath flights-definition.json -exec

bin/pinot-admin.sh StartKafka &

bin/pinot-admin.sh StreamAvroIntoKafka -avroFile flights-2014.avro -kafkaTopic flights-realtime &
``````````````````````````````

When i posted a query to pinot broker ,pinot return null.
