### ISSUE TITLE
The function lastwithtime throws an exception when the applied column has Japanese characters

### ISSUE THREAD

**Issue by huaheh** [apache/pinot#10061]
The exception is 

execute query error: QueryExecutionError: java.lang.RuntimeException: Caught exception while building data table. at org.apache.pinot.core.operator.blocks.InstanceResponseBlock.<init>(InstanceResponseBlock.java:46) at org.apache.pinot.core.operator.InstanceResponseOperator.getNextBlock(InstanceResponseOperator.java:118) at org.apache.pinot.core.operator.InstanceResponseOperator.getNextBlock(InstanceResponseOperator.java:39) at org.apache.pinot.core.operator.BaseOperator.nextBlock(BaseOperator.java:39) ... Caused by: java.nio.BufferOverflowException at java.base/java.nio.HeapByteBuffer.put(HeapByteBuffer.java:221) at java.base/java.nio.ByteBuffer.put(ByteBuffer.java:914) at org.apache.pinot.segment.local.customobject.StringLongPair.toBytes(StringLongPair.java:46) at org.apache.pinot.core.common.ObjectSerDeUtils$11.serialize(ObjectSerDeUtils.java:438)

In our case, lastwithtime is applied to a column that stores SQL-like string. The exception is thrown when the column has a value such as 
`select Account.Id, Account.Name, Account.CrmId, Account.Status, Account.AccountNumber, Account.restaurant_id__c, Account.yoshin_kanricd__c from Account where (((((((CrmId is null or CrmId = '') and Status = 'Active') and ((account_p__c = '事業者' or account_p__c = '再販事業者') or account_p__c = 'TSP事業者')) and (ParentId is null or ParentId = '')) and Account.CreatedDate <= '2023-01-05T09:55:00') and Account.yoshin_kanricd__c is not null) and Account.yoshin_kanricd__c != '')`

**Comment by Jackie-Jiang** [comment]
This is fixed in #9985, and will be released in `0.12.0`
