### ISSUE TITLE
Segment build fails with null value for time column

### ISSUE THREAD

**Issue by elonazoulay** [apache/pinot#10073]
Happy New Year!
We noticed that creating a segment fails due to TimeUtils.VALID_MIN_TIME_MILLIS being 1971/01/01 instead of 1970/01/01, i.e. 0 epoch millis. Is this intended?

Context:
The TimeUtils.isValidInterval check fails. This is invoked by SegmentColumnarIndexCreator.writeMetadata (if skip check is enabled) and always invoked by PinotSegmentUploadDownloadRestletResource.uploadSegment.

Is this intentional or should the min time be changed?

**Comment by Jackie-Jiang** [comment]
It is intentional to prevent users from putting the wrong time unit.
E.g. if the time value is `daysSinceEpoch`, but user mistakenly put `MILLISECONDS` as the time unit, this validation will fail and can catch this error.

**Comment by elonazoulay** [comment]
Ah ok, thanks! So how does someone insert values where the epoch milli is 0? It fails the validation.

**Comment by Jackie-Jiang** [comment]
One workaround would be to turn the validation off (there is a flag in table config). But in regular case people should not ingest records with timestamp in 1970. The underlying logic is that there should be no data generated in 1970.

**Comment by elonazoulay** [comment]
Thanks for responding @Jackie-Jiang !  I tried that and create segment is fine but upload segment still invokes the check regardless. lmk what you think: would it be worth it to add a flag to upload segment or keep the behavior about 1970? We have a use case where "0" is inserted into our datawarehouse data but have to filter it out in pinot.

**Comment by elonazoulay** [comment]
@Jackie-Jiang update: inserting null values for both timestamp and timestamp arrays results in epoch millis 0, i.e. 1970-01-01 00:00:00.000 - so that can be used to bypass the min value check. Is that intended? 
So behavior looks like it's:
0 <= input_ts < epochMiillis(1971-01-01 00:00:00.000) -> error
input_ts = null -> 1970-01-01 00:00:00.000
input_ts > epochMiillis(1971-01-01 00:00:00.000) -> input_ts
Is that correct?

**Comment by Jackie-Jiang** [comment]
Can you check if `null` is filled with 1970-01-01? It shouldn't be the case though. If default value is not provided, we will fill `null` with the current time, and that's why it might pass the value check.
We put this restriction on the time column because it is used to determine whether a segment is expired, or can be pruned.
Do you think you can put `null` in the source data, and put a very old default value (e.g. 1980)?

**Comment by elonazoulay** [comment]
It is not. Just did a test inserting null for the time column. Also tested realtime: it allows null value for the time column.

**Comment by Jackie-Jiang** [comment]
No. Ideally we don't want any time value < 1971-01-01
Are you using the latest version pinot library for the offline ingestion? There should be a check on the time column value range (in `SegmentColumnarIndexCreator.writeMetadata()`). Do you have time column configured in the offline table config?

**Comment by elonazoulay** [comment]
Thanks @Jackie-Jiang ! Yep, the `isValidTimeInterval` is where the validation fails (as expected).
