### ISSUE TITLE
add array_join for multi-valued column

### ISSUE THREAD

**Issue by weixiangsun** [apache/pinot#10113]
I try to support the array_join function similar to https://prestodb.io/docs/current/functions/array.html

array_join(x, delimiter, null_replacement) → varchar[#](https://prestodb.io/docs/current/functions/array.html#array_join)
Concatenates the elements of the given array using the delimiter and an optional string to replace nulls.

**Comment by monicaluodialpad** [comment]
Hey, I am also looking for the similarity of LISTAGG : https://stackoverflow.com/questions/43931929/aggregate-string-values-to-a-list
Or agg function for multi-value column that also return a combined list.

**Comment by Jackie-Jiang** [comment]
#14537 added the scalar function (ARRAY_TO_STRING) to join array into a string
#13146 added the LIST_AGG support

**Comment by monicaluodialpad** [comment]
@Jackie-Jiang Thank you. Do we have LISTAGG documentation on Pinot's official website?
