### ISSUE TITLE
[multistage] Aggregation Query with No Grouping Sets Returns Empty Response

### ISSUE THREAD

**Issue by ankitsultana** [apache/pinot#10124]
When we run an aggregation query without any grouping-sets, if no rows match the operators under the aggregation then the result is empty. Example:

```
select
  count(*)
from
  baseballStats_OFFLINE
WHERE
  playerID IN (
    select
      playerID
    from
      baseballStats_OFFLINE
    where
      teamID = 'foo'
  )
```

The expected behavior here would be to receive a single row `[0]` but instead we don't get any rows.

For the case when a stage does a full aggregate (as opposed to a partial aggregate), if there's no grouping key we may want to assign only 1 worker for that stage since otherwise it may be hard to ensure that stages above the full aggregate stage receive exactly 1 row which contains all the aggregation functions.

Opening this issue for discussing any other solutions.

cc: @walterddr @siddharthteotia

**Comment by walterddr** [comment]
yes there's a feature missing in the AggregationOperator where when `_groupByKeyHolder` is empty and `_groupSet` is also empty we should return single row instead of empty row.

**Comment by walterddr** [comment]
did a bit of research in https://github.com/apache/pinot/commit/18316a3047ba11ac7376719dc5315c0ea948cfd4
it is a bit tricky b/c we rely on the empty row results for distributed global agg/sort to produce correct results (e.g. all data funnel through first server while the rest returns directly EOS) 
so in order for this change to merge we also need to make an adjustment for the final aggregation or change the reducer in QueryDispatcher.

**Comment by siddharthteotia** [comment]
I didn't mean to close this issue. Just merged the other PR and this automatically got closed. Please feel free to reopen this if needed.

**Comment by walterddr** [comment]
this should be closed. the PR #10222 verifies it
