### ISSUE TITLE
[multistage] Expensive RoundRobinScheduler::hasNext Calls

### ISSUE THREAD

**Issue by ankitsultana** [apache/pinot#10140]
**Context**

When the `Monitor` in `RoundRobinScheduler` leaves, it will call `Monitor#signalNextWaiter` which will call `RoundRobinScheduler#hasNext` since the `signalNextWaiter` method iterates over all the guards for the given monitor and checks if they are satisfied.

Now the `hasNext` method tries to re-compute the _ready queue every time it is called.

**What we are seeing internally**

We looked at one of our servers which was having memory issues and took thread-dumps over a period of few minutes. We found that all the QueryWorker threads are always waiting on acquiring the Guard:

```
"query_worker_on_8421_port-1-thread-1" #2871 prio=5 os_prio=0 cpu=135674.67ms elapsed=69632.90s tid=0x00007ee398016000 nid=0xd24 waiting on condition  [0x00007ef0a8758000]
   java.lang.Thread.State: WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@11.0.15/Native Method)
--
"query_worker_on_8421_port-1-thread-2" #2882 prio=5 os_prio=0 cpu=101003.62ms elapsed=69629.03s tid=0x00007ee398017000 nid=0xd30 waiting on condition  [0x00007e9974377000]
   java.lang.Thread.State: WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@11.0.15/Native Method)
--
...
```

There's always one thread which is trying to compute the ready queue.

```
"grpc-default-executor-37238" #54551 daemon prio=5 os_prio=0 cpu=2507.80ms elapsed=14701.97s tid=0x00007edbb0234000 nid=0xd955 runnable  [0x00007edcbddb1000]
   java.lang.Thread.State: RUNNABLE
        at java.util.HashMap.hash(java.base@11.0.15/HashMap.java:340)
        at java.util.HashMap.containsKey(java.base@11.0.15/HashMap.java:592)
        at java.util.HashSet.contains(java.base@11.0.15/HashSet.java:204)
        at java.util.Collections.disjoint(java.base@11.0.15/Collections.java:5465)
        at com.google.common.collect.Sets$2.isEmpty(Sets.java:871)
        at org.apache.pinot.query.runtime.executor.RoundRobinScheduler.computeReady(RoundRobinScheduler.java:147)
```

The number of threads can increase quite a lot, since the callback is called in `MailboxContentStreamObserver` which uses grpc default executor (which seems unbounded?).

```
❯❯❯ cat 2.thdump| grep "Monitor.enter" | wc -l
    4227
...
❯❯❯ cat 6.thdump| grep "Monitor.enter" | wc -l
   10658
...
❯❯❯ cat 7.thdump| grep "Monitor.enter" | wc -l
   13802
...
❯❯❯ cat 7.thdump| grep "grpc-default-executor" | wc -l
   13712  <<== number of grpc-default-executor threads
```

cc: @agavra @walterddr

**Comment by ankitsultana** [comment]
@agavra : Also, do you think we can have default scheduler release timeout of a few minutes? The scenario where the stages have been dispatched and one of the stages dies, leading to no data to the ancestor stages can be quite common.

At present since the default is -1, we accumulate these OpChains in the queue and never remove them. Would be great if these are removed in a few minutes by default given how commonly we could run into such issues.

<img width="796" alt="image" src="https://user-images.githubusercontent.com/8644710/213214997-9e35255c-24f9-4f88-9f3b-3e12d3986b50.png">

**Comment by agavra** [comment]
Nice catch @ankitsultana - for your second question, we might want to make the default be the default query timeout x2 or something like that. That way it only gets triggered to clean up queries that would have timed out anyway. The point of keeping it infinite was exactly to catch these kind of bugs.

**Comment by agavra** [comment]
I think we might want to make `onDataAvailable` non-blocking (e.g. doesn't go through `_monitor`). That makes it much more complicated and error prone for the implementation (e.g. `_seenMail` in `RoundRobinScheduler` needs to handle concurrent read/writes). 

Separately, we should also see if we can bound the GRPC worker threads (cc @61yao as well since you've been looking into improving the way we use GRPC) - I don't think there's ever a good reason to have that many of them.

**Comment by ankitsultana** [comment]
Side-note: I think entries in seenMail may get leaked if `_releaseTs` is set to a finite value. The reason is that the OpChain may hang up and the sender may send the data after the corresponding OpChain has already finished as far as the scheduler is considered. It's only a small leak but a leak nevertheless.

Broadly speaking I think we need to gracefully handle the cases where a sender is ready to send data to a stage but the receiver either hasn't been registered yet or has already hung up.

> Separately, we should also see if we can bound the GRPC worker threads

+1
