### ISSUE TITLE
[multistage] [debuggability] Return meaningful error msg for unsupported type

### ISSUE THREAD

**Issue by 61yao** [apache/pinot#10205]
For example, today, the error msg is below when the column type is json.

It is better we print out "json is not supported"

[
  {
    "message": "SQLParsingError:\njava.lang.RuntimeException: Error composing query plan for: select ID from testRecords\n\tat org.apache.pinot.query.QueryEnvironment.planQuery(QueryEnvironment.java:143)\n\tat org.apache.pinot.broker.requesthandler.MultiStageBrokerRequestHandler.handleRequest(MultiStageBrokerRequestHandler.java:157)\n\tat org.apache.pinot.broker.requesthandler.MultiStageBrokerRequestHandler.handleRequest(MultiStageBrokerRequestHandler.java:132)\n\tat org.apache.pinot.broker.requesthandler.BrokerRequestHandler.handleRequest(BrokerRequestHandler.java:47)\n...\nCaused by: java.lang.UnsupportedOperationException: unsupported!\n\tat org.apache.pinot.query.type.TypeFactory.toRelDataType(TypeFactory.java:82)\n\tat org.apache.pinot.query.type.TypeFactory.createRelDataTypeFromSchema(TypeFactory.java:49)\n\tat org.apache.pinot.query.catalog.PinotTable.getRowType(PinotTable.java:49)\n\tat org.apache.calcite.sql.validate.EmptyScope.resolve_(EmptyScope.java:161)",
    "errorCode": 150
  }
]

**Comment by abhioncbr** [comment]
I am taking up this issue. thanks

**Comment by kishoreg** [comment]
We should support it.. and use String for json

**Comment by abhioncbr** [comment]
We can close this issue. Thanks
