### ISSUE TITLE
jvm options ( such as Xmx for example ) used by pinot processes should be logged

### ISSUE THREAD

**Issue by thatran** [apache/pinot#10218]
jvm options ( such as Xmx for example ) used by pinot processes should be logged.  Currently, the only way to tell what Xmx pinot is using is to do a ps and grep on the result.  But, that's for a currently running process.  For past jvm options used, it is difficult, if not impossible to tell what Xmx and other jvm options were used for the pinot process.

**Comment by thatran** [comment]
EDIT - not just jvm options but whatever other options are used to start the pinot process

**Comment by abhioncbr** [comment]
Please assign this issue to me. Thanks

**Comment by abhioncbr** [comment]
Here is the [PR](https://github.com/apache/pinot/pull/10446) for the change.

**Comment by swaminathanmanish** [comment]
@thatran - You could also use this swagger api to get the jvm configs

curl -X GET "http://localhost:9000/appconfigs" -H "accept: application/json"

jvmConfig": { "args": [ "-javaagent:/Applications/IntelliJ IDEA CE.app/Contents/lib/idea_rt.jar=50367:/Applications/IntelliJ IDEA CE.app/Contents/bin", "-Dfile.encoding=UTF-8" ], "garbageCollectors": [ "G1 Young Generation", "G1 Old Generation" ], "envVariables": { "__CFBundleIdentifier": "com.jetbrains.intellij.ce", "PATH": "/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin", "SHELL": "/bin/zsh", "MANPATH": "/opt/homebrew/share/man::", "HOMEBREW_CELLAR": "/opt/homebrew/Cellar", "OLDPWD": "/", "USER": "manishswaminathan", "HOMEBREW_PREFIX": "/opt/homebrew", "COMMAND_MODE": "unix2003", "TMPDIR": "/var/folders/xj/yl13brv573g9_v_vhxx7knx00000gn/T/", "SSH_AUTH_SOCK": "/private/tmp/com.apple.launchd.lyuZIHVl7g/Listeners", "XPC_FLAGS": "0x0", "__CF_USER_TEXT_ENCODING": "0x1F5:0x0:0x0", "LOGNAME": "manishswaminathan", "LC_CTYPE": "en_US.UTF-8", "HOMEBREW_REPOSITORY": "/opt/homebrew", "JAVA_MAIN_CLASS_1666": "org.apache.pinot.tools.Quickstart", "PWD": "/Users/manishswaminathan/projects/forked/pinot", "XPC_SERVICE_NAME": "application.com.jetbrains.intellij.ce.975373.976077", "INFOPATH": "/opt/homebrew/share/info:", "HOME": "/Users/manishswaminathan" },
