### ISSUE TITLE
Avoid PinotFS::listFiles Call in Realtime Segment Commit Flow

### ISSUE THREAD

**Issue by ankitsultana** [apache/pinot#10243]
At present we make a `PinotFS::listFiles` call in the segment commit flow. This is done in `PinotLLCRealtimeSegmentManager`

https://github.com/apache/pinot/blob/master/pinot-controller/src/main/java/org/apache/pinot/controller/helix/core/realtime/PinotLLCRealtimeSegmentManager.java#L494

For realtime tables with high ingestion throughput, the segment commits are quite frequent (100s per minute). For such tables the number of segments is also high (10s of thousands), making this listFiles call costly. This not only can impact ingestion latency but also put pressure on the underlying FS used by PinotFS.

Edit: Description of the issue and the proposal for the fix here: https://docs.google.com/document/d/18PqeN7eUP9Yc2MqwihSrGMmadJ3nuDsrcWf6F_ks_hQ/edit#

cc: @Jackie-Jiang

**Comment by ankitsultana** [comment]
Wrote a quick proposal and description of the issue: https://docs.google.com/document/d/18PqeN7eUP9Yc2MqwihSrGMmadJ3nuDsrcWf6F_ks_hQ/edit#

cc: @Jackie-Jiang

**Comment by mcvsubbu** [comment]
@ankitsultana can you open the doc for comments please?

**Comment by ankitsultana** [comment]
@mcvsubbu : Done. Can you check now?

**Comment by wirybeaver** [comment]
Already talk with Ankit and attempted to solve this issue to mitigate the shortage of HDFS quota.

**Comment by wirybeaver** [comment]
Created a related issue in terms of the PinotFS interface description. https://github.com/apache/pinot/issues/11491
