### ISSUE TITLE
Enabling ingress V1 in helm chart does not work

### ISSUE THREAD

**Issue by piby180** [apache/pinot#10249]
If ingress.v1beta1.enabled is False and ingress.v1.enabled is True, no ingress rule gets deployed. This is because if condition at Line 1 [here](https://github.com/apache/pinot/blob/master/kubernetes/helm/pinot/templates/broker/ingress.yaml) disables the entire file. 

Ingress rules should be placed in separate files.

**Comment by Jackie-Jiang** [comment]
cc @xiangfu0

**Comment by abhioncbr** [comment]
Please assign the issue to me. Thanks

**Comment by abhioncbr** [comment]
Hi, here is the [PR](https://github.com/apache/pinot/pull/10367)
