### ISSUE TITLE
[Feature] Null support in Pinot

### ISSUE THREAD

**Issue by 61yao** [apache/pinot#10252]
Design doc:
https://docs.google.com/document/d/1w2eBuZrS73xE2JIw8MYlySy5pNaX9iE8kZr_YAL20CM/edit

[x ] Correctly pass null in thrift (https://github.com/apache/pinot/pull/10217)
[x]  Get the null value in LiteralTransform func (https://github.com/apache/pinot/pull/10376, https://github.com/apache/pinot/pull/10380)
[ ]  Support null in transform functions (https://github.com/apache/pinot/pull/10386, https://github.com/apache/pinot/pull/10579, https://github.com/apache/pinot/pull/10562, 
https://github.com/apache/pinot/pull/10545, https://github.com/apache/pinot/pull/10563, https://github.com/apache/pinot/pull/10575, https://github.com/apache/pinot/pull/10594, https://github.com/apache/pinot/pull/10598, https://github.com/apache/pinot/pull/10613)
[ ] Null support in aggregations
[ ] Null support in sort operator 
[ ] Null support in group by operator 
[ ] Null support in filter operator

**Comment by 61yao** [comment]
@Jackie-Jiang

**Comment by abhioncbr** [comment]
Hi @61yao, Can I pick up the work for Null support in the conditional operator? I would like to give it a try, It's related to 1053

**Comment by 61yao** [comment]
@abhioncbr conditional operator work hasn't started. If you are interested in case when, you can take a look at case when transform functions. Let me know if you have any questions. The project is kinda urgent. If you can send a PR within next two weeks, I am happy to take some of your help. :)

**Comment by abhioncbr** [comment]
Thanks, @61yao; let me give it a try. I understand that it's time-sensitive, and I will share my updates.

**Comment by Jackie-Jiang** [comment]
Majority of them are already supported. Use #11802 to track the remaining items
