### ISSUE TITLE
Provide support for AWS Corretto and Microsoft JDK 11 

### ISSUE THREAD

**Issue by abhijeetkushe** [apache/pinot#10274]
Current Docker image of Pinot is built on OpenDJK 11.Open JDK 11 will end the active support from September 30. Please see https://endoflife.date/java 
![Screen Shot 2023-02-13 at 11 19 57 AM](https://user-images.githubusercontent.com/2093096/218563043-bf1a775c-567c-49bf-b964-f4c229f000ce.png)

Can Pinot start pushing official images for AWS corretto 11 and Microsoft JDK 11 for EKS on AWS or Azure users ?

**Comment by Jackie-Jiang** [comment]
cc @xiangfu0

**Comment by abhijeetkushe** [comment]
Any updates on this ?

**Comment by abhijeetkushe** [comment]
@xiangfu0  Our org does need to build a corretto imageJust wanted to see if I can help with story
Looking at the README it looks like existing dockerfile already supports modifying the Java distribution 
https://github.com/apache/pinot/tree/master/docker/images/pinot-base.If it is the case will i work if we just add another task for Corretto by passing env arg OPENJDK_IMAGE to [amazoncorretto](https://hub.docker.com/_/amazoncorretto). Or do you think we might need a new DockerFile
https://github.com/apache/pinot/blob/master/.github/workflows/build-pinot-docker-image.yml#L59-L67
cc @mayankshriv

**Comment by xiangfu0** [comment]
https://github.com/apache/pinot/pull/10422

**Comment by abhijeetkushe** [comment]
Closing issue as #10422 covers this

**Comment by xiangfu0** [comment]
https://github.com/apache/pinot/pull/10429

**Comment by abhijeetkushe** [comment]
@xiangfu0  I had opened a issue on bitnami for supporting corretto but they decided to not include that in their plans.So we might have to create a custom zookeeper with corretto
https://github.com/bitnami/containers/issues/27515#issuecomment-1473391641

**Comment by xiangfu0** [comment]
> @xiangfu0 I had opened a issue on bitnami for supporting corretto but they decided to not include that in their plans.So we might have to create a custom zookeeper with corretto [bitnami/containers#27515 (comment)](https://github.com/bitnami/containers/issues/27515#issuecomment-1473391641)

I believe this should still go with Zookeeper community to support the docker image to avoid the potential divergence.

Both bitnami and Pinot are the consumer of the Zookeeper docker image.

If your project has strict requirements on the JDK distribution, I would suggest to build the docker image by your self then wait for the response from the community.
