### ISSUE TITLE
Improve the trailing slash for S3

### ISSUE THREAD

**Issue by snleee** [apache/pinot#10271]
The following config will lead the wrong path for s3. The code should handle this more gracefullly.
```
controller.data.dir=s3://<bucket_name>/controller/
->
s3://<bucket_name>/controller//epoch_table/epoch_table__0__0__20230210T1100Z
```

**Comment by abhioncbr** [comment]
Please assign this issue to me.

**Comment by abhioncbr** [comment]
Here is the [PR](https://github.com/apache/pinot/pull/10395) for the fix. Please review. Thanks
