### ISSUE TITLE
API for Rebalance Status

### ISSUE THREAD

**Issue by suddendust** [apache/pinot#10313]
Currently, there's no way to check if the rebalance is complete without checking server logs. This is arduous, especially for tables that have a large no of segments. It'd be helpful to add an API that shows the rebalance status, just like the reload API. Thanks!

**Comment by suddendust** [comment]
I think this can be pretty similar to the reload API. During rebalance, we persist the rebalance config and the segments to monitor in ZK. When the status API is called, we can fetch the IS, the EV and check if they have converged (don't need to calculate the segments to move as it's already persisted in ZK). We can either respond with a yes or no, or can return the segments that have actually not converged yet. @Jackie-Jiang @saurabhd336 Does this sound like a correct approach? Thanks!

**Comment by swaminathanmanish** [comment]
I'll be looking into this and will take it up.

**Comment by Jackie-Jiang** [comment]
Rebalance is slightly different from reload because the target assignment (IS) can change multiple times with no-downtime settings, also if the IS changes while rebalancing, pinot will re-compute the target assignment.
To solve this, we can pass in a hook to the rebalancer, and let the rebalancer pass back the current rebalancing state. Only rebalancer knows the progress of the rebalance since IS can change dynamically.

**Comment by Jackie-Jiang** [comment]
cc @navina

**Comment by Jackie-Jiang** [comment]
This is duplicate with #9558

**Comment by suddendust** [comment]
@Jackie-Jiang But we can calculate the target and the current assigned when the API is invoked? We can just run a rebalance with `dryRun = true` and check the status?

**Comment by Jackie-Jiang** [comment]
> @Jackie-Jiang We can run a rebalance with `dryRun = true` and check the status when the API is invoked?

That is possible, but there is also a corner case as following:
1. Rebalance is triggered and finished
2. Some new segment is pushed/committed
3. Dry run gives a different result from the current assignment, but the rebalance is already done

**Comment by suddendust** [comment]
@Jackie-Jiang Got it, controller should report back on the status. I did this using an Observer and registering it with the rebalancer: https://github.com/apache/pinot/pull/10345. I wasn't aware @swaminathanmanish has already taken this up. @swaminathanmanish Please see if you can use this PR to get a head-start, thanks :)

**Comment by swaminathanmanish** [comment]
Thanks @suddendust for sharing your ideas. I'll take a look. Im also trying to figure out what kind of response will be useful to users (more like requirements gathering).

**Comment by swaminathanmanish** [comment]
Thanks @suddendust . This is useful.Yes the number of pending segments to be rebalanced can help detect the state when rebalance is stuck (or no progress when it continues to be in_progress indefinitely) for some reason.

**Comment by swaminathanmanish** [comment]
Completed -
Look for `checking the status` section in this doc
https://docs.pinot.apache.org/operators/operating-pinot/rebalance/rebalance-servers
