### ISSUE TITLE
issue connecting to zk from controller 

### ISSUE THREAD

**Issue by pshenoy3** [apache/pinot#10378]
2023/03/03 23:52:44.209 INFO [StartControllerCommand] [main] Executing command: StartController -configFileName /var/pinot/controller/config/pinot-controller.conf
2023/03/03 23:52:45.609 INFO [StartServiceManagerCommand] [main] Executing command: StartServiceManager -clusterName pinot-quickstart -zkAddress zk-server-headless:2181 -port -1 -bootstrapServices []

2023/03/03 23:52:45.710 INFO [StartServiceManagerCommand] [main] Starting a Pinot [CONTROLLER] at 10.595s since launch
2023/03/03 23:53:50.222 ERROR [StartServiceManagerCommand] [main] Failed to start a Pinot [CONTROLLER] at 75.106 since launch
org.apache.helix.zookeeper.zkclient.exception.ZkTimeoutException: Unable to connect to zookeeper server within timeout: 60000
	at org.apache.helix.zookeeper.zkclient.ZkClient.connect(ZkClient.java:2533) ~[pinot-all-0.13.0-SNAPSHOT-jar-with-

**Comment by Jackie-Jiang** [comment]
Do you have a zookeeper up and running at `zk-server-headless:2181`?

**Comment by pshenoy3** [comment]
yes I do have zk headless service up and running

NAME                 TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)    AGE
zk-server-headless   ClusterIP   None         <none>        2181/TCP   3h46m

###############################

Clients:
 /2620:149:1001:f1f:0:0:0:fe4:43654[0](queued=0,recved=1,sent=0)

Latency min/avg/max: 0/0/0
Received: 2595
Sent: 2594
Connections: 1
Outstanding: 0
Zxid: 0x0
Mode: standalone
Node count: 4
root@zk-0:/usr/bin# echo ruok | nc zk-0 2181
imokroot@zk-0:/usr/bin#

**Comment by pshenoy3** [comment]
Issue resolved after fixing ACL in Kubernetes cluster was blocking connections
