### ISSUE TITLE
filter clause with where <literal>=<literal> or <identifier>=<identifier> fail or are slow

### ISSUE THREAD

**Issue by jadami10** [apache/pinot#10383]
Queries with filter `where 1=1` will fail. Several of the optimizers hit a null pointer exception. I tried tracking these down, but kept hitting ever more complex null pointer issues.

Queries with filter `where "colA" = "colA"` work correctly, but for expensive queries, these end up taking almost twice as long.

While this is quite a weird edge case, we see it where users are passing a string query between functions. They start the query with `where A=A` so they can keep appending filters after that without need to know if there was already a filter.

**Comment by Jackie-Jiang** [comment]
The reason why `where colA = colA` is slow is because it will be converted to `where colA - colA = 0`, which involves transform.
One solution is to remove the equality predicate when the LHS and RHS are the same.
