### ISSUE TITLE
[multistage] fix stats/trace

### ISSUE THREAD

**Issue by walterddr** [apache/pinot#10402]
See TODO from #10390 

1. [x] if not enableTrace, disable all complexity in intermediary Operators, only MailboxSend and MailboxReceive should be dealing with metadata (e.g. no need to record operator level stats then convert them into stage level) --> to speed up metadata processing (In Review: https://github.com/apache/pinot/pull/10447)
2. [ ] ~~fix operator stats processing issue: CPU time is overlapping, we need to unoverlap~~ Order Operator Stats correctly so that we can compare child and parent stats easily (WIP: https://github.com/apache/pinot/pull/10574)
3. [x] fix operator stats starting time measurement: currently it starts at first block. it should start at first non no-op block - https://github.com/apache/pinot/pull/10450
4. [ ] enable some compression for operator stats, for example 
    - [x] similar to trace info the entire string should be encoded once and pass around afterwards to avoid duplicate ser/de on the map https://github.com/apache/pinot/pull/10473
    - [ ] allow agg on server level when dealing with large cardinality of (opID + serverID + stageID + requestID) so we report only the avg and stdev of the stats across all servers

CC @Jackie-Jiang @xiangfu0 @KKcorps

**Comment by KKcorps** [comment]
Taking up the first issue.

**Comment by walterddr** [comment]
this issue should be closed. we can follow up with the remaining issue separately
