### ISSUE TITLE
[multistage] Type Inference for Case/When Has Some Issues

### ISSUE THREAD

**Issue by ankitsultana** [apache/pinot#10415]
Detected this in https://github.com/apache/pinot/pull/10409

There's a todo left in `FunctionOperand` as well related to this: https://github.com/apache/pinot/blob/master/pinot-query-runtime/src/main/java/org/apache/pinot/query/runtime/operator/operands/FunctionOperand.java#L53

Essentially after the PR linked above, for the query below a couple of project nodes are merged and the case/when starts returning a Double at runtime which is compared against `16.0` which is a float.

```
SELECT intCol, CASE WHEN (SELECT SUM(floatCol) FROM {tbl1}) > 16.0 THEN 'Large sum' ELSE 'Small sum' END AS aggVal, strCol FROM {tbl1}
```

cc: @walterddr

**Comment by abhioncbr** [comment]
Please assign this ticket to me.

**Comment by abhioncbr** [comment]
@walterddr just pushed the [initial commit](https://github.com/apache/pinot/pull/10472); I want to validate my approach and understanding. Can you please have a look?

**Comment by walterddr** [comment]
@ankitsultana could you share some query examples that have failed? so we can add test cases for this.

**Comment by ankitsultana** [comment]
Only case I had detected was present in the UTs. I think the PR already removes the "ignored" flag.

**Comment by walterddr** [comment]
thank you will comment on the PR for some additional test examples
