### ISSUE TITLE
Store validDocIds with each segment when sealed

### ISSUE THREAD

**Issue by egalpin** [apache/pinot#10437]
It might already be the case that the set of valid doc IDs (upsert) are stored as part of the segments themselves. Having access to the bitmap of valid (or likely smaller bitmap, invalid) doc IDs would allow for compaction or other externalized reprocessing of segments where the information about which docs are valid is desirable.  Once a document becomes invalid it can never become valid again, so this should be safe to store.

**Comment by Jackie-Jiang** [comment]
Please take a look at #10052 which added an API to download the validDocIds from the server
