### ISSUE TITLE
"metadata.properties" file in the segment has non-deterministic order

### ISSUE THREAD

**Issue by claudeyj** [apache/pinot#10442]
Hi, I have a question regarding the CRC verfification process. According to current implementation, the CrcUtils will get all files in the given directory, sort them and compute the checksum for them and get the encoded CRC or MD5 value. However, in the corresponding test, CrcUtilsTest, there's a file named "metas.properties" which list the properties of the creation of segment. The order of the properties in the file is not deterministic. So my question is that **is the non-determinism desired or undesired**? In different environment the order of properties of the same segment could be different, leading to verification failure (different checksum computed). If it is undesired, I can create a PR to fix it and ensure the determinism.

**Comment by claudeyj** [comment]
You can also check my draft PR in my forked repo if you like: https://github.com/claudeyj/pinot/pull/2.

**Comment by Jackie-Jiang** [comment]
cc @saurabhd336 to also take a look

This is great finding! When writing the segment metadata (`SegmentColumnarIndexCreator.writeMetadata()`), seems there are multiple unordered maps (e.g. `customProperties`). I'd suggest always ordering the keys using alphabetical order. Currently the dimensions (`segment.dimension.column.names`) and metrics (`segment.metric.column.names`) field is using alphabetical order.

**Comment by claudeyj** [comment]
Thanks @Jackie-Jiang for the confirmation. I had a PR #10445 to fix this issue and you may want to take a look. Also thanks @saurabhd336 as we previously discussed on Slack. It's also a good strategy to sort the keys before writing. You can consider updating my PR or creating a new one regarding this bug.

**Comment by saurabhd336** [comment]
Should we also include the indexCreator maps in this scope? i.e. https://github.com/apache/pinot/blob/master/pinot-segment-local/src/main/java/org/apache/pinot/segment/local/segment/creator/impl/SegmentColumnarIndexCreator.java#L97-L106

these creator maps are HashMaps which may lead to non deterministic ordering (not in metadata.properties, but columns.psf).

**Comment by Jackie-Jiang** [comment]
Another attempt: #10468

**Comment by claudeyj** [comment]
> Another attempt: #10468

This PR looks good to me but previously another developer @zhtaoxiang worries about whether replacing HashMap would lead to performance degradation. But if it's not a problem it should be fine. Looking forward to the bug being fixed.

**Comment by Jackie-Jiang** [comment]
Good call on the performance. Since the maps changed in the PR are all small maps (same size as number of columns), using TreeMap should have at least similar performance as HashMap

**Comment by claudeyj** [comment]
That's great, looking forward to the PR being merged.

**Comment by Jackie-Jiang** [comment]
Thanks for reporting the issue! Closing the ticket as the fix is merged
