### ISSUE TITLE
Support delete record with upsert table

### ISSUE THREAD

**Issue by navina** [apache/pinot#10452]
# Context 
Upsert feature allows users to update existing records in Pinot. Deletes of existing records, however, are currently not supported. 
Delete can be treated as a special kind of update operation and handled in Pinot's realtime engine. This will open up support for ingesting Change Data Capture (CDC) data like Debezium where the changes from a source (typically, transactional) will also contain a DELETE event. 
The challenge here would be to handle out of order events correctly in the presence of deletes. 

# PEP Details
* Design proposal: [link](https://docs.google.com/document/d/19s1AHCRjmqeVa0z_djYBTAt_meg6qWcUxwRO3y-G9O4/edit#)
* Owner: @navina 
* Label: `PEP-Request`

**Comment by navina** [comment]
Labels: `feature` , `ingestion` 
Assignee `navina`

**Comment by navina** [comment]
@Jackie-Jiang @npawar @yupeng9 @mcvsubbu 
Here is the updated design proposal for this issue - [design](https://docs.google.com/document/d/19s1AHCRjmqeVa0z_djYBTAt_meg6qWcUxwRO3y-G9O4/edit#) 

I have implemented the changes based on this design in this PR #10703  and it seems to work well. PTAL. Ty!

**Comment by mcvsubbu** [comment]
> @Jackie-Jiang @npawar @yupeng9 @mcvsubbu Here is the updated design proposal for this issue - [design](https://docs.google.com/document/d/19s1AHCRjmqeVa0z_djYBTAt_meg6qWcUxwRO3y-G9O4/edit#)
> 
> I have implemented the changes based on this design in this PR #10703 and it seems to work well. PTAL. Ty!

Thanks, Navina. I dropped some (relatively minor) querstions in the design doc. Could you please modify accordingly?
cc: @sajjad-moradi

**Comment by navina** [comment]
Resolving this issue. Documentation updated here - https://docs.pinot.apache.org/basics/data-import/upsert#delete-column
