### ISSUE TITLE
Partial Upsert Tables Read a Lot of MMAP'ed Data

### ISSUE THREAD

**Issue by ankitsultana** [apache/pinot#10494]
For Full Upsert tables, if we get a new event for an existing primary-key, we simply use that new event as the new record.

However for Partial Upsert tables we have to read the entire existing record. This means that we have to do row-based reads on the columnar data which can have a big overhead especially if the number of columns are higher.

Not only does it increase the overall Disk IO Utilization, if there's even a modest spike in Disk IO Utilization the ingestion latency for partial upsert tables can be impacted.

I don't think there's a way around this given how Partial Upsert tables are designed but interested to see what the community thinks.

**Comment by Jackie-Jiang** [comment]
For some context, do you observe this issue when some columns are raw (no dictionary) and also compressed? It will be the worst case when values are compressed but we just need to read one value out

**Comment by swaminathanmanish** [comment]
@ankitsultana  - Just curious, if you have any stats that can indicate how bad the situation is and also how frequently this happens ?

**Comment by ankitsultana** [comment]
> For some context, do you observe this issue when some columns are raw (no dictionary) and also compressed? It will be the worst case when values are compressed but we just need to read one value out

In our case we have ~100 columns. All are dictionary encoded. We also have a bit high ingestion rate (messages per second) for this use-case, so the number of columns multiplied with the ingestion rate worsen the issue.

> @ankitsultana - Just curious, if you have any stats that can indicate how bad the situation is and also how frequently this happens ?

We don't have any general stats to share. Most likely you'll run into this when your table is larger than mmap memory, and the (messages per second x number of columns) are "high".

**Comment by ankitsultana** [comment]
let's follow-up offline. I think we can keep the open source code as is for now.

**Comment by rohityadav1993** [comment]
This issue has been addressed with lazy reads for the previous records in [11826 ](https://github.com/apache/pinot/pull/11826). Only the necessary columns will be read instead of actively reading the complete row.
