### ISSUE TITLE
[multistage] returning empty string('') instead of null for Case/When

### ISSUE THREAD

**Issue by abhioncbr** [apache/pinot#10513]
[Case/When Query ](https://github.com/apache/pinot/blob/master/pinot-query-runtime/src/test/resources/queries/Case.json#L25) is failing because of returning '' empty string instead of null.

```
SELECT intCol, CASE WHEN boolCol = true THEN 'Yes' END AS boolVal, strCol FROM {tbl1}
java.lang.AssertionError: Not match at (1,1)! Expected: [2, null, two] Actual: [2, , two] 
Expected :0
Actual   :1
```

It should return NULL but returns '' (empty string) when the case is not matched.

cc @ankitsultana @walterddr

**Comment by Jackie-Jiang** [comment]
cc @61yao as it is related to the null support

**Comment by abhioncbr** [comment]
It's not specific to the above query. It's happening for all queries without the `ELSE` clause. Here are more examples
```
SELECT intCol, CASE WHEN intCol % 2 = 0 THEN intCol END AS intVal, strCol FROM {tbl1}
SELECT intCol, CASE WHEN floatCol > 4.0 THEN floatCol END AS floatVal, strCol FROM {tbl1}
SELECT intCol, CASE WHEN doubleCol > 6.0 THEN doubleCol END AS doubleVal, strCol FROM {tbl1}
SELECT intCol, CASE WHEN longCol > 10 THEN longCol * 4 END AS longVal, strCol FROM {tbl1}
```

**Comment by 61yao** [comment]
I checked the code. It should be calling the scalar case when functions. And seems like it has been fixed. @abhioncbr @walterddr

**Comment by 61yao** [comment]
This calls caseWhenTransform function. It doesn't handle return null when condition is not matched. This is a known issue we will fix soon. 

Please refer https://github.com/apache/pinot/issues/10252 for progress and design doc

**Comment by abhioncbr** [comment]
Thanks, @61yao for the information and for sharing the design doc. Let me know, if I can pick/contribute some work. Thanks

**Comment by abhioncbr** [comment]
Fixed.
