### ISSUE TITLE
Deprecate Kafka 0.9 support as official Plugin

### ISSUE THREAD

**Issue by xiangfu0** [apache/pinot#10521]
Due to the lack of usage of Kafka 0.9(released in 2015), we will remove the code and library releases for kafka 0.9 from next release.

The latest Kafka 0.9 support is by 0.12.1.

**Comment by abhioncbr** [comment]
Please assign this issue to me. Thanks

**Comment by abhioncbr** [comment]
There is a [PR](https://github.com/apache/pinot/pull/10522) already for this. Thanks
