### ISSUE TITLE
Segment Pruning does not respect query timeout

### ISSUE THREAD

**Issue by jadami10** [apache/pinot#10539]
We're seeing cases internally where segment pruning on the server side will run for minutes when the timeout is explicitly set to 30s. I imagine we would want to support timing out here, but I could use some design input.

1. should we still emit the `SEGMENT_PRUNING` time metric on timeout?
2. Does it make sense to dig into every implementer of the `SegmentPruner` and add timeouts or use something like the guava `TimeLimiter` to do it once (I need to dig into how this thing works and if it will actually interrupt a while loop or IO)
  - guava `TimeLimiter` uses a separate `ExecutorService` in the background, so I'm not sure how we feel about anything outside of the 2 threadpools that exist

**Comment by ankitsultana** [comment]
The issue regarding timeout based pre-emption is general. For supporting interrupts we'll have to add interrupt checks everywhere so it is not limited to `SegmentPruner`.

I haven't checked Guava `TimeLimiter` either but I don't think it would be able to stop an arbitrary function unless the function itself supports interruption (by checking Thread interrupt status). For context even Future methods like `Future.cancel` only set the interrupt flag and don't actually "cancel" any arbitrary function.

The thing that is interesting though is why the segment pruner is taking this long. Can you share more context about the issue: how many segments you have, what's the query you are trying, etc.

I presume it is the `ColumnValueSegmentPruner` which is taking a long time.

**Comment by priyen** [comment]
@ankitsultana , I work with johan so I can also chime in here, this is on a instance using hard-drive's as the backing store, and one instance can also have thousands of segments. The single threaded nature of the current pruning + large segments in the thousands means pruning takes a while and sometimes longer then the query timeout.

**Comment by Jackie-Jiang** [comment]
Certain segment pruner requires loading data (e.g. bloom filter, dictionary) which might take time. IMO we should move the segment pruning step into the query plan phase so that we can utilize multiple threads to process them. Within the plan node, we get the early termination for free

**Comment by jadami10** [comment]
@Jackie-Jiang, for "the query plan phase", are you specifically referring to `InstancePlanMakerImplV2`?

**Comment by klsince** [comment]
https://github.com/apache/pinot/pull/10660 trying to tackle this issue: 1) to parallelize the BF based pruner; 2) and honor the timeout set in query option. pls help review.

**Comment by jadami10** [comment]
looks like it merged! I'll help test it next week. cc @priyen-stripe
