### ISSUE TITLE
Clean up replicaGroupStrategyConfig / replicaGroupPartitionConfig

### ISSUE THREAD

**Issue by priyen** [apache/pinot#10608]
replicaGroupStrategyConfig is the old one and replicaGroupPartitionConfig is the new, but right now you need to maintain both because the new one doesn't have partitioning column but the old one does.
It can easily lead to confusion why there is 2 configs especially since they share field names.

We should fully clean up and remove the old one

**Comment by abhioncbr** [comment]
I would like to try if no one is working on this. Thanks.

**Comment by siddharthteotia** [comment]
This cleanup is backwards incompatible. I fully agree that we need to start using the new one and there is confusion / maintenance overhead etc but simply removing it right away is going to break things for people in production.

**Comment by GSharayu** [comment]
This is a good issue, but we should not deprecate the old flow since this will impact production systems. We should bring a plan  for migrations / compatibility  along these cleanups to align all the stakeholders before deprecating this fully.

**Comment by Jackie-Jiang** [comment]
We want to do it in a backward compatible way:
- Add a new field `_partitionColumn` into the `InstanceReplicaGroupPartitionConfig`
- If the field is not found, fall back to the old `ReplicaGroupStrategyConfig`
- Keep the `ReplicaGroupStrategyConfig` and use it when the new config doesn't exist

**Comment by abhioncbr** [comment]
Thanks, @siddharthteotia,  @GSharayu and @Jackie-Jiang, for the comments.

I'm just asking the question here that I have asked on the draft PR. 
What if a user provides a different `partitionColumn` value in both configs? As per @Jackie-Jiang's comment, we will use the value of `partitionColumn` provided in `InstanceReplicaGroupPartitionConfig`. Is it correct? Also, for `numInstancesPerPartition`, it's going to be the same?

I was going over the [documentation](https://docs.pinot.apache.org/operators/operating-pinot/instance-assignment), and I think we need to update the documentation by mentioning `ReplicaGroupStrategyConfig ` as deprecated.

Please let me know if anything else needs to be updated. Thanks

**Comment by Jackie-Jiang** [comment]
@abhioncbr The overall goal is to keep the existing config work if new config is not provided, and use the new config if provided. So if the `partitionColumn` is provided in both places, we can either throw an exception to let the user know the config is invalid (preferred, can be done within the `TableConfigUtils.validate()`), or just use the one from the new config.

**Comment by abhioncbr** [comment]
Please review the changes. Thanks
