### ISSUE TITLE
Pinot doesn't return most data in the `metadata` JSON Property when tables are created

### ISSUE THREAD

**Issue by travis-cook-sfdc** [apache/pinot#10680]
Submitting the following table config:

```
{
  "tableName": "test_table",
  "tableType": "OFFLINE",
  "tenants": {
    "broker": "DefaultTenant",
    "server": "DefaultTenant"
  },
  "segmentsConfig": {
    "segmentPushType": "APPEND",
    "retentionTimeUnit": "DAYS",
    "retentionTimeValue": "10",
    "replication": "2",
    "schemaName": "test_schema",
    "minimizeDataMovement": true,
    "timeColumnName": "date_str",
    "timeType": "DAYS"
  },
  "tableIndexConfig": {
    "loadMode": "MMAP"
  },
  "metadata": {
    "test_value": "123"
  },
  "routing": {
    "segmentPrunerTypes": [
      "time",
      "partition"
    ],
    "instanceSelectorType": "replicaGroup"
  },
  "instanceAssignmentConfigMap": {
    "OFFLINE": {
      "tagPoolConfig": {
        "tag": "DefaultTenant_OFFLINE",
        "poolBased": false
      },
      "replicaGroupPartitionConfig": {
        "replicaGroupBased": true,
        "numReplicaGroups": 2,
        "numInstancesPerReplicaGroup": 10,
        "minimizeDataMovement": true
      }
    }
  }
}
```

Then make a request to the Pinot API: `GET /tables/test_table?type=OFFLINE`

You'll see that the `metadata` key is missing:
```
  "tableName": "test_table",
  "tableType": "OFFLINE",
  "tenants": {
    "broker": "DefaultTenant",
    "server": "DefaultTenant"
  },
  "segmentsConfig": {
    "segmentPushType": "APPEND",
    "retentionTimeUnit": "DAYS",
    "retentionTimeValue": "10",
    "replication": "2",
    "schemaName": "test_schema",
    "minimizeDataMovement": true,
    "timeColumnName": "date_str",
    "timeType": "DAYS"
  },
  "tableIndexConfig": {
    "loadMode": "MMAP"
  },
  "metadata": {},
  "routing": {
    "segmentPrunerTypes": [
      "time",
      "partition"
    ],
    "instanceSelectorType": "replicaGroup"
  },
  "instanceAssignmentConfigMap": {
    "OFFLINE": {
      "tagPoolConfig": {
        "tag": "DefaultTenant_OFFLINE",
        "poolBased": false
      },
      "replicaGroupPartitionConfig": {
        "replicaGroupBased": true,
        "numReplicaGroups": 2,
        "numInstancesPerReplicaGroup": 10,
        "minimizeDataMovement": true
      }
    }
  }
}
```

However, if you make the same request to create a table it will be included:

```
{
   ...
   "metadata": {
       "customConfigs": {
            "test_value": "123"
       }
   },
   ...
```

Given the way the [documentation is currently written](https://docs.pinot.apache.org/configuration-reference/table#top-level-fields) this is a bug.  

This is because the `TableCustomConfig.java` is expecting a JSON Property called `customConfigs`.  However, this level of nesting seems unnecessary.

https://github.com/apache/pinot/blob/a130cb2b1e465ad9ad3bdb4428a32fef5bf54cdd/pinot-spi/src/main/java/org/apache/pinot/spi/config/table/TableCustomConfig.java#L32

**Comment by Jackie-Jiang** [comment]
Good finding!
Currently the only usage for this `customConfigs` is a deprecated key `generate.inverted.index.before.push`.
We can either fix the documentation, or pull this map one level up so that it is more intuitive.
@jackjlli Do you use other properties within the `customConfigs` internally?

**Comment by jackjlli** [comment]
Hi guys, I've checked the internal usage of this custom configs. Currently there are quite a few configs which are being used in that custom config map. I think the easier approach is to fix the documentation. Otherwise, there will be some non-trivial effort to put this map one level up (e.g. migrating all the existing table config, making code change, etc).

**Comment by Jackie-Jiang** [comment]
Sounds good. Updated the documentation. We may revisit this in the future.

**Comment by travis-cook-sfdc** [comment]
I can't remember what the documentation said previously, but I had interpreted the `metadata` field to be used for arbitrary custom key/value pairs to be added to the table.  

Would it be reasonable to leave `customConfigs` where it is but also make it possible that additional `metadata` fields at the top level could be included?  That would make it possible to store custom attributes for individual tables inside of `metadata` instead of necessarily needing to nest inside of `customConfigs`.

**Comment by Jackie-Jiang** [comment]
> Would it be reasonable to leave `customConfigs` where it is but also make it possible for additional `metadata` fields at the top level to be included? That would make it possible to store custom attributes for individual tables inside of `metadata` instead of necessarily needing to nest inside of `customConfigs`. It also wouldn't require doing anything to pull things currently stored in `customConfigs` up.

I don't think it is possible unless we do manual ser-de for that JSON field, which is quite complicated. If we want to make `metadata` an arbitrary key-value store, we need to define `metadata` field as a map, but that means there is no way to set `customConfigs` as an inner map of it.
