### ISSUE TITLE
Adding sorted / columns with inv index to noDictionaryColumns followed by a reload causes query failures

### ISSUE THREAD

**Issue by saurabhd336** [apache/pinot#10713]
Adding any columns to `noDictionaryColumns` list that aren't eligible for removing dictionary (like sorted, columns with inv index etc https://github.com/apache/pinot/blob/master/pinot-segment-local/src/main/java/org/apache/pinot/segment/local/segment/index/loader/ForwardIndexHandler.java#L362), followed by reload causes query failures since the DictionaryReader isn't created even though the segment metadata still says it has a dictionary.

The indexReader creator seems to honour the current table config over what the physical segment metadata says about the available indexes https://github.com/apache/pinot/blob/master/pinot-segment-spi/src/main/java/org/apache/pinot/segment/spi/index/IndexReaderFactory.java#L60

**Comment by saurabhd336** [comment]
@gortiz

**Comment by gortiz** [comment]
Here we have a case where the user explicitly say they don't want to have a dictionary but some other index requires the dictionary. Historically, in this situation we decided to ignore user request and create the dictionary anyway, but the new isn't consistent: It doesn't fail at validation time and it fails at runtime as the code follows a path we don't expect.

It is clear that we need to either go back to the previous behavior or break compatibility. My suggestion is to introduce these special cases in `DictionaryIndex.getConfig` (or more specifically in `createDeserializer`). Other alternatives are focused on changing the behavior at reading time, but that would break the key idea introduced in `index-spi` where getConfig returns the actual configuration the index should use and therefore the invariant that FieldIndexConfigs can be seen as the source of trust.

**Comment by egalpin** [comment]
I've just confirmed that #10851 also fixes  #10875. I validated locally using the same approach which was previously resulting in error.
