### ISSUE TITLE
Environment variables not substituted in configuration

### ISSUE THREAD

**Issue by dd-willgan** [apache/pinot#10719]
Environment variable substitution for Pinot configuration works for certain configs such as broker passwords

```
# pinot-broker.conf
pinot.broker.access.control.principals.admin.password=${env:ADMIN_PASSWORD}
```

but not for others. Particularly, initializing username and password for Pinot ZK controller auth and [authorization tokens](https://docs.pinot.apache.org/operators/tutorials/authentication-authorization-and-acls) on the controller and server can't be done with environment variables

```
# pinot-controller.conf
access.control.init.username=admin
access.control.init.password=${env:INIT_PASSWORD}
controller.segment.fetcher.auth.token=${env:AUTH_TOKEN}

# pinot-server.conf
pinot.server.segment.fetcher.auth.token=${env:AUTH_TOKEN}
pinot.server.segment.uploader.auth.token=${env:AUTH_TOKEN}
pinot.server.instance.auth.token=${env:AUTH_TOKEN}
```

Configs in Pinot are based on the `CompositeConfiguration` in the Apache Commons Library, which has the behavior that interpolation e.g. environment variable substitution is only done when a specific type is returned.

- `String CompositeConfiguration.getProperty(String name)` does interpolation
- `Object CompositeConfiguration.getProperty(String name)` doesn't

The issue is that the `PinotConfiguration` [class](https://github.com/apache/pinot/blob/master/pinot-spi/src/main/java/org/apache/pinot/spi/env/PinotConfiguration.java) that wraps `CompositeConfiguration` is a bit inconsistent with whether it calls a typed `getProperty` or calls the generic Object `getProperty` and then casts the type. `PinotConfiguration` also supports a `toMap` function which returns a `Map<String, Object>` object. The parsing of the `auth.token` uses that so it's tricky to get environment variables to be substituted.

**Comment by Jackie-Jiang** [comment]
This is fixed with #10785
