### ISSUE TITLE
can't add schema using Pinot UI, always get the error " HTTP 415 Unsupported Media Type "

### ISSUE THREAD

**Issue by thatran** [apache/pinot#10717]
Problem is easy to observe, just try adding any table schema using the Pinot UI, you'll get the error " HTTP 415 Unsupported Media Type ".

Using Chrome Developer Tools, you can see it's because the schema /validate rest api is called with incorrect Content-Type request header:
Content-Type: text/plain;charset=UTF-8
instead of 
Content-Type: application/json

Workaround is to add the schema by calling the rest API directly (using curl or SwaggerUI) instead of via the Pinot UI

**Comment by jonasgeiregat** [comment]
I'm unable to reproduce this with pinot version 0.12.0 using Chrome. 

I could clearly see the content-type being application/json; charset=UTF-8 at my end.

Do you have more information on how to reproduce this ?

![Screenshot 2023-05-05 at 19 26 29](https://user-images.githubusercontent.com/288105/236525655-25a3c084-ee95-45ef-a15f-d984697004b6.png)

**Comment by navina** [comment]
@thatran which pinot version did you try? I am able to add the schema using the UI and don't see any error about unsupported media type.

**Comment by thatran** [comment]
i think it's my mistake, i cannot reproduce this in OSS pinot, only in ST pinot, so i will close this issue and open an ST jira
