### ISSUE TITLE
Pinot worker gets high CPU load sometimes

### ISSUE THREAD

**Issue by yeahCaesar** [apache/pinot#10724]
We built 3 pinot work nodes to store data. 
Recently, we found that sometimes a random one of the 3 nodes would have a cpu load of 100%, causing very slow queries
Pinot was installed as a docker image.
JVM Parameter: -Xms4G -Xmx15G -XX:+UseG1GC -XX:MaxGCPauseMillis=200
![image](https://user-images.githubusercontent.com/19277364/236365162-fec7d315-9744-4bdf-ada1-2fdad95b2e9f.png)

**Comment by Jackie-Jiang** [comment]
We need more information to debug this. What queries are you running? A thread dump would be helpful
