### ISSUE TITLE
RecordReader config is not correctly wired in `SegmentGenerationAndTaskExecutor`

### ISSUE THREAD

**Issue by snleee** [apache/pinot#10727]
`SegmentGenerationAndTaskExecutor` doesn't correctly wire `recordReader.prop.<keys>`. Due to this, record reader config (e.g. delimiter for csv file) cannot be configured in `SegmentGenerationAndTaskExecutor`.

```
SegmentGenerationAndPushTaskExecutor: L286
      RecordReaderSpec recordReaderSpec = new RecordReaderSpec();
      recordReaderSpec.setDataFormat(taskConfigs.get(BatchConfigProperties.INPUT_FORMAT));
      recordReaderSpec.setClassName(taskConfigs.get(BatchConfigProperties.RECORD_READER_CLASS));
      recordReaderSpec.setConfigClassName(taskConfigs.get(BatchConfigProperties.RECORD_READER_CONFIG_CLASS));
      ...
      
      --> We need to add the following line:
      recordReaderSpec.setConfigs(IngestionConfigUtils.getRecordReaderProps(taskConfigs));
```

We should also add the test to check if the record reader config gets propagated to the segment generation logic properly.

**Comment by abhioncbr** [comment]
Please assign the ticket to me. I will work on it. Thanks

**Comment by snleee** [comment]
@abhioncbr  FYI, Johan from OSS reported this and he showed the interest to pick this ticket. I mentioned you in the discussion thread from Apache Pinot Slack Channel.

**Comment by jvenant** [comment]
Here it is
