### ISSUE TITLE
[multistage] The multistage aggregate planner and runtime do not work with all v1 aggregation functions

### ISSUE THREAD

**Issue by somandal** [apache/pinot#10745]
The aggregation functions supported by v1 engine are not fully supported in v2 engine and we should be able to leverage them without rewriting them for v2 engine.  Today the multistage engine expects that to add support for each new aggregation function, we modify the planner and runtime code. This approach is not scalable in the long term and requires detailed knowledge of the Pinot engine to add support for new functions. We should make the multistage engine aggregation support generic and extensible.

Some of the high-level changes we need to make: 

- Generic way to register all existing and new aggregate functions dynamically to the `SqlOperatorTable` (using annotations / etc). (By overriding `getOperatorList()`?) . Also have an additional check in Optimization rule `matches()`  to early terminate if a agg function doesn’t exist.  This way, when a new Aggregation Function is introduced in Pinot, the author need not make heavy planner and runtime changes.
- `onMatch()`  The `AggregationFunction` should dictate the splitting logic. Planner Optimization should not get into the business of determining the logic for each and every aggregation function. e.g. today we split COUNT into COUNT (leaf) + SUM(intermediate)
- `AggregateOperator` (in intermediate stage) should be merged or at least call into `AggregationOperator` (in leaf). The accumulate logic should be common. The row vs column processing can be implemented as a wrapper to convert wherever necessary. If needed in the future, we can modfiy the operators to have two functions, one for row based and one for column based. For now conversion of row -> column is fine
- `AggregateOperator`  should not work on `RexExpression`. Should be converted to a `ExpressionContext`. Also leaf `AggregationFunctionFactory::getAggregationFunction()`  currently takes in the `QueryContext`. This should also be avoided (fields used from `QueryContext` to create the aggregation functions can instead be added to `FunctionContext` if needed).

cc @siddharthteotia @vvivekiyer @walterddr @kishoreg

**Comment by kishoreg** [comment]
Thanks @somandal for summarizing. I forgot to bring up the issue with the return data type for aggregation functions.

we should enhance the aggregation function to have a method that provides the result data type based on the input type.

```  
  ColumnDataType getIntermediateResultColumnType();

  ColumnDataType getFinalResultColumnType();
   
/** new method*/
  default ColumnDataType getIntermediateResultColumnType(ColumnDataType[] argTypes){
    return getIntermediateResultColumnType();
  }

  
 /** new method*/
  default ColumnDataType getFinalResultColumnType(ColumnDataType[] argTypes){
    return getFinalResultColumnType();
  }
  ```

**Comment by siddharthteotia** [comment]
@vvivekiyer and @jasperjiaguo  will be picking this up dividing the work between themselves for planner and runtime.

**Comment by siddharthteotia** [comment]
We sync'd up. @somandal will help with planner side changes and @vvivekiyer  will help with runtime side changes.

**Comment by siddharthteotia** [comment]
FYI @kishoreg ^^

**Comment by somandal** [comment]
Please review this proposal written by me and @vvivekiyer : https://docs.google.com/document/d/1Us6aBvTpNLMEy0ODo34OgTk73h_LVFFAH6q17689h1M/edit?usp=sharing
