### ISSUE TITLE
RowDataBlock throws exceptions during ser/de of MV byte and empty MV types

### ISSUE THREAD

**Issue by jasperjiaguo** [apache/pinot#10762]
see https://github.com/apache/pinot/blob/9e1160272aec88591d9e768d15104b72521b2ffb/pinot-core/src/test/java/org/apache/pinot/core/common/datablock/DataBlockTest.java#L104C22-L144

**Comment by navina** [comment]
@jasperjiaguo : what is the GH issue about? 
can you add more details so other contributors can potentially help out?  Thanks!

**Comment by jasperjiaguo** [comment]
@navina the details are in the two test cases I linked, basically I think RowDataBlock has some bug when doing ser/de on MV columns, which will throw exceptions when working on valid rows that contains MV data. Ideally DataBlock should be able to wrap all types of data correctly.

**Comment by Jackie-Jiang** [comment]
cc @walterddr

**Comment by walterddr** [comment]
int array fixed. 

BYTES array is never supported thus will not be fixed in this bugfix PR
