### ISSUE TITLE
[multistage] group-by throws NPE when dealing with null values

### ISSUE THREAD

**Issue by walterddr** [apache/pinot#10782]
several issues with handling null in group-by, (typical scenario: group-by is applied after left-join)

the problems are:
1. when the nullable column is in the group-key.  the group-set aggregation causes the results (or error) to not populated through.
2. when the nullable column is in the agg function. it simply throws NPE

the problem might also happen to other operators that doesn't handle null arguments

**Comment by Jackie-Jiang** [comment]
Fixed with #10799
