### ISSUE TITLE
Question: Use HDFS as Deep Storage

### ISSUE THREAD

**Issue by yeahCaesar** [apache/pinot#10822]
There is a sentence in the Pinot Docs #HDFS as Deep Storage :
    "To use HDFS as deep storage you need to include HDFS dependency jars and plugins."
I'd like to know what exact the HDFS dependency jars and plugins are? A full Hadoop cluster with HDFS is needed or just some jar packages? If jar packages, what packages are they?

If I can get an entire sample for using HDFS as Deep Storage , that would be really helpful to me.

**Comment by Jackie-Jiang** [comment]
@yeahCaesar This is a good question to be asked in the slack channel under #troubleshooting

**Comment by yeahCaesar** [comment]
> @yeahCaesar This is a good question to be asked in the slack channel under #troubleshooting

ok，thanks for replying me
