### ISSUE TITLE
LIKE doesn't seem to support escaping SQL wildcards

### ISSUE THREAD

**Issue by kirkrodrigues** [apache/pinot#10849]
A query like:

`SELECT * FROM table WHERE col LIKE '%2\_2%'`

gets translated to 

`SELECT * FROM table WHERE REGEXP_LIKE(col, '2\\.2')`

Is this the right syntax for escaping SQL wildcards?

If so, this issue looks to be because [`likeToRegexpLike`](https://github.com/apache/pinot/blob/master/pinot-common/src/main/java/org/apache/pinot/common/utils/RegexpPatternConverterUtils.java#L35) doesn't handle escaped wildcards.

**Comment by Aravind-Suresh** [comment]
@Jackie-Jiang @atris I've raised a fix for this - please review.

**Comment by atris** [comment]
Good catch. Reviewing.
