### ISSUE TITLE
Long respond time with simple filter query

### ISSUE THREAD

**Issue by geekboood** [apache/pinot#10844]
I have one pinot server instance useing version 0.12.1, with 8000+ segments and each segments contains 1048576 rows. I create inverted index and bloom filter (and set on heap) for this filter field, but the query time still too slow. Here is the tracing detail. 
`{\"ColumnValueSegmentPruner Time\":18},{\"SegmentPrunerService Time\":35},{\"CombinePlanNode Time\":7192},{\"SelectionOrderByCombineOperator Time\":813},{\"InstanceResponseOperator Time\":813}`
```
  "numServersQueried": 1,
  "numServersResponded": 1,
  "numSegmentsQueried": 8507,
  "numSegmentsProcessed": 427,
  "numSegmentsMatched": 19,
  "numConsumingSegmentsQueried": 0,
  "numConsumingSegmentsProcessed": 0,
  "numConsumingSegmentsMatched": 0,
  "numDocsScanned": 628,
  "numEntriesScannedInFilter": 0,
  "numEntriesScannedPostFilter": 1256,
  "numGroupsLimitReached": false,
  "totalDocs": 8920236032,
  "timeUsedMs": 8098,
```
What could be the problem?

**Comment by Jackie-Jiang** [comment]
Is this during a cold start? Do you have SSD or HDD on your server? `CombinePlanNode` takes majority of the time, which means binary search on the dictionary to find the matching dictionary id might be the root cause.

**Comment by geekboood** [comment]
My Pinot server run on HDD so this seems normal. Does Pinot has mechanism to put index on SSD, such as a seperate index directory?

**Comment by Jackie-Jiang** [comment]
Do you have SSD attached to your servers? If so, you may change the data directory in the server config to point to the SSD. You may reference this page for the server config: https://docs.pinot.apache.org/configuration-reference/server

**Comment by geekboood** [comment]
Adding SSD improved overall performance. I add a bcache layer using SSD to Pinot data drive and the performance drastically improved, both initial starting and querying. For Pinot, it has static data segment files so this might be a good idea to balance between performance and cost.
