### ISSUE TITLE
[multistage] server restart causes broker unable to find server

### ISSUE THREAD

**Issue by walterddr** [apache/pinot#10864]
Description
===
this specifically happens 
1. when the server mailbox / v2 engine service port is dynamically configured; or 
2. when server expansions happened without cluster restart

when server restarts, 
1. server updates the segment instance configuration with the new dynamically assigned config port
3. broker listens to the instance config change and updates its routing table with the newly assigned port. 

this is not happening for now.

Follow up
===
one reported incident in https://apache-pinot.slack.com/archives/C011C9JHN7R/p1686141604049009?thread_ts=1685963058.774949&cid=C011C9JHN7R shows that the current work around is restart broker to let it pick up the new config. this indicates most likely the broker listener is not updating the config, server is updating fine

**Comment by xiangfu0** [comment]
I cannot really reproduce this.
Let's add a default port for `pinot.query.runner.port` and `pinot.query.server.port` in helmChart to bypass this problem if it really exists.

**Comment by walterddr** [comment]
Sounds good at least containerized environment will be stable (  we can see if others can still reproduce the unavailable issue still with the new helm )

**Comment by xiangfu0** [comment]
https://github.com/apache/pinot/pull/11180

**Comment by xiangfu0** [comment]
Close as not reproducible.

**Comment by xiangfu0** [comment]
This is the fix: https://github.com/apache/pinot/pull/11386
