### ISSUE TITLE
execute() should return true and non-null _resultSet when there is no match

### ISSUE THREAD

**Issue by zhuangdaz** [apache/pinot#10879]
Hi team, I am using [jooq](https://www.jooq.org/) for querying Pinot but running into an exception when there is no match. 
```
Caused by: java.sql.SQLException: Unknown column index : 2
```

I think the root cause is b/c:

1.`PinotStatement`/`PinotPreparedStatement` returns a null when there is empty-row(no match) result;

https://github.com/apache/pinot/blob/a75544f2c644874a88b61cea48b640d9cf05283c/pinot-clients/pinot-jdbc-client/src/main/java/org/apache/pinot/client/PinotStatement.java#L80-L90

line 82 returns a non-null `_resultSet`. However, since `_resultSet.next()` return `false`(rowCount == 0), `_resultSet` is reset to `null` and the method returns false.

2. Then [Jooq](https://github.com/jOOQ/jOOQ/blob/83e30567b16eacb7a126f0d105cb119b42c0fff9/jOOQ/src/main/java/org/jooq/impl/AbstractResultQuery.java#L253-L259) tries to insert an `UPDATE_COUNT` row which fails to be parsed with the original cols

I wonder if this has any existing solution or we should update `PinotStatement.execute()`(and `PinotPreparedStatement.execute()`) to return a non-null ResultSet with 0 row instead(this looks the correct fix since an empty-row ResultSet should still be valid based on the discussion [here](https://github.com/jOOQ/jOOQ/issues/6907#:~:text=So%20yes.%20I%20come%20from%20SQL%20and%20JDBC%2C%20and%20null%20meaning%20no%20result%2C%20not%20empty%20result%2C%20is%20the%20only%20reasonable%20interpretation%20here.)).

**Comment by zhuangdaz** [comment]
The Jooq integration was introduced from this issue: https://github.com/apache/pinot/issues/6557

**Comment by mayankshriv** [comment]
Seems like returning an empty resultSet should be the right approach? Can you file a PR?
cc: @KKcorps

**Comment by KKcorps** [comment]
iirc these classes are adhering to JDBC interfaces

if JDBC allows the signature change then we can do it

**Comment by lukaseder** [comment]
Folks, I was pointed here from twitter. Maybe, this blog post helps with the delicate JDBC statement execution protocol:
https://blog.jooq.org/how-i-incorrectly-fetched-jdbc-resultsets-again/

It's really not obvious to implement correctly, unfortunately.
