### ISSUE TITLE
[multistage][feature] support explain on physical plan

### ISSUE THREAD

**Issue by walterddr** [apache/pinot#10901]
currently running
```
EXPLAIN PLAN FOR
SELECT ...
```
returns a logical plan. but we should also allow return a `ExplainPlanVisitor.explainPlan` API to return a physical plan with all the stage assigned and worker info attached.

**Comment by abhioncbr** [comment]
Please assign this to me. Thanks

**Comment by walterddr** [comment]
thank you @abhioncbr please share what you had in mind before implementing it. 

there's 2 part in this.
1. syntax to explain physical plan. we might be able to do something with `EXPLAIN PLAN FOR` will behave the same for now and `EXPLAIN PHYSICAL PLAN` will return the physical plan
2. actually invoking and returning the plan (this most likely can be done via `ExplainPlanPlanVisitor.explain` API)

**Comment by abhioncbr** [comment]
Hi @walterddr, I will start work on this and follow the pointers you mentioned above.
- Going to add support for `EXPLAIN PHYSICAL PLAN FOR`; I think it's better to add `FOR` in the end for consistency with the other one.
- Implement the second part as suggested by you. 

I will ask specific questions if needed. Thanks

**Comment by walterddr** [comment]
yeah that's OK. let me know if you have any problems. 
- i think changing the syntatic plugin part might be a bit different and I am not even sure calcite's parser allows that plugin. (see the example for supporting `SqlInsertFromFile` in pinot-common/src/main/codegen/includes/parserImpls.ftl) 
- with that parsing mechanism done you should be able to generate a valid parser that turns into a SqlExplain node. and from there it should be relatively simple.

**Comment by abhioncbr** [comment]
@walterddr, qq
I was going through the [SqlExplain code](https://github.com/apache/calcite/blob/main/core/src/main/java/org/apache/calcite/sql/SqlExplain.java), and it looks like we have the option to get Physical plan of the query by using the option `WITH IMPLEMENTATION` in `Explain Plan for` SQL statement itself.

One such example is like below
```
EXPLAIN Plan WITH IMPLEMENTATION for SELECT MIN(AirTime), MAX(AirlineID), SUM(ArrDelay), AVG(ArrDelayMinutes), Year, Quarter 
FROM airlineStats
WHERE Year = 2014
GROUP BY Year, Quarter 
ORDER BY Year, Quarter DESC
```

From the implementation perspective, we have to add the [code here](https://github.com/apache/pinot/blob/master/pinot-query-planner/src/main/java/org/apache/pinot/query/QueryEnvironment.java#L196) in-case if we get the flag true from [SqlExplain's](https://github.com/apache/calcite/blob/main/core/src/main/java/org/apache/calcite/sql/SqlExplain.java#L145) `withImplementation()` method.

Also, if we are going with the implementation of `EXPLAIN PHYSICAL PLAN FOR` itself, do we want to support some options like `EXPLAIN PHYSICAL PLAN AS JSON` or similar?  and, also just confirming from the v1 engine perspective the response would be same for `EXPLAIN PLAN` and `EXPLAIN PHYSICAL PLAN`?

**Comment by walterddr** [comment]
with implementation sounds good to me if this is something calcite already supports that's even better IMO

**Comment by abhioncbr** [comment]
We can close this issue.
