### ISSUE TITLE
Is it possible to update the `retentionTimeValue` of a table after it's been created?

### ISSUE THREAD

**Issue by travis-cook-sfdc** [apache/pinot#10923]
As far as I know, the best way to update the `retentionTimeValue` would be to drop the table, recreate it with a different time value and then rerun a metadataPush job, but that seems like a lot of overhead just to get Pinot to increase/decrease the retention time.

Would `PUT /tableConfigs​/{tableName}` with the exact same table body but a new retention value work?

**Comment by eaugene** [comment]
Yes, @travis-cook-sfdc. That is possible
