### ISSUE TITLE
 `mvn clean install` fail on Mac with M1 chip

### ISSUE THREAD

**Issue by mingmxu** [apache/pinot#10945]
When running ` mvn clean install ` on latest code, some unit tests(from module `pinot-segment-spi`, `pinot-segment-local`, `pinot-core`, ...), fail with error message like below:
```
java.lang.UnsatisfiedLinkError: 'long xerial.larray.impl.LArrayNative.mmap(long, int, long, long)'
        at xerial.larray.impl.LArrayNative.mmap(Native Method)
        at xerial.larray.mmap.MMapBuffer.<init>(MMapBuffer.java:94)
        at org.apache.pinot.segment.spi.memory.PinotNativeOrderLBuffer.mapFile(PinotNativeOrderLBuffer.java:49)
```

```
[ERROR] Failures: 
[ERROR]   PinotDefaultByteBufferTest>PinotDataBufferTest.testConstructors:294 » UnsatisfiedLink
[ERROR]   PinotLArrayByteBufferTest>PinotDataBufferTest.testConstructors:294 » UnsatisfiedLink
[ERROR]   PinotLArrayByteBufferTest>PinotDataBufferInstanceTestBase.testMapFileBE:140 » UnsatisfiedLink
[ERROR]   PinotLArrayByteBufferTest>PinotDataBufferInstanceTestBase.testMapFileLE:153 » UnsatisfiedLink
[ERROR]   PinotLArrayByteBufferTest>PinotDataBufferInstanceTestBase.testMultipleClose:78 » UnsatisfiedLink
[ERROR]   PinotLArrayByteBufferTest>PinotDataBufferTest.testPinotNativeOrderBuffer:90->PinotDataBufferTest.testOrderBuffer:79 » UnsatisfiedLink
[ERROR]   PinotLArrayByteBufferTest>PinotDataBufferTest.testPinotNativeOrderBufferReadWriteFile:136->PinotDataBufferTest.testPinotBufferReadWriteFile:120 » UnsatisfiedLink
[ERROR]   PinotLArrayByteBufferTest>PinotDataBufferTest.testPinotNonNativeOrderBuffer:96->PinotDataBufferTest.testOrderBuffer:79 » UnsatisfiedLink
[ERROR]   PinotLArrayByteBufferTest>PinotDataBufferTest.testPinotNonNativeOrderBufferReadWriteFile:142->PinotDataBufferTest.testPinotBufferReadWriteFile:120 » UnsatisfiedLink
[ERROR]   PinotLArrayByteBufferTest>PinotDataBufferTest.testViewAndToDirectByteBuffer:205 » UnsatisfiedLink
[INFO] 
[ERROR] Tests run: 128, Failures: 10, Errors: 0, Skipped: 0
```

I suspect it's related with [xerial/larray](https://github.com/xerial/larray) which doesn't mention MacM1/2 support. Should create a `mac_m1_m2` profile to exclude these tests?
```
larray-mmap (MMapBuffer and LArray.mmap) uses JNI and is available for the following major CPU architectures:

Windows (32/64-bit)
Linux (i368, amd64 (Intel 64-bit), arm, armhf)
Mac OSX (Intel 64bit)
```
cc @mayankshriv

**Comment by Jackie-Jiang** [comment]
@gortiz I remember you encountered similar issue?

**Comment by gortiz** [comment]
Hi @mingmxu. You have to options:
1. Use Rosetta to run maven, as explained in [Pinot doc](https://docs.pinot.apache.org/basics/getting-started/running-pinot-locally#m1-and-m2-mac-support). Remember that Rosetta must be enabled in your shell. You can verify if it is the case by executing `mvn --version`, which will print the `arch` it is using. It should say `amd64`. In case Rosetta is disabled, it would say `arch: "aarch64"`.
2. Run maven with Java 17, which will not use LArray but the new buffer library that doesn't use JNI

**Comment by mingmxu** [comment]
Thanks @gortiz for the suggestions. I don't find a `amd64` JVM, would try the approach later.

Java17 helps to block the LArray JNI failure, there's another `clp-ffi` in `pinot-core` module, cc @kirkrodrigues who might have some context.

**Comment by gortiz** [comment]
I usually use sdkman to install different JDKs. In case you are using it, you need to enable Rosetta in sdkman as well in order to install the amd64 JDK. This article explains how to do use sdkman to install JDKs in different architectures: https://itnext.io/how-to-install-x86-and-arm-jdks-on-the-mac-m1-apple-silicon-using-sdkman-872a5adc050d.

**Comment by kirkrodrigues** [comment]
Hi @mingmxu, clp-ffi doesn't have aarch64 support yet. I will try and add it this weekend and submit a PR.

**Comment by ankitsultana** [comment]
@kirkrodrigues : if it is not a lot of work for you folks, can you try to add this support?

mvn tests don't work on M1/M2 systems because of this.

**Comment by kirkrodrigues** [comment]
Sorry, things keep getting reprioritized. We did create a build with the new binaries, just need to finish testing it on different platforms. Will release a new clp-ffi version in the next couple days and then PR to Pinot.

**Comment by gortiz** [comment]
We have now Maven profiles for aarch64 (see https://github.com/apache/pinot/pull/13648) which disabled the CLP tests. Once we have the CLP binaries for aarch64 we can enable these tests again.

Should we close this issue as resolved?

**Comment by ankitsultana** [comment]
This worked for me finally! Thanks a lot folks!

Will close this. We can re-open if the issue still exists.
