### ISSUE TITLE
Text Index does not match against mutable segments for MV Columns

### ISSUE THREAD

**Issue by itschrispeck** [apache/pinot#10975]
### Problem 
I'm querying a column via text_match that is a MV String column. This results in partial results as consuming segments cannot be matched on. Looking into this, the cause appears to be that text index on MV columns for mutable segments [is not yet supported](https://github.com/apache/pinot/blob/master/pinot-segment-spi/src/main/java/org/apache/pinot/segment/spi/index/mutable/MutableTextIndex.java#L34). 

I'm curious to get others' input on implementation options. I'm also curious about [support for the noDict implementation for mutable var-width column types](https://github.com/apache/pinot/blob/master/pinot-segment-local/src/main/java/org/apache/pinot/segment/local/segment/index/forward/ForwardIndexType.java#L293C18-L293C18)

cc: @kirkrodrigues @chenboat

**Comment by Jackie-Jiang** [comment]
cc @atris
