### ISSUE TITLE
json_extract_scalar times out when the expression contains index

### ISSUE THREAD

**Issue by wirybeaver** [apache/pinot#10981]
json_extract_scala times out even though the returned number of rows is only 1.

```
SELECT json_extract_scalar(direct_tags, '$.root_workflow[0].tag_value', 'STRING')
FROM foo
where event_time=1687826999657
```

Directly poll the column works.
```
SELECT direct_tags
FROM foo
where event_time=1687826999657
```
The result below
{"parent_workflow":[{"tag_attribute":"direct","tag_value":"XXX"}],"root_workflow":[{"tag_attribute":"direct","tag_value":"YYY"}],"workflow":[{"tag_attribute":"direct","tag_value":"ZZZ"}],"workflow_type":[{"tag_attribute":"direct","tag_value":"UUU"}]}

**Comment by chenboat** [comment]
cc @Jackie-Jiang @mayankshriv

**Comment by wirybeaver** [comment]
The pinot field spec:
    {
      "name": "direct_tags",
      "dataType": "STRING",
      "maxLength": 102400
    }

**Comment by wirybeaver** [comment]
```
SELECT *
FROM rta_odin_analytics_staging_audit_v6
where JSON_MATCH(direct_tags, '"$.root_workflow[0].tag_value" = ''foo''')
```
works

**Comment by wirybeaver** [comment]
All segments are in Consuming State, i.e., mutable segment

**Comment by jackluo923** [comment]
Based on my experimentation and the version of Pinot you are currently using, it appears that there may be difficulties when using json_extract_scalar to extract values from JSON documents that contain keys with an array of maps. A work around is to extract the maps within the array using `regexpExtract` before running `json_extract_scalar`. Specifically, this will work with your example: 

```
select json_extract_scalar(regexpExtract("direct_tags", '(?<=\"root_workflow\":\[)[^\]]*'), '$.tag_value', 'STRING') from foo 
 where event_time=1687826999657
```

**Comment by wirybeaver** [comment]
version 0.12 works fine. Close this issue
