### ISSUE TITLE
Block-level, intra-segment bloom filters

### ISSUE THREAD

**Issue by egalpin** [apache/pinot#10998]
This idea is not mine, but rather was mentioned by @npawar during the '22 RTA Summit video covering Tiered Storage[1]. The context in the video was using block-level bloom filters to enable loading of blocks in parallel / knowing which blocks would (likely) contain the sought after data.

Has this idea been explored for "local" pinot as well (coupled compute and storage), or would its overhead not provide query processing speed improvements?

[1] https://www.youtube.com/watch?v=nEAvHAvh0tY

**Comment by Jackie-Jiang** [comment]
cc @klsince

**Comment by klsince** [comment]
Yes. This idea has been implemented as sparse index, an extension available in StarTree Pinot: https://dev.startree.ai/docs/startree-extensions/sparse-index for more details. It works well with both “local” and “remote”, particularly for columns with very high cardinality. 

Loop in @gortiz the author of this feature to shed more light if needed.

**Comment by egalpin** [comment]
Thanks all 👍  I'll close this issue out so it doesn't appear as outstanding work etc.
