### ISSUE TITLE
pinot-client unable to dynamically choose broker for multi-table query

### ISSUE THREAD

**Issue by walterddr** [apache/pinot#11003]
see follow-up in #10873 

we replaced the simple SqlNode-based parsing mechanism to extract all visited tables with Calcite's relational toolset because it handles a much wider range of corner cases. 

However, this is a problem for pinot-client: pinot-client doesn't have a full picture of all the tables and their associated schema/config info to successfully create a local logical planner. thus it cannot determine the list of tables to look for common broker tenant/host. 

several redesign thoughts are possible
1. only allow controller-based broker selector in the multi-tenant scenario. otherwise fall back to random tenant/host selection 
    - additionally it also need to build a local table cache within the client
    - or hit controller endpoint to get query routing info before hitting the broker
2. utilize DML to gather information about table/schema in pinot-client. 
3. explicitly ask for broker tenant info in pinot-client

**Comment by abhioncbr** [comment]
I want to give it a try. Please assign it to me. Thanks

**Comment by walterddr** [comment]
this is fixed by #11069
