### ISSUE TITLE
[multistage]: Removing 'experimental feature' message for v2 multi-stage engine on UI

### ISSUE THREAD

**Issue by abhioncbr** [apache/pinot#11026]
Currently, when we use the V2 multi-stage query engine on Pinot UI, we get the default message  
```
Using V2 Multi-Stage Query Engine. This is an experimental feature. Please report any bugs to Apache Pinot Slack channel.
```

Do we have any plans to remove the message in the near future?

**Comment by Jackie-Jiang** [comment]
Once we believe V2 engine is mature enough (need some verification in real prod environment), we will remove this message. Currently we are still actively adding a lot of features into V2.
cc @walterddr

**Comment by abhioncbr** [comment]
With this [PR](https://github.com/apache/pinot/pull/11336), no more `experimental` message on UI. Thanks @jayeshchoudhary
