### ISSUE TITLE
Improve `DateTimeGranularitySpec` to follow the convention of new dateTimeField

### ISSUE THREAD

**Issue by snleee** [apache/pinot#11028]
https://docs.pinot.apache.org/configuration-reference/schema#new-datetime-formats

We have introduced the new datetime formats `e.g. EPOCH|MILLISECONDS|1`

On the other hand, our granularity spec is still following the old format `e.g. 1:MILLISECONDS`. 

We should provide the support of new format for `DateTimeGranularitySpec` as well.

Proposed change:

```
old format: 
size:timeUnit -> 1:MILLISECONDS

new format:
timeUnit|size -> MILLISECONDS|1
```

**Comment by snleee** [comment]
@rajagopr

**Comment by s0nskar** [comment]
Hi @snleee, I would like to work on this.

**Comment by s0nskar** [comment]
@snleee Raised PR for the same PTAL
