### ISSUE TITLE
[multistage]: Support different output formats(XML, JSON, DOT and TEXT) for explain physical plan

### ISSUE THREAD

**Issue by abhioncbr** [apache/pinot#11039]
**Problem**
Currently, `ExplainPlanPlanVisitor.explain` ([code reference](https://github.com/apache/pinot/blob/master/pinot-query-planner/src/main/java/org/apache/pinot/query/planner/ExplainPlanPlanVisitor.java#L63)) provides the physical plan of the SQL query in a simple text format. One such example of the output is as follows.
```
 [0]@localhost:3 MAIL_RECEIVE(RANDOM_DISTRIBUTED)
├── [1]@localhost:2 MAIL_SEND(RANDOM_DISTRIBUTED)->{[0]@localhost@{3,3}|[0]}
│   └── [1]@localhost:2 PROJECT
│      └── [1]@localhost:2 TABLE SCAN (a) null
└── [1]@localhost:1 MAIL_SEND(RANDOM_DISTRIBUTED)->{[0]@localhost@{3,3}|[0]}
   └── [1]@localhost:1 PROJECT
      └── [1]@localhost:1 TABLE SCAN (a) null
```

`EXPLAIN PLAN FOR` SQL query supports various formats(XML, JSON, DOT and TEXT), and with the solution approach to the [issue](https://github.com/apache/pinot/issues/10901)(support explain on physical plan ); the output of the physical plan of the query should follow the same format as mentioned in the `Explain` Query.

**Solution Approach**
- Extend the `ExplainPlanPlanVisitor` class for different output formats and generate the physical plan based on the format mentioned in the `Explain` query.
- `TEXT` will be the default output format, if not mentioned in the `Explain` query.

**NOTE**
example of the `Explain` query with format option
```
EXPLAIN Plan As JSON Select * from airlineStats
```

labels:
- enhancement

cc: @walterddr

**Comment by walterddr** [comment]
i think it is fine not to do the formatting for physical plan. it is no longer a tree (but a DAG) so 
- it doesn't seem desirable to support the JSON and XML format which technically still is a tree structure
- supporting DOT is definitely desirable but i would assume the effort would be a lot.

**Comment by abhioncbr** [comment]
Okay, I got the point. Let me close the issue and in future, if we want to support `DOT`, we will create a new task. Thanks

**Comment by gortiz** [comment]
I think we are merging terms here. Our custom physical implementation may be a DAG, but the plan is always a tree.

At the same time it is not clear to me the difference between Calcite default `EXPLAIN PLAN WITH IMPLEMENTATION` and our extension `EXPLAIN IMPLEMENTATION PLAN`. But having the two versions is very confusing and right now (1.1.0) `EXPLAIN PLAN WITH IMPLEMENTATION` does literally does the same thing as `EXPLAIN PLAN`, which is even more confusing.

**Comment by Jackie-Jiang** [comment]
@gortiz Seems like `EXPLAIN IMPLEMENTATION PLAN` is Pinot customized SQL syntax. Is `EXPLAIN PLAN WITH IMPLEMENTATION` a commonly used way for showing physical plan? If so, I'd suggest moving to the standard syntax

**Comment by abhioncbr** [comment]
Referring the [PR](https://github.com/apache/pinot/pull/11052) where we have introduced this. 

@gortiz mentioned it correctly, We want the physical and logical plan separately. If I remember it correctly, following the standardized Calcite approach, we weren't able to to get the physical plan alone. Logical plan is always there and hence we came up with the Pinot specific way to get physical plan.

**Comment by gortiz** [comment]
I've created [this document](https://docs.google.com/document/d/14YD-Tbb2NxxMULwpFX4b6uC9YjhygPYgiHvI0jt0q0s/edit#heading=h.om79hm58o58) to try to summarize the current explain options we want and to propose a unified future version.

**Comment by gortiz** [comment]
I've created https://github.com/apache/pinot/issues/12696 to show the current explain state and to propose a new version where explain behaves in the same way in V1 and V2. I'm not planning to work on this in the short term but I think it may be useful to have it.
