### ISSUE TITLE
[feature-request] Add Support for SQL Formatting in Controller Query Editor

### ISSUE THREAD

**Issue by ankitsultana** [apache/pinot#11116]
Would be great if we had a one click button to pretty-format the sql in the controller query editor. There are open-source libs which may be used: https://www.npmjs.com/package/sql-formatter

Leaving it as a feature request since I am not familiar with the frontend code in Pinot.

**Comment by ArnavBalyan** [comment]
This would be super helpful! I would like to work on this, can you please assign it to me. Thanks!
