### ISSUE TITLE
Delete the usage of the old commons-httpclient dependency 

### ISSUE THREAD

**Issue by abhioncbr** [apache/pinot#11118]
Currently, pinot has the dependency both on [commons-httpclient](https://github.com/apache/pinot/blob/master/pom.xml#L523C18-L523C36) and [httpcomponents](https://github.com/apache/pinot/blob/master/pom.xml#L302). 

I think using the two versions of the same library doesn't make much sense. We should delete the use of the old version, i.e. `commons-httpclient`. Also, the removal of this dependency helps us get rid of some of the vulnerabilities because of the library. 

- `commons-httpclient` is getting used in a handful of classes, and to remove the dependency, we need to make the changes in the classes using it.

I can work on it if this looks good. Thanks

cc: @Jackie-Jiang 

labels: dependency

**Comment by Jackie-Jiang** [comment]
I'm +1 to this

**Comment by xiangfu0** [comment]
+1

**Comment by abhioncbr** [comment]
Done.
