### ISSUE TITLE
Support Native Text Index on columns of multi-value type

### ISSUE THREAD

**Issue by Aravind-Suresh** [apache/pinot#11123]
Currently, in Pinot, we have native text index on single value columns (strings). We lack that functionality on multi value columns.

The idea is to support an OR-based search on this collection of strings - if any of the string in this collection matches the provided term, the predicate evaluates to true and all such rows are returned.

cc @atris

**Comment by atris** [comment]
Please refer to:

https://github.com/apache/pinot/pull/11000 for reference on how to add this capability

**Comment by utulshigiri** [comment]
added by @itschrispeck in https://github.com/apache/pinot/pull/11204.
