### ISSUE TITLE
[flakytest] timeout in fork most likely on RealtimeKinesisIntegrationTest

### ISSUE THREAD

**Issue by walterddr** [apache/pinot#11135]
see 
https://github.com/apache/pinot/actions/runs/5595643067/jobs/10231738127?pr=11132 
https://github.com/apache/pinot/actions/runs/5595738571/jobs/10231935149?pr=11133
https://github.com/apache/pinot/actions/runs/5600370566/jobs/10242653727?pr=11105

which occurs on 3 different PR

**Comment by Jackie-Jiang** [comment]
Kinesis consumer was re-implemented in #12806. Don't observe the same failure since then
