### ISSUE TITLE
[multistage][agg] count(*) return final result on leaf causes compilation error

### ISSUE THREAD

**Issue by walterddr** [apache/pinot#11168]
```
select /*+ aggOptions(is_partitioned_by_group_by_keys = 'true') */
AirlineID, count(*)
from airlineStats 
group by 1
order by 2
```
causes error b/c directly the `order by` operation cannot know count(*) is a non-nullable result column thus the isNullLast check in query context compilation will fail (b/c V2 engine doesn't carry the `*` argument over to the QueryContext thus causes isNullLast check accessing operand position out of bound:
```
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:372) ~[?:?]
	at java.util.ArrayList.get(ArrayList.java:459) ~[?:?]
	at org.apache.pinot.core.query.request.context.utils.QueryContextConverterUtils.isNullsLast(QueryContextConverterUtils.java:178) ~[classes/:?]
```

**Comment by walterddr** [comment]
CC @Jackie-Jiang @shenyu0127 @vvivekiyer 
basically this unfortunate error only occurs if v2 engine compiles count(*) and at the same time order by (SortNode) gets push down to leaf. 
- null check assumes QueryContext expression cannot have empty operand;
- count(*) pushing down to leaf will not have an operand (or the `*` is stripped)

potential solution 
1. add a dummy (*) during physical plan construction
2. make v1 QueryContextConverterUtils handle empty operand 

I am more in favor of solution 1. thoughts?

**Comment by Jackie-Jiang** [comment]
In `RequestContextUtils` line 94-95 I can see a TODO to handle count without argument. I think we should just add the dummy `*` in leaf stage so that the format is the same as v1

**Comment by abhioncbr** [comment]
Please assign it to me. Thanks

**Comment by walterddr** [comment]
oops too late @abhioncbr :-)

**Comment by shenyu0127** [comment]
Once https://github.com/apache/pinot/pull/11199 is checked in, the isNullsLast check will not fail for empty operand inside NULLS_LAST/NULLS_FIRST/ASC/DESC.

**Comment by walterddr** [comment]
this is needed b/c other empty operand functions such as `now()` will still be impacted (although currently it is not a valid query in v1) thank you for the follow up @shenyu0127
