### ISSUE TITLE
Delete format support in Explain physical plan sql queries

### ISSUE THREAD

**Issue by abhioncbr** [apache/pinot#11178]
Recently, we started supporting the [physical plan](https://github.com/apache/pinot/issues/10901) for the queries based on the `EXPLAIN IMPLEMENTATION PLAN`. 

However, the implemented [solution](https://github.com/apache/pinot/pull/11052) supports different formats, which doesn't make sense. We already have [discussed](https://github.com/apache/pinot/issues/11039) it. Based on it, this is just a minor follow-up issue to remove the format support in the physical plan queries.

labels: multistage

cc: @walterddr

**Comment by abhioncbr** [comment]
fix, https://github.com/apache/pinot/pull/11179

**Comment by walterddr** [comment]
Good catch!
