### ISSUE TITLE
Filtering NULL support

### ISSUE THREAD

**Issue by shenyu0127** [apache/pinot#11209]

**Comment by shenyu0127** [comment]
https://github.com/apache/pinot/pull/11199
https://github.com/apache/pinot/pull/11198
https://github.com/apache/pinot/pull/11185
https://github.com/apache/pinot/pull/11137
https://github.com/apache/pinot/pull/11078

**Comment by shenyu0127** [comment]
https://github.com/apache/pinot/pull/11188

**Comment by shenyu0127** [comment]
https://github.com/apache/pinot/pull/11249
https://github.com/apache/pinot/pull/11220
https://github.com/apache/pinot/pull/11242

**Comment by shenyu0127** [comment]
Fixing some regressions: 
https://github.com/apache/pinot/pull/11257
https://github.com/apache/pinot/pull/11253

**Comment by PeterCorless** [comment]
I know this is closed, but can there be any better comments made for this feature?
