### ISSUE TITLE
Emit LL consumer current offset metrics

### ISSUE THREAD

**Issue by itschrispeck** [apache/pinot#11238]
Pinot already logs currentOffset in [LLRealtimeSegmentDataManager](https://github.com/apache/pinot/blob/c68b3be360fafac1c38f3322ed5fa64201d08daf/pinot-core/src/main/java/org/apache/pinot/core/data/manager/realtime/LLRealtimeSegmentDataManager.java#L1648). We'd like to emit this as a metric. 

The goal is to use this metric to enable automation for Kafka expansion to handle increases in ingestion throughput automatically. It's difficult to define set bytes/messages per sec limits to trigger. Table configs + the messages' data structures have large implications on throughput per partition.

**Comment by mcvsubbu** [comment]
The LLRealtimeSegmentDataManager is a stream-agnostic class. The long offset is a Kafka-specific way of storing offsets. Other strings have strings, so emitting a metric from this class is not the best. 

I believe Kafka plugin already emits the metric. If not, we can add it there. Will that solve your problem?

**Comment by mcvsubbu** [comment]
There are a few other features we have that may be of help:

- Ingestion rate limiter
- Data freshness metric
- Ingestion based consumption status checker

**Comment by itschrispeck** [comment]
Thank you for the context! On closer inspection it looks like this metric is already emitted, but only for long offsets due to the issue you refer to

https://github.com/apache/pinot/blob/c68b3be360fafac1c38f3322ed5fa64201d08daf/pinot-core/src/main/java/org/apache/pinot/core/data/manager/realtime/LLRealtimeSegmentDataManager.java#L451
