### ISSUE TITLE
Tenant isolation / better task schedule prioritisation in minions  

### ISSUE THREAD

**Issue by tibrewalpratik17** [apache/pinot#11240]
At present, there is no way to associate specific minion hosts to execute tasks for a set of tables or prioritise task for those tables.
This is similar to tenancy model we have for broker and server. 

One idea is to have an additional config in tables: `minionTenant` and use minion instance tags to assign those instances to execute tasks for those tables. This will also help in attribution of costs for the minion nodes to be simplified. 

Another approach can be to have some scheduling logic in minions to prioritise tasks for table A over table B based on some config parameter.

Related slack thread: https://apache-pinot.slack.com/archives/C013WKLT5T7/p1690229524236789

cc @atris

**Comment by Jackie-Jiang** [comment]
cc @snleee 

Adding minion tenant sounds good. We might want to add it to the tenant config, but also allow overriding it on a per task basis in case user want to run a task type on a given tenant.

**Comment by atris** [comment]
Thanks for the inputs @Jackie-Jiang . I am working on a WIP right now and will post soon.

**Comment by tibrewalpratik17** [comment]
Closing this as it is superseded by #12698.
