### ISSUE TITLE
Create a separated query endpoint for multi-stage query engine

### ISSUE THREAD

**Issue by xiangfu0** [apache/pinot#11251]
This majorly beneficial for data Viz tooling like superset or retool which can specify a different query endpoint for multi-stage query engine without making any frontend change.

E.g. current superset connection string is: `pinot://pinot-broker:8099/query/sql?controller=http://pinot-controller:9000/`
[Link to Add Pinot Database in Superset](https://docs.pinot.apache.org/integrations/superset#adding-pinot-database)

We can create a new endpoint for multi-stage query at `pinot://pinot-broker:8099/query/v2/sql?controller=http://pinot-controller:9000/`

Changes proposed:
1. Add new query endpoint for multi-stage query engine in controller and broker
2. Follow up: Update java/python/golang clients to use the new endpoint.

**Comment by Jackie-Jiang** [comment]
I'm not a big fan of `v2`. If we are not going to change to v3 (hopefully not), maybe we can just use `/query` and eventually deprecate `/query/sql`

**Comment by abhioncbr** [comment]
Please assign it to me if not urgent.
