### ISSUE TITLE
Pinot Does not FSync and Relies on FD Close

### ISSUE THREAD

**Issue by ankitsultana** [apache/pinot#11368]
While playing with some Pinot data, I realized that Pinot in some instances doesn't do fsync and instead relies on `close(int fd)` calls (via `FileChannel#close`).

One example is here: https://github.com/apache/pinot/blob/master/pinot-segment-local/src/main/java/org/apache/pinot/segment/local/segment/creator/impl/inv/json/BaseJsonIndexCreator.java#L147

[Close doesn't flush data to disk](https://man7.org/linux/man-pages/man2/close.2.html#:~:text=Typically%2C%20filesystems%20do%20not%20flush,%2C%20use%20fsync) and one has to manually call `FileChannel#force` to make it happen (afaik).

In my case, I discovered this while playing with custom code on local where I was mimicking file reads/writes similar to how Pinot does it (by using FileChannel in try-resources) and found that the file wasn't getting written to.

I have just started playing with index related code so I might be missing something.

**Comment by Jackie-Jiang** [comment]
Great finding! Without force, the data should sit within the operating system's file I/O buffers if not written to disk yet. I don't know if OS is smart enough to force the data if we try to access the file after it is closed (e.g. compress the data), but I think it is best practice to force it especially when performance is not that critical.

**Comment by ArnavBalyan** [comment]
Hi I would like to work on this, can you please assign it to me. Thanks!
