### ISSUE TITLE
[Multi Stage] Add ROWS support for aggregation window functions

### ISSUE THREAD

**Issue by somandal** [apache/pinot#11406]
Today the aggregation window functions only support RANGE type window frames with the default frame boundaries (`UNBOUNDED PRECEDING` and `UNBOUNDED FOLLOWING`/`CURRENT ROW` depending on the existence of `ORDER BY` in the `OVER` clause). `ROWS` support exists for the `ROW_NUMBER` window function (this doesn't support RANGE type at all). We should add support for `ROWS` type frames for the aggregation window functions as well. For now we will do this for the default frame boundaries since sliding window support hasn't been added yet.

I'll be working on this change, please assign it to me

cc @siddharthteotia @walterddr @Jackie-Jiang

**Comment by siddharthteotia** [comment]
@somandal  will be working on this

**Comment by dan0nchik** [comment]
Hi! Any update on this? Can I help somehow? Really need this feature!

**Comment by Jackie-Jiang** [comment]
@xiangfu0 Can you confirm if this is already supported?

**Comment by yashmayya** [comment]
> We should add support for ROWS type frames for the aggregation window functions as well. For now we will do this for the default frame boundaries since sliding window support hasn't been added yet.

https://github.com/apache/pinot/pull/14273 adds this support as well as support for offset based ROWS window frames (`n PRECEDING` / `n FOLLOWING`) using a new sliding window based value aggregator mechanism. I'll update the documentation soon, there some to be multiple issues in the current documentation page for window functions.
