### ISSUE TITLE
[Flaky-test] TableCacheTest.testTableCache

### ISSUE THREAD

**Issue by Jackie-Jiang** [apache/pinot#11435]
Error:  org.apache.pinot.controller.helix.TableCacheTest.testTableCache[false](2)  Time elapsed: 0.024 s  <<< FAILURE!
org.apache.pinot.controller.api.exception.TableAlreadyExistsException: External view for cacheTestTable_OFFLINE still exists. If the table is just deleted, please wait for the clean up to finish before recreating it. If the external view is not removed after a long time, try restarting the servers showing up in the external view
	at org.apache.pinot.controller.helix.core.PinotHelixResourceManager.addTable(PinotHelixResourceManager.java:1549)
	at org.apache.pinot.controller.helix.TableCacheTest.testTableCache(TableCacheTest.java:102)

**Comment by ege-st** [comment]
@Jackie-Jiang what's the best way to wait for the table to be deleted? Use `waitForCondition` and wait until the table no longer exists?

Maybe, unless we're specifically testing table deletion, we should use use some kind of "name mangling" on the table names every test uses to make sure there is no conflict between them.

**Comment by Jackie-Jiang** [comment]
What could potentially happen is that the table creation and deletion happens so fast, and EV for the previous table is not even created before the table is deleted. Then it is created just after the EV check for the new table creation.
To fix it, we can wait for EV to show up before dropping the table

**Comment by ege-st** [comment]
@Jackie-Jiang that makes sense. Also, I'm guessing we have a few other tests that have similar race conditions.
