### ISSUE TITLE
Add array UDFs to operate multiple MV columns

### ISSUE THREAD

**Issue by wirybeaver** [apache/pinot#11442]
Data Model, tag_names, tag_values and tag_properties are MultipleValue columns.
tag_names: [x, foo, foo, x]
tag_values: [bar, y, y, y]
tag_properties: [a, b, c, d]

We have a customer want to move from Clickhouse to Pinot and their CH expression below:  
`arrayElement(tag_properties, arrayFirstIndex (( n, v) -> n = 'x' AND v = 'y', tag_names,  tag_values))`
return `d`

Another advanced usage is 
`arrayElement(tag_properties, arrayFirstIndex (( n, v) -> n = 'x' AND match(bar, '/.*fo.*/'), tag_names,  tag_values))`
return `a`

https://clickhouse.com/docs/en/sql-reference/functions/array-functions

In order to meet `arrayElement(tag_properties, arrayFirstIndex (( n, v) -> n = 'x' AND v = 'y', tag_names,  tag_values))`, I wanted to contribute following ArrayFunctions below: `arrayElement(tag_properties, arrayFirstInt(arrayIntersect(arrayIndexAllString(tag_name, x), arrayIndexAllString(tag_value, y))))`

```
arrayIndexAllString(tag_name, x) -> [0,3]
arrayIndexAllString(tag_value, y) -> [1, 2, 3]
arrayIntersect([0,3], [1,2,3]) -> [3] (Note, the result is always sorted)
arrayFirstInt([3]) -> 3
arrayElement(tag_properties, 3) -> d
```

For the lambda expression implementation (regexp should be part of the lambda), it's out of the scope of this PR. In my two cents, maybe we can use groovy in the future.

**Comment by Jackie-Jiang** [comment]
`arrayFirstInt(col)` is equivalent to `arrayElementAtInt(col, 0)`
`arrayElement` is available in different types (currently pinot doesn't have type matching, so the type needs to be included in the function name

Would you like to help contribute the other 3?

**Comment by wirybeaver** [comment]
> `arrayFirstInt(col)` is equivalent to `arrayElementAtInt(col, 0)` `arrayElement` is available in different types (currently pinot doesn't have type matching, so the type needs to be included in the function name
> 
> Would you like to help contribute the other 3?

yep, I will contribute the ArrayIndexAll{Type} and ArrayIntersect.

**Comment by xiangfu0** [comment]
Also, does `arrayIndexAllString(tag_name, x)` have an implicit filter of `WHERE tag_name=x` ?

**Comment by wirybeaver** [comment]
> Also, does `arrayIndexAllString(tag_name, x)` have an implicit filter of `WHERE tag_name=x` ? If so we can also leverage inverted index for filtering.

Great idea. But the result needs to be the index in the MV column. I need to check how to leverage inverted index.

**Comment by xiangfu0** [comment]
Yeah, I would first try to rewrite the query `arrayElement(tag_properties, arrayFirstIndex (( n, v) -> n = 'x' AND v = 'y', tag_names,  tag_values))` to pinot format.
E.g.
```
SELECT 
    arrayElement(
        tag_properties,
        arrayElementAtInt(
            arrayIntersect(
                arrayIndexAllString(tag_name, x),
                arrayIndexAllString(tag_value, y)
            ),
            0
        )
    )
FROM myTable
WHERE tag_name=x AND tag_value=y
```
