### ISSUE TITLE
Enable Compression on BYTES star tree index

### ISSUE THREAD

**Issue by t0mpere** [apache/pinot#11485]
https://github.com/apache/pinot/issues/9694#issue-1430395681

In our use case building a star tree index using `distinctcounthll` as aggregation function is VERY expensive in terms of space used. Would it be possible to turn on compression? Thanks

**Comment by Jackie-Jiang** [comment]
It should be doable. Would you like to help contribute this?

**Comment by t0mpere** [comment]
I can look into it but I'd need some directions. Do you have some design documents on this side of Pinot?

**Comment by Jackie-Jiang** [comment]
Let's use the original issue ticket to track this
