### ISSUE TITLE
Broker Cache

### ISSUE THREAD

**Issue by xiangfu0** [apache/pinot#115]
Right now every query hitting broker will be scatter gathered to servers. We can make a simple caching layer in broker to keep the most recent query and response.
We can use com.google.common.cache.LoadingCache to handle request as well as cache results.

Some thoughts:
1. cache should have a configurable size and expire after a configurable time.
2. Some queries may not be cached (e.g. query without up-bound time value specified) 
3. Current request metrics need to compile request first. Otherwise we don't which table this request will query.
4. In order to achieve 2, we need to compile the query, get table name, get time column from the table, and check query time range.

**Comment by raviarin** [comment]
Few other thoughts
1. It would be great to include a flag or some property in the response to indicate that the response came from the cache. This will help in future debugging.
2. User should be able to bypass the cache by passing in a request flag / property. 
3. Not sure what you plan to store in the cache, but consider the performance of serialization / deserizalation of objects in cache. Sometimes it might be better to store the raw serialized version from the server cache to avoid overhead. This is a perf optimization and can be prioritized for a later time.
4. What happens to cached rows if the underlying segments expire or gets deleted?
5. It will be good to list out the cache invalidation scenarios. May be to begin with it is purely time based?

**Comment by Jackie-Jiang** [comment]
Same as #656
