### ISSUE TITLE
COUNT(DISTINCT col1, col2) does not throw a syntax error and returns an incorrect result

### ISSUE THREAD

**Issue by cyrilou242** [apache/pinot#11503]
## Problem Observed
Context:  
`DISTINCTCOUNT` can only apply on one column. This is an expected behaviour.  
`COUNT(DISTINCT(col))` is rewritten to `DISTINCTCOUNT(col)`. This is the expected behaviour.

Problem:  
`COUNT(DISTINCT col1, col2)` should not be supported and throw a syntax error.
Currently, it is accepted and rewritten to `DISTINCTCOUNT(col1)`. Notice `col2` is lost.

## How to reproduce
```
select 
COUNT(DISTINCT DestStateName),
COUNT(DISTINCT DestStateName, OriginAirportID)
from airlineStats limit 10
```

Returns
```
|distinctcount(DestStateName)|distinctcount(DestStateName)|
|           53               |           53               |
```

## Expected behaviour: 
COUNT(DISTINCT col1, col2) should throw a SQL syntax error.

A different ticket will be opened to support COUNT DISTINCT on multiple columns with query engine v2.

**Comment by cyrilou242** [comment]
Thanks a lot @Jackie-Jiang!

**Comment by prajyotkcsu** [comment]
good observation!
