### ISSUE TITLE
Broker fails to start because of reflexion on methods using Boolean type

### ISSUE THREAD

**Issue by jvenant** [apache/pinot#11525]
I think there is an issue with this commit 6c69be463fea9ba9c0fe0103215f47581d41f8d4 preventing broker server to start

It happen during reflection when the server search for `@ScalarFunction` annotated methods. A ReflectionsException is raised complaining that `ObjectFunctions` doesn't have `caseWhen` member
I think it's more a bug in Reflexion library itself. It seems to be confuse with the Boolean type and boolean native type.
the `Reflections.getMethodsAnnotatedWith` (called from `PinotReflectionUtils.getMethodsThroughReflection`) generate a methods descriptor String looking like :
`org.apache.pinot.common.function.scalar.ObjectFunctions.caseWhen(boolean, java.lang.Objet, ...)`
and compare it with the method signature : 
`org.apache.pinot.common.function.scalar.ObjectFunctions.caseWhen(java.lang.Boolean, java.lang.Objet, ...)`
in `Utils.getMemberFromDescriptor`
As the two signatures don't match. It can't find the class member and raise the exception

**Comment by xiangfu0** [comment]
Interesting, can you share the jdk version or the docker image you are using?

**Comment by xiangfu0** [comment]
Ack, we recently deprecated the support for openjdk and switched to `amazoncorretto`.
Can you try: `apachepinot/pinot-base-build:11-amazoncorretto` and `apachepinot/pinot-base-runtime:11-amazoncorretto`?
Also you can refer to https://github.com/apachepinot/pinot-fork/blob/master/docker/images/pinot/Dockerfile.build and https://github.com/apachepinot/pinot-fork/blob/master/docker/images/pinot/Dockerfile.package
for image build and package.

**Comment by jvenant** [comment]
I found the root cause. I have a pinot plugin depending on an older version of pinot.
This plugin build a fat jar using the shade maven plugin.
Pinot packages were not exclude from the fat jar.
So reflections lib found older versions of the methods signatures in the classpath and put them in its store.

So I think it's a good practice to exclude pinot packages from plugins shaded jars

I close this issue
