### ISSUE TITLE
Pinot minions not building NATIVE indices

### ISSUE THREAD

**Issue by shwin** [apache/pinot#11520]
Pinot version: `apachepinot/pinot:0.13.0-SNAPSHOT-f31ce3835c-20230823-11-ms-openjdk-linux-arm64` 
Full table config here: https://gist.github.com/shwin/7817b6d96a9facf6687f749bbe1a1507

When building a segment on a **minion**, native indices are **not** built; that is, there are no `.nativetext.idx` present in the segments pushed to the segment output directory.

This is unlike lucene indices, which are present:
```
columns.psf                                    creation.meta                                  index_map                                      toProtocolAttributes.lucene.index              transactionToProtocolAttributes.lucene.index
contractAddressProtocolAttributes.lucene.index fromProtocolAttributes.lucene.index            metadata.properties                            transactionFromProtocolAttributes.lucene.index
```

I suspect this is not a problem with our table config, since the ***servers*** do attempt to build the native text indices; this is a snippet from a **server** log:
```
Creating new text index for column: chain in segment: 6ace1858-ec7e-4bc8-acea-abbeb48f16d2-test-one-segment_OFFLINE_1641487292000_1641509420000_0_a42ac055-2275-425d-b623-492f08bfa591, hasDictionary: true
83
Created text index for column: chain in segment: 6ace1858-ec7e-4bc8-acea-abbeb48f16d2-test-one-segment_OFFLINE_1641487292000_1641509420000_0_a42ac055-2275-425d-b623-492f08bfa591
79
```

The native index files are then present on the **servers.**

This is bad, since our servers end up undergoing a lot more memory and CPU pressure (see this gist for an example server stack trace: https://gist.github.com/shwin/a80c8c648d9251723e4a6cf2699023eb, but that's a separate issue).

If this happened on minions, that would be one thing; this happening on our servers is a lot more impactful.

See https://apache-pinot.slack.com/archives/C011C9JHN7R/p1693783364237779 for more discussion, but I think this is a decent summary.

**Comment by shwin** [comment]
https://github.com/apache/pinot/issues/10934 is probably related to the stack above, but still want to get to the bottom of why minions are not building the segments.

**Comment by shwin** [comment]
cc @atris

**Comment by xiangfu0** [comment]
How much memory do you configure for minion? Does it work when you give more memory?

**Comment by shwin** [comment]
@xiangfu0 sorry, I cleared up the description. The stack trace happens on servers, but we can set that aside for a second; the minions are not *attempting* to build the native indices at all, which is the bug here.

**Comment by Jackie-Jiang** [comment]
@gortiz Can you help take a look? I took a quick look and seems `TextIndexType.getFileExtension()` always returns lucene index extension. Not sure if that is related

**Comment by gortiz** [comment]
I've just created https://github.com/apache/pinot/pull/11600 which may fix this issue. As indicated by @Jackie-Jiang, TextIndexType.getFileExtension was incorrect. I didn't have the chance to verify if this PR fixes the error reported here. I'm optimistic, but I won't have time to verify that before next week.

**Comment by hpvd** [comment]
@shwin does this merged fix solves this issue for you?
