### ISSUE TITLE
Reloading segments does not update LUCENE vs NATIVE text indices

### ISSUE THREAD

**Issue by shwin** [apache/pinot#11529]
Say you have a field defined on a table like:
```
{
        "name": "chain",
        "encodingType": "RAW",
        "indexType": "TEXT",
        "indexTypes": [
          "TEXT"
        ],
        "indexes": null,
        "tierOverwrites": null,
        "properties": {"fstType":  "native"}      
},
```

You run into some issues (https://gist.github.com/shwin/a80c8c648d9251723e4a6cf2699023eb) loading segments, so you switch that back to a regular text index:
```
{
        "name": "chain",
        "encodingType": "RAW",
        "indexType": "TEXT",
        "indexTypes": [
          "TEXT"
        ],
        "indexes": null,
        "tierOverwrites": null
},
```

And you reload all your segments, expecting that the NATIVE indices would be dropped, and LUCENE indices added. This is not the case. The reload documentation is not clear on this front, eg, the UI says: `Reloads all segments of the table to apply changes such as indexing, column default values, etc`; I'd expect that to include the above change.

The alternative is to:
1. drop the original text index
2. reload all segments
3. add the updated text index back
4. reload all segments

But this is obviously inferior to just updating the index config and doing a single load.

**Comment by shwin** [comment]
In case it's helpful, @mneedham pointed me to https://github.com/apache/pinot/blob/master/pinot-segment-local/src/main/java/org/apache/pinot/segment/local/segment/index/loader/invertedindex/TextIndexHandler.java#L121, which seems to not handle this case.

**Comment by shwin** [comment]
cc @atris, not super pressing just something that would be helpful as we continue to try out native indices :)

**Comment by gortiz** [comment]
This should be fixed with https://github.com/apache/pinot/pull/11600

**Comment by hpvd** [comment]
@shwin does this merged fix solves this issue for you?
