### ISSUE TITLE
Protobuf Stream Config validationg assumes Kafka streams

### ISSUE THREAD

**Issue by JeffBolle** [apache/pinot#11530]
https://github.com/apache/pinot/blob/e949d958a8238a48ba147048fa72ada033ea889e/pinot-segment-local/src/main/java/org/apache/pinot/segment/local/utils/TableConfigUtils.java#L518

This function assumes that the streaming ingest will be `kafka`.  Something like this might work better:
```
  static void validateDecoder(StreamConfig streamConfig) {
    if (streamConfig.getDecoderClass().equals("org.apache.pinot.plugin.inputformat.protobuf.ProtoBufMessageDecoder")) {
      String streamType = streamConfig.getType();
      String descriptorFilePath = String.format("stream.%s.decoder.prop.descriptorFile", streamType);
      String protoClassName = String.format("stream.%s.decoder.prop.protoClassName",streamType);
      // check the existence of the needed decoder props
      if (!streamConfig.getDecoderProperties().containsKey(descriptorFilePath)) {
        throw new IllegalStateException("Missing property of descriptorFile for ProtoBufMessageDecoder");
      }
      if (!streamConfig.getDecoderProperties().containsKey(protoClassName)) {
        throw new IllegalStateException("Missing property of protoClassName for ProtoBufMessageDecoder");
      }
    }
  }
```
@navina

**Comment by xiangfu0** [comment]
Good catch, @JeffBolle do you want to open a PR to fix this?

**Comment by JeffBolle** [comment]
Maybe...I'm working another issue with missing metadata that is more important in my environment.

**Comment by navina** [comment]
@xiangfu0 I can create a PR for this. I think @JeffBolle is busy fixing the pulsar connector here - https://github.com/apache/pinot/pull/11542#issuecomment-1710485079
