### ISSUE TITLE
Queries that involve string timestamps do not work properly unless the string is singled quoted

### ISSUE THREAD

**Issue by jugomezv** [apache/pinot#11543]
I have a table with the following time column schema:

```
  "dateTimeFieldSpecs": [
    {
      "dataType": "STRING",
      "format": "1:DAYS:SIMPLE_DATE_FORMAT:yyyy-MM-dd-HH",
      "granularity": "1:DAYS",
      "name": "time_stamp"
    }
  ],

```

When I run the following query that should yield non-null output I do get empty response with no failure:

```
"SELECT \"time_stamp\", avg(\"fifteen_minutes_freshness\") AS \"fifteen_minutes_freshness:avg\" FROM DailyPinotGlobalDataFreshnessTable WHERE ((\"time_stamp\" >= 2023-08-02-00 AND \"time_stamp\" <= 2023-08-31-23)) GROUP BY \"time_stamp\"  ORDER BY avg(\"fifteen_minutes_freshness\") DESC  LIMIT 30"
+------------+-------------------------------+
| time_stamp | fifteen_minutes_freshness:avg |
+------------+-------------------------------+
+------------+-------------------------------+

```

Adding single quotes around the timestamp values makes the query work properly:
```

"SELECT \"time_stamp\", avg(\"fifteen_minutes_freshness\") AS \"fifteen_minutes_freshness:avg\" FROM DailyPinotGlobalDataFreshnessTable WHERE ((\"time_stamp\" >= '2023-08-02-00' AND \"time_stamp\" <= '2023-08-31-23')) GROUP BY \"time_stamp\"  ORDER BY avg(\"fifteen_minutes_freshness\") DESC  LIMIT 30"
+---------------+-------------------------------+
|   time_stamp  | fifteen_minutes_freshness:avg |
+---------------+-------------------------------+
| 2023-08-29-00 | 99.28717948717949             |
| 2023-08-30-00 | 98.84102564102564             |
| 2023-08-25-00 | 98.5228426395939              |
+---------------+-------------------------------+
```

**Comment by jugomezv** [comment]
Further more using a single boundary does yield a result but not the proper one:
```
"SELECT \"time_stamp\", avg(\"fifteen_minutes_freshness\") AS \"fifteen_minutes_freshness:avg\" FROM DailyPinotGlobalDataFreshnessTable WHERE (**\"time_stamp\" >= 2023-08-29-00**) GROUP BY \"time_stamp\"  ORDER BY avg(\"fifteen_minutes_freshness\") DESC  LIMIT 30"
+---------------+-------------------------------+
|   time_stamp  | fifteen_minutes_freshness:avg |
+---------------+-------------------------------+
| 2023-08-29-00 | 99.28717948717949             |
| 2023-08-30-00 | 98.84102564102564             |
| **2023-08-25-00** | 98.5228426395939              |
+---------------+-------------------------------+

```

When you do use single quotes around the time stamp, it does yield the proper result:
```

"SELECT \"time_stamp\", avg(\"fifteen_minutes_freshness\") AS \"fifteen_minutes_freshness:avg\" FROM DailyPinotGlobalDataFreshnessTable WHERE (\"time_stamp\" >= '2023-08-29-00') GROUP BY \"time_stamp\"  ORDER BY avg(\"fifteen_minutes_freshness\") DESC  LIMIT 30"
+---------------+-------------------------------+
|   time_stamp  | fifteen_minutes_freshness:avg |
+---------------+-------------------------------+
| 2023-08-29-00 | 99.28717948717949             |
| 2023-08-30-00 | 98.84102564102564             |
+---------------+-------------------------------+

```

**Comment by jugomezv** [comment]
This is not a big deal for manual queries but we do have some tooling that autogenerates queries like these that do work well in other SQL interface dbs but they produce the wrong output in Pinot silently: i.e. there is no error reported but the query result is incorrect.

**Desired Behavior:** is that query figures that the passed timestamp is a string with the format in the schema and parsed as such. If not and error must be reported while parsing the query.

**Comment by Jackie-Jiang** [comment]
This is incorrect. `2023-08-31-23` will be parsed as `2023 - 8 - 31 - 23` (minus) ==> `1961`. The query itself parses but is semantically wrong. String literal must be quoted

**Comment by jugomezv** [comment]
Uff that is a very misleading parsing, specially given the fact that the server knows that this field is a string: shouldn't the schema play a role here? If I am filtering on a string column using a numeral that should be an error right? or even better the field being used as filter should be interpreted as a string.

**Comment by Jackie-Jiang** [comment]
> Uff that is a very misleading parsing, specially given the fact that the server knows that this field is a string: shouldn't the schema play a role here? If I am filtering on a string column using a numeral that should be an error right? or even better the field being used as filter should be interpreted as a string.

AFAIK, no DB can handle this because that is the standard way of parsing it. We can make pinot fail the query if it detects type mismatch (this might be the standard SQL behavior), but that is an incompatible change because I can imagine people might ingest numbers as string type, and filter string with number
