### ISSUE TITLE
Remove deprecated methods from pinot-java-client

### ISSUE THREAD

**Issue by lucifer4j** [apache/pinot#11582]
With the 1.0 release of Pinot nearing, it would be nice to clean up the pinot-java-client module. There are a few deprecated methods like https://github.com/apache/pinot/blob/daa6d118396834135457d253cba0d6540b3cfa61/pinot-clients/pinot-java-client/src/main/java/org/apache/pinot/client/PinotClientTransport.java#L36 that can be removed.

There is also the interface https://github.com/apache/pinot/blob/daa6d118396834135457d253cba0d6540b3cfa61/pinot-clients/pinot-java-client/src/main/java/org/apache/pinot/client/PinotClientTransportFactory.java#L24 which has one method and the comment mentions that its deprecated as well.

Would a PR to remove this deprecated stuff be useful and acceptable?

(pinging @xiangfu0, since my earlier pinot-java-client PR's were reviewed by you)

**Comment by Jackie-Jiang** [comment]
Sure, let's clean them up!
