### ISSUE TITLE
Query response code/content is confusing 

### ISSUE THREAD

**Issue by walterddr** [apache/pinot#11593]
we have 2 query endpoints: `<controller_hostport>/sql` and `<broker_hostport>/query/sql`

when querying with proper queries they return the same results. however when there's an error. 
Controller returns different format of error comparing to broker
- Controller error for `SELECT * FROM tbl LIMIMIMIT 1`:
    HTTP code: 200; content: RAW STRING `SQLParsingError:\norg.apache.pinot.s .....`
- Broker error for `SELECT * FROM tbl LIMIMIMIT 1`:
    HTTP code: 200; content: JSON STRONG `{"requestId":null,"brokerId":null,"exceptions":[{"message":"SQLParsingError:\norg.apache.pinot.s...`

we should follow a single format. I propose to use JSON b/c both HTTP codes are return 200 indicating a valid request

backward incompatible, we will change the response content of a REST API

**Comment by Jackie-Jiang** [comment]
+1. We should at least return a valid JSON
