### ISSUE TITLE
segmentReloadStatus API never completes

### ISSUE THREAD

**Issue by jadami10** [apache/pinot#11603]
I'm noticing an issue where the `segmentReloadStatus` API will increase the `totalSegmentCount` with each call before finally stabilizing. But `successCount` will never actually reach `totalSegmentCount` even though controller logs say `Reloaded segments with metadata in table: ...`

**Comment by jadami10** [comment]
this seems to be somewhat related to running multiple reload requests either in parallel or close sequence. It's unfortunate this endpoint doesn't have an actual "status" field, though.

**Comment by Jackie-Jiang** [comment]
@saurabhd336 Can you help take a look at this?

**Comment by jadami10** [comment]
I looked at the code, and it's a little tough to debug. We store the "submissionTime" of the reload request in ZK, then successCount == count(segment.loadTime >= submissionTime). It's hard to debug because the segment loadTime isn't actually queryable. For now, the only way I could imagine this issue arising is clock skew where the server time is behind the controller time. But this feels highly unlikely since the reload message has to pass via helix to servers.

**Comment by jadami10** [comment]
i've replicated this locally. it happens when you have several thousands segments and reload several times back to back, so it's not pervasive. But it does seem to be to clock skew. You effectively see small, single digit millisecond differences where the load time on the server is 2-4ms earlier than the job submission time.

There's really no non-hacky way to solve this without storing some state that ties the segment name to the reload job id it reloaded for. I'm not sure how feasible that is. I think for now I'll probably just change the check internally to give it like a 5 second buffer.

**Comment by Jackie-Jiang** [comment]
This is actually a bug. #11803 is the fix
