### ISSUE TITLE
about 1.0.0 release

### ISSUE THREAD

**Issue by chenrui333** [apache/pinot#11605]
👋 Not sure if 1.0.0 is the latest release, but the website still shows 0.12.1 and `latest release` label still points to 0.12.1, raise this issue for some awareness. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/142600

**Comment by xiangfu0** [comment]
Thanks @chenrui333 for asking! The 1.0.0 release process is still in the process. The distribution is built and published already.

Right now, we are finalizing the last steps and preparing for the announcement!

**Comment by chenrui333** [comment]
Thanks for confirming it! :)

**Comment by chenrui333** [comment]
just nit comment, maybe this should not be marked as latest release

![image](https://github.com/apache/pinot/assets/1580956/e1b48603-8564-45f0-9f03-33849a808d21)

**Comment by chenrui333** [comment]
actually just saw the release announcement 🎉 Gonna close this issue for now. Thanks @xiangfu0! 

![image](https://github.com/apache/pinot/assets/1580956/cb843a95-3ec1-480b-b232-aa2e55503041)
