### ISSUE TITLE
MultiStage Engine Fails to Parse Table Names with `-` (Dash)

### ISSUE THREAD

**Issue by Ferix9288** [apache/pinot#11639]
**Image Snapshot: 1.1.0-SNAPSHOT-b1b070f68d-20230918-21-openjdk-linux-arm64**

For us, we utilize UUIDs as Pinot table names. V1 engine works and supports it just fine but looks like V2 crashes and burns with the following error:

Message prettified from query console: 
```
Error Code: 720

QueryPlanningError:
Error composing query plan for: select * from "8593490b-01bf-46d4-a92c-bc270ac49aee" limit 10
org.apache.pinot.query.QueryEnvironment.planQuery(QueryEnvironment.java:182)
org.apache.pinot.broker.requesthandler.MultiStageBrokerRequestHandler.handleRequest(MultiStageBrokerRequestHandler.java:134)
org.apache.pinot.broker.requesthandler.BaseBrokerRequestHandler.handleRequest(BaseBrokerRequestHandler.java:263)
org.apache.pinot.broker.requesthandler.BrokerRequestHandler.handleRequest(BrokerRequestHandler.java:48)
Caught exception while parsing query: SELECT * FROM 8593490b-01bf-46d4-a92c-bc270ac49aee_OFFLINE
org.apache.pinot.sql.parsers.CalciteSqlParser.compileToSqlNodeAndOptions(CalciteSqlParser.java:144)
org.apache.pinot.sql.parsers.CalciteSqlParser.compileToPinotQuery(CalciteSqlParser.java:186)
org.apache.pinot.sql.parsers.CalciteSqlCompiler.compileToBrokerRequest(CalciteSqlCompiler.java:32)
org.apache.pinot.query.routing.WorkerManager.getRoutingTable(WorkerManager.java:206)
Encountered " "FROM" "FROM "" at line 1, column 10.
Was expecting:
    <EOF> 
    
org.apache.pinot.sql.parsers.parser.SqlParserImpl.generateParseException(SqlParserImpl.java:38633)
org.apache.pinot.sql.parsers.parser.SqlParserImpl.jj_consume_token(SqlParserImpl.java:38430)
org.apache.pinot.sql.parsers.parser.SqlParserImpl.SqlStmtsEof(SqlParserImpl.java:1033)
org.apache.pinot.sql.parsers.CalciteSqlParser.compileToSqlNodeAndOptions(CalciteSqlParser.java:134)
```

Let me know if you guys need additional info. Also sorry if this is a dupe but I couldn't find any similar issues

**Comment by Jackie-Jiang** [comment]
cc @xiangfu0 @walterddr can you help take a look?

**Comment by walterddr** [comment]
i dont think this is a bug. it is not a standard SQL naming convention: https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS

**Comment by dttung2905** [comment]
More explanation on the above comment from my conversation with @walterddr. [Slack thread](https://apache-pinot.slack.com/archives/C013WKLT5T7/p1707087484866339).
> Turned out it is not because of the hyphen - in the table name but because of the number as the first character in the table name (see the picture below) being numeric instead of alphabetical. The hyphen issue has been fixed in the [PR](https://github.com/apache/pinot/pull/12212/files) earlier
![image](https://github.com/apache/pinot/assets/28837684/d8d5688e-6479-4512-8cd3-a20bbedc2784)

**Comment by walterddr** [comment]
going to close this as a non-issue. feel free to discuss further in separate thread if thats not the case or other issues related

**Comment by Ferix9288** [comment]
No worries and appreciate you guys for looking into it!  Understood that us quoting the table in V1 engine as a workaround for non-standard SQL table won't work for multistage. 

We actually have since prefixed it with an actual label to our Pinot tables as the solution and forgot to update this thread.
