### ISSUE TITLE
Reduce the number of threads for `IngestionDelayTimerThread`

### ISSUE THREAD

**Issue by snleee** [apache/pinot#11632]
while debugging some issue, we have observed that we create a lot of threads for `IngestionDelayTimerThread`. It would be better if we can cap this number.

![Screenshot 2023-09-20 at 12 00 58 AM](https://github.com/apache/pinot/assets/27253407/e4c7ba47-3172-48c6-a4d3-04c7ec85912c)

According to https://stackoverflow.com/questions/1933520/java-timer-and-thread-it-creates, it recommends to use `ScheduledExecutorService` over `Timer`

```
IngestionDelayTracker:

    _timer.schedule(new TimerTask() {
        @Override
        public void run() {
          timeoutInactivePartitions();
        }
      }, INITIAL_TIMER_THREAD_DELAY_MS, _timerThreadTickIntervalMs);
```

**Comment by snleee** [comment]
cc: @jugomezv

**Comment by cypherean** [comment]
Hey @snleee 
Can I take this up?

**Comment by jugomezv** [comment]
Yes should be an easy change. I had this as follow up but have other tasks at work now.  @snleee we can let @cypherean take a stab? keep me in the loop for reviews
