### ISSUE TITLE
How to disable fwd and inverted index on a `BYTES` metric column.

### ISSUE THREAD

**Issue by t0mpere** [apache/pinot#11659]
Hello I'm struggling to follow the doc [here](https://docs.pinot.apache.org/basics/indexing/forward-index#disabling-the-forward-index) regarding disabling fwd and inverted indexes for a `bytes` column on an existing table. It says that I can't disable the fwd index without having the inverted index enabled, althoug the doc says that it's possible to disable both. What am I missing here?

My issue is that column has a very high cardinality and it’s in `BYTES` format since it contains an HLL intermediate state. `noDictionary` is not an option since  30mb of raw data it creates a 2GB `forwardIndex` (just for this column) and `noDictionaryConfig` does nothing when i set `lz4` compression on the column. On the other hand `raw` or `invertedIndex` hover around 1gb per 30mb of data which is still huge considering that the column is only used in an aggregated function.

**Comment by Jackie-Jiang** [comment]
Trying to understand the problem. What do you store in this column? If you disable both fwd and inverted index, the column won't be queryable, in which case you should just remove the column.

**Comment by t0mpere** [comment]
Ok, found the answer. To enable `LZ4` on `noDictionary` columns I needed to re-ingest the data.
