### ISSUE TITLE
Multistage: Lastwithtime shows type errors in v2 engine

### ISSUE THREAD

**Issue by pjpringle** [apache/pinot#11668]
In V1 can write a query like this where updatedTimestamp is a long millis column.

`select country, lastwithtime( val, updatedTimestamp, 'double' )
from myTable
where purchaseDate='2023-09-25'
group by country
limit 10`

Running the same thing in V2 gives this error

`Caused by: org.apache.calcite.runtime.CalciteContextException: From line 1, column 16 to line 1, column 62: 
Cannot apply 'LASTWITHTIME' to arguments of type 
'LASTWITHTIME(<DOUBLE>, <BIGINT>, <CHAR(6)>)'. 
Supported form(s): 
'LASTWITHTIME(<ANY>, <TIMESTAMP>, <CHARACTER>)'`

**Comment by Jackie-Jiang** [comment]
cc @walterddr we should probably loose the argument check.

**Comment by xiangfu0** [comment]
https://github.com/apache/pinot/pull/11683

**Comment by walterddr** [comment]
If we do support implicit cast previously in v1 (from bigint to timestamp) we should inherent that behavior. Good catch

**Comment by Jackie-Jiang** [comment]
@walterddr We do support implicit cast in `BlockValSet`, so it should work even in intermediate stage
