### ISSUE TITLE
Retention support for upsert deleted key

### ISSUE THREAD

**Issue by tibrewalpratik17** [apache/pinot#11736]
labels: 
- feature enhancement
- Design review

We have an upsert use-case where we are receiving deletes at the scale of millions per day. It becomes expensive to keep these keys in-memory until table retention cleans them up. Creating this issue to add a new feature in upsert - `deletedKeysTTL` which will remove these deleted keys from in-memory hashmap and mark the docID as invalid after the `deletedKeysTTL` threshold period. This will help in huge cost savings for our particular use-case.

We cannot use presently available `upsertKeyTTL` as there are records which can receive updates even after months so we cannot apply a TTL for all non-deleted keys.

Wrote a short design-doc for review - https://docs.google.com/document/d/19odpbURBKALANBo1-bWQMVS9b_Enyt3jWpdLKeVYMvU/edit

Will raise a draft PR shortly after doc-review.

cc @Jackie-Jiang @deemoliu

**Comment by deemoliu** [comment]
Upsert deletion is a soft deletion. Enabling tTLs for soft deletion keys is similar to regular keys, it will need to have consistency enforcement as metadataTTL does, so it won't be easy to implement by simply deleting out of retention deleted keys. 

do you think we can enable the deleted key hard deletion during segment compaction minion job?

**Comment by tibrewalpratik17** [comment]
>  Enabling tTLs for soft deletion keys is similar to regular keys, it will need to have consistency enforcement as metadataTTL does
What does consistency mean here? Consistency of HashMap during server restarts?

The goal is to remove keys marked for deletion after a TTL window + mark the validDocIds as invalid. Once we mark the validDocID as invalid, i think during server restart the HashMap won't have the primary-key as well. Even if it does, the key will be removed in the next cycle.

> do you think we can enable the deleted key hard deletion during segment compaction minion job?

Segment compaction minion job doesn't remove primary-keys from the HashMap. It picks one segment at a time, looks at the validDocIDs and only persists those records back into the segment. Doing this via segment compaction, means using `queyrableDocIDs` to compact segments and also how will we still update the ConcurrentHashMap via minion nodes?

**Comment by deemoliu** [comment]
There are many race conditions if you take a synchronized approach to cleanup primary keys. Instead of introducing a new TTL, you can add a boolean field to apply metadataTTL (upsertTTL) to cleanup only deleted keys.

**Comment by Jackie-Jiang** [comment]
For both `upsertKeyTTL` and the new proposed `deletedKeyTTL`, when adding a new server, we still need to load all metadata again because the memory saving comes from skipping loading the invalid docs based on the valid doc ids snapshot. In order to use them in production, we need to solve this problem first, or no server can be replaced because very likely if we load all the keys (rebootstrap the metadata), the server will run out of memory.

**Comment by tibrewalpratik17** [comment]
> There are many race conditions if you take a synchronized approach to cleanup primary keys. Instead of introducing a new TTL, you can add a boolean field to apply metadataTTL (upsertTTL) to cleanup only deleted keys.

Yes, so instead of applying a boolean field via some config like `removeDeletedKeysOnly`, I was just suggesting a new config `deletedKeysTTL`. The plan was to remove the keys the way upsertTTL does by iterating through the map and removing the keys which falls out of TTL window and leveraging upsertTTL workflow itself.

> For both upsertKeyTTL and the new proposed deletedKeyTTL, when adding a new server, we still need to load all metadata again because the memory saving comes from skipping loading the invalid docs based on the valid doc ids snapshot. In order to use them in production, we need to solve this problem first, or no server can be replaced because very likely if we load all the keys (rebootstrap the metadata), the server will run out of memory.

@Jackie-Jiang for metadataTTL afaik, there is a watermark which preserves all keys from reloaded into the memory and does not load the one outside the upsertTTL window. But @deemoliu can confirm on that if I misunderstood anything.

As far as this `deletedKeysTTL` is concerned, I am planning to mark the validDocID for these keys as invalid in the segments anyways. I know there can be a scenario where between marking them as invalid and taking snapshot, the server gets restarted but then there will be only few keys which will be reloaded again and can be purged in the next deletion cycle.

**Comment by tibrewalpratik17** [comment]
I synced with @deemoliu offline and we aligned on re-using most of the upsertTTL stuff with a new boolean config `removeDeletedKeysOnly` and in the for loop, we will mark the validDocID as invalid as well based on this flag and isDeletedKey = true.

**Comment by deemoliu** [comment]
@tibrewalpratik17 i think the concerns @Jackie-Jiang raised is valid. the watermark is persisted on the local machine, and the replaced machine doesn't have access of the watermark file, because of that, during node replacement we cannot resue the watermark. let me open a separate thread to discuss on that.

**Comment by tibrewalpratik17** [comment]
@Jackie-Jiang @deemoliu referring to #11779, we do not intend to leverage the watermark feature of upsertTTL to address this use case. We would require loading all segments' validDocIds (not just after the watermark window). However, given that we mark deletedKeys validDocIds as invalid, these keys will not be recreated in the HashMap, minimizing the risk of server crashes during restarts or replacements.

There is a specific scenario to consider: only the deletedKeys from the last purge may get loaded again since the invalidation operation of those validDocIds may not have been snapshotted. Nevertheless, these keys will be purged in the subsequent run.

But do point out if i am missing something trivial here which will not fulfill to what we need.

**Comment by tibrewalpratik17** [comment]
Closed as completed via #12037
