### ISSUE TITLE
Upgrade inconsistency: Confusing behaviour with noDictionaryConfig and fieldConfig for enabling compression on raw forward index. 

### ISSUE THREAD

**Issue by t0mpere** [apache/pinot#11745]
Up to version `0.12.1` `noDictionaryConfig` was usable to enable compression for raw forward indexes on metrics column. Now in `1.0` this is only doable by `fieldConfig`. Is there a plan to deprecate `noDictionaryConfig`? This might be an issue upgrading since `BYTES` column without compression tend to blow up in size due to the raw forward index.

**Comment by Jackie-Jiang** [comment]
@gortiz Can you take a look? I feel it might be a bug in the index-spi

**Comment by gortiz** [comment]
Sorry for the delay. I was able to reproduce the issue. It should be fixed in #11784, which also adds some tests to verify the correct behavior

**Comment by Jackie-Jiang** [comment]
Fixed with #11784
