### ISSUE TITLE
Add GENERATE_ARRAY function

### ISSUE THREAD

**Issue by xiangfu0** [apache/pinot#11786]
Pinot supports `ARRAY[x, y, z]` syntax to manually craft an array literal. This is good for small scale, and in real prod, we need to add an ARRAY function to generate an ARRAY sequence for a given range.

Similar to the [GENERATE_ARRAY](https://cloud.google.com/bigquery/docs/reference/standard-sql/array_functions#generate_array) function in Google BQ

**Comment by xiangfu0** [comment]
To implement this, we just need to add the corresponding function in TransformFunction and ScalarFunction, as well as register the function in TransformFunctionType.

In `org.apache.pinot.integration.tests.custom.VectorTest`, there is some test queries related `ARRAY` op.
It's good to add an `ArrayTest` for those tests.

**Comment by dttung2905** [comment]
Hi @xiangfu0, I'm coming from kafka world and new to pinot , hence, I would like to take on this task to understand more about pinot internal. Would that be ok for the team?

**Comment by anandheritage** [comment]
@xiangfu0  Let me know if I can pick this up.
cc: @mayankshriv

**Comment by xiangfu0** [comment]
> Hi @xiangfu0, I'm coming from kafka world and new to pinot , hence, I would like to take on this task to understand more about pinot internal. Would that be ok for the team?

Since you reply first , please go ahead and give it a try. Feel free to ping me on Slack for any question!

**Comment by xiangfu0** [comment]
> @xiangfu0 Let me know if I can pick this up. cc: @mayankshriv

Thanks Anand for your interest! Since Dao took this up, I will find more stuffs for you :p

**Comment by anandheritage** [comment]
Okay @xiangfu0 , Kindly let me know.

**Comment by dttung2905** [comment]
Yes @xiangfu0 . I will definitely ping you on community slack channel if I encounter any problem

**Comment by aadilkhalifa** [comment]
@xiangfu0 Since there has not been an update for a while, can I pick this up?

**Comment by xiangfu0** [comment]
Hi @dttung2905, kindly letting us know if you are still active on this, or we can let @aadilkhalifa take it,  many thanks!

**Comment by dttung2905** [comment]
Hi everyone, im not working on this currently. Please help me take over the issue. Thanks alot

**Comment by aadilkhalifa** [comment]
@dttung2905 Okay. I can take it up in that case.

**Comment by aadilpanw** [comment]
@xiangfu0 Does Pinot support array literal currently? Because I see [here](https://github.com/apache/pinot/issues/9659) that the issue is still open.
