### ISSUE TITLE
Handle Out-of-order events for upserts

### ISSUE THREAD

**Issue by tibrewalpratik17** [apache/pinot#11796]
In one of our use-cases, there are lot of out-of-order events being sent in Kafka. Though we don't consider out-of-order events for updating [Metadata HashMap](https://github.com/apache/pinot/blob/1b7cb166de34f18c9a170cd74934162b3ea103b0/pinot-segment-local/src/main/java/org/apache/pinot/segment/local/upsert/ConcurrentMapPartitionUpsertMetadataManager.java#L54), we do [persist the row](https://github.com/apache/pinot/blob/1b7cb166de34f18c9a170cd74934162b3ea103b0/pinot-segment-local/src/main/java/org/apache/pinot/segment/local/indexsegment/mutable/MutableSegmentImpl.java#L493) in the table anyways without any merger (in case of partial-upsert). 

I am proposing to add a boolean config `disableIngestingOutOfOrderEvents` so that these events don't end up in the segments anyways and save on disk utilisation as well. This will also avoid confusion using `skipUpsert` for partial-upsert tables as nulls start showing up for columns where a previous non-null was encountered and we don't know if it's an out-of-order event or not. 

We should also add a virtual boolean column `$.isOutOfOrderEvent` to detect these scenarios as well and help in easy debugging when using `skipUpsert`. This is orthogonal to above proposed `disableIngestingOutOfOrderEvents`.

cc @Jackie-Jiang let me know your thoughts on this.

**Comment by Jackie-Jiang** [comment]
Good suggestion. We may introduce a config `dropOutOfOrderRecord`, and modify `addRecord` to return whether the record should be kept in the segment.
For the second request, in order to add it, we need user to config this column explicitly in the schema similar to the delete record column.

**Comment by tibrewalpratik17** [comment]
Cool! Can you assign this to me?

**Comment by klsince** [comment]
> This will also avoid confusion using skipUpsert for partial-upsert tables as nulls start showing up for columns where a previous non-null was encountered and we don't know if it's an out-of-order event or not. 

for my learning, could you please share some examples about this confusing behavior? thanks

**Comment by tibrewalpratik17** [comment]
> for my learning, could you please share some examples about this confusing behavior? thanks

<img width="634" alt="Screenshot 2023-10-17 at 1 47 30 AM" src="https://github.com/apache/pinot/assets/23629228/732d1529-7051-4d89-a475-4b450271478d">

The 1st column here is `$segmentName` and the last column is the comparison column. The 5th record is an out-of-order event and it gets persisted with 3rd and 4th column as zeros though the user was expecting some non-null (non-zero) value given they have previously sent non-null values for the same columns. This is a partial-upsert table and the user is using `skipUpsert`. 
This leads to confusion as they are not able to identify out-of-order events via query.

**Comment by tibrewalpratik17** [comment]
We can close this as it is implemented. Documentation here - https://docs.pinot.apache.org/basics/data-import/upsert#handle-out-of-order-events
