### ISSUE TITLE
Deep store upload retry does not scale for large clusters

### ISSUE THREAD

**Issue by itschrispeck** [apache/pinot#11874]
The issue we're seeing is that for large clusters (lots of segments, lots of tables), the RealtimeSegmentValidationManager task takes so long to run we cannot rely on it if deep store upload retry is enabled. 

From a quick inspection, `RealtimeSegmentValidationManager` attempts to upload segments missing from the deep store. This step happens before `.ensureAllPartitionsConsuming` would be called. The deep store upload retry portion can be extremely slow even if there aren't many missing deep store links - subjectively it's linked closely to total number of segments. 

One approach could be to move the deep store upload retry into a separate task, which would let other realtime segment validations run normally.

**Comment by Jackie-Jiang** [comment]
It would be very helpful if you can run a profile or gather more stats to point out the hotspot, then we may decide either to optimize the hotspot code or move it into a separate task. Ideally we want to optimize the hotspot and not abuse periodic tasks.

**Comment by itschrispeck** [comment]
I added some logs to see where the time was taken. It doesn't appear to be due to total segments as I initially thought. The majority of time taken is during segment re-upload. 

I guess this points to either introducing some parallelism for segment upload (there is a TODO in the code for this), or pulling it out into another task to avoid a period of high deep store upload failure blocking other segment validation functions. Thoughts?

**Comment by Jackie-Jiang** [comment]
I'll vote for making the upload async (we may also control the parallelism) so that it doesn't block the validation manager. Pulling all segment ZK metadata is quite expensive, so adding a separate periodic task will involve quite high overhead
