### ISSUE TITLE
Improve the performance of ZkBasicAuthAccessFactory

### ISSUE THREAD

**Issue by xiangfu0** [apache/pinot#11902]
Coming from this slack thread: https://apache-pinot.slack.com/archives/C011C9JHN7R/p1698376556374379

I can see some inefficiency here like reconstruct user/password map every time.

https://github.com/apache/pinot/blob/master/pinot-core/src/main/java/org/apache/pinot/server/access/ZkBasicAuthAccessFactory.java#L92

cc: @INNOCENT-BOY

**Comment by INNOCENT-BOY** [comment]
Hi @xiangfu0 I will try to fix this issue Thanks for your remind.

**Comment by INNOCENT-BOY** [comment]
Hi @xiangfu0 This [PR 11904](https://github.com/apache/pinot/pull/11904) is proposed to fix this issue.
