### ISSUE TITLE
[build][ci][flaky] cache maven artifact in GHA containers?

### ISSUE THREAD

**Issue by walterddr** [apache/pinot#11925]
seeing more and more issues with 
```
Error:  Failed to execute goal on project pinot-pulsar: Could not resolve dependencies for project org.apache.pinot:pinot-pulsar:jar:1.1.0-SNAPSHOT: Could not transfer artifact io.netty:netty-handler:jar:4.1.94.Final from/to central (https://repo.maven.apache.org/maven2): /home/runner/.m2/repository/io/netty/netty-handler/4.1.94.Final/netty-handler-4.1.94.Final.jar.part (No such file or directory) -> [Help 1]
```
either due to timeout or unavailability, or simply downloaded jar cannot be unzip due to corruption.

should we consider using file system caching when init GHA and only update when maven command decided to do so?

**Comment by walterddr** [comment]
simple solution is to add 2 steps in GHA
- at the end: package the `/.m2` folder and upload to some cloud storage
- at the beginning: download the `/.m2` folder from that storage

**Comment by Jackie-Jiang** [comment]
IIRC, @xiangfu0 tried this approach, but it is way too slow
