### ISSUE TITLE
Querying 2 tables across different broker tenants gives an ambiguous error message

### ISSUE THREAD

**Issue by jadami10** [apache/pinot#11990]
We have table A on broker tenant A. Table B on broker tenant B. Trying to join these tables show `ProcessingException(errorCode:450, message:InternalError)`.

While it's expected this doesn't work (broker needs to know about both tables), the error message is extremely vague. I ended up having to search for it in the broker logs before confirming what the real issue was.

**Comment by Jackie-Jiang** [comment]
@walterddr Can you help take a look?

**Comment by walterddr** [comment]
hmm. interesting. the error should have 5 lines of stack trace at least. is it only this without any messages attached?

**Comment by jadami10** [comment]
this is the only one i've seen. we ran into it randomly

**Comment by Jackie-Jiang** [comment]
@walterddr From what I can tell, the query should fail at `WorkerManager.assignWorkersToNonPartitionedLeafFragment()`: `Preconditions.checkState(!routingTableMap.isEmpty(), "Unable to find routing entries for table: %s", tableName);`

**Comment by walterddr** [comment]
not really. this is only true if broker API is directly called. if it is called via controller API. the error message will be from 
`PinotQueryResource.getMultiStageQueryResponse`: 
```
QueryException.getException(QueryException.BROKER_REQUEST_SEND_ERROR, new Exception(
            String.format("Unable to dispatch multistage query for tables: [%s]", tableNames))).toString();
```
b/c the return code is 450, it looks like it is directly hitting a broker and yes we are not returning proper error message here. good catch. will create a fix soon

**Comment by jadami10** [comment]
@walterddr i just hit this again, and refound this issue. apologies for not replying. this is indeed from the controller
