### ISSUE TITLE
Log4j configuration location is incorrect in helm deployment

### ISSUE THREAD

**Issue by vipulchandraker** [apache/pinot#12010]
Log4j conf file in helm deployment is configured as below in values.yaml file
`log4j2ConfFile: /opt/pinot/etc/config/pinot-controller-log4j2.xml`

The actual location of the log properties file in the container is /**opt/pinot/etc/conf/** 

 ls -l /opt/pinot/etc/conf/
-rw-r--r-- 1 root root 3765 Oct 31 02:23 pinot-broker-log4j2.xml
-rw-r--r-- 1 root root 3069 Oct 31 02:23 pinot-controller-log4j2.xml
-rw-r--r-- 1 root root 3021 Oct 31 02:23 pinot-minion-log4j2.xml
-rw-r--r-- 1 root root 3040 Oct 31 02:23 pinot-server-log4j2.xml

**Comment by Jackie-Jiang** [comment]
Good catch! Do you want to help contribute a fix?

**Comment by vipulchandraker** [comment]
Sure, I will create a fix

**Comment by vipulchandraker** [comment]
@Jackie-Jiang , please review #12083
