### ISSUE TITLE
Lack of JSON_EXISTS_PATH 

### ISSUE THREAD

**Issue by INNOCENT-BOY** [apache/pinot#12064]
> Json Index have a limitation: 
> The key (left-hand side) of the filter expression must be the leaf level of the JSON object, for example, "$.addresses[*]"='main st' won't work.

In some scenarios, we need to justify some non-leaf path is not null. Like below example:
We have one json column named: person
```
{
  "name": "adam",
  "age": 20,
  "addresses": [
    {
      "country": "us",
      "street": "main st",
      "number": 1
    },
    {
      "country": "ca",
      "street": "second st",
      "number": 2
    }
  ],
  "skills": [
    "english",
    "programming"
  ]
}
```
We want to execute JSON_MATCH(person, '"$.addresses" IS NOT NULL') to conduct data exploration. 
Meanwhile we found there is an function named JSON_EXISTS_PATH in Doris: https://doris.apache.org/docs/sql-manual/sql-functions/json-functions/json-exists-path which satisfied our demand. We would like to know if the community have plan to do this. 
cc @xiangfu0  @Jackie-Jiang

**Comment by INNOCENT-BOY** [comment]
> One work around is to use `jsonPathString`: https://github.com/apache/pinot/blob/master/pinot-common/src/main/java/org/apache/pinot/common/function/scalar/JsonFunctions.java#L133 E.g.
> 
> ```
> jsonPathString(person, '"$.addresses") != 'null'
> ```
> 
> For `JSON_EXISTS_PATH` you can simply add a scalar function in `JsonFunctions.java` to achieve it. Do you wanna make a contribution for this?
Hi @xiangfu0, jsonPathString is not work. jsonPathString is only to extract scalar value not nested json data. 
Sure. I will try to write this function if community needs.

**Comment by INNOCENT-BOY** [comment]
Hi @xiangfu0 , jsonPathString is not work. jsonPathString is only to extract scalar value not nested json data. 
Sure. I will try to write this function if pinot community need this.

**Comment by Jackie-Jiang** [comment]
Seems `jsonPathExists` is a more commonly used function name for this purpose

**Comment by INNOCENT-BOY** [comment]
Good advice, I will use jsonPathExists as the function name.
