### ISSUE TITLE
fix instances where the number of {} placeholders in the logger message doesn't match the number of other arguments to the logging call

### ISSUE THREAD

**Issue by timveil** [apache/pinot#12132]
found a number of instances where the number of `{}` placeholders in the logger message doesn't match the number of other arguments to the logging call. 

for example...

```
_segmentLogger.error("Illegal state {}" + _state.toString());
```
should be...
```
_segmentLogger.error("Illegal state {}", _state.toString());
```

**Comment by walterddr** [comment]
wondering if this should be captured by Checkstyle rules 
for example `String.format("{}, {}", arg1, arg2, arg3)` will be captured by checkstyle rule that the arg count mismatch.
