### ISSUE TITLE
Typo in pinot doc

### ISSUE THREAD

**Issue by Lvnszn** [apache/pinot#12176]
Hi team, 

Here is a typo in image

![image](https://github.com/apache/pinot/assets/12541438/9f14cfd9-137e-4492-a6dc-237f0caecc8e)

link: 
https://docs.pinot.apache.org/operators/operating-pinot/instance-assignment

**Comment by kelseiv** [comment]
thank you, @Lvnszn! fixed typo: https://docs.pinot.apache.org/operators/operating-pinot/instance-assignment
