### ISSUE TITLE
Please don't hardcode zookeeper version

### ISSUE THREAD

**Issue by pospospos2007** [apache/pinot#12174]
Hello, can you please not hardcode the zookeeper version of docker image:

          **image: docker.io/bitnami/zookeeper:3.8.0-debian-11-r5**
          
  When I use helm install pinot and it pull zookeeper image 3.8, can you please give latest verison of zookeeper?

**Comment by xiangfu0** [comment]
Where did you find it? We can definitely make it configurable.

Feel free to raise a PR for this.

**Comment by suyashpatel98** [comment]
Hello, @pospospos2007 @xiangfu0 @Jackie-Jiang. I am fairly new to Apache Pinot and the open-source world. I think this would be a good bug to get familiar with Apache Pinot. Can I please work on this? I don't think this would require a lot of changes and I should be able to fix this soon

**Comment by pospospos2007** [comment]
Just double checked. It seems it is not from your repo.
