### ISSUE TITLE
Pulsar OAuth configuration is not used

### ISSUE THREAD

**Issue by JeffBolle** [apache/pinot#12196]
When providing the required configuration for authenticating with OAuth to a pulsar cluster, the necessary authentication factory is not created.  This is a result of a typo in the recently merged PR: https://github.com/apache/pinot/pull/12068

I have submitted a PR to address this issue:
https://github.com/apache/pinot/pull/12195

@KKcorps Sorry I missed this in the initial testing of the feature.

**Comment by walterddr** [comment]
closed via #12195
