### ISSUE TITLE
Support uptime API in all pinot components

### ISSUE THREAD

**Issue by xiangfu0** [apache/pinot#12298]
Pinot only has the healthcheck endpoint for all the components.
One missing feature here is to show the uptime of each component, which can be an epoch seconds value.
Another api can I think of is to add the component start time.

**Comment by suyashpatel98** [comment]
Hello, @xiangfu0! I am very new to Pinot and I am interested in contributing. I think this issue will be a great starting point. Can you please assign this ticket to me? Thanks!

**Comment by xiangfu0** [comment]
Thanks @suyashpatel98 !
Assigned the ticket to you!

**Comment by suyashpatel98** [comment]
@xiangfu0 Please review when you find time. Thanks!

**Comment by suyashpatel98** [comment]
@mayankshriv @saurabhd336 @xiangfu0 Addressed comments on the first PR. Please review when you find time. I closed the old PR and created a new because the history of the old PR got messy. Thanks!

**Comment by xiangfu0** [comment]
Close this issue as the PR is merged.
