### ISSUE TITLE
Allow setup timezone in cluster config or config file.

### ISSUE THREAD

**Issue by xiangfu0** [apache/pinot#12299]
Right now pinot time zone is decided by the local timezone, this caused a lot of confusion especially during ingestion time or use datetrunc function etc.

The way to set timezone for pinot is either using environment variable or JVM argument: https://docs.pinot.apache.org/basics/getting-started/frequent-questions/general#how-to-change-timezone-when-running-pinot

Ideally, we should make a config to set time zone for pinot component.

Default should be UTC always.

**Comment by aadilkhalifa** [comment]
Hey @xiangfu0. Can I take this up?
