### ISSUE TITLE
Add QueryOption support for column-level index skipping at query time

### ISSUE THREAD

**Issue by egalpin** [apache/pinot#12355]
In some cases it may be beneficial to skip the usage of an index despite its existence, such as utilizing many inverted indices over many columns, and combining the resulting bitmaps.  It may be faster to use only the more highly selective index (if that can be known at query time) and instead scan those resulting documents to fulfill another filter (as opposed to fulfill that other filter via another index and combining the bitmaps). 

Something like `SET indexSkipList='col1:inverted,range;col2:inverted';` (especially if also combined with `SET AndScanReordering = 'True';`)

**Comment by egalpin** [comment]
Thoughts on the list scheme? How should the index names be referenced? Re-using the names from the tableSpec looks a little bit odd as it would lead to things like `SET indexSkipList='col1:invertedIndexColumns';`. `fieldConfigList.INDEX_TYPE` might work, but I've forgotten whether that is the new format being moved towards, or the old format being deprecated.

**Comment by kishoreg** [comment]
+1 to this feature. We have this for StarTree index.

**Comment by egalpin** [comment]
After a bit of thought, I'm more in favour of matching the generally-familiar URL params scheme: `indexSkipConfig='col1=inverted,range&col2=inverted'`. Thoughts?

**Comment by gortiz** [comment]
I really like this feature. What I'm not sure about is the syntax. Not because I'm against URL params. But I would like to prioritize consistency here. It doesn't seem we have other query options where the value is a `Map<String, Collection<T>>`, so adding this feature as it is would mean that future options should use this syntax.

**Comment by egalpin** [comment]
@gortiz totally makes sense that we should be more careful in cases of setting precedent.  Are there any similar features in other DBs that would provide familiar syntax? I'll take a look around

**Comment by egalpin** [comment]
I did find that Impala[1] uses `:` as a delimiter for list-type options. Used in this issue context, it might look like: `myColumn=inverted:range`.  I'll look a bit more for other examples

[1] https://impala.apache.org/docs/build/html/topics/impala_default_hints_insert_statement.html

**Comment by gortiz** [comment]
Thanks for your findings! Anyway, if there is no clean alternative, we can just apply the one you proposed with url arguments.
