### ISSUE TITLE
How to enable the Groovy transform functions for table

### ISSUE THREAD

**Issue by Rancbar** [apache/pinot#12413]
First of all, thank you for your invaluable contributions.

I am trying to learn Pinot and I am going through the samples you provided but I have been struggling for multiple days only because of the following error in using Groovy transformFunction or filterFunction.

> INFO [AddTableCommand] [main] {"code":400,"error":"Invalid TableConfigs. Invalid TableConfigs: my_table. Groovy transform functions are disabled for table config. Found 'Groovy({bids.max{ it.toBigDecimal() }}, bids)' for column 'maxBid'"}

I added the following lines to my table config but still not working:
```
{
    "tableName": "my_table",
    "tableType": "REALTIME",
    "query" : {
        "disableGroovy": false
    },
    ...
}
```

Please guide me on how to enable it for the table.

**Comment by kishoreg** [comment]
https://docs.pinot.apache.org/developers/advanced/ingestion-level-transformations#groovy-functions

**Comment by Rancbar** [comment]
Thanks @kishoreg, I forgot to mention I have added the following configuration to the `conf/pinot-controller.conf` too:

`controller.disable.ingestion.groovy=false`

**Comment by Jackie-Jiang** [comment]
@zhtaoxiang How do we add config into docker?

@Rancbar Another way to add this config is to add it into the ClusterConfig using the rest API
![Screenshot 2024-02-13 at 3 43 51 PM](https://github.com/apache/pinot/assets/17555551/c0771e70-5271-444a-b41f-0419d221fdc7)

**Comment by Rancbar** [comment]
Thank you @Jackie-Jiang,
Using this approach I am able to use Groovy functions now.
