### ISSUE TITLE
Invalid transform function JSONPATHDOUBLE

### ISSUE THREAD

**Issue by vineethvp** [apache/pinot#12422]
I'm working on a pinot cluster with version 1.1.0.  I have created a table schema with one field as JSON element.  I have defined a JSON field and DOUBLE field in my schema.

{
    "name" : "data",
    "dataType" : "JSON",
    "notNull" : false
    },{
      "name" : "machine_util",
      "dataType" : "DOUBLE",
      "notNull" : false
    },

I'm using below transformation configs to flatten JSON files. 

 "transformConfigs": [
        {"columnName": "machine_util", "transformFunction": "JSONPATHDOUBLE(data, '$.machine_util')" }]

I'm getting below error while creating table. I'm running this in a K8 cluster. The same code was working for me in a local setup using docker with same version.

**{"code":400,"error":"Invalid transform function 'JSONPATHDOUBLE(data, $.cpu_util)' for column 'cpu_util'"}bash-4.2#** 

I'm executing the commands to create table using a curl command within controller.

**Comment by abhioncbr** [comment]
Seems like a transform function looking for the `cpu_util ` value in the JSON, however as per the transformConfigs it's `machine_util `. Is this correct?

**Comment by vineethvp** [comment]
Hi,

Not really. The error message shown was for a different field. Both fields have same transform applied.

**{"code":400,"error":"Invalid transform function 'JSONPATHDOUBLE(data, $. machine_util)' for column 'machine_util'"}bash-4.2#**

**Comment by abhioncbr** [comment]
Can you check the ponot version is same on docker and on K8s? Which Pinot version?

**Comment by vineethvp** [comment]
I'm able to resolve it now. The issue was related some kind of character encoding. I'm able to execute post commands with data in file instead of plain text.
