### ISSUE TITLE
1.0.1 release timeline

### ISSUE THREAD

**Issue by wendigo** [apache/pinot#12428]
Is there an ETA for the next minor/patch release?

**Comment by hpvd** [comment]
+1
maybe worth it since there were already >450 merged pr since last release:
https://github.com/apache/pinot/pulls?q=is%3Apr+merged%3A%3E%3D2023-09-12+

**Comment by hpvd** [comment]
of course it would be good to look into/solve the known/reported open vulnerabilities before:
https://github.com/apache/pinot/issues?q=is%3Aissue+label%3Avulnerability+is%3Aopen+

**Comment by hpvd** [comment]
just fyi:
there is an `1.1- RC` branch from 3 weeks ago:
https://github.com/apache/pinot/tree/release-1.1-rc

**Comment by hpvd** [comment]
has moved to 1.1.0-rc
https://github.com/apache/pinot/tree/release-1.1.0-rc

**Comment by hpvd** [comment]
1.1.0-rc was released:
https://github.com/apache/pinot/releases/tag/release-1.1.0-rc0

**Comment by hpvd** [comment]
so maybe this issue can already be closed?

**Comment by PeterCorless** [comment]
Final release tag here:

[https://github.com/apache/pinot/releases/tag/release-1.1.0](https://github.com/apache/pinot/releases/tag/release-1.1.0)

**Comment by wendigo** [comment]
@PeterCorless yes, already tested it and found some bug that blocks us (Trino) from upgrading 😢
