### ISSUE TITLE
non-compliant download page: links should use closer.lua script

### ISSUE THREAD

**Issue by pjfanning** [apache/pinot#12442]
https://infra.apache.org/release-download-pages.html#download-scripts

See https://spark.apache.org/downloads.html as an example.

Its download links to https://www.apache.org/dyn/closer.lua/spark/spark-3.5.0/spark-3.5.0-bin-hadoop3.tgz (as an example).

INFRA team do not want us to link to https://archives.apache.org or https://downloads.apache.org directly. This is ok for the asc and sha sum files but the main file should have a clink like the spark one above. You don't need to change it for archived releases - the lua script will work that out.

**Comment by pjfanning** [comment]
@Jackie-Jiang I am not a Pinot contributor and don't know where your web site code is kept. Should I bring this up with Pinot dev list. For me, ASF project PMC members should be looking to comply with ASF rules. The ASF doesn't overburden you with rules - but the download links is a rule that you are expected to follow.

**Comment by Jackie-Jiang** [comment]
@kelseiv Can you please take a look at this?

**Comment by tlberglund** [comment]
This is for me. I'll get you a PR early in the week.

**Comment by tlberglund** [comment]
@pjfanning Unrelatedly, we're seeing a problem with YouTube embeds not working. We're working around it on the Pinot site right now, but you can see an [example of the same problem on the Kafka site](https://kafka.apache.org/intro). Where's the right channel to chase this down?

**Comment by pjfanning** [comment]
> @pjfanning Somewhat relatedly, we're seeing a problem with YouTube embeds not working. We're working around it on the Pinot site right now, but you can see an [example of the same problem on the Kafka site](https://kafka.apache.org/intro). Where's the right channel to chase this down?

The Infrastructure team has added Content Security Policy headers to ASF websites.

**Comment by tlberglund** [comment]
Is there a procedure by which we might ask to enable YouTube embeds?

**Comment by pjfanning** [comment]
> Is there a procedure by which we might ask to enable YouTube embeds?

You should be able to deploy a .htaccess file or something similar that overrides the CSP header. Raise an INFRA issue if you need assistance.

**Comment by xiangfu0** [comment]
Fixed here: https://github.com/apache/pinot-site/pull/113
