### ISSUE TITLE
Add a config similar to `realtime.segment.flush.threshold.rows` but independent of partitions consumed by server

### ISSUE THREAD

**Issue by Jackie-Jiang** [apache/pinot#12508]
This is a followup on the discussion in #10137 

When `realtime.segment.flush.threshold.rows` is used, the flush threshold for the new CONSUMING segment is determined by both this value and the max partitions consumed by any server. This is not very straight forward, and rebalancing a table could cause new consuming segment size to change.

In order to tackle this problem, we may add a new config (proposing `realtime.segment.flush.threshold.segment.rows`) which works independent of partitions consumed.

**Comment by suyashpatel98** [comment]
@Jackie-Jiang Can you please assign this to me? Thanks!

**Comment by karthi07** [comment]
@suyashpatel98  are you still working on this task? if not, I would like to take up this issue.

**Comment by suyashpatel98** [comment]
@karthi07 Please take up the issue. I am slightly busy - I will find something else to do when I find time.
