### ISSUE TITLE
Pinot Kafka config environment variables no longer being applied 

### ISSUE THREAD

**Issue by dd-willgan** [apache/pinot#12556]
Recently when we upgraded from Pinot 0.12.0 to 1.0+ we found that variables such as

```
{
  "ingestionConfig": {
    "streamIngestionConfig": {
      "streamConfigMaps": [
        {
          "sasl.jaas.config": "${PINOT_KAFKA_CONFIG_00}"
        }
      ]
    }
  }
}
```

were no longer being applied. I noticed this function call in `release-0.12.0` https://github.com/apache/pinot/blob/release-0.12.0/pinot-controller/src/main/java/org/apache/pinot/controller/helix/core/PinotHelixResourceManager.java#L1680 is no longer present in `master`.

**Comment by Jackie-Jiang** [comment]
Thanks for raising the issue. Verified that this is a bug, and is fixed with #12560
