### ISSUE TITLE
Retention manager not running for all tables

### ISSUE THREAD

**Issue by vineethvp** [apache/pinot#12660]
I have multiple realtime tables in my cluster which are having older segments. Below is configuration for one of them. It looks like retention manager is not running for these tables. while looking at controller logs, it seems retention manager is running only for one of the dimensional table.

I have verified that the timestamp field for the table is having the proper value in milliseconds inserted in the db.

Below is the table config for which retention is not happening and the relevant information from controller log.

**{
    "tableName": "events",
    "tableType": "REALTIME",
    "segmentsConfig": {
      "timeColumnName": "upload_ts_millis",
      "timeType": "MILLISECONDS",
      "schemaName": "events",
      "retentionTimeUnit": "HOURS",
      "retentionTimeValue": "6",
      "replication": "2"
    },
    "tenants": {},
    "ingestionConfig": {
      "ingestionConfig": {
        "indexableExtrasField": "extras"
      },
      "transformConfigs": [
        {"columnName": "upload_timestamp","transformFunction": "Groovy({timestamp}, timestamp)"},
        {"columnName": "upload_date", "transformFunction": "toEpochDays(upload_timestamp)" },
        {"columnName": "upload_ts_millis", "transformFunction": "FromEpochSeconds(upload_timestamp)" }
 },
        {"columnName": "sensor_temperature", "transformFunction": "JSONPATHSTRING(data, '$.sensor_temperature')" },
        {"columnName": "data_source", "transformFunction": "JSONPATHSTRING(data, '$.data_source')" }
      ]
     },
     "instanceAssignmentConfigMap": {
      "CONSUMING": {
        "tagPoolConfig": {
          "tag": "DefaultTenant_REALTIME"
        },
        "replicaGroupPartitionConfig": {
          "numInstances": 2
        }
      }
    },
    "tableIndexConfig": {
      "loadMode": "MMAP",
      "jsonIndexConfigs": {
        "data" : {
          "maxLevels":2,
          "excludeArray":false,
          "disableCrossArrayUnnest":true,
          "includePaths":null,
          "excludePaths":null
        }
      },
      "streamConfigs": {
        "streamType": "kafka",
        "stream.kafka.consumer.type": "lowlevel",
        "stream.kafka.topic.name": "derived-measurements-data",
        "stream.kafka.decoder.class.name": "org.apache.pinot.plugin.stream.kafka.KafkaJSONMessageDecoder",
        "stream.kafka.consumer.factory.class.name": "org.apache.pinot.plugin.stream.kafka20.KafkaConsumerFactory",
        "stream.kafka.broker.list": "b-2.agsdevus3msk.xlcy7b.c6.kafka.us-east-2.amazonaws.com:9092,b-1.agsdevus3msk.xlcy7b.c6.kafka.us-east-2.amazonaws.com:9092,b-3.agsdevus3msk.xlcy7b.c6.kafka.us-east-2.amazonaws.com:9092",
        "realtime.segment.flush.threshold.rows": "0",
        "realtime.segment.flush.threshold.time": "24h",
        "realtime.segment.flush.threshold.segment.size": "300M",
        "stream.kafka.consumer.prop.auto.offset.reset": "largest"
      }
    },
    "metadata": {
      "customConfigs": {}
    }
  }**
  
  _**Controller log**_

**Starting RetentionManager with running frequency of 21600 seconds.
[TaskRequestId: auto] Start running task: RetentionManager
Processing 1 tables in task: RetentionManager
Start managing retention for table: account_hierarchy_OFFLINE
Segment push type is not APPEND for table: account_hierarchy_OFFLINE, skip managing retention
Segment lineage metadata clean-up is successfully processed for table: account_hierarchy_OFFLINE
Removing aged deleted segments for all tables
Finish processing 1/1 tables in task: RetentionManager
[TaskRequestId: auto] Finish running task: RetentionManager in 9ms**

Do i need any additional configs for running the retention manager for all tables?

**Comment by Jackie-Jiang** [comment]
How many controllers do you have? If you have multiple controllers, each table has a lead controller which handles the retention for it

**Comment by vineethvp** [comment]
HI @Jackie-Jiang I have 2 controller instances. I have checked the logs for other controller as well. not seeing any logs related to retention there.

**Comment by Jackie-Jiang** [comment]
That is unexpected. Is this table queryable?
How many tables do you have in your cluster? Please check the log `Processing <n> tables in task: RetentionManager` in all controllers, and see if they add up?

**Comment by vineethvp** [comment]
Hi @Jackie-Jiang  Yes the table is queryable. previously when i checked ,i was creating an error when running retention manager because mismatch in timestamp granularity. I have deleted and recreated the table with same now, but not seeing the retention manager being run now for this table.

Also i checked logs in both controllers , i'm seeing `Processing <n> tables in task: RetentionManager` only in one instance as i mentioned above.

**Comment by vineethvp** [comment]
It is actually starting to execute on for the offline dimensional tables i have. Only for realtime tables its not running.

`Segment push type is not APPEND for table: device_summary_OFFLINE, skip managing retention`

**Comment by Jackie-Jiang** [comment]
Which Pinot version are you running? Reading through the code and I don't really see how it is possible..

**Comment by vineethvp** [comment]
@Jackie-Jiang I'm running the latest version. I have re created some of my tables and the issue seems to be slightly different now. I can see some of the segments are being purged now. but i'm still able to query data that came before 6 hours - which is my retention period. Am i missing something here?

**Comment by Jackie-Jiang** [comment]
The retention manager can remove the segment only if the newest record in the segment is out of the retention window. E.g. if the segment flushes every 12 hours, and the retention is 6 hours, you might see data ingested up to 18 hours ago.

**Comment by vineethvp** [comment]
Thanks @Jackie-Jiang. That is probably what causing the mismatch. Thanks for the reponse.
