### ISSUE TITLE
Support decoding protobuf input using code generation to call native methods

### ISSUE THREAD

**Issue by rseetham** [apache/pinot#12679]
The current protobuf decoder uses DynamicMessage to deserialize protobuf. It's performance is known to be 3x-4x times slower than the classes and builders compiled by protoc for a message. We should also provide the option to use codegen for deseriazing protobuf.
Other open source projects also support this codegen way of decoding protobuf. [Flink](https://issues.apache.org/jira/browse/FLINK-18202) generates code on the fly to decode protobuf using the methods in a compiles protobuf message jar.

**Comment by Jackie-Jiang** [comment]
Thanks for reporting this! Do you want to help enhance it?

**Comment by rseetham** [comment]
Yes. I'm working on it. I did some local benchmarking. Decoding is 3x faster. I'll post a design doc soon with details.

**Comment by rseetham** [comment]
Here's a design doc with a proposal:
https://docs.google.com/document/d/186mVLISgYEmljla3-IHrFNJ2dGMJ21qJ-MWFtsx-ayI/

**Comment by Jackie-Jiang** [comment]
cc @snleee @swaminathanmanish @KKcorps

**Comment by KKcorps** [comment]
Checkout out the implementation present in - https://github.com/apache/flink/blob/master/flink-formats/flink-protobuf/src/main/java/org/apache/flink/formats/protobuf/deserialize/PbCodegenRowDeserializer.java#L72

This approach is better. We can pick this up @snleee

**Comment by rseetham** [comment]
@KKcorps Could you take a look at the draft code and let me know if there's any issues. I tested it and it works. I will write unit tests and integration tests if the structure if good.

**Comment by KKcorps** [comment]
hey, will take a look today! Thanks a lot for contributing

**Comment by rseetham** [comment]
@ankitsultana  @deemoliu Could you take a look at this PR?
