### ISSUE TITLE
Ingest from Pulsar: relying on/ compatible to EOL version of Pulsar

### ISSUE THREAD

**Issue by hpvd** [apache/pinot#12713]
Ingest from Pulsar: relying on/ compatible to EOL version of Pulsar

Details:
Pinot ingest streaming from pulsar currently relies on Pulsar client version 2.7.2
https://docs.pinot.apache.org/basics/data-import/pinot-stream-ingestion/apache-pulsar#supported-pulsar-versions

Java Client version numbering seems to be in sync with Pulsar (bundle)
https://pulsar.apache.org/docs/next/client-libraries/#language-specific-client-libraries

Apache Pulsar 2.7.2 was released on 2021-05-11
https://pulsar.apache.org/release-notes/versioned/pulsar-2.7.2/

Active and Security support for this version ended 03 Dec 2021
https://pulsar.apache.org/contribute/release-policy/

Current Pulsar/Pulsar Client version is 3.2.1 from 08 Mar 2024
https://pulsar.apache.org/download/

=> hard to start / to use the "pulsar+pinot dream team"

**Comment by Jackie-Jiang** [comment]
We have upgraded Pulsar to 2.11.* in `release 1.1.0`. Can you please try it out?

**Comment by hpvd** [comment]
yep, good to see there was an upgrade with the shiny new 1.10!

Looking into Pulsars Release Policy, even for 2.11 active and also security support were already terminated
on 11 Jan 2024
https://pulsar.apache.org/contribute/release-policy/

**Comment by hpvd** [comment]
Just for the overview and to put the work in the right order, here are some open pull request in the field of pulsar..
https://github.com/apache/pinot/pulls?q=is%3Apr+is%3Aopen+pulsar
at least one of them looks ready to merge (approved+ checks ok)

**Comment by hpvd** [comment]
latest version is `3.2.1.`
`depend bot` seems to have been canceled for this https://github.com/apache/pinot/pull/12123

**Comment by Jackie-Jiang** [comment]
From what I can tell, Pulsar is actively maintaining 2 major versions, and `3.2.1` and `2.11.4` are released on the same day (03/08/2024). We can evaluate `3.2.*`, but I guess it is backward incompatible with `2.11.*`

**Comment by hpvd** [comment]
hmm when looking into their release policy it looks like this:
![2024-03-26_19h46_02](https://github.com/apache/pinot/assets/5681880/064daf94-bd19-4865-84e0-038af9361fa2)
https://pulsar.apache.org/contribute/release-policy/

**Comment by Jackie-Jiang** [comment]
I see. Interestingly they still release on non-active support version. We will try to upgrade it to `3.2.1`

**Comment by hpvd** [comment]
fyi: v3.2.2 was just released, including some client fixes:
https://github.com/apache/pulsar/releases/tag/v3.2.2
