### ISSUE TITLE
NPE when broker header is null

### ISSUE THREAD

**Issue by jtao15** [apache/pinot#12745]
A recent change in #12417 expect broker query http headers to be non-null which seems to be incompatible because we are checking if the header is null here: https://github.com/apache/pinot/blob/470f8ba2e07254df2312c8961c35baedf3db35ad/pinot-broker/src/main/java/org/apache/pinot/broker/requesthandler/BaseBrokerRequestHandler.java#L266

This has caused NPE in our e2e test on this line: https://github.com/apache/pinot/blob/470f8ba2e07254df2312c8961c35baedf3db35ad/pinot-common/src/main/java/org/apache/pinot/common/utils/DatabaseUtils.java#L97

**Comment by jtao15** [comment]
cc @vvivekiyer @Jackie-Jiang @jackjlli @siddharthteotia

**Comment by jackjlli** [comment]
Thanks @jtao15 for reporting! Would @shounakmk219 take this up? Also, does it make more sense to unify the way of passing parameters for queries? There are already quite a few ways to pass query parameters, but it seems this https://github.com/apache/pinot/pull/12417 PR just introduces more way to do it. I can image that we'll have to spend the effort on unifying them in the future.

**Comment by shounakmk219** [comment]
Sure, I will take this up.

**Comment by shounakmk219** [comment]
@jackjlli regarding how the database name is being passed, let's use the discussion thread [here](https://docs.google.com/document/d/1l1dco4lRhB28y-yKMVKlOMZ0sdFKObjJfhAjG6cmktU/edit?disco=AAABKcWGOes)

**Comment by Jackie-Jiang** [comment]
I saw we are passing `null` as `HttpHeaders` from the test. In reality, could it ever be `null` when it is passed from the rest API stub?

**Comment by jackjlli** [comment]
The `handleRequest()` methods of `BrokerRequestHandler` class are not always invoked from rest; it could be invoked by the request handler that is fetched from `getBrokerRequestHandler()` mtehod in `BaseBrokerStarter` class. So it's still possible that the http header becomes null when `handleRequest()` methods are called.

**Comment by jackjlli** [comment]
PR merged. We can close this issue now. Thanks everyone for working on this!
