### ISSUE TITLE
Add API to reset error segments in parallel instance by instance

### ISSUE THREAD

**Issue by wirybeaver** [apache/pinot#12781]
It's painful to trigger api per segments per instance during table rebalance. Instead of running curl, it's better to have a built-in api

**Comment by Jackie-Jiang** [comment]
I don't follow the ask here. Can you elaborate more on the current pain point and the expected behavior?

**Comment by wirybeaver** [comment]
@Jackie-Jiang Actually I find out there's an endpoint `segments/{tableNameWithType}/reset` which can fit my purpose. The default value of `errorSegmentsOnly` should have been `true` for safety purpose.
