### ISSUE TITLE
Support ORC 2.0+

### ISSUE THREAD

**Issue by Jackie-Jiang** [apache/pinot#12858]
#12841
Solve the incompatibility between ORC 1.5.9 to 2.0.0

**Comment by hpvd** [comment]
notable changes:
https://orc.apache.org/releases/

**Comment by abhioncbr** [comment]
I will look into it. Thanks

**Comment by abhioncbr** [comment]
orc version 2.0.0 drops support for java 8/11.
For reference - 
https://github.com/apache/orc/releases/tag/v2.0.0, 
[ORC-1512](https://issues.apache.org/jira/browse/ORC-1512): Drop Java 8/11 and make Java 17 by default
