### ISSUE TITLE
[HELM] Allow statefulsets to automatically roll when updating configmaps

### ISSUE THREAD

**Issue by nilaprasad** [apache/pinot#13046]
### Background
Currently, the helm charts don't roll the corresponding pods for a given statefulset when an associated configmap is updated and it needs to be done manually. This can lead to issues where the expected configuration for an environment differs from what's actually there. To allow for quicker iterations on the configuration the helm charts should support automatic rolling of the statefulsets.

### Proposed Solution
Allow for an optional annotation that uses helm's ability to [automatically roll deployments](https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments). For example, this can be set under the controller annotations [here](https://github.com/apache/pinot/blob/master/helm/pinot/templates/controller/statefulset.yaml#L40).

`templates/controller/statefulset.yaml`
```yaml
      ...
      annotations:
        {{- if .Values.controller.automaticReload.enabled }}
        checksum/config: {{ include (print $.Template.BasePath "<configmap-dir>") . | sha256sum }}
{{ toYaml .Values.controller.podAnnotations | indent 8 }}
```

`values.yaml`
```yaml
...
controller:
  ...
  automaticReload:
    enabled: true
  ...
```

**Comment by abhioncbr** [comment]
Looking into it.

**Comment by abhioncbr** [comment]
We can close this issue. Thanks
