### ISSUE TITLE
Merge `RecordEnricher` into `RecordTransformer`

### ISSUE THREAD

**Issue by Jackie-Jiang** [apache/pinot#13049]
`RecordEnricher` was introduced in #12243, which is very similar to `RecordTransformer`. It can cause confusion to maintain both of the abstractions because there is no clear boundary when to use which one.
We should merge `RecordEnricher` into `RecordTransformer`, and make the existing enrichers implement `RecordTransformer` interface. We might need to modify `RecordTransformer` a little bit to serve the purpose of `RecordEnricher`

**Comment by deepthi912** [comment]
Looking into it.

**Comment by aadilkhalifa** [comment]
@deepthi912 Are you working on this?

**Comment by deepthi912** [comment]
@aadilkhalifa  Not working on it currently but you can take it.
