### ISSUE TITLE
Google library dependency management

### ISSUE THREAD

**Issue by Jackie-Jiang** [apache/pinot#13077]
Currently we use the google cloud [BOM](https://mvnrepository.com/artifact/com.google.cloud/libraries-bom/26.38.0) to manage all the google library dependencies. Within the BOM there are separate versions maintained for some major dependencies such as guava, grpc etc.
Currently we specify them in the pom, but seems they are not picked up. Need to figure out how to manage the google dependencies.

```
    <!-- Google Libraries -->
    <google.cloud.libraries.version>26.37.0</google.cloud.libraries.version>
    <google.auth.version>1.23.0</google.auth.version>
    <gson.version>2.10.1</gson.version>
    <guava.version>33.1.0-jre</guava.version>
    <google.http-client.version>1.44.1</google.http-client.version>
    <protobuf.version>3.25.2</protobuf.version>
    <grpc.version>1.61.1</grpc.version>
```

**Comment by abhioncbr** [comment]
I would like to look into it. Thanks

**Comment by abhioncbr** [comment]
I was looking into it, and as I understand, the version mentioned takes effect by importing the sub-projects BOM or including them as a dependency in the parent pom. These properties are useless
```bash
    <google.auth.version>1.23.0</google.auth.version>
    <gson.version>2.10.1</gson.version>
    <guava.version>33.1.0-jre</guava.version>
    <google.http-client.version>1.44.1</google.http-client.version>
    <protobuf.version>3.25.2</protobuf.version>
    <grpc.version>1.61.1</grpc.version>
```
Also, I would like to highlight that overriding the version of a dependency managed by a BOM can lead to compatibility issues, as the BOM's purpose is to ensure that all the libraries and their dependencies work well together.

Let me know if I can delete the properties, or if we want to override them, I will add their BOMs in dependency management.

**Comment by Jackie-Jiang** [comment]
IMO we can delete them. Wondering if we can access these values from the BOM in case we have other dependencies sharing these values?
