### ISSUE TITLE
MaxLength is not honored for JSON columns (the way is it for long STRING columns)

### ISSUE THREAD

**Issue by npawar** [apache/pinot#13123]
The maxLength for a JSON field is ignored because truncating a json field would invalidate the JSON.  

Suggestion: If the JSON is too long, don’t ingest the JSON but instead 
a) put in an empty JSON value 
OR
b) put in some JSON value that is not empty but that reflects that the incoming JSON was too long so was not ingested 

Along with this, also emit a metric showing how many such JSON values had to be rejected by Pinot for being longer than the maxLength.

**Comment by npawar** [comment]
@deepthi912 want to give this a shot?

**Comment by deepthi-912** [comment]
Yeah, I will check it out.

**Comment by deepthi912** [comment]
@npawar To clarify more, Should we add any config property so that user can have the flexibility to set the maximum length or should it be like fixed length defined inside our code? If so, what should be the default maxlength for json, same as a string(512)?

**Comment by Jackie-Jiang** [comment]
@deepthi912 `_maxLength` property is available in `FieldSpec`

**Comment by Jackie-Jiang** [comment]
Resolved with #13103
