### ISSUE TITLE
Broker "POST" "query/sql" API returns 500 when using Keycloak-based Pinot Broker authentication implementation dropped into "plugins" or "lib" Pinot distribution folder

### ISSUE THREAD

**Issue by sudeshnasengupta** [apache/pinot#13148]
When extending org.apache.pinot.broker.broker.AccessControlFactory to have Pinot v. 1.1.0 Broker talk to a Keycloak server for authenticating all Broker POST "query/sql" API calls, and configuring the associated, local Broker distribution to use the custom factory via the Broker configuration property "pinot.broker.access.control.class", the only way the same local Pinot v.1.1.0 distribution works is if that customization is part of the "pinot-broker" module from Pinot's code base.  However, if the uber JAR containing the customization and all its dependencies is dropped into the same distribution's "lib" or "plugins" folder, the Broker HTTP server encounters a response 500, leading to the following "Grizzly 2.4.4" error response body: <html><head><title>Grizzly 2.4.4</title><style></style> </head><body><div class="header">Request failed.</div><div class="body">Request failed.</div><div class="footer">Grizzly 2.4.4</div></body></html>.

**Comment by sudeshnasengupta** [comment]
If my above observations are indeed valid, I would like to provide a contribution to support Keycloak-based Broker authentication & authorization.

**Comment by mayankshriv** [comment]
Hi @sudeshnasengupta, thanks for filing the issue. Were you able to debug what happens in the access control factory when it is initialized?

It would be better to fix the drop-plugin approach than to add individual implementations, as they might bring in their own transitive dependencies. I'd say if you are able to debug why the plugin is not loaded, lets start from there?

https://github.com/apache/pinot/blob/b91bc69ba8875cdb89e503f8aa2fe46fa163bc8b/pinot-broker/src/main/java/org/apache/pinot/broker/broker/AccessControlFactory.java#L49

**Comment by sudeshnasengupta** [comment]
Hi @mayankshriv : I agree - that would have more "power" for Pinot users, that out of this issue/use-case, Pinot be able to support the ability for a Keycloack Broker authentication implementation be dropped as an external plugin.  The issue is indeed class loader based: obviously, it's not hard to produce an uber JAR containing the Keycloak implementation and its dependencies; the hurdle I'm facing that I discovered while debugging within my IDE is to insert this JAR in the org.apache.pinot.broker.broker.BrokerAdminApiApplication's Grizzly HTTP Server's class loader, before it loads the rest of the classes in the "pinot-broker" module.  I wish I knew more about how to configure Grizzly's HTTP Server's class path: perhaps you know someone who does, who can help?

**Comment by sudeshnasengupta** [comment]
Thankfully (so as to reduce scope of work), we were able to discover the root cause of this issue: since the custom authentication implementation needs to look at the headers stored in the instance of org.apache.pinot.broker.api.HttpRequesterIdentity to obtain the HTTP request's bearer token for validation against Keycloak, any attempt to call org.apache.pinot.broker.api.HttpRequesterIdentity#getHttpHeaders() would fail, because Pinot shades all classes in packages whose names start with "com.google".  To work around this, our implementation is using Java reflection to convert the associated collection into a java.util.Map instance, prior to extracting the bearer token.  As such, I'm closing this issue.  Thanks!

**Comment by dang-stripe** [comment]
@sudeshnasengupta I opened https://github.com/apache/pinot/pull/13209 which should hopefully help surface the error message for these issues a bit better. We ran into a similar issue with Pinot's shading w/ `com.google.common` and our access control plugin.
