### ISSUE TITLE
Metrics for IdeaState update

### ISSUE THREAD

**Issue by pengding-stripe** [apache/pinot#13253]
There are no metrics for recording IdeaState update latency, retry, failures. However this is useful for debugging and monitoring purpose, especially for uploading segment metadata process. We have been seen issues that high latency and retries of updating IdeaState causing segments in error state.
It looks like an easy change to add metric in this function https://github.com/apache/pinot/blob/fdfae5e57aaeb4cd8ca2921cee33c2a45534e40c/pinot-common/src/main/java/org/apache/pinot/common/utils/helix/HelixHelper.java#L100

**Comment by Jackie-Jiang** [comment]
Good suggestion! Do you want to help contribute this?

**Comment by pengding-stripe** [comment]
> Good suggestion! Do you want to help contribute this?

sure

**Comment by pengding-stripe** [comment]
@Jackie-Jiang here is the PR https://github.com/apache/pinot/pull/13266, please help add the observability tag to the PR, I don't have access to do so
