### ISSUE TITLE
What is the best way to track if realtime consumption is stopped at partition level

### ISSUE THREAD

**Issue by tibrewalpratik17** [apache/pinot#13277]
We are exploring ways to set alerts on our realtime table that if consumption stops for any partition in any replica, we can be notified. Consumption can stop due to various reasons:
- Scenario 1: The upstream Kafka partition itself does not have data (this is a legit scenario for no messages consumed)
- Scenario 2: Consuming segment in ERROR / OFFLINE state in any one replica
- Scenario 3: Consuming segment in ERROR / OFFLINE state in ALL replicas

The issue we are facing is differentiating between scenario 1 and scenario 3 intelligently. Till now, we have explored these 2 metrics:
- realtimerowsconsumed
- llcpartitionconsuming

The above metrics specially `llcpartitionconsuming` works great in detecting scenario 2. But in other scenarios (1 and 3), metrics stops getting published rather than a clear differentiation that CONSUMING segment is ONLINE but not consuming (something like publishing 0 realtimerowsconsumed).

We also checked `missingConsumingSegmentTotalCount` but it checks whether CONSUMING segment is present in IDEAL state but not the ExternalView of the table.

Note: There is a not-so-straight-forward way of doing this is using one of the above `realtimerowsconsumed` / `llcpartitionconsuming` metric and having a dependent alert on upstream kafka topic message rate. But can we simplify this somehow from Pinot itself using some form of `callbackGauge` in consuming thread to ping that it is online but not consuming any messages?

Looking forward to suggestions from community on how they are tracking stopped ingestion in their clusters. Thanks!

**Comment by rohityadav1993** [comment]
The delay tracking metric `REALTIME_INGESTION_DELAY_MS` in #9994 should ideally be able to capture the scenario1 with 0 lag and scenario2/3 as a continuously increasing lag.

A controller periodic task should be able to figure out if any of the segment is supposed to be in consuming state, I see `missingConsumingSegmentNewPartitionCount` (#8877) is present and should have worked.

If these metrics are not helpful or emitted properly in scenario of OFFLINE/ERROR segments then we can improve them as well.

**Comment by Jackie-Jiang** [comment]
cc @swaminathanmanish

**Comment by suddendust** [comment]
>But in other scenarios (1 and 3), metrics stops getting published rather than a clear differentiation that CONSUMING segment is ONLINE but not consuming

@tibrewalpratik17 Yes, that metric is not reported when the consumer loop breaks, so you'll observe gaps in the metric. Can you check if this works for you?

```
(sum by (table, topic, partition) (pinot_server_llcPartitionConsuming_Value{} or last_over_time(pinot_server_llcPartitionConsuming_Value[2d]) * 0) == 0) AND on(table) (pinot_controller_tableDisabled_Value{} == 0 AND pinot_controller_tableConsumptionPaused_Value{} == 0)
```

This takes care of the gaps, cases when tables are disabled/paused. Just make sure you give a long enough eval period for the alert, as there are gaps in actual cases as well (these gaps are pretty small, less than 2m). Try having an eval period of 30m.

**Comment by tibrewalpratik17** [comment]
Thanks for your help @suddendust!! 

We are using M3 to track our metrics so the query might become a bit complicated. Let me see if we can workaround in any way. Though I see we can use something like `transformNull 0` and rely on disabled table metric which got added in this PR -- #12000.

**Comment by tibrewalpratik17** [comment]
Closing this as we were able to use `llcPartitionConsuming` and use `transformNull 0` to resolve this.
Sample query for ref:
```
        fetch service:stream-pinot role:pinot-server env:${envRegion.env} name:general_pinot_metric tag_0:llcpartitionconsuming 
          | transformNull 0
          | moving 5m max
          | tagSub tag_1 "((.*_realtime.*?-\d+))-(.*)" "\$1"
          | excludeByTag tag_1 "null"
          | sum tag_1
          | aliasByTags tag_1
```
This kind of works for us for now. We will cherry-pick the disabled table and paused consumption metric to enhance this further.
