### ISSUE TITLE
Pinot UI load time improvements

### ISSUE THREAD

**Issue by npawar** [apache/pinot#13278]
We've noticed Pinot UI tends to load very slow when certain scale is reached (num znodes or payload size). Here's a detailed doc explaining the observations and some potential solutions: https://docs.google.com/document/d/1kcH9JWFjg9PiZFWofaA-xf_m4jhr89Xi3janLgwX8do/edit. Thanks to @shounakmk219  and @jayeshchoudhary for compiling this doc.

**Comment by deepthi912** [comment]
Looking into it.
