### ISSUE TITLE
Error while performing schema evolution

### ISSUE THREAD

**Issue by aishwaryathondapu** [apache/pinot#13312]
While updating the schema through command line AddSchema -schemaFile <schemaConfig.json> -exec it is throwing an error that the "s**chema already exists**". The AddSchema is trying to construct the URL and call to POST API /schemas with override and force parameters. While doing it is constructing the URL wrong and submitting the request. **It is adding "?" in between the query params instead of "&"**

It is added as a part of Pinot 1.1 release in AddSchemaCommand.java class

**Comment by Jackie-Jiang** [comment]
Good catch! Do you want to help contribute a fix?

**Comment by aishwaryathondapu** [comment]
yes.

**Comment by aishwaryathondapu** [comment]
yes.

**Comment by suyashpatel98** [comment]
@Jackie-Jiang Please assign this to me. I will raise the PR soon

**Comment by hpvd** [comment]
@aishwaryathondapu does this bugfix solves this issue for you,
so that we can close it?
