### ISSUE TITLE
Pinot consumer group in kafka ui 

### ISSUE THREAD

**Issue by EhsanMaani** [apache/pinot#13378]
First of all, thank you for your invaluable contributions.

I am writing to seek assistance with an issue we are experiencing with the Pinot consumer in our Kafka UI (image:provectuslabs/kafka-ui).
Our Kafka cluster is running in KRaft mode with Apache Kafka version 2.13-3.7.0. The consumer group configuration for Pinot is as follows:

> streamConfigs": {
    "streamType": "kafka",
    "stream.kafka.topic.name": "test",
    "stream.kafka.broker.list": "broker1:9092,broker2:9092,broker3:9093",
    "stream.kafka.consumer.type": "simple",
    "stream.kafka.consumer.prop.auto.offset.reset": "smallest",
    "stream.kafka.consumer.factory.class.name": "org.apache.pinot.plugin.stream.kafka20.KafkaConsumerFactory",
    "stream.kafka.decoder.class.name": "org.apache.pinot.plugin.stream.kafka.KafkaJSONMessageDecoder",
    "realtime.segment.flush.threshold.rows": "0",
    "stream.kafka.consumer.group.id": "pinot-consumer-group",
    "realtime.segment.flush.threshold.time": "24h",
    "realtime.segment.flush.threshold.segment.size": "100M"
}

Pinot version is 1.1.0 and consuming messages from Kafka is ok but we can't see Pinot consumer in Kafka ui or in Kafka brokers doesn't respond to this command
`bin/kafka-consumer-groups.sh --bootstrap-server broker:9092 --list`

Thank you for your assistance.

**Comment by Conaire** [comment]
same

**Comment by Conaire** [comment]
Pinot doesn't use kafka consumer groups: [Explanation](https://dev.startree.ai/docs/pinot/concepts/real-time-data-ingestion#why-does-pinot-not-use-kafka-consumer-groups)
