### ISSUE TITLE
Inefficient Broker query response

### ISSUE THREAD

**Issue by soumitra-st** [apache/pinot#13414]
### Issue
The broker query response serializes BrokerResponseNative to a JSON String, and then Jersey converts it to a HeapCharBuffer to send the response to the client. This results in three copies of the same data: BrokerResponseNative, JSON String, and HeapCharBuffer. Moreover, the JSON String is quite expensive, and together with other objects, the memory cost of the query response is pretty high.

### Steps to reproduce the issue:

1. Run `quick-start-batch.sh` with `-Xms2G -Xmx2G -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath="<directory to dump heap>" -XX:+ExitOnOutOfMemoryError` to limit the max heap and dump heap on OOM error
2. Execute concurrent queries to `githubComplexTypeEvents` table to download lots of data. Run 10 queries concurrently in a loop to OOM kill the Java process and dump the heap:
`select * from githubComplexTypeEvents limit 100000`

### Issue visible in heap analysis
BrokerResponseNative is ~26M, JSON String is 77M, and HeapCharBuffer is ~77M
![Screenshot 2024-06-17 at 10 57 51 AM](https://github.com/apache/pinot/assets/127247229/20cb8c3a-03a4-421a-8ace-f78f29251170)

### Proposed fix
Broker should stream the BrokerResponse object using [StreamingOutput](https://eclipse-ee4j.github.io/jersey.github.io/apidocs/2.22/jersey/index.html?javax/ws/rs/core/StreamingOutput.html) to avoid converting to String and save heap memory.

**Comment by gortiz** [comment]
> Is it possible to make reducer to run in the off-heap mode?

That would be cool, but the issue here is when data is being serialized using Jersey. Whenever we are returning data that may be large, we should use streaming output so we don't need to keep a new copy in memory.
