### ISSUE TITLE
ago() does not work when year and/or month are specified

### ISSUE THREAD

**Issue by piby180** [apache/pinot#13432]
select ago('P1D') -> works
select ago('P1M') -> does not work
select ago('P1Y') -> does not work

`pinot error: {'errorCode': 720,
 'message': 'QueryPlanningError:\n'
            "Error composing query plan for: select ago('P1M')\n"
            'LIMIT 100001\n'
            'org.apache.pinot.query.QueryEnvironment.planQuery(QueryEnvironment.java:157)\n'
            'org.apache.pinot.broker.requesthandler.MultiStageBrokerRequestHandler.handleRequest(MultiStageBrokerRequestHandler.java:141)\n'
            'org.apache.pinot.broker.requesthandler.BaseBrokerRequestHandler.handleRequest(BaseBrokerRequestHandler.java:288)\n'
            'org.apache.pinot.broker.requesthandler.BrokerRequestHandler.handleRequest(BrokerRequestHandler.java:48)\n'
            'Cannot generate a valid execution plan for the given query: '
            'LogicalSort(fetch=[100001])\n'
            "  LogicalProject(EXPR$0=[ago(_UTF-8'P1M')])\n"
            '    LogicalValues(tuples=[[{ 0 }]])\n'
            '\n'
            'org.apache.pinot.query.QueryEnvironment.optimize(QueryEnvironment.java:323)\n'
            'org.apache.pinot.query.QueryEnvironment.compileQuery(QueryEnvironment.java:261)\n'
            'org.apache.pinot.query.QueryEnvironment.planQuery(QueryEnvironment.java:148)\n'
            'org.apache.pinot.broker.requesthandler.MultiStageBrokerRequestHandler.handleRequest(MultiStageBrokerRequestHandler.java:141)\n'
            'Caught exception while invoking method: public static long '
            'org.apache.pinot.common.function.scalar.DateTimeFunctions.ago(java.lang.String) '
            'with arguments: [P1M]\n'
            'org.apache.calcite.rel.rules.PinotEvaluateLiteralRule.evaluateLiteralOnlyFunction(PinotEvaluateLiteralRule.java:197)\n'
            'org.apache.calcite.rel.rules.PinotEvaluateLiteralRule$EvaluateLiteralShuttle.visitCall(PinotEvaluateLiteralRule.java:137)\n'
            'org.apache.calcite.rel.rules.PinotEvaluateLiteralRule$EvaluateLiteralShuttle.visitCall(PinotEvaluateLiteralRule.java:121)\n'
            'org.apache.calcite.rex.RexCall.accept(RexCall.java:189)\n'
            'Caught exception while invoking method: public static long '
            'org.apache.pinot.common.function.scalar.DateTimeFunctions.ago(java.lang.String) '
            'with arguments: [P1M]\n'
            'org.apache.pinot.common.function.FunctionInvoker.invoke(FunctionInvoker.java:142)\n'
            'org.apache.calcite.rel.rules.PinotEvaluateLiteralRule.evaluateLiteralOnlyFunction(PinotEvaluateLiteralRule.java:183)\n'
            'org.apache.calcite.rel.rules.PinotEvaluateLiteralRule$EvaluateLiteralShuttle.visitCall(PinotEvaluateLiteralRule.java:137)\n'
            'org.apache.calcite.rel.rules.PinotEvaluateLiteralRule$EvaluateLiteralShuttle.visitCall(PinotEvaluateLiteralRule.java:121)\n'
            'null\n'
            'jdk.internal.reflect.GeneratedMethodAccessor490.invoke(Unknown '
            'Source)\n'
            'java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n'
            'java.base/java.lang.reflect.Method.invoke(Method.java:566)\n'
            'org.apache.pinot.common.function.FunctionInvoker.invoke(FunctionInvoker.java:139)\n'
            'Text cannot be parsed to a Duration\n'
            'java.base/java.time.Duration.parse(Duration.java:417)\n'
            'org.apache.pinot.common.function.scalar.DateTimeFunctions.ago(DateTimeFunctions.java:563)\n'
            'jdk.internal.reflect.GeneratedMethodAccessor490.invoke(Unknown '
            'Source)\n'
            'java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n'}`

**Comment by yashmayya** [comment]
Also removing the `multi-stage` label since this behavior is the same in the v1 query engine as well.

**Comment by piby180** [comment]
Doesn't it make sense to consider adding support for months and years with syntax `PnYnMnDTnHnMnS`

I am not a java programmer but something like this
https://www.threeten.org/threeten-extra/apidocs/org.threeten.extra/org/threeten/extra/PeriodDuration.html#parse(java.lang.CharSequence)

**Comment by yashmayya** [comment]
Hm Java's `Duration` class supports parsing only the "duration" part (`PnDTnHnMn.nS`) of the entire format and the `Period` class supports parsing only the "period" part (`PnYnMnD and PnW `) of the entire format (see https://docs.oracle.com/javase/8/docs/api/java/time/Period.html#parse-java.lang.CharSequence-). Unfortunately, it doesn't look like the entire format is supported by any of the `java.time` classes. However, we can consider using something like [this](https://docs.oracle.com/javase/6/docs/api/javax/xml/datatype/DatatypeFactory.html#newDuration%28java.lang.String%29) or [this](https://www.joda.org/joda-time/apidocs/org/joda/time/format/ISOPeriodFormat.html#standard--) to support the full standard.

**Comment by yashmayya** [comment]
Nothing in the original [issue](https://github.com/apache/pinot/issues/6708) or [PR](https://github.com/apache/pinot/pull/6820) for the `ago` function suggests that this was intentional, so I think it makes sense to support the full `PnYnMnDTnHnMnS` ISO-8601 standard.

**Comment by yashmayya** [comment]
Never mind, seems like this was intentional. Years and months are not standard durations since they vary in length. Even Joda-Time throws an exception if we try to convert an `ISO-8601` formatted string containing years or months to milliseconds.

**Comment by piby180** [comment]
Yes, I now think so as well. 
`P1M` could be 28, 29, 30 or 31 days.  This is the distinction betweeen "Calander Time" and "Absolute Time"
https://stackoverflow.com/questions/26265751/what-is-the-value-of-the-iso-8601-duration-p1m-in-seconds

Yet, it would have been nice if Pinot can "Calander Time" because otherwise we would have to handle leap year and month duration within our application code.

**Comment by yashmayya** [comment]
What is the use case exactly? The `ago` function had a very specific use case outlined here - https://github.com/apache/pinot/issues/6708, and what you're describing doesn't seem to fit with the use case that the `ago` function was created for.

**Comment by piby180** [comment]
We have a lot of usecases to compare time series across different time windows. 
For now, I am happy with the ago() function as it is now.  My developers were not aware of `PnDTnHnMn.nS` and raised incidents as per `PnYnMnDTnHnMnS`

I think we can close this issue with an update to Pinot docs.
