### ISSUE TITLE
Add OOM query killing in multi-stage query engine

### ISSUE THREAD

**Issue by gortiz** [apache/pinot#13433]
Pinot has the ability to protect itself from OOM when executing heavy queries by enabling [automatic query killing](https://docs.pinot.apache.org/operators/operating-pinot/oom-protection-using-automatic-query-killing). But this feature is limited to single-stage queries.

We need to add support for multi-stage queries.

**Comment by suyashpatel98** [comment]
I would love to work on this @gortiz. Please assign this to me - I have already merged some tickets to understand the code base better, this will give me an opportunity to contribute to the core parts

**Comment by hpvd** [comment]
@Jackie-Jiang what do think of introducing a new `Resiliency` label for issues like this one?
Would be fitting to all issues making pinot more robust and give users a better more stable experience out of the box

**Comment by siddharthteotia** [comment]
Yes Resiliency label would be useful. In fact, I think we have a bunch of resiliency related open / in-progress work that should ideally be coupled under resiliency label.

**Comment by yashmayya** [comment]
Fixed in https://github.com/apache/pinot/pull/13598 / https://github.com/apache/pinot/pull/13955.
