### ISSUE TITLE
LEAD and LAG window functions not functioning as expected in version 1.1.0

### ISSUE THREAD

**Issue by francescomultari** [apache/pinot#13454]
**Description**
It has been observed that the LEAD and LAG window functions are not producing the expected results when used in our SQL queries. These functions are intended to access data from subsequent or preceding rows within the same result set, but they appear to be accepted among the windows functions

**Steps to Reproduce**
Use the LEAD or LAG window functions in a SQL query.
Compare the output with the expected results.

**Expected Behavior**
The LEAD function should return the value from the next row, and the LAG function should return the value from the previous row, as per their functionality.

**Actual Behavior**
Used the following query:

select id,name, LEAD(name,1) OVER (ORDER BY x)
from table
limit 10

Error obtained when using LEAD or LAG functions

![image](https://github.com/apache/pinot/assets/129774172/19edb591-0eee-477b-be8f-c130978a47fb)
![image](https://github.com/apache/pinot/assets/129774172/002eae1b-d8d8-4a83-bb04-23b9340022e2)

**Comment by Jackie-Jiang** [comment]
@xiangfu0 is this fixed?

**Comment by yashmayya** [comment]
Looks like this should be fixed by https://github.com/apache/pinot/pull/12878 in the upcoming Pinot 1.2.0 release. @francescomultari you can verify by running Pinot from the latest `master` branch (https://github.com/apache/pinot?tab=readme-ov-file#building-pinot).
