### ISSUE TITLE
The TEXT_MATCH result does not meet expectations.

### ISSUE THREAD

**Issue by 0ZhangJc0** [apache/pinot#13455]
When I use TEXT_MATCH to search, I find that the results do not meet expectations.
How should I go about investigating the cause of this issue?

![image](https://github.com/apache/pinot/assets/48285423/30378d93-ef41-47b4-a38b-344d3eb2aa0d)
Here is the configuration for that field.

![image](https://github.com/apache/pinot/assets/48285423/e7acc70a-9c20-4f26-95e6-e0555ede9153)

**Comment by 0ZhangJc0** [comment]
Because the default stop words list of StandardAnalyzer includes "a", it will be excluded from the tokenization results.

**Comment by Jackie-Jiang** [comment]
Does #12027 solve this issue?

**Comment by 0ZhangJc0** [comment]
> Does #12027 solve this issue?
Thank you for your reply。My issue is not related to [#12027](https://github.com/apache/pinot/pull/12027)，just because the default stop words list of StandardAnalyzer includes "a", it will be excluded from the tokenization results. After I correctly configured stopWordExclude, this issue was resolved.

**Comment by Jackie-Jiang** [comment]
I see. Do you use this [config](https://docs.pinot.apache.org/basics/indexing/text-search-support#text-parsing-and-tokenization) to solve the problem? Can we close this issue if it is solved?

**Comment by 0ZhangJc0** [comment]
> I see. Do you use this [config](https://docs.pinot.apache.org/basics/indexing/text-search-support#text-parsing-and-tokenization) to solve the problem? Can we close this issue if it is solved?
This issue can be closed
