### ISSUE TITLE
Multi-stage engine might break MV filter semantic

### ISSUE THREAD

**Issue by Jackie-Jiang** [apache/pinot#13595]
With the dataset in the integration test:

V1 query returns 129:
```
SELECT COUNT(*) FROM mytable WHERE DivWheelsOffs < 1416 AND DivWheelsOffs >= 2344
```

V2 query returns 0:
```
SELECT COUNT(*) FROM mytable WHERE ARRAY_TO_MV(DivWheelsOffs) < 1416 AND ARRAY_TO_MV(DivWheelsOffs) >= 2344
```

The reason is that V2 planner directly detect `ARRAY_TO_MV(DivWheelsOffs) < 1416 AND ARRAY_TO_MV(DivWheelsOffs) >= 2344` as `false`, but it might not be `false` with MV semantic. If one value matches `< 1416` and another value matches `>= 2344` we count it as match.

**Comment by gortiz** [comment]
Can we mark somehow `ARRAY_TO_MV` as a not pure function? Meaning that the returned value is not determined by the input? Something like `random()`.
