### ISSUE TITLE
Flaky metric: llcPartitionConsuming

### ISSUE THREAD

**Issue by tibrewalpratik17** [apache/pinot#13629]
We use `llcPartitionConsuming` to monitor whether Pinot is ingesting data for every partition across all replicas. However, we have been experiencing numerous flaky alerts because Pinot sometimes fails to emit the `llcPartitionConsuming` metric for certain consuming segments.

The metric typically resumes under the following conditions:
- The server is explicitly restarted.
- The segment is committed, and a new consuming segment is formed.

This behavior is unexpected because we emit this metric within the `consumeLoop` method. Therefore, even if it is missed once, it should be emitted at some point during the lifecycle of the entire consuming segment.

**Comment by Jackie-Jiang** [comment]
cc @zhtaoxiang

**Comment by Jackie-Jiang** [comment]
@tibrewalpratik17 Have you figured out thy the metric is not emitted?

**Comment by tibrewalpratik17** [comment]
> Have you figured out thy the metric is not emitted?

I'm not entirely sure, but the `cleanupMetrics` method might be the cause. It specifically removes the `llcPartitionConsuming` metric from the metrics registry.
Ref: https://github.com/apache/pinot/blob/e64ef15330f356dc96fae38d52bce80e6af2068f/pinot-core/src/main/java/org/apache/pinot/core/data/manager/realtime/RealtimeSegmentDataManager.java#L1198-L1200

This method is called after every segment replacement or removal, which, in our case, occurs when a mutable segment becomes an immutable segment. This might somehow conflict with the new consuming segment metric.

**Comment by tibrewalpratik17** [comment]
I found this comment -- https://github.com/apache/pinot/pull/6887#issuecomment-837094283 
where one of the concerns was that removing the metric while a new consuming segment is added might lead to this kind of issue we are talking about but according to the reply, Yammer shouldn't have this.
We have our own metrics factory in Uber -- M3 and so it might be M3-specific issue for us? 

cc @jackjlli @mcvsubbu do we really need this cleanup or is it needed only during number of partitions increased? In that way we can move it behind a config maybe? 

cc @ankitsultana who worked on Yammer -> M3 migration in Uber for Pinot.

**Comment by jackjlli** [comment]
@tibrewalpratik17 this `cleanupMetrics()` method is very essential to be invoked, as there is no guarantee that new consuming segments for the same partition will always be assigned to the same realtime pinot-server.

I don't think we encounter such metric issue here at LinkedIn and the method has been there for a while. I'd suggest collecting more stats from your side for M3 and see if there is any potential race condition that could occur.

**Comment by tibrewalpratik17** [comment]
Thanks for the reply @jackjlli! 

> I'd suggest collecting more stats from your side for M3 and see if there is any potential race condition that could occur.

Hmm this might be a bigger effort on our end as we will have to scope this out with the centralised observability team.

> this cleanupMetrics() method is very essential to be invoked, as there is no guarantee that new consuming segments for the same partition will always be assigned to the same realtime pinot-server.

What about upsert tables? Pinot guarantees for upsert tables the consuming segments will be in the same partition. Can we change the logic to set gauge value to 0 instead of removing from metrics-registry specifically for upsert tables? I am setting to 0 as table rebalance might be the only reason that would change partition <> host mapping for upsert tables. This will cover most of the use-cases at Uber where we are trying to put alerts on this metric for tracking consumption.

Let me know your thoughts on this!

**Comment by jackjlli** [comment]
@tibrewalpratik17 Even for upsert tables if there is a need to uplift it's still possible that segments will be assigned to a different server.
And what's more, we couldn't use 0 here, as `0` denotes the current pinot-server is still responsible for the target partition but the data is not being consumed right now, which leads to false alarm to be triggered (in LinkedIn we do set up the alert on monitoring the value of this metric and the alert will be triggered as long as the value is non-0.

I'd suggest getting more evidence from your side, say when a new consuming segment for the same partition is initialized, check the log to make sure if the metric is actually created.

**Comment by tibrewalpratik17** [comment]
> I'd suggest getting more evidence from your side, say when a new consuming segment for the same partition is initialized, check the log and the monitoring console to make sure if the metric is actually created.

Sure we are rolling out one more patch for partial-upserts to pause consumption during segment commit unlike realtime tables where we release consumer semaphore before. Hopefully, after that this issue will reduce as `closeStreamConsumers` is called right before `cleanupMetrics`. But I will keep this thread posted in case that fixes majority of our problems or not.

**Comment by tibrewalpratik17** [comment]
Found the root-cause. Addressed it here: #13679 

cc @jackjlli @Jackie-Jiang please help review.

**Comment by jackjlli** [comment]
Thanks @tibrewalpratik17 for addressing the issue! Feel free to close this OSS issue if it's been resolved by your PR.

**Comment by tibrewalpratik17** [comment]
Closing as completed by #13679
