### ISSUE TITLE
[Backward incompatible issues in 1.1] segmentAssignmentStrategy can be NULL after it is deprecated in SegmentValidationAndRetentionConfig

### ISSUE THREAD

**Issue by MeihanLi** [apache/pinot#13659]
Due to #11869, now segmentAssignmentStrategy can be NULL, this seems a breaking change as it requires explicitly code change otherwise we will create TableInfo with NULL segmentAssignmentStrategy.

**Comment by MeihanLi** [comment]
cc @Jackie-Jiang I also saw you commented in the pr that this is backward incompatible, do we have a fix for it?

**Comment by Jackie-Jiang** [comment]
Can you elaborate more on the problem? We didn't introduce backward incompatibility in the PR (I commented and the contributor reverted the change). Basically it is okay to have it as `null`. Are you using this field in your internal code?

**Comment by MeihanLi** [comment]
yes, we control the table config creation so it's a big change for us. As long as leaving it as NULL works, we are fine with it. Thanks @Jackie-Jiang for taking a look at this issues, we can close it.
