### ISSUE TITLE
Improve InstanceSelector routing logic for new segments

### ISSUE THREAD

**Issue by tibrewalpratik17** [apache/pinot#13683]
Recently, we experienced an incident in our production environment where numerous query failures occurred due to the absence of a replica group to route the queries to. We are using the `strictReplicaGroup` policy.

Upon debugging, we identified the following issue:

- A new consuming segment was added to the Ideal state at `19:32`
- Both replica servers received Helix transition message `SegmentOnlineOfflineStateModel.onBecomeConsumingFromOffline()` at 19:32
- Both replicas actually began consuming (`Created new consumer thread Thread:`) at 19:39, and the External view was updated at `19:39`.

Here's how the broker-segment-state updates occurred:

-  The segment was added to `_newSegmentStateMap` at approximately `19:33` : [Ref](https://github.com/apache/pinot/blob/00871f242fa7342e252d956b54d246d289887408/pinot-broker/src/main/java/org/apache/pinot/broker/routing/instanceselector/BaseInstanceSelector.java#L398-L417)
- By `19:38`, it was no longer considered a new segment due to this clause ([Ref](https://github.com/apache/pinot/blob/00871f242fa7342e252d956b54d246d289887408/pinot-broker/src/main/java/org/apache/pinot/broker/routing/instanceselector/InstanceSelector.java#L38-L40)) and was moved from `_newSegmentStateMap` to `_oldSegmentCandidatesMap`.
- At `19:38`, we started seeing query failures as both instances were tagged unavailable, thus making the replicas unavailable. Both instances were tagged unavailable because the External view was NULL for this "old-tagged" segment.
LOG:
```
Found unavailable instance: <SampleInstance1> in instance group: [SampleInstance1, SampleInstance2] for segment: 
SegmentName1, table: TableName1 (IS: {SampleInstance1=CONSUMING, SampleInstance2=CONSUMING}, EV: null)
```

One of the solution is:

- Make the `NEW_SEGMENT_EXPIRATION_MILLIS` parameter configurable here:
https://github.com/apache/pinot/blob/00871f242fa7342e252d956b54d246d289887408/pinot-broker/src/main/java/org/apache/pinot/broker/routing/instanceselector/InstanceSelector.java#L38-L40 

Note: The strategy discussed in #13284 would also have not helped in this scenario as both the replicas were not present in ExternalView.

**Comment by rohityadav1993** [comment]
Thanks @tibrewalpratik17 for the analysis. This could be aggravated due to https://github.com/apache/pinot/pull/13256.

Configuring NEW_SEGMENT_EXPIRATION_MILLIS can be a good short-term fix.

**Comment by tibrewalpratik17** [comment]
Hey @rohityadav1993 yes looks like #13256 might be the reason. I see the new consuming thread blocked for 5-6 minutes when the old consuming segment was getting replaced by Immutable segment.

**Comment by ankitsultana** [comment]
@tibrewalpratik17 @rohityadav1993 : can you folks confirm what's the plan for fixing the semaphore release issue which you mentioned is likely introduced by #13256 ?

Because technically that would be the right thing to fix here right?

**Comment by tibrewalpratik17** [comment]
> Because technically that would be the right thing to fix here right? (or are we saying that there's no way to improve upon https://github.com/apache/pinot/pull/13256, and this is something we will have to deal with for partial upsert tables going forward

Yeah for data-consistency guarantees, we need to release the semaphore post the segment has been committed completely (immutable segment replaced mutable segment). One thing which i was thinking is that in the new consuming segment thread during the state change `OFFLINE -> CONSUMING`, we are waiting for the lock release. Maybe if we can move that operation to another async thread and change the segment state irrespective then that might help. But that is more of a fundamental change which will affect all types of tables (upsert / non-upsert ones) so we can leave that to another discussion. 

For our case specifically, we saw the segment build time is taking ~7 mins likely because the number of columns are 300+. We can use this #13686 as a fix for this particular use-case and then discuss about the general fix. Wdyt?

**Comment by ankitsultana** [comment]
Haven't thought deeply about this, but instead of adding a new routing config as in #13686, could we instead use a separate semaphore for blocking partial upsert table consumption in `PartitionConsumer#run` (or there might be some other better place)?

The idea is that to ensure consistency for Partial Upserts, it's enough to make sure the consumption doesn't start before the previous segment is completely destroyed. To do that, using the current semaphore is a bit of an overkill since it straight up blocks the creation of the segment data manager.

Instead, all we want to block in that case is the consumption, which could be done in a more fine-grained manner by doing it in `PartitionConsumer`.

We won't need any new configs for this either.

**Comment by tibrewalpratik17** [comment]
> could we instead use a separate semaphore for blocking partial upsert table consumption in PartitionConsumer#run (or there might be some other better place)?
The idea is that to ensure consistency for Partial Upserts, it's enough to make sure the consumption doesn't start before the previous segment is completely destroyed. To do that, using the current semaphore is a bit of an overkill since it straight up blocks the creation of the segment data manager.
Instead, all we want to block in that case is the consumption, which could be done in a more fine-grained manner by doing it in PartitionConsumer.

I agree that this approach makes more sense, but I'm a bit concerned about potential repercussions. During the state transition from `OFFLINE -> CONSUMING`, we create the segment-data-manager and then register it. If we register it without starting consumption, there might be side effects that I can't fully identify yet.

I'm open to exploring that route as well. However, since it might involve significant changes (considering the fundamental nature of Helix transitions), could we quickly patch the configuration proposed in #13686 to unblock our production issues for now? 

Allowing flexibility to fine-tune the segment-expiration configuration wouldn't have any major side effects and would be beneficial in other scenarios where build times are high.
