### ISSUE TITLE
Error in Pinot Release: "duplicate artifacts attached"

### ISSUE THREAD

**Issue by ankitsultana** [apache/pinot#13707]
While trying to perform the 1.2.0 Release, I ran into an issue while running `release:perform`.

```
[INFO] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-source-plugin:3.3.1:jar (attach-sources) on project pinot-spi: Presumably you have configured maven-source-plugin to execute twice in your build. You have to configure a classifier for at least one of them. -> [Help 1]
[INFO] [ERROR]
[INFO] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[INFO] [ERROR] Re-run Maven using the -X switch to enable full debug logging.
[INFO] [ERROR]
[INFO] [ERROR] For more information about the errors and possible solutions, please read the following articles:
[INFO] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[INFO] [ERROR]
[INFO] [ERROR] After correcting the problems, you can resume the build with the command
[INFO] [ERROR]   mvn <args> -rf :pinot-spi
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Pinot 1.3.0-SNAPSHOT:
[INFO]
[INFO] Pinot .............................................. FAILURE [01:06 min]
[INFO] Pinot Service Provider Interface ................... SKIPPED
[INFO] Pinot Segment Service Provider Interface ........... SKIPPED
```

### Why this error is coming up?

This error is coming because `maven-source-plugin` from `3.3.0` onwards has a check that will fail execution if it detects multiple invocations of the plugin. [ref-1](https://github.com/rvesse/source-plugin-breaks-releases), [corresponding jira](https://issues.apache.org/jira/browse/MSOURCES-143).

### Why didn't this come with Pinot 1.1.0 Release?

This is because during Pinot 1.1.0 release, we were running with `org.apache.apache:21` ([ref](https://github.com/apache/pinot/blame/release-1.1.0-rc/pom.xml#L28)).

And that version was using `maven-source-plugin:3.0.1` ([ref](https://repository.apache.org/service/local/repo_groups/public/content/org/apache/apache/21/apache-21.pom)).

### How do we fix this?

A potential fix is to switch to `jar-no-fork` in our root `pom.xml` for the `maven-source-plugin`.

### Related

While doing a release of Pinot internally at Uber, they had run into a similar issue. At the time, since `maven-source-plugin` didn't outright fail the `release:perform` command, they were running into a separate point of failure, but the root cause was the same.

PR #4889 was raised 5 years ago by @chenboat. Though that PR also pins the version of `maven-source-plugin`, which I hope is not necessary.

**Comment by xiangfu0** [comment]
Thanks for the explanation and the fix.

**Comment by ankitsultana** [comment]
This was fixed by the linked PR. #13708
