### ISSUE TITLE
How can I use Groovy Scripts in Pinot while in Web Application

### ISSUE THREAD

**Issue by Drun1baby** [apache/pinot#13807]
I just tried a post request

```http

http://127.0.0.1:9000/schemas/validate

{
  "schemaName": "flights",
  "enableColumnBasedNullHandling": false,
  "dateTimeFieldSpecs": [
    {
      "name": "flights",
      "transformFunction": "Groovy({new File('/tmp/success').createNewFile()})",
      "dataType": "STRING",
      "format": "SIMPLE_DATE_FORMAT|yyyy-MM-dd",
      "granularity": "1:DAYS"
    }
  ]
}

```

<img width="1879" alt="image" src="https://github.com/user-attachments/assets/a4139dd4-483d-4ea1-99b2-7c4e78771fc9">

but not triggered successfully, how can I trigger it successfully?

**Comment by Jackie-Jiang** [comment]
I think it is triggered successfully. The request is to **validate** the schema, and it does return the validated schema.

**Comment by Drun1baby** [comment]
But actually that Grovvy scripts not triggered, and as a result, i can not get any info from logs

**Comment by Jackie-Jiang** [comment]
Hmm.. It doesn't work this way, and actually you are trying to attack the system because the system shouldn't allow accessing local files through table creation or query.

**Comment by Drun1baby** [comment]
all right I know it lol
