### ISSUE TITLE
[Question] S3 as deep storage usage is high

### ISSUE THREAD

**Issue by manhnt98** [apache/pinot#13861]
Hi folks,
I'm new to Pinot and try setting deep storage.
The data usage in S3 is increasing high after days even though it's not much on server.
Can setting retention on tables will reduce S3 deep store usage by having old segment files removed ?

**Comment by Jackie-Jiang** [comment]
Yes. Retention manager should be able to remove segments from deep store after they expire

**Comment by Jackie-Jiang** [comment]
You may ask questions in our Slack `troubleshooting` channel, where you might be able to find answer faster :)
