### ISSUE TITLE
Environment variables in table configs are revealed

### ISSUE THREAD

**Issue by vytautas-karpavicius** [apache/pinot#13983]
**Context**
Pinot allows replacing environment variables in tables configs [as documented](https://docs.pinot.apache.org/configuration-reference/table#environment-variables-override)

This can be used to replace secrets configured in table config. For example to ingest from kafka cluster that has authorization one might configure:
```
{
  "tableIndexConfig": {
    "streamConfigs": {
      "sasl.jaas.config": "${KAFKA_SASL_CONFIG}"
    }
  }
}
```

**Problem**
While environment variable replacement works, it reveals the secret when showing table config in UI or API. This defeats the purpose of having secrets replaced with environment variables.

**To reproduce**
1. Follow startup guide:
```
# Clone a repo
$ git clone https://github.com/apache/pinot.git
$ cd pinot

# Build Pinot
$ mvn clean install -DskipTests -Pbin-dist
```

2. Export secret
```
export MY_SECRET=to_not_reveal
```

3. Start Pinot
```
# Run the Quick Demo
$ cd build/
$ bin/quick-start-batch.sh
```

4. Open sample table:
http://localhost:9000/#/tenants/table/airlineStats_OFFLINE
Edit its config, change metadata and save:
```
    "metadata": {
      "customConfigs": {
        "regular": "some-value",
        "secret": "${MY_SECRET}"
      }
    },
```

5. After saving, the secret is revealed in the same UI:
```
    "metadata": {
      "customConfigs": {
        "regular": "some-value",
        "secret": "to_not_reveal"
      }
    },
```

6. Check the state in Zookeeper, it is saved correctly:
```
"metadata": "{\"customConfigs\":{\"regular\":\"some-value\",\"secret\":\"${MY_SECRET}\"}}",
```

**Expected behaviour**
Environment variables should be replaced only internally within Pinot. They should not be replaced when stored in ZK, nor when revealed in UI or via API call.

**Comment by Jackie-Jiang** [comment]
Thanks for reporting the issue. We need to mask the value in rest API. cc @xiangfu0 @soumitra-st
