### ISSUE TITLE
Bump commons-io:commons-io from 2.11.0 to 2.16.1

### ISSUE THREAD

**Issue by abhioncbr** [apache/pinot#14026]
Check the failure [here](https://github.com/apache/pinot/pull/14019)

**Comment by Jackie-Jiang** [comment]
@rfscholte Can you please take a look at this? We should avoid hard-coding library version in the test

**Comment by rfscholte** [comment]
In this case commons-io is not a project dependency but a test resources, which is being downloaded by Maven. It should not be updated, unless you adjust the version at https://github.com/apache/pinot/blob/dependabot/maven/commons-io-commons-io-2.16.1/pinot-spi/src/test/java/org/apache/pinot/spi/plugin/ClassLoaderTest.java#L172-L174

**Comment by rfscholte** [comment]
Maybe https://github.com/apache/pinot/pull/14031 can help to prevent this in the future.
