### ISSUE TITLE
[Documentation] Contribution Guide Link Not Working

### ISSUE THREAD

**Issue by engrravijain** [apache/pinot#14095]
Link mentioned at https://github.com/apache/pinot?tab=readme-ov-file#contributing-to-pinot for the contribution guide is re-directing to https://docs.pinot.apache.org/community/contribution which gives a **Page not found** error. 

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/0d4812d9-e335-4c78-8c4a-874535ae5f6f">

**Comment by Jackie-Jiang** [comment]
Fixed by #14095
