### ISSUE TITLE
Do not allow setters in `IndexLoadingConfig`

### ISSUE THREAD

**Issue by Jackie-Jiang** [apache/pinot#14106]
`IndexLoadingConfig` should always be initialized by `TableConfig` and `Schema`, and all the index related config should be extracted from them. Right now we allow setters to internal fields such as `_invertedIndexColumns`, `noDictionaryColumns` etc which makes config management extremely hard, especially after introducing Index SPI. We have run into problems such as forward index config not picked up from table config.

We use this issue to track all effort of removing setters from `IndexLoadingConfig`.

Similarly, we should also remove all setters in `SegmentGeneratorConfig`

**Comment by Jackie-Jiang** [comment]
Do not allow setting TableConfig in IndexLoadingConfig after construction: #14098

**Comment by deepthi912** [comment]
I can look into this.

**Comment by Jackie-Jiang** [comment]
Cleanup `ForwardIndexHandlerTest`: #14124

**Comment by Jackie-Jiang** [comment]
Cleanup `SegmentPreProcessorTest`: #14143

**Comment by Jackie-Jiang** [comment]
Cleanup `LoaderTest`: #14149
