### ISSUE TITLE
Native text file is not copied during segment seal?

### ISSUE THREAD

**Issue by jt-kloudfuse** [apache/pinot#14136]
This is the file that gets created by NativeTextIndexCreator during segment seal - https://github.com/apache/pinot/blob/56ccbc3d5f04f0d62041c32d314b814c1b7cab4f/pinot-segment-local/src/main/java/org/apache/pinot/segment/local/segment/creator/impl/text/NativeTextIndexCreator.java#L81

Later on, in the segment creation lifecycle, pinot converts from v1/v2 to v3 format. This is when all index files are either put into the V3 directory or copied inside the column.psf file. This happens here
https://github.com/apache/pinot/blob/56ccbc3d5f04f0d62041c32d314b814c1b7cab4f/pinot-segment-local/src/main/java/org/apache/pinot/segment/local/segment/index/converter/SegmentV1V2ToV3FormatConverter.java#L160

If you notice, there is a condition to specifically skip text and vector indexes. The comment says text indexes are copied separately.  A few lines, there is a function that copies out the lucene index files into v3 directory. 

The problem is that there is no such code to copy out nativeTextIndex files. So they are just completely ignored and deleted.

The unit tests all still end up working fine because at segment load time, the segmentPrePrecessort ends up recreating the full text index. Here, https://github.com/apache/pinot/blob/56ccbc3d5f04f0d62041c32d314b814c1b7cab4f/pinot-segment-local/src/main/java/org/apache/pinot/segment/local/segment/index/loader/invertedindex/TextIndexHandler.java#L201

This seems like a bug to me. If you guys can confirm I can submit a patch to fix it. Fix seems pretty simple.

**Comment by Jackie-Jiang** [comment]
Thanks for triaging this. Yes I believe this is a bug. Please help submit a fix, thanks!
