### ISSUE TITLE
Pinot Helm Chart New Version Release

### ISSUE THREAD

**Issue by nilaprasad** [apache/pinot#14168]
New changes have been made to the Pinot helm chart.

1.  Added namespace support in K8s deployment #13380 
2. Fixed Kubernetes Routing Issue #13450 

This issue is to release/publish a newer version of the Pinot Helm chart.

Currently in progress by myself

**Comment by nilaprasad** [comment]
cc @abhioncbr @xiangfu0

**Comment by hpvd** [comment]
added this to  [parent issue] Kubernetes related topics #14162

**Comment by nilaprasad** [comment]
PR was merged in earlier today and the new version has been published.
