### ISSUE TITLE
Add documentation for `JSON_EXTRACT_INDEX`

### ISSUE THREAD

**Issue by Jackie-Jiang** [apache/pinot#14202]
`JSON_EXTRACT_INDEX` was added in #11739, and was further improved with #12466, #12532, #12683, #12748

We want to document it under these pages:
- https://docs.pinot.apache.org/basics/indexing/json-index
- https://docs.pinot.apache.org/configuration-reference/functions

**Comment by Jackie-Jiang** [comment]
@itschrispeck Do you want to help with this?

**Comment by itschrispeck** [comment]
Yep, I think I owe some docs.
