### ISSUE TITLE
Lucene 9.12.0 upgrade

### ISSUE THREAD

**Issue by abhioncbr** [apache/pinot#14232]
Refer the [PR](https://github.com/apache/pinot/pull/14219)

**Comment by hpvd** [comment]
Overview of what has been changed and what has to be done after upgrade e.g. reindex
https://lucene.apache.org/core/corenews.html#apache-lucenetm-1000-available

**Comment by hpvd** [comment]
full changelog:
https://lucene.apache.org/core/10_0_0/changes/Changes.html#v10.0.0

**Comment by abhioncbr** [comment]
The documentation shared by @hpvd, [link](https://lucene.apache.org/core/corenews.html#apache-lucenetm-1000-available) mentions that Lucene 10 needs JDK21 or newer

<img width="730" alt="image" src="https://github.com/user-attachments/assets/6c755ae3-702d-43e4-a5f9-51ed68cc29d4">

I don't think that we can opt for these changes because we do support Java 11 and 17.

**Comment by Jackie-Jiang** [comment]
Thanks for the investigation! Shall we upgrade to `9.12.0` instead?

**Comment by abhioncbr** [comment]
Sure, definitely.

**Comment by hpvd** [comment]
added this topic to https://github.com/apache/pinot/issues/14325

**Comment by hpvd** [comment]
@Jackie-Jiang sure, done: https://github.com/apache/pinot/issues/14354
