### ISSUE TITLE
ImmutableTableOptions and ImmutableQueryEnvironment not found

### ISSUE THREAD

**Issue by chunxiaozheng** [apache/pinot#14261]
when i run pinot locally, org.apache.pinot.calcite.rel.rules.ImmutableTableOptions and other classes were not found

**Comment by gortiz** [comment]
You have to compile the code at least once to generate these classes. If you are running it in intellij, be sure you it updates the code once maven has compiled it.

**Comment by chunxiaozheng** [comment]
> You have to compile the code at least once to generate these classes. If you are running it in intellij, be sure you it updates the code once maven has compiled it.

Thank you for your reply. I have found the problem, I compiled it using JDK21, currently, it has been resolved using JDK11
