### ISSUE TITLE
Add list of tables queried to Pinot query response

### ISSUE THREAD

**Issue by dang-stripe** [apache/pinot#14381]
We'd like the Pinot broker query response to contain a “tablesQueried” field instead that contains a list of tables that were queried. This should ideally work for both single-stage and multi-stage queries.

We are performing some validation that relies on the stageStats API to do some validation before the query response is returned, but realize that stageStats isn't meant to be a stable API.

**Comment by Jackie-Jiang** [comment]
cc @gortiz

**Comment by vrajat** [comment]
Coincidentally I had added this feature in #14110 I've extracted the code and opened a PR.

**Comment by dang-stripe** [comment]
Great, thank you @vrajat!
