### ISSUE TITLE
Nullity Error When Querying `MAX` On Non-Numeric Column

### ISSUE THREAD

**Issue by ashishjayamohan** [apache/pinot#14459]
When querying the `MAX` of a column, we use `NonScanBasedAggregationOperator` to use the stored metadata. This produces a nullity error on non-numeric columns as these columns do not have a stored max value. Ideally, this should produce a more informative error that states this aforementioned reason.
![Screenshot 2024-11-14 at 2 50 11 PM](https://github.com/user-attachments/assets/84f56080-b4ad-48c5-9ad7-80a176bf980b)

**Comment by Jackie-Jiang** [comment]
Hmm, it is actually a `NumberFormatException` which is expected because `MAX` only works on numbers as of now

**Comment by ashishjayamohan** [comment]
Correct, I updated to not be NPE. I think it would be better to state this error more informatively (rather than "null," state type)

**Comment by Jackie-Jiang** [comment]
`"null"` is the actual string value, which cannot be parsed as number
