### ISSUE TITLE
RequestUtils getTableNames does not return multiple table names for sql join queries

### ISSUE THREAD

**Issue by AlexanderKM** [apache/pinot#14555]
For a query like 
```sql
SELECT 
  table1.foo,
  table2.bar 
FROM 
  table1 
JOIN table2 ON table1.id = table2.id 
LIMIT 10;
```

the method [RequestUtils#getTablesNames](https://git.hubteam.com/HubSpot/pinot/blob/hubspot-1.1.0/pinot-common/src/main/java/org/apache/pinot/common/utils/request/RequestUtils.java#L385) will only return the `table1` as table names from the query.

For context of usage, we use this method to track metrics on the tables we are querying, so it is quite useful to us.

**Comment by yashmayya** [comment]
Fixed in https://github.com/apache/pinot/pull/14554
