### ISSUE TITLE
nested schema and all string schema?

### ISSUE THREAD

**Issue by lucentcosmos** [apache/pinot#1917]
Hello, my kafka data is like this:

{"pDateTime":"2017091900","dataType1":"2","dataType2":"1006","dataContent":"{\"time\":\"2017-09-19T00:51:45.106Z\",\"dataType1\":\"2\",\"dataType2\":\"1006\",\"ipAdd\":\"00.00.0.00\",\"accountId\":\"xxxxx\"}"}

I wonder if pinot support for nested schema? Also, my data field is all strings, even time. Do I have to change to your format? Thanks.

**Comment by anujambekar** [comment]
+1

**Comment by Jackie-Jiang** [comment]
Support is added as https://docs.pinot.apache.org/basics/data-import/pinot-input-formats/complex-type
