### ISSUE TITLE
How to use real time table to get kafka data from port other than 19092?

### ISSUE THREAD

**Issue by lucentcosmos** [apache/pinot#1942]
Hello,

I want to use pinot to consume my existing kafka topics which run on port 9092. I cannot change that since I don't own that kafka cluster. 

I wonder if there is a way to work with existing kafka topics? I checked your scripts and code and could not find a way. 

Please help! Thanks in advance.

**Comment by mcvsubbu** [comment]
@letsflykite you should be able to configure your kafka topic broker name in the streamConfigs section of the table configuration. You can follow the example as in  LLRealtimeClusterIntegrationTest (most of the configuration is in the super-class).

**Comment by letsflykite** [comment]
Thanks. However after reading source code including https://github.com/linkedin/pinot/blob/master/pinot-integration-tests/src/test/java/com/linkedin/pinot/integration/tests/RealtimeClusterIntegrationTest.java, I did not find any way of using schema.json change only or even an argument to sh script to achieve the Kafka port customization. Can you give an example without revising Pinot java source code?
