### ISSUE TITLE
Too many segments in a table caused entire cluster ingestion hanging

### ISSUE THREAD

**Issue by xiangfu0** [apache/pinot#2088]
We recently observed a long time ago set up table with long retention caused large number of segments in idealstates(after compressed) and eventually exceeded the 1mb znode limit.

The exception of znode write hangs the controller zkclient which blocked all the new segments added(idealstates update) and stale the ingestion pipeline.

In order to prevent this happen again, we may need to check the idealstate size before write it and better to expose the metrics so we can alert accordingly.

Also is there a way to detect zkclient issue and reconnect it ?

**Comment by kishoreg** [comment]
Helix library checks for the size and should fail if the request if the
data size exceeds 1MB. What was the exact behavior here?. Any stack traces?

**Comment by fx19880617** [comment]
the old logs are flushed out, what I've seen is zkclient got connected and disconnect immediately.
2017/11/05 23:51:09.994 INFO [ClientCnxn] Opening socket connection to server kloakzk44-dca1.prod.uber.internal/10.184.26.29:2181. Will not attempt to authenticate using SASL (unknown error)
2017/11/05 23:51:09.994 INFO [ClientCnxn] Socket connection established to kloakzk44-dca1.prod.uber.internal/10.184.26.29:2181, initiating session
2017/11/05 23:51:10.003 INFO [ClientCnxn] Session establishment complete on server kloakzk44-dca1.prod.uber.internal/10.184.26.29:2181, sessionid = 0x2a5b3a45884667a2, negotiated timeout = 30000
2017/11/05 23:51:10.015 INFO [ZkClient] zookeeper state changed (SyncConnected)
2017/11/05 23:51:10.029 INFO [ClientCnxn] Unable to read additional data from server sessionid 0x2a5b3a45884667a2, likely server has closed socket, closing socket connection and attempting reconnect
2017/11/05 23:51:10.141 INFO [ZkClient] zookeeper state changed (Disconnected)
2017/11/05 23:51:10.262 INFO [ClientCnxn] Opening socket connection to server kloakzk42-dca1.prod.uber.internal/10.184.24.25:2181. Will not attempt to authenticate using SASL (unknown error)
2017/11/05 23:51:10.262 INFO [ClientCnxn] Socket connection established to kloakzk42-dca1.prod.uber.internal/10.184.24.25:2181, initiating session
2017/11/05 23:51:10.272 INFO [ClientCnxn] Session establishment complete on server kloakzk42-dca1.prod.uber.internal/10.184.24.25:2181, sessionid = 0x2a5b3a45884667a2, negotiated timeout = 30000
2017/11/05 23:51:10.285 INFO [ZkClient] zookeeper state changed (SyncConnected)
2017/11/05 23:51:10.307 WARN [ClientCnxn] Session 0x2a5b3a45884667a2 for server hostname/xx.xxx.xx.xxx:2181, unexpected error, closing socket connection and attempting reconnect
java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:117)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:366)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2017/11/05 23:51:10.419 INFO [ZkClient] zookeeper state changed (Disconnected)

**Comment by estebanz01** [comment]
I'm seeing this behaviour in a table with 36 GB of data in roughly 368000 segments. It's not fun when it happens :grinning:

**Comment by Jackie-Jiang** [comment]
This problem can be solved by adjusting the ZK settings (documented [here](https://docs.pinot.apache.org/reference/troubleshooting/troubleshoot-zookeeper#adjust-zookeeper-znode-size))

@estebanz01 It shouldn't hit the 1MB limit with 3680 segments unless segments are all with very long and unique names (compression rate very low). Usually the ZK issue is hit with more than 10K segments
