### ISSUE TITLE
metricField with long type throw IndexOutOfBoundsException

### ISSUE THREAD

**Issue by binlijin** [apache/pinot#22]
table schema file 
{
  "dimensionFieldSpecs" : [
    {
      "name": "field",
      "dataType" : "STRING",
      "delimiter" : null,
      "singleValueField" : true
    },
    {
      "name": "host",
      "dataType" : "STRING",
      "delimiter" : null,
      "singleValueField" : true
    }
  ],
  "timeFieldSpec" : {
    "incomingGranularitySpec" : {
      "timeType" : "SECONDS",
      "dataType" : "LONG",
      "name" : "time"
    }
  },
  "metricFieldSpecs" : [
    {
      "name" : "value",
      "dataType" : "LONG",
      "delimiter" : null,
      "singleValueField" : true
    }
   ],
  "schemaName" : "changefield"
}
table definition file 
{
    "tableName":"changefield",
    "segmentsConfig" : {
        "retentionTimeUnit":"DAYS",
        "retentionTimeValue":"7",
        "segmentPushFrequency":"daily",
        "segmentPushType":"APPEND",
        "replication" : "1",
        "schemaName" : "changefield",
        "timeColumnName" : "time",
        "timeType" : "SECONDS",
        "segmentAssignmentStrategy" : "BalanceNumSegmentAssignmentStrategy"
    },
    "tableIndexConfig" : {
        "invertedIndexColumns" : ["field", "host"],
        "loadMode"  : "HEAP",
        "lazyLoad"  : "false",
                "streamConfigs": {
                        "streamType": "kafka",
                        "stream.kafka.consumer.type": "highLevel",
                        "stream.kafka.topic.name": "changefield-realtime",
                        "stream.kafka.decoder.class.name": "com.linkedin.pinot.core.realtime.impl.kafka.KafkaJSONMessageDecoder",
                        "stream.kafka.zk.broker.url": "localhost:2181",
                        "stream.kafka.hlc.zk.connect.string": "localhost:2181"
                }
    },
    "tableType":"REALTIME",
        "tenants" : {
                "broker":"brokerOne",
                "server":"serverOne"
        },
    "metadata": {
    }
}
one example record： ["field311", "host10", "1435636716222", "815"]

when i use the above schema i get  IndexOutOfBoundsException when dump segment, but if i change the value dataType from "LONG" to "INT", it just success.
Exception ：
2015/06/29 11:48:33.386 INFO [com.linkedin.pinot.core.data.manager.realtime.RealtimeSegmentDataManager] [] Trying to build segment!
2015/06/29 11:48:33.394 INFO [com.linkedin.pinot.core.segment.creator.impl.SegmentIndexCreationDriverImpl] [] Start building StatsCollector!
2015/06/29 11:49:59.837 ERROR [com.linkedin.pinot.core.data.manager.realtime.RealtimeSegmentDataManager] [] Caught exception in the realtime indexing thread
java.lang.IndexOutOfBoundsException
        at java.nio.Buffer.checkIndex(Buffer.java:538)
        at java.nio.DirectByteBuffer.getLong(DirectByteBuffer.java:766)
        at com.linkedin.pinot.core.index.reader.impl.FixedByteWidthRowColDataFileReader.getLong(FixedByteWidthRowColDataFileReader.java:204)
        at com.linkedin.pinot.core.index.readerwriter.impl.FixedByteSingleColumnSingleValueReaderWriter.getLong(FixedByteSingleColumnSingleValueReaderWriter.java:140)
        at com.linkedin.pinot.core.realtime.impl.RealtimeSegmentImpl.getRawValueRowAt(RealtimeSegmentImpl.java:539)
        at com.linkedin.pinot.core.realtime.converter.RealtimeSegmentRecordReader.next(RealtimeSegmentRecordReader.java:78)
        at com.linkedin.pinot.core.segment.creator.impl.SegmentIndexCreationDriverImpl.build(SegmentIndexCreationDriverImpl.java:105)
        at com.linkedin.pinot.core.realtime.converter.RealtimeSegmentConverter.build(RealtimeSegmentConverter.java:88)
        at com.linkedin.pinot.core.data.manager.realtime.RealtimeSegmentDataManager$2.run(RealtimeSegmentDataManager.java:153)
        at java.lang.Thread.run(Thread.java:744)

**Comment by kishoreg** [comment]
Can you provide additional context such as you schema, sample record etc.
Can you reproduce this easily? we can add some logging to get more info.

thanks,
Kishore G

**Comment by binlijin** [comment]
I can reproduce it easily, because when the data reach 5000000 then cause dump segment and the exception will throw.

**Comment by kishoreg** [comment]
Can you come online on https://gitter.im/linkedin/pinot, I will provide you
the instructions to add additional logging.

**Comment by binlijin** [comment]
diff --git a/pinot-core/src/main/java/com/linkedin/pinot/core/realtime/impl/RealtimeSegmentImpl.java b/pinot-core/src/main/java/com/linkedin/pinot/core/realtime/impl/RealtimeSegmentImpl.java
index 29fcc83..3b4ee66 100644
--- a/pinot-core/src/main/java/com/linkedin/pinot/core/realtime/impl/RealtimeSegmentImpl.java
+++ b/pinot-core/src/main/java/com/linkedin/pinot/core/realtime/impl/RealtimeSegmentImpl.java
@@ -528,26 +528,26 @@ public class RealtimeSegmentImpl implements RealtimeSegment {
     for (String metric : dataSchema.getMetricNames()) {
       switch (dataSchema.getFieldSpecFor(metric).getDataType()) {
         case INT:
-          rowValues.put(metric,
-              ((FixedByteSingleColumnSingleValueReaderWriter) columnIndexReaderWriterMap.get(metric)).getInt(docId));
           break;
         case FLOAT:
-          rowValues.put(metric,
-              ((FixedByteSingleColumnSingleValueReaderWriter) columnIndexReaderWriterMap.get(metric)).getFloat(docId));
           break;
         case LONG:
-          rowValues.put(metric,
-              ((FixedByteSingleColumnSingleValueReaderWriter) columnIndexReaderWriterMap.get(metric)).getLong(docId));
           break;
         case DOUBLE:
-          rowValues.put(metric,
-              ((FixedByteSingleColumnSingleValueReaderWriter) columnIndexReaderWriterMap.get(metric)).getDouble(docId));
           break;
         default:
           throw new UnsupportedOperationException("unsopported metric data type");
       }
     }
 
+        for (String metric : dataSchema.getMetricNames()) {
+            int dicId =
+                    ((FixedByteSingleColumnSingleValueReaderWriter) columnIndexReaderWriterMap
+                            .get(metric)).getInt(docId);
+            Object rawValue = dictionaryMap.get(metric).get(dicId);
+            rowValues.put(metric, rawValue);
+        }
+
     rowValues.put(
         outgoingTimeColumnName,
         dictionaryMap.get(outgoingTimeColumnName).get(

**Comment by binlijin** [comment]
When pinot build segment, it store the dicId for metric field instead of value.
