### ISSUE TITLE
Broker responds to GET requests?

### ISSUE THREAD

**Issue by brandtg** [apache/pinot#24]
In `PinotClientRequestServlet` in the Broker, it looks like there is a handler for GET requests that's looking for a `"bql"` parameter:

``` java
  @Override
  protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
    try {
      resp.getOutputStream().print(handleRequest(new JSONObject(req.getParameter("bql"))).toJson().toString());
      resp.getOutputStream().flush();
      resp.getOutputStream().close();
    } catch (final Exception e) {
      resp.getOutputStream().print(e.getMessage());
      resp.getOutputStream().flush();
      resp.getOutputStream().close();
      LOGGER.error("Caught exception while processing GET request", e);
      brokerMetrics.addMeteredValue(null, BrokerMeter.UNCAUGHT_GET_EXCEPTIONS, 1);
    }
  }
```

Is GET part of the officially supported API? If so, should `"bql"` be `"pql"` to be consistent with the documentation?

Also, should a more efficient / robust library like Jackson be used to parse JSON here?

**Comment by fx19880617** [comment]
I think this is a backward compatible with v1 api, we should change this, but make sure internal pinot-broker MP is not broken.

**Comment by dhaval2025** [comment]
so the bql/pql across GET and POST is for backwards compatibility and will be made consistent eventually, for now documentation only mentions using the post API, also we use antlr for the actual parsing. At the servlet layer we simply, read the string entry with key pql from the payload and pass it on to the antlr compiler.

also I think from the code you pasted above, it looks like the get API is broken, the code you pasted above needs to be something like 

```
@Override
  protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
    try {
      JSONObject jsonQuery = new JSONObject();
      jsonQuery.put("pql", req.getParameter("bql"));
      resp.getOutputStream().print(handleRequest(jsonQuery));
      resp.getOutputStream().flush();
      resp.getOutputStream().close();
    } catch (final Exception e) {
      resp.getOutputStream().print(e.getMessage());
      resp.getOutputStream().flush();
      resp.getOutputStream().close();
      LOGGER.error("Caught exception while processing GET request", e);
      brokerMetrics.addMeteredValue(null, BrokerMeter.UNCAUGHT_GET_EXCEPTIONS, 1);
    }
  }
```
from above you can see why jackson would be an overkill. all we are doing here is making the same method handle both post and get calls. 

I will push this and close the issue once i do ...
Thanks
