### ISSUE TITLE
Deep Storage Support

### ISSUE THREAD

**Issue by jenniferdai** [apache/pinot#2539]
An extension of: https://github.com/linkedin/pinot/issues/2248.

# Motivation
Pinot wants to provide options for users to choose their method of storage. Much of the code assumes the use of a local mount to store segments; for example, deletion using the retention manager assumes a local filesystem. We want to abstract away the local file operations so that the code can easily be used by companies who want to store segments in HDFS or s3, for example and make the code extendable to also support other deep storage options. Currently, while Pinot does support deep storage to some extent, each option goes through a different code path. The idea is to pull out an interface for people with different storage system requirements to implement and create a uniform code path regardless of the storage option.

# Proposed Architecture
![deep storage support](https://user-images.githubusercontent.com/5035129/36082623-07a7ef58-0f60-11e8-8f51-5d6ea3891f33.png)

# New Proposed Interface
## Deep Storage
The user will store segments in an upload directory that they provide to Pinot.
```
/uploadDirectory/fabric/segment.tar.gz
		     	    /segmentUploadRequest.txt
		     	    /segment.metadata
```
To enable versioning, Pinot will copy all segments to its own data directory
`/segmentDirectory/fabric/myTableName/mySegment-v1.tar.gz
`
When replacing segments, they will need to be renamed to remove the versioning so they can be replaced properly.

## NFS
The process for this will remain the same. The entire segment will be uploaded to the controller from the user data directory. We will continue to not have versioning here as NFS is limited.
Interface for PinotFileSystem
```
// Configuration for users to include credentials and other custom configurations depending on the storage type
public PinotFileSystemConfiguration {
	Map<String, String> credentials; // so they aren’t logged
	Configuration configuration;
}
```
## Required parameters for configuration
```
pinot.storage.dataDirectory
pinot.storage.type
```

Each storage system will need to implement the following interface with file system operations.
```
public interface PinotFile {
void init(PinotFileSystemConfiguration config);
boolean delete(String uri) throws Exception;
// Allows users to store segment files in deep storage, especially for realtime use cases
boolean move(String srcUriString, String dstUriString) throws Exception;
boolean copy(String srcUriString, File dstUriString) throws Exception;
boolean exists(String uriString);
long length(String uriString);
String[] listFiles(String directoryUri);
}
```
## Pinot Library API
```
public interface PinotFileSystem {
/**
* The JVM will take care of the cleanup through java.io.File.deleteOnExit()
**/
SegmentMetadata fetchSegmentMetadataToLocal(String tableNameWithType, String segmentName, intVersion) throws Exception;

/**
This method drops the segment in an upload directory then moves/copies the segment from the upload directory to the final directory then versions it accordingly
*/
int uploadAndCommitSegment(String tableNameWithType, String segmentName);

/** Note that we will need to delete different versions of a segment when we move to deep storage. This will clean up the Pinot data directory copy, not the user data directory.
*/
boolean deleteSegment(String segmentName, String tableNameWithType);
}
```

**Comment by jenniferdai** [comment]
@jamesyfshao @fx19880617 Any thoughts?

**Comment by kishoreg** [comment]
> When replacing segments, they will need to be renamed to remove the versioning so they can be replaced properly.

who has to be renamed and who should do that? 

Can you add a diagram that describes the steps for the following scenarios
- segment upload from external clients.
- segment upload from realtime
- Download from servers (offline/realtime)

**Comment by fx19880617** [comment]
@jamesyfshao FYI.

**Comment by fx19880617** [comment]
For the storage interface, I'm actually thinking of building Pinot API on top of Hadoop [org.apache.hadoop.fs.FileSystem](org.apache.hadoop.fs) API directly,
which already provides local FS/HDFS/ViewFS/S3/Azure implementation. So we don't need to reinvent the wheel.

**Comment by kishoreg** [comment]
Agree with leveraging the FileSystem API but it's better to have a simple interface within Pinot and a default implementation that takes in a FileSystem instance. The only motivation here is to avoid the compile time dependency on Hadoop jars. I think we already do that today and we should remove that.

**Comment by fx19880617** [comment]
Agree that a clean api for deep storage might be better as we could distinguish the usage for local data ops and deep storage.

**Comment by ananthdurai** [comment]
Though implementing own FileSystem abstraction is a good idea, I would like to point to some of the genuine concern raised in Flink development and how they handle it.

https://issues.apache.org/jira/browse/FLINK-5706

**Comment by jamesyfshao** [comment]
@jenniferdai hi Jennifer we are curious about the current progress of this effort? We did a bit exploration on the latest pinot code and I see that you have already implemented the logic for localPinotFS and HadoopPinotFS. However, some of the components still seem to use native file API instead of the generic file system API. ([example](https://github.com/linkedin/pinot/blob/master/pinot-controller/src/main/java/com/linkedin/pinot/controller/api/resources/LLCSegmentCompletionHandlers.java#L292)). 

As we are currently working on integrating low level consumer to our workflow, hdfs back up is an main blocker for us. I wonder if you have any plans/existing works on changes related to that? If not, we are thinking about contributing changes related to using hdfs back up for uploaded segment.

**Comment by jenniferdai** [comment]
Hi @jamesyfshao,

I have not gotten a chance to implement realtime support for deep storage. If it is needed urgently, I would love to discuss/design a solution together if you would like. We would welcome contributions from your side!

**Comment by chenboat** [comment]
Hi @jenniferdai , this is Ting Chen from Uber. I will work on the HDFS feature with James. We are happy to contribute. I am still looking into the current progress in the codebase and will contact you with more questions. Thanks.
