### ISSUE TITLE
When the number of table more than eight, there will be no consumption of kafka

### ISSUE THREAD

**Issue by dongyanfeng** [apache/pinot#26]
More than 8 tables in the cluster number, then the next table can't consumption kafka.

```
I tested many times, discover finally create table does not generate the data properly.

Created in front of the table, respectively table1_realtime,table1_offline,
                                            table2_realtime,table2_offline,
                                            table3_realtime,table3_offline,
                                            table4_realtime,table4_offline,
                                            table5_realtime
table5_realtime cannot consumption kafka. 
```

**Comment by dhaval2025** [comment]
@dongyanfeng  can how tell us how many instances are you using for these tables...

thanks

**Comment by jfim** [comment]
If there is a limited number of servers relative to ZK nodes, it could be the case that this exhausts the limit of ZK connections from a single node. The default value for `maxClientCnxns` in ZK is 10, so if there is only one ZK host and all the cluster is running on one machine, it could prevent the kafka client from connecting to zk.
