### ISSUE TITLE
 Error: Could not find or load main class com.linkedin.pinot.tools.Quickstart

### ISSUE THREAD

**Issue by oferoh** [apache/pinot#29]
After i run this script 
git clone https://github.com/linkedin/pinot.git
cd pinot
mvn install package  -DskipTests
cd pinot-distribution/target/pinot-0.016-pkg
chmod +x bin/*.sh

bin/quick-start-offline.sh
Im getting this error Error: Could not find or load main class com.linkedin.pinot.tools.Quickstart

**Comment by kishoreg** [comment]
Hi,

Can you confirm that mvn install package -DskipTests command was
successful. Also can you list output of the following command.

cd pinot-distribution/target/pinot-0.016-pkg;
find . -name \*.jar

**Comment by oferoh** [comment]
Thank you Kishoreg for helping 
as you can the package install correctly 
![image](https://cloud.githubusercontent.com/assets/11095042/8817935/e6668c22-3042-11e5-88dd-710c143f27f0.png)

here is the output 

./lib/antlr-2.7.7.jar
./lib/antlr-3.4.jar
./lib/antlr-runtime-3.4.jar
./lib/args4j-2.32.jar
./lib/async-http-client-1.9.22.jar
./lib/avro-1.7.6.jar
./lib/commons-beanutils-1.8.3.jar
./lib/commons-beanutils-core-1.8.0.jar
./lib/commons-cli-1.2.jar
./lib/commons-codec-1.6.jar
./lib/commons-collections-3.2.1.jar
./lib/commons-compress-1.4.1.jar
./lib/commons-configuration-1.6.jar
./lib/commons-csv-1.0.jar
./lib/commons-digester-1.8.jar
./lib/commons-fileupload-1.2.2.jar
./lib/commons-httpclient-3.1.jar
./lib/commons-io-2.1.jar
./lib/commons-lang-2.6.jar
./lib/commons-lang3-3.1.jar
./lib/commons-logging-1.1.1.jar
./lib/commons-math-2.1.jar
./lib/commons-validator-1.4.0.jar
./lib/fastjson-1.1.24.jar
./lib/fastutil-6.5.9.jar
./lib/guava-11.0.2.jar
./lib/helix-core-0.6.4.jar
./lib/httpclient-4.1.3.jar
./lib/httpcore-4.2.4.jar
./lib/jackson-annotations-2.2.3.jar
./lib/jackson-core-2.2.3.jar
./lib/jackson-core-asl-1.8.8.jar
./lib/jackson-databind-2.2.3.jar
./lib/jackson-dataformat-csv-2.2.3.jar
./lib/jackson-dataformat-smile-2.2.3.jar
./lib/jackson-dataformat-xml-2.2.3.jar
./lib/jackson-dataformat-yaml-2.2.3.jar
./lib/jackson-mapper-asl-1.8.8.jar
./lib/jackson-module-jaxb-annotations-2.2.3.jar
./lib/JavaFastPFOR-0.0.13.jar
./lib/javax.servlet-3.0.0.v201112011016.jar
./lib/javax.servlet-api-3.0.1.jar
./lib/jetty-ajp-8.1.14.v20131031.jar
./lib/jetty-continuation-8.1.8.v20121106.jar
./lib/jetty-http-8.1.8.v20121106.jar
./lib/jetty-io-8.1.14.v20131031.jar
./lib/jetty-security-8.1.8.v20121106.jar
./lib/jetty-server-8.1.8.v20121106.jar
./lib/jetty-servlet-8.1.8.v20121106.jar
./lib/jetty-util-8.1.14.v20131031.jar
./lib/jetty-webapp-8.1.8.v20121106.jar
./lib/jetty-xml-8.1.8.v20121106.jar
./lib/jline-0.9.94.jar
./lib/joda-time-2.0.jar
./lib/jopt-simple-3.2.jar
./lib/json-20080701.jar
./lib/jsr305-1.3.9.jar
./lib/kafka-clients-0.8.2.0.jar
./lib/kafka_2.10-0.8.2.0.jar
./lib/libthrift-0.9.1.jar
./lib/log4j-1.2.17.jar
./lib/lz4-1.2.0.jar
./lib/metrics-core-2.2.0.jar
./lib/netty-3.10.3.Final.jar
./lib/netty-all-4.0.27.Final.jar
./lib/org.restlet-2.2.1.jar
./lib/org.restlet.ext.fileupload-2.2.1.jar
./lib/org.restlet.ext.jackson-2.2.1.jar
./lib/org.restlet.ext.jetty-2.2.1.jar
./lib/paranamer-2.3.jar
./lib/pinot-api-0.016.jar
./lib/pinot-broker-0.016.jar
./lib/pinot-common-0.016.jar
./lib/pinot-controller-0.016.jar
./lib/pinot-core-0.016.jar
./lib/pinot-hadoop-0.016.jar
./lib/pinot-perf-0.016.jar
./lib/pinot-server-0.016.jar
./lib/pinot-tools-0.016.jar
./lib/pinot-transport-0.016.jar
./lib/RoaringBitmap-0.4.9.jar
./lib/scala-library-2.10.4.jar
./lib/slf4j-api-1.7.7.jar
./lib/slf4j-log4j12-1.7.7.jar
./lib/snakeyaml-1.12.jar
./lib/snappy-java-1.0.5.jar
./lib/ST4-4.0.4.jar
./lib/stax-api-1.0-2.jar
./lib/stax2-api-3.1.3.jar
./lib/stringtemplate-3.2.1.jar
./lib/swagger-ui-2.1.8-M1.jar
./lib/tyrus-standalone-client-1.5.jar
./lib/woodstox-core-asl-4.2.0.jar
./lib/xz-1.0.jar
./lib/zkclient-0.1.jar
./lib/zkclient-0.3.jar
./lib/zookeeper-3.3.4.jar
./repo/antlr/antlr/2.7.7/antlr-2.7.7.jar
./repo/args4j/args4j/2.32/args4j-2.32.jar
./repo/com/101tec/zkclient/0.3/zkclient-0.3.jar
./repo/com/alibaba/fastjson/1.1.24/fastjson-1.1.24.jar
./repo/com/fasterxml/jackson/core/jackson-annotations/2.2.3/jackson-annotations-2.2.3.jar
./repo/com/fasterxml/jackson/core/jackson-core/2.2.3/jackson-core-2.2.3.jar
./repo/com/fasterxml/jackson/core/jackson-databind/2.2.3/jackson-databind-2.2.3.jar
./repo/com/fasterxml/jackson/dataformat/jackson-dataformat-csv/2.2.3/jackson-dataformat-csv-2.2.3.jar
./repo/com/fasterxml/jackson/dataformat/jackson-dataformat-smile/2.2.3/jackson-dataformat-smile-2.2.3.jar
./repo/com/fasterxml/jackson/dataformat/jackson-dataformat-xml/2.2.3/jackson-dataformat-xml-2.2.3.jar
./repo/com/fasterxml/jackson/dataformat/jackson-dataformat-yaml/2.2.3/jackson-dataformat-yaml-2.2.3.jar
./repo/com/fasterxml/jackson/module/jackson-module-jaxb-annotations/2.2.3/jackson-module-jaxb-annotations-2.2.3.jar
./repo/com/github/sgroschupf/zkclient/0.1/zkclient-0.1.jar
./repo/com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9.jar
./repo/com/google/guava/guava/11.0.2/guava-11.0.2.jar
./repo/com/linkedin/pinot/pinot-broker/0.016/pinot-broker-0.016.jar
./repo/com/linkedin/pinot/pinot-common/0.016/pinot-common-0.016.jar
./repo/com/linkedin/pinot/pinot-controller/0.016/pinot-controller-0.016.jar
./repo/com/linkedin/pinot/pinot-core/0.016/pinot-core-0.016.jar
./repo/com/linkedin/pinot/pinot-server/0.016/pinot-server-0.016.jar
./repo/com/linkedin/pinot/pinot-tools/0.016/pinot-tools-0.016.jar
./repo/com/linkedin/pinot/pinot-transport/0.016/pinot-transport-0.016.jar
./repo/com/thoughtworks/paranamer/paranamer/2.3/paranamer-2.3.jar
./repo/com/yammer/metrics/metrics-core/2.2.0/metrics-core-2.2.0.jar
./repo/commons-beanutils/commons-beanutils/1.8.3/commons-beanutils-1.8.3.jar
./repo/commons-beanutils/commons-beanutils-core/1.8.0/commons-beanutils-core-1.8.0.jar
./repo/commons-cli/commons-cli/1.2/commons-cli-1.2.jar
./repo/commons-codec/commons-codec/1.6/commons-codec-1.6.jar
./repo/commons-collections/commons-collections/3.2.1/commons-collections-3.2.1.jar
./repo/commons-configuration/commons-configuration/1.6/commons-configuration-1.6.jar
./repo/commons-digester/commons-digester/1.8/commons-digester-1.8.jar
./repo/commons-fileupload/commons-fileupload/1.2.2/commons-fileupload-1.2.2.jar
./repo/commons-httpclient/commons-httpclient/3.1/commons-httpclient-3.1.jar
./repo/commons-io/commons-io/2.1/commons-io-2.1.jar
./repo/commons-lang/commons-lang/2.6/commons-lang-2.6.jar
./repo/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar
./repo/commons-validator/commons-validator/1.4.0/commons-validator-1.4.0.jar
./repo/io/netty/netty-all/4.0.27.Final/netty-all-4.0.27.Final.jar
./repo/it/unimi/dsi/fastutil/6.5.9/fastutil-6.5.9.jar
./repo/javax/servlet/javax.servlet-api/3.0.1/javax.servlet-api-3.0.1.jar
./repo/javax/xml/stream/stax-api/1.0-2/stax-api-1.0-2.jar
./repo/jline/jline/0.9.94/jline-0.9.94.jar
./repo/joda-time/joda-time/2.0/joda-time-2.0.jar
./repo/log4j/log4j/1.2.17/log4j-1.2.17.jar
./repo/me/lemire/integercompression/JavaFastPFOR/0.0.13/JavaFastPFOR-0.0.13.jar
./repo/net/jpountz/lz4/lz4/1.2.0/lz4-1.2.0.jar
./repo/net/sf/jopt-simple/jopt-simple/3.2/jopt-simple-3.2.jar
./repo/org/antlr/antlr/3.4/antlr-3.4.jar
./repo/org/antlr/antlr-runtime/3.4/antlr-runtime-3.4.jar
./repo/org/antlr/ST4/4.0.4/ST4-4.0.4.jar
./repo/org/antlr/stringtemplate/3.2.1/stringtemplate-3.2.1.jar
./repo/org/apache/avro/avro/1.7.6/avro-1.7.6.jar
./repo/org/apache/commons/commons-compress/1.4.1/commons-compress-1.4.1.jar
./repo/org/apache/commons/commons-csv/1.0/commons-csv-1.0.jar
./repo/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.jar
./repo/org/apache/commons/commons-math/2.1/commons-math-2.1.jar
./repo/org/apache/helix/helix-core/0.6.4/helix-core-0.6.4.jar
./repo/org/apache/httpcomponents/httpclient/4.1.3/httpclient-4.1.3.jar
./repo/org/apache/httpcomponents/httpcore/4.2.4/httpcore-4.2.4.jar
./repo/org/apache/kafka/kafka-clients/0.8.2.0/kafka-clients-0.8.2.0.jar
./repo/org/apache/kafka/kafka_2.10/0.8.2.0/kafka_2.10-0.8.2.0.jar
./repo/org/apache/thrift/libthrift/0.9.1/libthrift-0.9.1.jar
./repo/org/apache/zookeeper/zookeeper/3.3.4/zookeeper-3.3.4.jar
./repo/org/codehaus/jackson/jackson-core-asl/1.8.8/jackson-core-asl-1.8.8.jar
./repo/org/codehaus/jackson/jackson-mapper-asl/1.8.8/jackson-mapper-asl-1.8.8.jar
./repo/org/codehaus/woodstox/stax2-api/3.1.3/stax2-api-3.1.3.jar
./repo/org/codehaus/woodstox/woodstox-core-asl/4.2.0/woodstox-core-asl-4.2.0.jar
./repo/org/eclipse/jetty/jetty-ajp/8.1.14.v20131031/jetty-ajp-8.1.14.v20131031.jar
./repo/org/eclipse/jetty/jetty-continuation/8.1.14.v20131031/jetty-continuation-8.1.14.v20131031.jar
./repo/org/eclipse/jetty/jetty-http/8.1.14.v20131031/jetty-http-8.1.14.v20131031.jar
./repo/org/eclipse/jetty/jetty-io/8.1.14.v20131031/jetty-io-8.1.14.v20131031.jar
./repo/org/eclipse/jetty/jetty-security/8.1.8.v20121106/jetty-security-8.1.8.v20121106.jar
./repo/org/eclipse/jetty/jetty-server/8.1.8.v20121106/jetty-server-8.1.8.v20121106.jar
./repo/org/eclipse/jetty/jetty-servlet/8.1.8.v20121106/jetty-servlet-8.1.8.v20121106.jar
./repo/org/eclipse/jetty/jetty-util/8.1.14.v20131031/jetty-util-8.1.14.v20131031.jar
./repo/org/eclipse/jetty/jetty-webapp/8.1.8.v20121106/jetty-webapp-8.1.8.v20121106.jar
./repo/org/eclipse/jetty/jetty-xml/8.1.8.v20121106/jetty-xml-8.1.8.v20121106.jar
./repo/org/eclipse/jetty/orbit/javax.servlet/3.0.0.v201112011016/javax.servlet-3.0.0.v201112011016.jar
./repo/org/glassfish/tyrus/bundles/tyrus-standalone-client/1.5/tyrus-standalone-client-1.5.jar
./repo/org/json/json/20080701/json-20080701.jar
./repo/org/restlet/jee/org.restlet/2.2.1/org.restlet-2.2.1.jar
./repo/org/restlet/jee/org.restlet.ext.fileupload/2.2.1/org.restlet.ext.fileupload-2.2.1.jar
./repo/org/restlet/jee/org.restlet.ext.jackson/2.2.1/org.restlet.ext.jackson-2.2.1.jar
./repo/org/restlet/jse/org.restlet/2.2.1/org.restlet-2.2.1.jar
./repo/org/restlet/jse/org.restlet.ext.jetty/2.2.1/org.restlet.ext.jetty-2.2.1.jar
./repo/org/roaringbitmap/RoaringBitmap/0.4.9/RoaringBitmap-0.4.9.jar
./repo/org/scala-lang/scala-library/2.10.4/scala-library-2.10.4.jar
./repo/org/slf4j/slf4j-api/1.7.7/slf4j-api-1.7.7.jar
./repo/org/slf4j/slf4j-log4j12/1.7.7/slf4j-log4j12-1.7.7.jar
./repo/org/tukaani/xz/1.0/xz-1.0.jar
./repo/org/webjars/swagger-ui/2.1.8-M1/swagger-ui-2.1.8-M1.jar
./repo/org/xerial/snappy/snappy-java/1.0.5/snappy-java-1.0.5.jar
./repo/org/yaml/snakeyaml/1.6/snakeyaml-1.6.jar

**Comment by kishoreg** [comment]
That looks correct. Is this on Windows and you are using cygwin by any
chance?

Also try running sh -x bin/quick-start-offline.sh, that might give me more
information on how the classpath is set up

thanks,
Kishore G

**Comment by oferoh** [comment]
Dear Kishore

Yes im using windows with gitbash to run the command can you suggest otherwise

I tried to run the command the you give me with this tool http://sourceforge.net/projects/unxutils/
and i did get this output 
![image](https://cloud.githubusercontent.com/assets/11095042/8819266/6773fb1e-3053-11e5-8517-fdee4e21421d.png)

**Comment by kishoreg** [comment]
Can you IM us at https://gitter.im/linkedin/pinot

**Comment by oferoh** [comment]
I installed the cygwin consol look like working very well,

**Comment by oferoh** [comment]
Thank you very much

**Comment by kishoreg** [comment]
Perfect.

**Comment by Neel-rishabhsoft** [comment]
@kishoreg @oferoh I followed the steps mentioned. 
And i ran the "sh quic-start-batch.sh" on Cygwin prompt.
I am getting the following errors:
quick-start-batch.sh: line 20: $'\r': command not found
quick-start-batch.sh: line 21: syntax error near unexpected token `$'{\r''
'uick-start-batch.sh: line 21: `jdk_version() {


Can you please provide your insights on this?

**Comment by Neel-rishabhsoft** [comment]
@oferoh @kishoreg I followed the steps mentioned above.
I am getting following warnings and errors while running the 
"sh quick-start-batch.sh"
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
WARNING: An illegal reflective access operation has occurred
..etc

And errors:

***** Starting Zookeeper, controller, broker and server *****
Executing command: StartZookeeper -zkPort 2123 -dataDir C:\cygwin64\tmp\\PinotAd
min/zkData
Start zookeeper at localhost:2123 in thread main
Executing command: StartController -clusterName QuickStartCluster -controllerHos
t 192.168.42.144 -controllerPort 9000 -dataDir C:\cygwin64\tmp\\PinotController
-zkAddress localhost:2123
Caught exception while starting controller, exiting.
java.lang.RuntimeException: Caught exception while initializing ControllerFilePa
thProvider
        at org.apache.pinot.controller.ControllerStarter.initControllerFilePathP
rovider(ControllerStarter.java:433) ~[pinot-all-0.4.0-SNAPSHOT-jar-with-dependen
cies.jar:0.4.0-SNAPSHOT-6f384eaae973978c66f4032e02659d5a5947ebc4]
.
.
Caused by: java.net.URISyntaxException: Illegal character in opaque part at inde
x 2: C:\cygwin64\tmp\\PinotController
        at java.net.URI$Parser.fail(URI.java:2936) ~[?:?]
        at java.net.URI$Parser.checkChars(URI.java:3107) ~[?:?]
        at java.net.URI$Parser.parse(URI.java:3143) ~[?:?]
        at java.net.URI.<init>(URI.java:623) ~[?:?]
        at org.apache.pinot.common.utils.URIUtils.getUri(URIUtils.java:40) ~[pin
ot-all-0.4.0-SNAPSHOT-jar-with-dependencies.jar:0.4.0-SNAPSHOT-6f384eaae973978c6
6f4032e02659d5a5947ebc4]
        at org.apache.pinot.controller.api.resources.ControllerFilePathProvider.
<init>(ControllerFilePathProvider.java:67) ~[pinot-all-0.4.0-SNAPSHOT-jar-with-d
ependencies.jar:0.4.0-SNAPSHOT-6f384eaae973978c66f4032e02659d5a5947ebc4]
        at org.apache.pinot.controller.api.resources.ControllerFilePathProvider.
init(ControllerFilePathProvider.java:49) ~[pinot-all-0.4.0-SNAPSHOT-jar-with-dep
endencies.jar:0.4.0-SNAPSHOT-6f384eaae973978c66f4032e02659d5a5947ebc4]
        at org.apache.pinot.controller.ControllerStarter.initControllerFilePathP
rovider(ControllerStarter.java:431) ~[pinot-all-0.4.0-SNAPSHOT-jar-with-dependen
cies.jar:0.4.0-SNAPSHOT-6f384eaae973978c66f4032e02659d5a5947ebc4]
        ... 7 more

Can you please provide your insights on this?
