### ISSUE TITLE
Request to support aliases in PQL.

### ISSUE THREAD

**Issue by mayankshriv** [apache/pinot#3471]
Currently PQL does not support aliasing for selection/aggregation column names. For example in the query below:
```sql
select sum(metric) from table where ... group by ...
```
The returned aggregated column is named as `sum_metric`.
It would be great if PQL can support aliasing, so that the above query can be written as follows, so that the aggregation column can now be referred as `aggregate` or any other user specified choice.

```sql
select sum(metric) as aggregate from table where... group by ...
```

**Comment by agrawaldevesh** [comment]
I am wondering if there is an update on this ? I could use it too. I think it is a more broader change but looks fairly straight forward.

**Comment by kishoreg** [comment]
It is straight forward for simple scenarios. Is this a blocker or nice to
have?

**Comment by agrawaldevesh** [comment]
My queries are relatively simple for now, so I have hacked my way away around it in the client. But schema inference is proving to be more involved ([issue 2302](https://github.com/apache/incubator-pinot/issues/2302)) and so I would rather get that done. So to answer your question, this is a nice to have for me presently.

**Comment by Jackie-Jiang** [comment]
This is supported in SQL (PQL is deprecated)
