### ISSUE TITLE
Why PQLCompiler can't be compiled because of two missing classes?

### ISSUE THREAD

**Issue by sxpujs** [apache/pinot#35]
When I downloaded the latest pinot code,  two classes are missing, could you please solve the problem?

```
import com.linkedin.pinot.pql.parsers.PQLLexer;
import com.linkedin.pinot.pql.parsers.PQLParser;

public class PQLCompiler extends AbstractCompiler {
```

**Comment by kishoreg** [comment]
These class are auto generated. Did you run mvn install -DskipTests?

thanks,
Kishore G

**Comment by sxpujs** [comment]
Thank you very much, it is already solved.:)
