### ISSUE TITLE
Pinot compilation errors with Java 11

### ISSUE THREAD

**Issue by mcvsubbu** [apache/pinot#3625]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.5.1:compile (default-compile) on project pinot-core: Compilation failure: Compilation failure:
[ERROR] /Users/kishoreg/projects/incubator-pinot/pinot-core/src/main/java/com/linkedin/pinot/core/segment/memory/PinotByteBuffer.java:[27,17] DirectBuffer is internal proprietary API and may be removed in a future release
[ERROR] /Users/kishoreg/projects/incubator-pinot/pinot-core/src/main/java/com/linkedin/pinot/core/segment/memory/PinotByteBuffer.java:[26,15] error: cannot find symbol
[ERROR]   symbol:   class Cleaner
[ERROR]   location: package sun.misc
[ERROR] /Users/kishoreg/projects/incubator-pinot/pinot-core/src/main/java/com/linkedin/pinot/core/segment/memory/PinotByteBuffer.java:[27,17] DirectBuffer is internal proprietary API and may be removed in a future release

**Comment by rustkas** [comment]
How to fix it?

**Comment by vivekjj** [comment]
How was this fixed? I get the exact same error.

**Comment by kishoreg** [comment]
@vivekjj Pinot is not tested with jdk 11. Please use JDK 9 for building and running Pinot.

**Comment by vivekjj** [comment]
Thanks!

**Comment by lsabi** [comment]
@kishoreg is there any plan/roadmap to support newer versions of java?

Also, the only mention that I could find on the docs about the supported java version(s) is in the getting started tutorial, see [https://pinot.readthedocs.io/en/latest/getting_started.html](https://pinot.readthedocs.io/en/latest/getting_started.html).

**Though it only says that is requires java 8 or later.** As a new user I was compiling with java 11 and getting errors. Only by trying out with java 8 I managed to run pinot. It would be better to explicitly write the supported java versions in order for new users to go through the tutorial smoothly.

Thanks.

**Comment by fx19880617** [comment]
I've fixed all the compilation error with java 11 I got and also added QuickStart tests to build Pinot with both JDK 8 and 11 for Travis.

Example: https://travis-ci.org/apache/incubator-pinot/builds/650497203
