### ISSUE TITLE
A  big problem about inverted index creation

### ISSUE THREAD

**Issue by flyyoung** [apache/pinot#38]
SegmentColumnarIndexCreator.java

if (config.createInvertedIndexEnabled()) {
        invertedIndexCreatorMap.put(
            column,
            new BitmapInvertedIndexCreator(file, indexCreationInfo.getSortedUniqueElementsArray().length, schema
                .getFieldSpecFor(column)));
      }

config.createInvertedIndexEnabled() method which comes from SegmentGeneratorConfig.java will decide inverted index creation.
It has a problem because we need depend on table config info(invertedIndexColumns) to decide that a column should create inverted index or not.
And config.setCreateInvertedIndex method don't call in the code.So config.createInvertedIndexEnabled() always be false.Table config info(invertedIndexColumns) can't take effect.

Table Config 
{
  "tableIndexConfig": {
    "invertedIndexColumns":["numberOfGamesAsBatter"],
    "loadMode":"HEAP",
    "lazyLoad":"false"
   },
   "tenants":{"server":"","broker":""},
   "tableType":"OFFLINE","metadata":{"customConfigs":{"d2Name":"xlntBetaPinot"}},
   "segmentsConfig":{
     "retentionTimeUnit":"DAYS",
     "segmentPushFrequency":"daily",
     "replication":1,
     "timeColumnName":"",
     "retentionTimeValue":"700",
     "timeType":"",
     "segmentPushType":"APPEND",
     "schemaName":"baseball",
     "segmentAssignmentStrategy":"BalanceNumSegmentAssignmentStrategy"
   },
   "tableName":"baseballStats"
}

**Comment by dongyanfeng** [comment]
config.createInvertedIndexEnabled() 。
createInvertedIndexEnabled is not set;

**Comment by dongyanfeng** [comment]
createInvertedIndexEnabled  is always false.
so Inverted index file can't produce.

**Comment by dhaval2025** [comment]
hey @dongyanfeng  we fixed this, now during segment generation you can pick columns that you want to create inverted index on. 
Also if inverted index is not created during segment generation and there are columns configured to have inverted indexes, then inverted index will be created over the fly when we load the segment on the server.

**Comment by izzizz** [comment]
Tried, and it works for offline table. But looks like it doesn't work for real time table, whatever the index segments are in memory or are flushed to disk.
