### ISSUE TITLE
SegmentOnlineOfflineStateModelFactory.class ,method:onBecomeOfflineFromOnline has a bug

### ISSUE THREAD

**Issue by dongyanfeng** [apache/pinot#39]
SegmentOnlineOfflineStateModelFactory.class ,method:onBecomeOfflineFromOnline has a bug.
line 279 : INSTANCE_DATA_MANAGER.removeSegment(segmentId);
in IndexSegmentImpl.class.
line 116: indexContainerMap.get(column).getInvertedIndex().close();  
throws NullPointException.
 indexContainerMap.get(column) return value is null.

**Comment by kishoreg** [comment]
Thanks. If you don't mind, can you submit a patch.
