### ISSUE TITLE
Quck Demo doesn't work with jdk1.9

### ISSUE THREAD

**Issue by lhong375** [apache/pinot#3929]
following the readme of this repo. 

> Run Quck Demo
> $ cd pinot-distribution/target/apache-pinot-incubating-<version>-SNAPSHOT-bin
> $ bin/quick-start-offline.sh

it throw errors and http://localhost:9000/query/ give me 404

after debugging with @kishoreg it turn out to be a jdk version issue around HK2 jar.
see more at : https://github.com/spotify/dockerfile-maven/issues/90

**Comment by xiangfu0** [comment]
close as not valid.
