### ISSUE TITLE
Can't upload any segments after loading about 10000 segment parts

### ISSUE THREAD

**Issue by jzmq** [apache/pinot#41]
After loading 9000 segments , we couldn't upload any segments successfully and pinot didn't log any useful information . We looked into and found , there were two places we should fix .
First: zookeeper doesn't support znode size bigger than 1M without adding parameter jute.maxbuffer to system environment 
Second : Helix cut down zookeeper message to 1M at ZNRecordStreamingSerializer.java line:168 

After we fixing above two places , we can load more segments now.

```
cZxid = 0x20002aec3
ctime = Fri Aug 21 14:01:46 CST 2015
mZxid = 0x2000a17a2
mtime = Sun Aug 23 21:20:26 CST 2015
pZxid = 0x20002aec3
cversion = 0
dataVersion = 2024
aclVersion = 0
ephemeralOwner = 0x0
dataLength = 1171020
numChildren = 0
```

Hope make myself clearly!
Thanks to my buddies @iamcrzay @code4love

**Comment by jfim** [comment]
There is indeed a maximum znode size. Helix supports having compressed znodes, which should help you with this. See https://issues.apache.org/jira/browse/HELIX-573

If you have that many segments, it might be worth looking into having the segments larger.
