### ISSUE TITLE
Alternative HyperLogLog implementation with higher accuracy

### ISSUE THREAD

**Issue by Jackie-Jiang** [apache/pinot#4248]
Current HyperLogLog implementation is fairly old: https://github.com/addthis/stream-lib/blob/master/src/main/java/com/clearspring/analytics/stream/cardinality/HyperLogLog.java

There are several alternative implementations that can potentially reduce memory cost and improve accuracy.
https://github.com/axiomhq/hyperloglog
https://github.com/clarkduvall/hyperloglog

**Comment by fx19880617** [comment]
@jamesyfshao just fyi, I think mobile analytics is using fasthll right now

**Comment by Jackie-Jiang** [comment]
@jamesyfshao If you are using FASTHLL, please check out the documentation change in #4251 as we are moving away from FASTHLL to DISCTINCTCOUNTHLL.

**Comment by fx19880617** [comment]
Could you elaborate more on the performance and do you do the performance testing?

Below is how we use fasthll:
For fasthll, there is a pre-aggregation phase before data ingestion, e.g. we have a job publish all the dimension combinations and it's corresponding unique counting FASTHLL object every 5mins and offline job is daily basis.  This leads to data volume reduction to only 10% of the original size.

From both storage and computation perspective, fasthll is more efficient IMO.

**Comment by Jackie-Jiang** [comment]
@fx19880617 FASTHLL takes String type of serialized HyperLogLog objects, while DISTINCTCOUNTHLL can take BYTES (byte array) type of serialized HyperLogLog objects, which is more efficient in both storage and deserialization. The BYTES support for DISTINCTCOUNTHLL is new added after Pinot supporting BYTES data type.

**Comment by fx19880617** [comment]
Got it. @jamesyfshao ^^

**Comment by fx19880617** [comment]
also cc @icefury71 ^^

**Comment by extesy** [comment]
https://github.com/prasanthj/hyperloglog is a java version (already in maven) which can be easily integrated.

**Comment by extesy** [comment]
@Jackie-Jiang @fx19880617 Any follow-up?

**Comment by extesy** [comment]
@Jackie-Jiang @fx19880617 @jamesyfshao any follow-up?

**Comment by Jackie-Jiang** [comment]
After some research, will try out the DataSketches (https://datasketches.github.io) library and evaluate its performance.

**Comment by leerho** [comment]
@Jackie-Jiang 
We haven't evaluated all of the above HLL variants, but we have a detailed comparison of the DataSketches HllSketch vs the Clearspring HLL++ implementation on our website:

[https://datasketches.github.io/docs/HLL/Hll_vs_Hllpp.html](https://datasketches.github.io/docs/HLL/Hll_vs_Hllpp.html) 

There is also a detailed discussion about measuring sketch performance in general that might be helpful.  

Note that the above links are to our old website, which has not yet migrated to Apache yet.  The links will soon change to [datasketches.apache.org](https://datasketches.apache.org).

**Comment by deemoliu** [comment]
Hi @Jackie-Jiang 

currently pinot is using https://github.com/addthis/stream-lib/blob/master/src/main/java/com/clearspring/analytics/stream/cardinality/HyperLogLog.java

we have some customers observed that HLL++ has higher accuracy than HLL when cardinality of dimension is at 10k-100k.

is there a plan to support hll++ in Pinot distinctHLLL (or other functions)? https://github.com/addthis/stream-lib/blob/master/src/main/java/com/clearspring/analytics/stream/cardinality/HyperLogLogPlus.java

**Comment by deemoliu** [comment]
linked a Draft PR: https://github.com/apache/pinot/pull/11346
