### ISSUE TITLE
Simplify Pinot data ingestion

### ISSUE THREAD

**Issue by kishoreg** [apache/pinot#4731]
Getting data into Pinot is non-trivial. Most users end up writing a custom hadoop/spark job for data ingestion. There is no standard way to write these jobs. The goal of this issue is to come up with a design that makes it easy to ingest data into Pinot.

Before getting to the solution, let's look at all the variables
1. **Formats**: JSON, CSV, AVRO, Parquet, Thrift, Protobuf, ORC
2. **Batch Datasources**: HDFS, S3, ADLS, GCS
3. **Streaming Datasources**: Stream: Kafka, EventHub
4. **Execution Frameworks**: Hadoop, Spark, Flink, Samza, etc

As of now, we have RecordReader interface to ingest batch data.
```  
  GenericRow next(GenericRow reuse)     throws IOException;
```

And the real-time uses a ```StreamMessageDecoder```  interface.
```
  GenericRow decode(T payload, GenericRow reuse);
```
The RecordReader implementations are spread all over pinot-core code which brings in lot of external dependencies. We have moved pinot-parquet and pinot-orc to separate packages.

For real-time, we need one implementation per datasource, dataFormat. e.g. KafkaAvroMessageDecoder.

Any thoughts on how to standardize Data Ingestion in Pinot?

**Comment by kishoreg** [comment]
One suggestion is to first refactor Pinot modules to something like this
Pinot-batch-reader (Implements RecordReader)
- parquet
- csv
- json
- avro
- thrift

Pinot-stream-decoders (StreamMessageDecoder)
- json
- avro
- protobuf
- Thrift

Pinot-connectors (For real-time StreamConsumerFactory etc) (PinotFS for batch)
- Kafka
- Hdfs
- S3
- ADLS
- GCS

Pinot-ingestion-job (no interface here) 
- Hadoop
- Spark
- Flink
- Samza

**Comment by mayankshriv** [comment]
Great idea, and also agree with the initial refactoring.

**Comment by mcvsubbu** [comment]
+1

Perhaps we can split PinotFS and Realtime ingestion connectors.

**Comment by kishoreg** [comment]
More detailed proposal. https://docs.google.com/document/d/1160Wz-694-SDuFEKrZ2rW_iIswcTqk4hJ3k-BNp0BaI/edit?usp=sharing
