### ISSUE TITLE
Grouping data by time interval

### ISSUE THREAD

**Issue by jpbetz** [apache/pinot#48]
I've been working on adding Pinot as a datasource to Grafana, a visualization tool for time series charts.

I'm looking for the the best way to query Pinot.

In InfluxDB's query language, grouping results into time buckets is usually done like:

```
SELECT MEAN(value) FROM measure WHERE time > (now() - 1h) GROUP BY time(5m)
```

Where the result set would look something like

```
{
  "columns": ["value", "time"],
  "results": [
    [40,1441756680100],
    [45,1441756680200],
    [43,1441756680300],
    ...
  ]
}
```

And can easily be plotted.

Does Pinot support this sort of query?  I've been trying a few group by queries but have been unable to formulate one that provides this sort of grouped response.  If this is not yet supported, would it be possible to add support?

**Comment by kishoreg** [comment]
Hi Joe,

I dont think Pinot supports that inbuilt udf. But it should be easy to add
those. Let me check if our new antlr grammar can support such syntax. Is
that the only way Graphana can query data sources?

**Comment by jpbetz** [comment]
When writing a Grafana datasource, we can send any query that would produce a suitable result set. What we fundamentally need is a way to get results that are grouped by regular time intervals such that they can be plotted as a time series chart.

For some data we could want to average the grouped data points, for others we would want to sum, and for others we would want to calculate percentiles.

**Comment by jfim** [comment]
We don't support it right now, but we can add support for it. Would something like `select timebucket(timeColumn, '5m') as time, avg(metric) from ... group by time` work?

I'll take a look at Grafana to see how we can support your use cases in Pinot. Are all the types of queries that you foresee all aggregations on time buckets or would you need other special operators/functions (eg. moving averages, etc.)?

**Comment by jpbetz** [comment]
Hi @jfim,

Yes, that looks reasonable. I'm not aware of any current needs for moving averages.

For Grafana, we need essentially need is a query that we can use to implement:

```
query(table, aggregations, from, to, interval);
```

So following your PQL example, that might be something like:
```
SELECT timebucket(timestamp, '5m') as time avg(metric) FROM table WHERE timestamp BETWEEN x AND y GROUP BY time
```

The reason I mention this is because `1h` time buckets might be for intervals that are not hour aligned, e.g. `[1:36-2:36)`, `[2:36-3:36)`, ... Not just for `[1:00-2:00)`, `[2:00-3:00)`.

Grafana supports auto-refresh of time series charts in the UI.  It does this by automatically making additional queries to the datasource. E.g.:

```
SELECT ... WHERE timestamp BETWEEN fromTime AND toTime ... # Initial query 
SELECT ... WHERE timestamp BETWEEN toTime AND refreshTime1 ... # auto-refresh 1
SELECT ... WHERE timestamp BETWEEN refreshTime1 AND refreshTime2 ... # auto-refresh 2
...
```

And Grafana assumes that these queries will not overlap. I believe Grafana also makes sure the time intervals it asks for are sized and aligned in a reasonable way.  Eg. It might ask for 5m intervals for the initial query and then for 30s intervals after that.

**Comment by jpbetz** [comment]
If you're curious.  Here's a (not yet working) Grafana pinot datasource:

https://github.com/coursera/grafana/tree/pinot-datasource/public/app/plugins/datasource/pinot

It's based on the InfluxDB datasource.  The main thing it's missing is the query we've been discussing.  Once supported, I would simply modify this:

https://github.com/coursera/grafana/blob/pinot-datasource/public/app/plugins/datasource/pinot/queryBuilder.js#L60

And we'd have basic Grafana support.

**Comment by jfim** [comment]
We could probably have a third optional parameter for time bucketing that chooses the reference start point for the buckets.

I'll have to come up with a good design for this. Out of curiosity, how does Grafana handle standard/daylight savings time or irregular time intervals (months with various lengths/bissextile years)?

**Comment by jpbetz** [comment]
@jfim I've only played around with Grafana for about a day.  Here's what I was able to find:

In most of the dropdowns they only support second, minute, hour and day. But it does look like they have support for month and year: http://docs.grafana.org/reference/timerange/ . I couldn't find any details on how exactly those work.

I'm planning to provide timeseries to Grafana in UTC (avoiding daylight savings confusion).  It looks like Grafana has at least basic support for taking UTC data and rendering graphs in the viewers locale.  But that feature does seem to have caused issues in the past (https://github.com/grafana/grafana/issues/143, https://github.com/grafana/grafana/issues/277, https://github.com/grafana/grafana/issues/13).  Regardless, UTC is the way to go.

For missing data,  Grafana still expects a data point for each time interval requests, but the data value can be "null" (in JSON) in which case Grafana supports a couple options: "connected", "null", and "null as zero".  I believe "connected" means to linear interpolate between the last point before the gap to the first point after the gap (not sure what happens if the gap is at the start or end).  And I believe "null" just means leave the gap in the rendered UI.  The default it "connected".

**Comment by archmind** [comment]
Any update on this feature?

**Comment by kishoreg** [comment]
https://github.com/linkedin/pinot/pull/899

https://github.com/linkedin/pinot/pull/648

Both are pending review. Once these two PR's get in, there is very little
work needed to support UDF's

**Comment by archmind** [comment]
Sounds great! Looking forward to it.

**Comment by cwensel** [comment]
Would be great to know if this issue was satisfied by the above PRs. Digging through the comments it doesn't look like the proposed plugin was ever contributed upstream (or completed).

**Comment by provenvelocity** [comment]
@jpbetz did you ever get a DC for pinot up and working?

**Comment by kishoreg** [comment]
@provenvelocity The udf's needed are supported in Pinot but I don't think the plugin for Grafana was contributed.

**Comment by rmatharu** [comment]
Is there a way. to get the Pinot Grafana plugin code or get it to work?

**Comment by Jackie-Jiang** [comment]
This is supported now

**Comment by Jackie-Jiang** [comment]
@synoxbm You may use `date_trunc(HOUR, col)` to truncate the time into hours and grouping on it

**Comment by synoxbm** [comment]
[Jackie-Jiang](https://github.com/Jackie-Jiang) thanks ;)
