### ISSUE TITLE
Supporting complex aggregation functions

### ISSUE THREAD

**Issue by mayankshriv** [apache/pinot#5261]
Today, almost all aggregation functions take a single argument (except Distinct). We need to be able to support more complex aggregation functions such as:

1. Aggregation functions with multiple arguments, for example:
   `ThetaSketch(expr1, expr2..., exprN): where exprN is the final set operation to evaluate, and expr1 through exprN-1 are terms in exprN` (more on this separately).

2. Composite aggregation functions such as:
    `sum(colA) + sum(colB)`

This requires us to rethink the AggregationFunction interface that is generic enough to support all such requirements.

**Comment by kishoreg** [comment]
This is amazing, requirements for the AggregationFunction interface
- ability to take multiple arguments
- The arguments can be a column, literal or Function (transform/aggregation)
- Default Name of the output column
- Annotations for static properties of the FunctionImpl e.g. Name (will help keep the interface simple)

**Comment by kishoreg** [comment]
- The ability for users to plugin the aggregation functions. We have a switch case today based on the name, this should go away.
