### ISSUE TITLE
Transformations using columns which themselves are a result of transformation

### ISSUE THREAD

**Issue by npawar** [apache/pinot#5351]
In https://github.com/apache/incubator-pinot/pull/5238 we added transform functions feature. 
This issue has the design doc: https://github.com/apache/incubator-pinot/issues/5135. 
This is one of the follow ups.

In the transform functions support so far, we have 1 limitation.
If `destColumn = f(sourceColumn)`, then, destColumn cannot be used as an input to another transform function in the same schema.
Example: 
source columns: `foodExpenses`=[100, 500, 200], `totalExpense`=4000 
destination columns: `totalFoodExpense = sumOfAll(foodExpenses)`
So `totalFoodExpense` cannot be used as input to another transformFunction.

This is the behavior that we want to change.

Now we want to add support for using `totalFoodExpense` as input to another transform function
source columns: `foodExpenses`=[100, 500, 200], `totalExpense`=4000 
destination columns: `totalFoodExpense = sumOfAll(foodExpenses)`, `percentFoodExpense = totalFoodExpense/totalExpense * 100`

**Comment by hotienvu** [comment]
hi @npawar I'd like to work on this. I think we need to sort the columns in topological order before applying the transform function
