### ISSUE TITLE
Add support for JDBC client for queries

### ISSUE THREAD

**Issue by KKcorps** [apache/pinot#5363]
Currently Pinot provides a Java client and a Golang client for querying the database. However, some of the UI tools don't support the custom clients. JDBC is the default API for querying in a lot of databases and so a Client needs to be written to support  it.

**Comment by npawar** [comment]
We had an issue for this: https://github.com/apache/incubator-pinot/issues/4978
Will close that one. Copying over the description from that on to this issue:
Provide a jdbc driver implementation for accessing Pinot from Java.
This can go in a module of its own pinot-jdbc-client

The existing pinot-client is not a jdbc client. It has many custom APIs in its ResultSet interface. The query execution has very specific switches between pql and sql.
The jdbc-client should be as simple as

```
PinotConnection connection = ....
Statement statement = connection.createStatement();
ResultSet rs = statement.executeQuery(sql);
while(rs.next()) {
  rs.get(
}
```
