### ISSUE TITLE
[TE] Let's put this name in configuration

### ISSUE THREAD

**Issue by xiaohui-sun** [apache/pinot#5393]
https://github.com/apache/incubator-pinot/blob/a1401de18c10fc07b557a6e5ce0efacd8d486869/thirdeye/thirdeye-frontend/app/pods/home/index/route.js#L81

@harleyjj

**Comment by Jackie-Jiang** [comment]
Closing third-eye related issue as the project has been moved out of the pinot repo. For unsolved issue that still applies, please create a new one under third-eye repo: https://github.com/project-thirdeye/thirdeye
