### ISSUE TITLE
Pinot 0.4 Release | Realtime table- Error in creating a segment

### ISSUE THREAD

**Issue by SudhaGarimella** [apache/pinot#5600]
This is the Realtime table use case where in data gets streamed from Kafka, during a segment creation - an exception is being thrown. Attached is the exception stack trace from the pinot server. Also attached is the list of file descriptions outputted from lsof command on all processes running on the pinot server.
Same works fine on release 0.3.
the file exists in Azure portal - Attached snap shot.
![azure-portal-file-exists](https://user-images.githubusercontent.com/26456419/85237609-c8090980-b445-11ea-81cb-76e55bb5fb9d.jpg)

[Log-0.4-seg-commit.txt](https://github.com/apache/incubator-pinot/files/4809980/Log-0.4-seg-commit.txt)
[LSOF - listFileDescr-0.4.txt](https://github.com/apache/incubator-pinot/files/4809981/LSOF.-.listFileDescr-0.4.txt)
[tableConfigYML.txt](https://github.com/apache/incubator-pinot/files/4809993/tableConfigYML.txt)

**Comment by kishoreg** [comment]
There was no change in the code related to segment creation. 

@mcvsubbu @npawar @Jackie-Jiang  any idea whats going on here?

**Comment by haibow** [comment]
The last few lines of the log shows
```
2020/06/21 11:26:45.012 INFO [SegmentDictionaryCreator] [jeepusermap__1__0__20200621T1125Z] Using fixed bytes value dictionary for column: field4, size: 0
2020/06/21 11:26:45.012 INFO [SegmentDictionaryCreator] [jeepusermap__1__0__20200621T1125Z] Created dictionary for STRING column: field4 with cardinality: 1, max length in bytes: 0, range:  to
2020/06/21 11:26:45.036 INFO [SegmentIndexCreationDriverImpl] [jeepusermap__2__0__20200621T1125Z] Start building IndexCreator!
2020/06/21 11:26:45.102 INFO [SegmentIndexCreationDriverImpl] [jeepusermap__0__0__20200621T1125Z] Start building IndexCreator!
2020/06/21 11:26:45.113 INFO [SegmentIndexCreationDriverImpl] [jeepusermap__1__0__20200621T1125Z] Start building IndexCreator!
2020/06/21 11:26:45.433 INFO [SegmentIndexCreationDriverImpl] [jeepusermap__2__0__20200621T1125Z] Finished records indexing in IndexCreator!
2020/06/21 11:26:45.470 INFO [SegmentIndexCreationDriverImpl] [jeepusermap__0__0__20200621T1125Z] Finished records indexing in IndexCreator!
2020/06/21 11:26:45.473 INFO [SegmentIndexCreationDriverImpl] [jeepusermap__1__0__20200621T1125Z] Finished records indexing in IndexCreator!
2020/06/21 11:26:48.632 INFO [SegmentIndexCreationDriverImpl] [jeepusermap__2__0__20200621T1125Z] Finished segment seal!
2020/06/21 11:26:48.638 INFO [SegmentIndexCreationDriverImpl] [jeepusermap__1__0__20200621T1125Z] Finished segment seal!
2020/06/21 11:26:48.674 INFO [SegmentIndexCreationDriverImpl] [jeepusermap__0__0__20200621T1125Z] Finished segment seal!
2020/06/21 11:27:22.204 ERROR [LLRealtimeSegmentDataManager_jeepusermap__0__0__20200621T1125Z] [jeepusermap__0__0__20200621T1125Z] Could not build segment
java.io.IOException: Unable to delete directory /var/pinot/server/data/index/jeepusermap_REALTIME/_tmp/tmp-jeepusermap__0__0__20200621T1125Z-1592738788709/tmp-1592738788896-2704508350342974686.
        at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1541) ~[pinot-all-0.4.0-jar-with-dependencies.jar:0.4.0-8355d2e0e489a8d127f2e32793671fba505628a8]
        at org.apache.commons.io.FileUtils.move
```
Looks like the segment sealed successfully but failed to delete the tmp folder. 
If you could paste more logs (esp after the exception) we might have more clues. Might be some permission issues.

**Comment by SudhaGarimella** [comment]
[seg-create-issue.txt](https://github.com/apache/incubator-pinot/files/4825293/seg-create-issue.txt)

Sorry did not realize that it was truncated. Please check this one.

**Comment by mcvsubbu** [comment]
@SudhaGarimella I am not sure how azure permissions work. Things to examine would be:
(1) What user did you run as when deleting the file from azure portal?
(2) what user does the pinot server executable run as?

**Comment by SudhaGarimella** [comment]
@mcvsubbu :  so 2 things
1. the azure portal path is mounted into the server, so isnt that like a local file for pinot server?
2. what we did today was we first had used 0.3 release, then did a rolling update (changed the img to 0.4). When using 0.3 you can see we created about 39 segments, when upgraded to 0.4, the first segment it tried to create had failed. So the point I am saying is - same setup worked well with 0.3 release, when v did a rolling update to 0.4, seg creation failed.

**Comment by kishoreg** [comment]
@fx19880617 any changes to the way we start k8s containers?

**Comment by fx19880617** [comment]
Is it possible to check the directory permission between two images for the mounted directory inside the container?
You can run `kubectl exec -it pod/pinot-controller-0 -n pino-quickstart bash` to get into the container's bash

**Comment by kishoreg** [comment]
@SudhaGarimella can you provide more info

**Comment by sudha-garimella** [comment]
I checked the folder permissions for 0.4 they have read write and execute. But i cant check for previous release since those folders are already deleted.

**Comment by SudhaGarimella** [comment]
![linux-folder-perm1](https://user-images.githubusercontent.com/26456419/86152423-c2828200-bb1d-11ea-8723-056026999bab.jpg)
![linux-folder-perm2](https://user-images.githubusercontent.com/26456419/86152431-c4e4dc00-bb1d-11ea-9f93-5a134b9711a0.jpg) 


Both of these are for 0.4 release

**Comment by SudhaGarimella** [comment]
As suggested by @fx19880617 , I updated the storage class for server to default (previous value was azurefile) and then segments are getting created now without any exception.
As per recommended approach, storage class for server has to be azuredisk which is the default and not azurefile.

**Comment by SudhaGarimella** [comment]
![pvc-snap](https://user-images.githubusercontent.com/26456419/86173282-5e6fb600-bb3d-11ea-85d8-5ad660a1fae3.jpg)
This image is post change
