### ISSUE TITLE
Kinesis integration

### ISSUE THREAD

**Issue by npawar** [apache/pinot#5648]
Add connector for ingesting from Amazon Kinesis
https://docs.google.com/document/d/1hFbzumQAGALAi8XZMOsVlwVHN-s2t37MA5QUfduL4Yk/edit#

**Comment by mcvsubbu** [comment]
@KKcorps is working on this, right?
For discussion, please join the channel #kinesis-integration

One outstanding question here is how to tackle kinesis increase/reduction of partitions. I could not discern from their documentation as to how this happens in kinesis, so we may have to pull out some more source code as plugin for this purpose.

**Comment by KKcorps** [comment]
Hi @mcvsubbu @npawar Yes, I am already working on this. It has been on pause for a while since I picked up JDBC driver.
The driver will need changes in SQL Parser so I am planning to  pick this up again and drive it to conclusion.

**Comment by npawar** [comment]
Created an issue because there wasn't one already

**Comment by kishoreg** [comment]
Looking at the voting result so far (https://poll.ly/#/2YeaKQ5o), We can probably get to this in q4.

**Comment by npawar** [comment]
Design doc: https://docs.google.com/document/d/1hFbzumQAGALAi8XZMOsVlwVHN-s2t37MA5QUfduL4Yk/edit#
