### ISSUE TITLE
unable to order aggregated results

### ISSUE THREAD

**Issue by gilmichlin** [apache/pinot#57]
based on : https://groups.google.com/forum/#!topic/pinot_users/Svz-ScObEj4

<code> select count(*), sum(hitsByPitch)
from baseballStats
where hitsByPitch>5 
group by teamID top 20 asc
</code>

errors:
<error>
ProcessingException(errorCode: 150,message: MismatchedTokenException(30 != -1))
</error>

**Comment by jfim** [comment]
Tracked as PINOT-2272. Will look into it to see if it's an easy fix or not.

**Comment by jfim** [comment]
This would require some changes to the query execution engine, so getting this right instead of just tacking this on on top of the current topN syntax would be better (eg. doing something like ORDER BY count(*) ASC).
