### ISSUE TITLE
Improve performance for DISTINCT queries

### ISSUE THREAD

**Issue by Jackie-Jiang** [apache/pinot#5771]
Optimizations to consider:
- Early-termination for DISTINCT without order-by (need to model DISTINCT as a new operator instead of aggregation function)
- Store dictIds inner segment to reduce the unnecessary dictionary reads

**Comment by Jackie-Jiang** [comment]
- Use dictionary to solve query without filter
- Specialize DISTINCT on single column (store Object instead of Object[] in the set)

**Comment by kishoreg** [comment]
This is done right?

**Comment by Jackie-Jiang** [comment]
@kishoreg Not yet
