### ISSUE TITLE
About Pinot's develop plans and timelines

### ISSUE THREAD

**Issue by flowbehappy** [apache/pinot#58]
Hi, I would like to know about the feature plans and ETA/timelines of Pinot.
We need to upgrade our realtime analyzing system and have done a lot of investigations on deferent kinds of system. Pinot is great and looks pretty suitable for us. But currently it do lack some query features we really need. They are:
1. Calculation on dimensions and aggregated metrics. e.g. `select (dimA / 100) as dimB, (sum(metricA) + sum(metricB)) as metricC from table group by dimB order by metricC`.
2. Not only the topN, but the real & completed _order by_ support. e.g. `select dimA, sum(metricA), sum(metricB) from table group by dimA order by sum(metricA) desc, sum(metricB) asc offset 10, 20`
3. Having clause.

**Comment by jfim** [comment]
Hey there @flowbehappy,

All of it is on our roadmap, but I don't have a good ETA for this. It's very unlikely that all of these would be supported by the end of December, though. Are there things that are higher priority among all of these features?

**Comment by flowbehappy** [comment]
@jfim I'm very glad to hear that :smile: 
The first two are very urgent for us so they get the higher priority. Having clause is *better to have*.

**Comment by flowbehappy** [comment]
Besides, when should I expect the next stable release, and the new features it will contains?

**Comment by kishoreg** [comment]
Hi Flowyi,

The first two should be available by end of this year. Having clause is
something we are not sure if/when we would add.

thanks
Kishore
