### ISSUE TITLE
Problem to understand the Thrideye into Pinot

### ISSUE THREAD

**Issue by MarceloNunesAlves** [apache/pinot#5800]
What should I do to The Thrideye works in the Pinot? I didn't find anything about how it use this into the Pinot. Is there a documentation? I executed Thrideye only in the Eclipse but I needed change the branch to release-0.4.0. This step by step -> https://thirdeye.readthedocs.io/en/latest/quick_start.html doesn't work.

**Comment by kishoreg** [comment]
@suvodeep-pyne ^^

**Comment by suvodeep-pyne** [comment]
Hi @MarceloNunesAlves 

I think this doc might need an update. I'd recommend setting up ThirdEye with a MySQL persistence layer (Please use MySQL 5.7) and then adding Pinot as the datasource. Here are 2 docs that might help.
1. [Getting Started](https://thirdeye.readthedocs.io/en/latest/getting_started.html)
2. [Adding Pinot as a data source](https://thirdeye.readthedocs.io/en/latest/pinot.html)

Let me know how it goes. It might be cool to join the [ThirdEye Slack](https://communityinviter.com/apps/apache-thirdeye/apache-thirdeye).

**Comment by kishoreg** [comment]
@MarceloNunesAlves is this resolved?

**Comment by MarceloNunesAlves** [comment]
@kishoreg, I haven't tried yet. tks

**Comment by Jackie-Jiang** [comment]
Closing third-eye related issue as the project has been moved out of the pinot repo. For unsolved issue that still applies, please create a new one under third-eye repo: https://github.com/project-thirdeye/thirdeye
