### ISSUE TITLE
Apache Pulsar Connector integration

### ISSUE THREAD

**Issue by SandishKumarHN** [apache/pinot#5837]
Add connector for ingesting from Apache Pulsar

**Comment by SandishKumarHN** [comment]
I would like to work on this if no one is already started working on it.

**Comment by fx19880617** [comment]
Please take it @SandishKumarHN . Thanks!

**Comment by kishoreg** [comment]
Sure, let me assign this to you.

**Comment by HansOspina** [comment]
@SandishKumarHN let me know if I can help with this one.

**Comment by SandishKumarHN** [comment]
@HansOspina you take up this one if you like, currently occupied with different tasks.

**Comment by HansOspina** [comment]
@SandishKumarHN can we at least tackle it together? not sure I have the pinot experience to actually do it all by myself.

**Comment by SandishKumarHN** [comment]
@HansOspina let's connect over pinot slack.

**Comment by Eywek** [comment]
Hello, any news on this integration?

Thank you

**Comment by fx19880617** [comment]
Hi @SandishKumarHN, any update on this and anything we can help?

**Comment by KKcorps** [comment]
@xiangfu0 Picking this up.
