### ISSUE TITLE
Support for a fixed precision Decimal column type

### ISSUE THREAD

**Issue by lgo** [apache/pinot#5904]
Systems like Presto support a fixed decimal type, as documented in https://prestodb.io/docs/current/language/types.html#fixed-precision.

Having this feature would help immensly for use-cases which need accurate aggregation for large numbers. In my particular use-case, I have a dataset where we produce and use Presto's fixed-decimal as `DECIMAL(38, 6)` as we need 6-decimal accuracy for relatively large numbers.

Input format compatibility will vary. For example, in JSON no such type is support so it would need to be the result of transforming a string to the decimal. It's also possible to have different trunctation or rounding semantics during parsing. For that reason, it may be more usable to not allow mapping this column's values directly but requiring a transformation config.

**Comment by kishoreg** [comment]
What operators will you need on top of DECIMAL. is sum the only one?

**Comment by lgo** [comment]
We'll just need basic arithmetic operations (+ abs) and `SUM` agg. Our aggregation functions may look like either this:
```
SELECT
  SUM(decimal_col)
FROM ...
```

Or some variations (`SUM(ABS(decimal_col))`, with other math ops inside the `SUM` expression)

**Comment by icefury71** [comment]
@kishoreg @lgo ok to close this issue ?

**Comment by Jackie-Jiang** [comment]
`SumPrecision` aggregation function introduced in #6053 solves the basic requirement
#8418 is adding the native BIG_DECIMAL data type into Pinot. Closing this issue and use that to track the progress
