### ISSUE TITLE
add pinot-confluent-protobuf to pinot-input-format

### ISSUE THREAD

**Issue by zzztimbo** [apache/pinot#5954]
https://github.com/apache/incubator-pinot/tree/master/pinot-plugins/pinot-input-format/pinot-confluent-avro

Similar to confluent-avro. I would like the ability to consume protobuf messages from Kafka that were serialized using the Confluent Schema Registry.

https://docs.confluent.io/current/schema-registry/serdes-develop/index.html#schema-formats-serializers-and-deserializers

https://docs.confluent.io/current/schema-registry/serdes-develop/index.html#wire-format

**Comment by franoisD** [comment]
Hello,
Are there any news about this topic?
I can't consume protobuf messages from kafka

**Comment by davizucon** [comment]
Pls, take a look here:
https://docs.pinot.apache.org/v/release-0.11.0/basics/data-import/pinot-input-formats#protocol-buffers

**Comment by Jackie-Jiang** [comment]
Thanks @davizucon!
