### ISSUE TITLE
Unreleased Resource: Streams

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [apache/pinot#5980]
https://github.com/apache/incubator-pinot/blob/6640affe5b2ac6bc0a972c7a9e291c1d5189effb/thirdeye/thirdeye-hadoop/src/main/java/org/apache/pinot/thirdeye/hadoop/backfill/BackfillControllerAPIs.java#L105

The program can potentially fail to release a system resource.

**Comment by Jackie-Jiang** [comment]
Closing third-eye related issue as the project has been moved out of the pinot repo. For unsolved issue that still applies, please create a new one under third-eye repo: https://github.com/project-thirdeye/thirdeye
