### ISSUE TITLE
Optimize the performance of DISTINCT queries

### ISSUE THREAD

**Issue by Jackie-Jiang** [apache/pinot#6081]
Opportunities:
1. Separate DISTINCT from aggregation and make it a standalone type of query (similar to select but deduplicate the records) so that early termination logic can be easily plugged in
2. Specialize order-by with 1 column, where we can directly work on primitive type

**Comment by Jackie-Jiang** [comment]
Use dictionary ids instead of fetching actual values inner segment

**Comment by atris** [comment]
@Jackie-Jiang Should we close this ticket?

**Comment by Jackie-Jiang** [comment]
@atris Yes, thanks for the notification
