### ISSUE TITLE
Support customized maxLength for fields in schemaBuilder 

### ISSUE THREAD

**Issue by deemoliu** [apache/pinot#6106]
When construct a Pinot schema using [schemaBuilder](https://github.com/apache/incubator-pinot/blob/master/pinot-spi/src/main/java/org/apache/pinot/spi/data/Schema.java#L474), the maxLength of fields are always set to DEFAULT_MAX_LENGTH which is 512. Currently we need to tune "maxLength" in table schema manually.

Would it be better to expose the maxLength configuration to schemaBuilder?

**Comment by deemoliu** [comment]
#6112

**Comment by mayankshriv** [comment]
Seems like this was addressed by #6112.
