### ISSUE TITLE
Support environment variables injection for Pinot ingestion job

### ISSUE THREAD

**Issue by xiangfu0** [apache/pinot#6115]
Pinot supports launch ingestion jobs with a template file and a command line option to set the values.

This logic is handled in class: `org.apache.pinot.spi.ingestion.batch.IngestionJobLauncher`.

Here we want to also support environment variables to set those values.

This will be convenient for users in k8s environment with dynamic configs settings.

E.g. user can do dynamic job loading with k8s cronjob by setting:

- Set `inputDirURI` to `'s3://event-logs/dt=${JOB_DATE}/'` in `batch_job_spec.yaml` file.
- Set container  `env` with `JOB_DATE` to `$(date -u +"%Y-%m-%d")`, so `JOB_DATE` will be the runtime date.
- Set container `args` to
```
[
    "LaunchDataIngestionJob",
    "-jobSpecFile",
    "/home/pinot/pinot-config/batch_job_spec.yaml"
]
```

**Comment by vgtom** [comment]
hi...i would like to work on this issue(although my response maybe slow because i have a FullTime job)

**Comment by JoaoComini** [comment]
Hi folks! 😄
Given that we already have Groovy templating working on `IngestionJobLauncher`, what would be the priority when there's a
`-values` parameter and an enviroment variable with the same name?
