### ISSUE TITLE
[Thirdeye] - Anamoly images periodically fails to load. 

### ISSUE THREAD

**Issue by venkatvghub** [apache/pinot#6182]
Hello, am seeing an image loading issue on the "Anamolies" page. At times, the images show up and at times it doesnt. Have to hit page load many a times to see a missing image. Same image dissappears after a while. For example, this is what am currently seeing:
The investigation URl, of course takes to the main page. The home page with the appropriate metric is showing the values correctly. Ran prediction previews and thats also showing up. Its kind of non reproducible consistently. Anything that can be done here?

Reference Slack Conversation: https://apache-thirdeye.slack.com/archives/CGS41AV7T/p1603277623030500

Additional Notes:
1. We aren't using any cache right now and fetching from backend directly.
2. The issue is largely non reproducible since the same image that loads once doesn't load another time and vice versa. 
3. Don't see any errors or others in the logs. 

Attaching sample screenshots:
![Screenshot from 2020-10-21 16-22-11](https://user-images.githubusercontent.com/5548660/96996624-cbc0b000-154d-11eb-81be-c4ebf53be537.png)
![Screenshot from 2020-10-21 16-21-57](https://user-images.githubusercontent.com/5548660/96996633-cd8a7380-154d-11eb-8f08-f47e66f2b9ed.png)

**Comment by Jackie-Jiang** [comment]
Closing third-eye related issue as the project has been moved out of the pinot repo. For unsolved issue that still applies, please create a new one under third-eye repo: https://github.com/project-thirdeye/thirdeye
