### ISSUE TITLE
make MAX_NUM_THREADS_PER_QUERY configurable

### ISSUE THREAD

**Issue by samarth-gupta-traceable** [apache/pinot#6374]
make MAX_NUM_THREADS_PER_QUERY configurable. 
Currently it depends on `Runtime.getRuntime().availableProcessors()` , due to which user is forced request high number of CPU in k8 deployments 

https://github.com/apache/incubator-pinot/blob/master/pinot-core/src/main/java/org/apache/pinot/core/operator/combine/CombineOperatorUtils.java#L38

**Comment by samarth-gupta-traceable** [comment]
created PR" https://github.com/apache/incubator-pinot/pull/6375

**Comment by hpvd** [comment]
@samarth-gupta-traceable 
is this still an issue? You have closed the related pull request
https://github.com/apache/pinot/pull/6375

If solved we d like to close this issue.

**Comment by hpvd** [comment]
thank you!
