### ISSUE TITLE
partial upsert feature is supported yet ?

### ISSUE THREAD

**Issue by flykent1990** [apache/pinot#6386]
Hi team partial for upsert has been supported for table session 0.6.0 yet

@Jackie-Jiang @fx19880617 @yupeng9 

thanks

**Comment by yupeng9** [comment]
It's not available yet. The community plans to work on it in 2021 and the design is in progress. We'll share the design when it's available in the next months.

**Comment by Jackie-Jiang** [comment]
#6575
