### ISSUE TITLE
support for expansion of * in the project part of a query

### ISSUE THREAD

**Issue by kant777** [apache/pinot#6470]
Currently pinot cannot support

```
select *, device='phone' from pageviews
```

would be great to support the above syntax.

**Comment by salamehsameera** [comment]
I'm looking for a task to get familiar with the project, I can take this since it's labeled with 'beginner-task'!

**Comment by PrachiPrakash** [comment]
@xiangfu0 is this still a required feature, was playing around with the code would like to give it a try

**Comment by shauryachats** [comment]
@kant777 you could try using
```
select *, 'phone' device from pageviews
```
which should do the same thing effectively.

**Comment by Jackie-Jiang** [comment]
Expansion of * is supported in #7959
