### ISSUE TITLE
Update document for JDBC client

### ISSUE THREAD

**Issue by HyunjoonCho** [apache/pinot#6519]
Hello, 
I updated JDBC client from 0.5.0 to 0.6.0 and it did not work with previous setting.
Then found out that it only requires controller url now, which is referred as WIP in document. 
https://docs.pinot.apache.org/users/clients/jdbc#usage 
Update on this document will be a big help for newcomers.
Thanks.

**Comment by kishoreg** [comment]
@KKcorps

**Comment by KKcorps** [comment]
Hi @HyunjoonCho Thanks for pointing out the issue. Fixing it in the docs now.

**Comment by KKcorps** [comment]
Hi @HyunjoonCho I can see it mentions controller URL only in the page you mentioned. Can you point me to the exact location where you found WIP and old config.

**Comment by HyunjoonCho** [comment]
Hi, the page I mentioned said WIP 8 hours ago but seems someone fixed it! Thanks
