### ISSUE TITLE
Support for configurable time column in Upserts

### ISSUE THREAD

**Issue by icefury71** [apache/pinot#6523]
Currently the Pinot upserts functionality is using the primary time column to resolve the latest version of a record/document. In some cases, its desirable to make this configurable so that we can choose a custom resolution column.

CC @yupeng9 @Jackie-Jiang @jeff-transmit

**Comment by keweishang** [comment]
We at Bolt also need this feature. We use Kafka Streams to join different Kafka topics. Kafka Streams' JOIN produces many Kafka records with the same event-time column value. Pinot randomly picks one record as the latest one when the event-time value is the same and it doesn't guarantee that the record of the latest Kafka offset is chosen.

It would be great to use other columns (e.g. an int/long column or Kafka Offset) than the event-time column to decide which is the last version when the primary key is the same.

We're evaluating Pinot at Bolt and this is a blocking issue for us at the moment.

**Comment by mayankshriv** [comment]
Tagging @yupeng9 to see if this could be done easily?

**Comment by yupeng9** [comment]
I don't think it's hard. We need to add a configuration, and have the upsert metadata manager use it instead of the time column for determining the latest. I can take this when I have some cycyles.
