### ISSUE TITLE
Real time tables with text index enabled lead to file leaks

### ISSUE THREAD

**Issue by sajjad-moradi** [apache/pinot#6562]
When a consuming segment completes, all the files in consuming directory are supposed to be deleted. However, text index for real time tables does not clean up all the files. For each segment, one file will remain undeleted.
I dug a bit into the code and I believe found the root cause.
In “consuming” -> “online”  transition on server, first we delete the consuming segment directory and then release the segment:
![image](https://user-images.githubusercontent.com/8548220/107400967-3bd05300-6ab7-11eb-8e97-3dfd16ff65b0.png)
Text index uses a file “write.lock” as the lock. The lock is released whenever the text index gets released.
So when we try to delete the consuming segment directory in CONSUMING to ONLINE transition, since the lock file is being used and not yet released, all files in segment directory get deleted except the lock file.
That’s why you see the following on a server having a realtime table with text index enabled:
![image](https://user-images.githubusercontent.com/8548220/107401160-73d79600-6ab7-11eb-95d2-d2ccb01f36d6.png)
The size of those lock files are all zero:
```bash
[smoradi@lva1-app0232 ~]$ ll /export/content/data/pinot-server/i001/pinot/consumerDir/RealtimeFeatureTest1_REALTIME/RealtimeFeatureTest1__0__101__20201229T1103Z/textDim1.lucene.index/
total 0
-rw-rw-r-- 1 app app 0 Dec 29 11:03 write.lock
```

**Comment by kishoreg** [comment]
@sajjad-moradi awesome find

**Comment by pabrahamusa** [comment]
I can also see lots of these lock file not getting deleted. @sajjad-moradi , @mcvsubbu and fix you guys planning to add? 

```
rw-r--r-- 1 root root 0 Feb 13 00:01 ./consumers/sblog__1__753__20210213T0000Z/log.lucene.index/write.lock
-rw-r--r-- 1 root root 0 Feb 13 00:02 ./consumers/sblog__1__754__20210213T0002Z/log.lucene.index/write.lock
-rw-r--r-- 1 root root 0 Feb 13 00:04 ./consumers/sblog__1__755__20210213T0004Z/log.lucene.index/write.lock
-rw-r--r-- 1 root root 0 Feb 13 00:06 ./consumers/sblog__1__756__20210213T0006Z/log.lucene.index/write.lock
-rw-r--r-- 1 root root 0 Feb 13 00:08 ./consumers/sblog__1__757__20210213T0008Z/log.lucene.index/write.lock
-rw-r--r-- 1 root root 0 Feb 13 00:12 ./consumers/sblog__1__758__20210213T0012Z/log.lucene.index/write.lock
-rw-r--r-- 1 root root 0 Feb 13 00:13 ./consumers/sblog__1__759__20210213T0013Z/log.lucene.index/write.lock
-rw-r--r-- 1 root root 0 Feb 13 00:16 ./consumers/sblog__1__760__20210213T0016Z/log.lucene.index/write.lock
-rw-r--r-- 1 root root 0 Feb 13 00:17 ./consumers/sblog__1__761__20210213T0017Z/log.lucene.index/write.lock
-rw-r--r-- 1 root root 0 Feb 13 00:19 ./consumers/sblog__1__762__20210213T0019Z/log.lucene.index/write.lock
-rw-r--r-- 1 root root 0 Feb 13 00:21 ./consumers/sblog__1__763__20210213T0021Z/log.lucene.index/write.lock
-rw-r--r-- 1 root root 0 Feb 13 00:22 ./consumers/sblog__1__764__20210213T0022Z/log.lucene.index/write.lock
-rw-r--r-- 1 root root 0 Feb 13 00:26 ./consumers/sblog__1__765__20210213T0026Z/log.lucene.index/write.lock
-rw-r--r-- 1 root root 0 Feb 13 00:28 ./consumers/sblog__1__766__20210213T0028Z/log.lucene.index/write.lock
-rw-r--r-- 1 root root 0 Feb 13 00:31 ./consumers/sblog__1__767__20210213T0031Z/log.lucene.index/write.lock
-rw-r--r-- 1 root root 0 Feb 13 00:33 ./consumers/sblog__1__768__20210213T0033Z/log.lucene.index/write.lock
```

**Comment by mghildiy** [comment]
Hey, I am just starting with pinot. So though of digging into the code to get a clear picture of what it does.
So if no-one else is working on this issue, I can give it a try. 
Any pointer on which part of code/tests to tinker with would really help.

**Comment by Jackie-Jiang** [comment]
@sajjad-moradi Does this issue still exist?

**Comment by sajjad-moradi** [comment]
I just checked in a couple of tables. Don't see the issue anymore.

**Comment by Jackie-Jiang** [comment]
Thanks @sajjad-moradi! Shall we close this ticket then?
