### ISSUE TITLE
[Enhancement Feature Request] Star Tree support for sumprecesion

### ISSUE THREAD

**Issue by dongxiaoman** [apache/pinot#6628]
Right now we support big decimal via `BYTES` column and process data by functions like `sumprecesion`. It seems we cannot pre-build star tree for `sumprecesion`. Furthermore we need a mechanism to specify the parameter to that function. It can be a fixed value of `sumprecision(my_column, 40, 12)` but the 40, 12 needs to be specified

**Comment by Jackie-Jiang** [comment]
#6668
