### ISSUE TITLE
Bump up DataTable version to address TODOs in DataTableBuilders

### ISSUE THREAD

**Issue by mqliang** [apache/pinot#6726]
As discussed into: https://github.com/apache/incubator-pinot/pull/6710, we need bump up DataTable version to address TODOs in DataTableBuilders:
```
// TODO: potential optimizations:
// TODO:   1. Fix float size.
// TODO:   2. Use one dictionary for all columns (save space).
// TODO:   3. Given a data schema, write all values one by one instead of using rowId and colId to position (save time).
// TODO:   4. Store bytes as variable size data instead of String
```

For the 3rd TODO, it speculative and benchmark result shows it's not needed: https://github.com/apache/incubator-pinot/issues/6720

**Comment by Jackie-Jiang** [comment]
(Optional) For the 3rd TODO, we may simplify the code by replacing `setColumn(int colId, int value)` to `pubValue(int value)` because we always put values one by one. Performance difference might not be huge, but should be cleaner.

**Comment by mqliang** [comment]
`AppendValue()` looks much better.

**Comment by Jackie-Jiang** [comment]
Done with #8890
