### ISSUE TITLE
Support REALTIME tables in reload status (segment metadata API) 

### ISSUE THREAD

**Issue by npawar** [apache/pinot#6767]
This PR https://github.com/apache/incubator-pinot/pull/5718 introduced the metadata API on the controller, which provides indexing info for each segment from the segments on the server. However, it is not handling REALTIME tables as of now.
Add support for realtime tables.
Once added, also ensure the Pinot Cluster Manager i.e. Pinot UI is able to show it for realtime tables (Reload Status button)

![Screen Shot 2021-04-09 at 1 04 04 PM](https://user-images.githubusercontent.com/19693933/114234822-24d1a400-9934-11eb-8b9e-4986e127d1c8.png)

**Comment by ramabme** [comment]
Committed below change to fix above issue. Fixed the UI button and REST API.
https://github.com/apache/pinot/pull/7169

**Comment by npawar** [comment]
Thanks @ramabme ! Closing this.
