### ISSUE TITLE
Add an endpoint to manually trigger each controller periodic task

### ISSUE THREAD

**Issue by Jackie-Jiang** [apache/pinot#6812]
Currently the controller periodic task can only be triggered via the scheduler. Occasionally users might need to use the periodic task to fix some state (e.g. use `RealtimeSegmentValidationManager` to add consuming segments for a new partition, use `SegmentRelocator` to relocate segments etc.). It would be good to add an endpoint to manually trigger the periodic task.

**Comment by mcvsubbu** [comment]
I think this is a useful feature to have, but we need to be careful to trigger this in the lead controller for the table. Otherwise,  if two controllers work on the same task simultaneously, weird things may happen

**Comment by Jackie-Jiang** [comment]
@mcvsubbu Good point. In order to run a particular task on a particular table, we also no to figure out which controller hosts the target table.

**Comment by mcvsubbu** [comment]
@amrishlal is working on this

**Comment by Jackie-Jiang** [comment]
#7155
