### ISSUE TITLE
Mask credentials in minion tasks spec and table configs.

### ISSUE THREAD

**Issue by xiangfu0** [apache/pinot#6823]
For example, s3 SecretKey.
It would be better to mask the credential information during table APIs and minion task APIs.

**Comment by kriti-sc** [comment]
Picking this up.

**Comment by kriti-sc** [comment]
PR: https://github.com/apache/incubator-pinot/pull/7081

**Comment by piyushchauhan** [comment]
@xiangfu0 does this still persist after merging #7407 ?

**Comment by Jackie-Jiang** [comment]
Fixed with #7407
