### ISSUE TITLE
Recover real-time consumption when consuming segment stuck

### ISSUE THREAD

**Issue by Jackie-Jiang** [apache/pinot#6854]
One possible solution is to manually delete the consuming segment and let the controller create a new one during real-time segment validation. But this scenario is not covered in the `PinotLLCRealtimeSegmentManager.ensureAllPartitionsConsuming()` yet.

**Comment by mcvsubbu** [comment]
Another way is to manually set the consuning segment to be in OFFLINE state (if it s not already so).

**Comment by mcvsubbu** [comment]
@Jackie-Jiang what was the exact scenario when consumption got "stuck" ?  As of now, it is the case that we retry a few times and if the stream throws exception, then we automatically mark the state as OFFLINE in idealstate. If all replicas are marked OFFLINE, then automatic recovery happens through periodic job. If some replicas are OFFLINE, then others are allowed to complete the segment, and eventually all replicas have a copy of he completed segment.

By "stuck", did you mean bad data? The only way to recover from bad data as of now is to let the periodic job keep retrying until the bad offset is retained out of the underlying stream, and it will eventually pick an offset and continue consumption. A long time to wait in production use cases. Is this the scenario you were referring to?

**Comment by Jackie-Jiang** [comment]
@mcvsubbu I don't remember the exact scenario when this ticket was created. But I do think we should handle the case of a partition not having a consuming segment. It could happen in the following cases:
- Consuming segment manually deleted accidentally
- Schema evolution to recreate the consuming segment
- Bootstrap a realtime table with immutable segments (e.g. cloning a realtime table)

**Comment by Jackie-Jiang** [comment]
@sajjad-moradi Yes, I think the pause/resume can be used to address all 3 cases mentioned above. Thanks for adding the great feature!
