### ISSUE TITLE
Change zookeeper helm chart dependency

### ISSUE THREAD

**Issue by pedro93** [apache/pinot#6923]
The current zookeeper helm chart component of Pinot's Kubernetes deployment is [deprecated](https://github.com/helm/charts/tree/master/incubator/zookeeper) as of Nov 13, 2020. 
Consider changing to the more up-to-date, better documented helm chart from bitnami: https://github.com/bitnami/charts/tree/master/bitnami/zookeeper

**Comment by ivanvy-wix** [comment]
The switch to Bitnami’s ZooKeeper chart was made in #7955 (chart v7.0.0, ZooKeeper v3.7.0). Later updated to v9.2.7 version of the chart (ZooKeeper v3.8.0) in #8936. I think the issue can be closed now.
