### ISSUE TITLE
Realtime to Offline segment conversion task fails to progress with data gaps

### ISSUE THREAD

**Issue by laxmanchekka** [apache/pinot#6988]
Realtime to Offline segment conversion task fails to progress when there are larger data gaps in REALTIME table.
Noticed when the data gap is larger than the bucketTimePeriod.

**Comment by laxmanchekka** [comment]
@Jackie-Jiang @npawar

**Comment by kriti-sc** [comment]
Picking this up

**Comment by Eywek** [comment]
Hello,
Any news on this?

**Comment by deepakcse2k5** [comment]
Hi kriti-sc,

Is there any update on this ?

**Comment by kriti-sc** [comment]
No, still working on this. @Eywek @deepakcse2k5
