### ISSUE TITLE
Support the  dimension contains  PredicateEvaluator

### ISSUE THREAD

**Issue by sundy-li** [apache/pinot#70]
I have found Pinot that contains  `regex Predicate`  but not implemented yet, I suggest that `dimension string contains  predicate`  would be much higher priority cause it was mostly used by filter querys.

   To implement it with current dictionary algorithm, pinot should scan the whole dictionary index of the datasource,it would be poor efficiency,  may be pinot build other index file for this filter such as `lucene` did ?

**Comment by Jackie-Jiang** [comment]
FST index is available to accelerate the regex match
