### ISSUE TITLE
Support query result post-aggregation / nested query 

### ISSUE THREAD

**Issue by MrNeocore** [apache/pinot#7043]
Following Slack discussion : https://apache-pinot.slack.com/archives/C011C9JHN7R/p1623346401028100

**Data**
date      | 01 | 02 | 03
entity1 | 1  |  2 |  3 
entity2 | 3  |  4 |  5

**Goal**
Aggregate data in "2 dimensions", first per entity (say, AVG), then per date (say, SUM)

This use case appears to be solvable using generic nested queries or an improvement to the existing post-aggregation feature.

**Nested query example** (not currently possible) 
`SELECT SUM(agg_value) FROM (SELECT dateString, AVG(value) as agg_value FROM table GROUP BY dateString)`

**Workarounds**
1. Perform post-aggregation client-side (provided that cardinality is lowish)
2. Use Presto

@Jackie-Jiang @mayankshriv: Feel free to edit the title & content

**Comment by Jackie-Jiang** [comment]
In order to do general post-aggregation and nest query, we should build another set of operators on broker side that work on `ResultTable` (row major table). Currently all the operators on the server side works on the `DataSource` which is column major.

**Comment by atris** [comment]
@Jackie-Jiang If it makes sense, I would like to start working on this.

**Comment by siddharthteotia** [comment]
At LinkedIn, we will be exploring a combined design for subqueries and distributed joins since design / architecture wise there might be overlap and it is good to think of both design wise. cc @amrishlal  @jackjlli 
Once we have had some preliminary thought / initial design, we will share with community to iterate upon and collaborate further.

**Comment by siddharthteotia** [comment]
https://github.com/apache/incubator-pinot/issues/5664

**Comment by atris** [comment]
@siddharthteotia Thats great to hear. I am already working on this feature, since its crucial for our evaluation of Pinot. I would request your inputs and feedback on the proposed design and lets ensure alignment with your overall plans for Joins (I plan to publish today).

**Comment by shuitai** [comment]
Any updates on this thread ?

**Comment by Jackie-Jiang** [comment]
This is supported with multi-stage engine
