### ISSUE TITLE
ThirdEye not supported anymore?

### ISSUE THREAD

**Issue by theauheral** [apache/pinot#7055]
Is ThirdEye not supported anymore by Pinot? I do not see it in the repo anymore and the docker image has the following errors when I launch it.

```log
Starting H2 database server

TCP server running at tcp://172.20.0.3:9092 (only local connections)

Creating ThirdEye database schema

Running Thirdeye backend config: ./config/ephemeral

[2021-06-12 19:13:33] INFO [main] o.h.v.i.u.Version - HV000001: Hibernate Validator null

Running Thirdeye frontend config: ./config/ephemeral

[2021-06-12 19:13:43] INFO [main] o.h.v.i.u.Version - HV000001: Hibernate Validator null
```

**Comment by Jackie-Jiang** [comment]
We have removed ThirdEye from Pinot repo in preparation for Apache Incubator graduation. @xiangfu0 Do we have a separate repo for ThirdEye alone?

**Comment by xiangfu0** [comment]
Thirdeye is moved to
https://github.com/project-thirdeye/thirdeye
