### ISSUE TITLE
Add `numConsumingSegmentsProcessed` and `numConsumingSegmentsMatched` into the query response metadata

### ISSUE THREAD

**Issue by Jackie-Jiang** [apache/pinot#7144]
Currently we have the following metadata in the query response:
- numSegmentsQueried: number of segments queried by the broker
- numSegmentsProcessed: number of segments processed after the server-side segment pruning
- numSegmentsMatched: number of segments that has records matched
- numConsumingSegmentsQueried: number of consuming segments queried by the broker

We want to also add `numConsumingSegmentsProcessed` and `numConsumingSegmentsMatched` to the query response metadata.

Note: In the `DataTable.MetadataKeys`, we mistakenly use `NUM_CONSUMING_SEGMENTS_PROCESSED` to represent the `numConsumingSegmentsQueried`

**Comment by yashrsharma44** [comment]
Can I pick this up?

**Comment by Jackie-Jiang** [comment]
@yashrsharma44 Sure, go ahead!

**Comment by ravishankar15** [comment]
Shouldn't we need to add numConsumingSegmentsProcessed and numConsumingSegmentsMatched to the response for this issue to be closed ?

**Comment by Jackie-Jiang** [comment]
@ravishankar15 Yes, reopened it
