### ISSUE TITLE
Make configs for controller periodic tasks human readable

### ISSUE THREAD

**Issue by jackjlli** [apache/pinot#7156]
The current configs for controller periodic tasks have to use number in seconds, which is not convenient. 
We can introduce a new set of configs to make them human readable, like `2h30m`.

**Comment by Jackie-Jiang** [comment]
Currently we have `frequencyInSeconds`, `initialDelayInSeconds` etc. We can add another set of configs `frequencyPeriod`, `initialDelayPeriod` which takes the human readable period string

**Comment by mcvsubbu** [comment]
Exactly, that is the idea.

**Comment by suddendust** [comment]
Hey @mcvsubbu can I pick this up?

**Comment by mcvsubbu** [comment]
Sure, please do. Just make sure that we accept _both_ old and new configurations, and prefer the new one if both or specified. Be sure to change the documentation as well to say that these new configs have been introduced and the old ones deprecated. 

[Sigh!] we have no way of deprecating configurations to make them easily visible for admin (other than release notes), so please tag your PR with release noes, and mention what  needs to go in there.

Thanks for your contribution.

**Comment by suddendust** [comment]
I have picked this up.

**Comment by suddendust** [comment]
@mcvsubbu I have raise a preliminary PR for this #7173

**Comment by mcvsubbu** [comment]
Thank you for your contribution, one of the committers will take a look
