### ISSUE TITLE
Helm chart 0.2.4 is no longer backwards compatible.

### ISSUE THREAD

**Issue by mikecdavis-dd** [apache/pinot#7176]
A recent helm chart [refactor](https://github.com/apache/incubator-pinot/pull/6839) added "chart" version as a matchLabel to the StatefulSets. This prevents upgrading from previous chart versions and upgrades to future versions since matchLabel changes are not allowed in the StatefulSet specification.

**Comment by ivanvy-wix** [comment]
The PR has been merged (by the way, thanks @mikecdavis-dd!) , but I guess GitHub didn’t recognise the _Resolves issue:_ syntax and so didn’t close the issue automatically.

**Comment by Jackie-Jiang** [comment]
Thanks @ivanvy-wix for pointing it out. Closing it
