### ISSUE TITLE
Connection is not closed in pinot JAVA client using the close API

### ISSUE THREAD

**Issue by khushbu14** [apache/pinot#7185]
As per the documentation of [pinot java client](https://docs.pinot.apache.org/users/clients/java), while closing the pinot connection using the close api, the connection is not closed. Only after the main thread in java terminates, the connection is closed.
This hinders using this client in a multithreaded app to query pinot in parallel.

**Comment by mayankshriv** [comment]
@khushbu14 I think there are two issues:
- ZK connection is not being closed (as you pointed out)
- The client in your case is perhaps opening one ZK connection per query. This is highly inefficient. At this point I am unclear on whether the same pinot client could be used across multiple threads. But assuming it cannot, the next best today would be to maintain one connection per thread in the executor service, and reuse it for all queries that the thread fires. Ideally, this should be part of pinot java client itself.

@ramambme Could you investigate:
- The ZK connection issue
- If connection is thread/safe or not, to be used by multiple threads?
- If it is not thread safe, can we provide a connection pool based client?

**Comment by ramabme** [comment]
Closing the issue as the fix has been merged - https://github.com/apache/pinot/pull/7196
