### ISSUE TITLE
[UI] Integrate minion into the Cluster Manager UI

### ISSUE THREAD

**Issue by Jackie-Jiang** [apache/pinot#7189]
Integrate minion as one of the top grids in the Cluster Manager UI, and add the page for minion similar to controller/broker/server

![Screen Shot 2021-07-21 at 6 21 45 PM](https://user-images.githubusercontent.com/17555551/126579908-f4965bf4-4c3f-4f95-91ad-d1d56af3d612.png)

**Comment by shahsank3t** [comment]
@Jackie-Jiang do we have the API to fetch minion? If so, can you help me with it. I'll add the top grid and page both.

**Comment by Jackie-Jiang** [comment]
@shahsank3t It should be the same as controller/broker/server. We already have all minions instances listed in this page, and we should be able to use the same way to create the minion page

**Comment by jayeshchoudhary** [comment]
I think we can close this ticket @Jackie-Jiang ?

**Comment by Jackie-Jiang** [comment]
Solved with #8978
