### ISSUE TITLE
Cross-account AWS Kinesis ingestion not supported

### ISSUE THREAD

**Issue by ryanjclark** [apache/pinot#7191]
If Pinot is deployed on AWS EKS in one account (`account A`), Pinot has no native way of reading a stream in another account (`account B`). You'll find this error if trying to read a stream in `account B`:
```
{"code":500,"error":"shaded.software.amazon.awssdk.services.kinesis.model.ResourceNotFoundException: Stream stream-name under account A not found.
```

**Comment by xiangfu0** [comment]
Copying over the slack discussion here:

We may need to add a few more params(credentialProvider, roleArn and roleSessionName) to make it happen, according to the example code: 
https://docs.aws.amazon.com/kinesisanalytics/latest/java/examples-cross.html#examples-cross-app

**Comment by xiangfu0** [comment]
https://github.com/apache/pinot/pull/9071
