### ISSUE TITLE
Fix website and documentation after TLP graudation

### ISSUE THREAD

**Issue by snleee** [apache/pinot#7197]
As part of the graduating process, we need to adjust our website and documentation with the new brand name and new infra (e.g. new git repo url).

Here are the lists that we need to address:
- [x] 1. Change documentation `https://github.com/apache/pinot-incubator` to `https://github.com/apache/pinot`.  
- [x] 2. Change `Apache Pinot (incubating)` -> `Apache Pinot` on website
- [x] 3. Change `Apache Pinot (incubating)` -> `Apache Pinot` on documentation
- [x] 4. Update the Apache release pipeline

**Comment by xiangfu0** [comment]
I will take care of the website update.

**Comment by xiangfu0** [comment]
PR for update pinot website: https://github.com/apache/pinot-site/pull/53/files

**Comment by xiangfu0** [comment]
done.

**Comment by suddendust** [comment]
I will take care of the documentation update.

**Comment by xiangfu0** [comment]
I feel we need to change the codebase first to remove all the incubating wording, then update the docs/website. There are multiple places referring to the directory names which contains incubating words.

**Comment by jerrinot** [comment]
a quick win: change the GitHub project description. It also says "Incubating": 
![image](https://user-images.githubusercontent.com/158619/146658098-ccfc6f46-2cc0-44f8-8798-177b661af6c3.png)

**Comment by xiangfu0** [comment]
> a quick win: change the GitHub project description. It also says "Incubating": ![image](https://user-images.githubusercontent.com/158619/146658098-ccfc6f46-2cc0-44f8-8798-177b661af6c3.png)

this is done by: https://github.com/apache/pinot/pull/7738
