### ISSUE TITLE
Support raw methods for PercentileTDigest and PercentileEst

### ISSUE THREAD

**Issue by lakshmanan-v** [apache/pinot#7212]
Add an aggregate function to offer raw data structures for PercentileTDigest(MergingDigest) and PercentileEst(QuantileDigest) functions. This will be 

This will be similar to raw HLL and ThetaSketch.

**Comment by suddendust** [comment]
I can pick this up if it's not urgent (I will need to read the theory behind these).

**Comment by suddendust** [comment]
@lakshmanan-v  @Jackie-Jiang I would need a bit more detail around the issue. What do you mean by "...offer raw data structures..."? Can you please elaborate upon the requirement a bit and if possible provide some references? Thanks.
