### ISSUE TITLE
Low level kafka consumer assumes string key

### ISSUE THREAD

**Issue by pjpringle** [apache/pinot#7239]
Low level Kafka consumer assumes string deserializer for the key. 

This causes exceptions if the kafka data is not keyed by a string.

Proposal to make the key deserializer class configurable.

Code link
https://www.github.com/apache/pinot/tree/master/pinot-plugins%2Fpinot-stream-ingestion%2Fpinot-kafka-2.0%2Fsrc%2Fmain%2Fjava%2Forg%2Fapache%2Fpinot%2Fplugin%2Fstream%2Fkafka20%2FKafkaPartitionLevelConnectionHandler.java

**Comment by npawar** [comment]
What kind of exception are you seeing? Is there a stack trace/log? I'm wondering why it is not getting read as a string automatically. I'm sure this is not the first time someone has tried to ingest a topic that used a non-string column as a key.

**Comment by pjpringle** [comment]
Potentially a different issue with confluent Kafka schema registry
properties which we have resolved.

The kafka serialization exception caused by 401 unauthorized by schema
registry went to the console log and is not present in the on disk log
files, this created some confusion.

Although still think it's worth changing the 2.0 kafka consumer code to use
byte[] key / serializer like 0.9 and to document the fact the the key is
not used and also the location for kafka logs.

**Comment by shreelakshmijoshi** [comment]
Hi @pjpringle !
I am a new open source contributor and would like to solve this issue, could you help me understand the issue better by providing some extra references ? 
Is this is issue open to contribute ?

**Comment by piyushchauhan** [comment]
++ @npawar we are putting long value as kafka key and it doesn't have any problem. It would be great if you could validate the problem and elaborate the issue with logs.

**Comment by pjpringle** [comment]
Actually no issue, will close. Although would be useful to have the option to store/map the kafka revord key in pinot.

**Comment by piyushchauhan** [comment]
@pjpringle But kafka key is the id of the primary key of the pinot table. So it is already being stored right?

**Comment by pjpringle** [comment]
No the key is not available inside pinot, hence why this config doesnt
matter. However the key does drive partitioning on kafka.

It would be good if we could define a key schema and access this data in
pinot.  This would make segment routing/pruning/primary key configuration
easier.
