### ISSUE TITLE
Removing ZKClient dependency from Pinot Client

### ISSUE THREAD

**Issue by mayankshriv** [apache/pinot#7256]
Currently, Pinot client uses ZK client to watch on list of available brokers to send the request to. While this works well to keep the live broker list up-to-date, the dependency on ZK connectivity may not be desirable. One way to eliminate this would be to:
- Use controller apis to get the list of brokers to query for a table.
- Use polling to keep the broker list up-to-date
- Additionally, also update broker list in case of errors (related to broker connectivity).

**Comment by xiangfu0** [comment]
Another issue documented in #7166 is about the broker address we are
publishing to client is for inter-Pinot cluster communications. It’s not
guaranteed that client side is within same network.
E.g. Pinot client outside k8s cluster doesn’t have access to broker exposed
through controller API.

**Comment by saurabhd336** [comment]
I'm working on the changes to support controller based broker selector in the client.
Initial PR: https://github.com/apache/pinot/pull/8467/files
@mayankshriv
