### ISSUE TITLE
Docker image to deploy?

### ISSUE THREAD

**Issue by PD666214** [apache/pinot#7261]

**Comment by xiangfu0** [comment]
https://hub.docker.com/layers/apachepinot/pinot/latest/images/sha256-ae26a48f6f3d7918d3311c132d2aee0dd2455eeefae4e8852438d7371a3c4a0b?context=repo

**Comment by xiangfu0** [comment]
Please refer to this doc for docker deployment: https://docs.pinot.apache.org/basics/getting-started/running-pinot-in-docker

And k8s: https://docs.pinot.apache.org/basics/getting-started/kubernetes-quickstart
