### ISSUE TITLE
Add noDowntime option to reset

### ISSUE THREAD

**Issue by npawar** [apache/pinot#7280]
Sometimes, reset API is called on a consuming segment, to make the consumption restart. This is quite desirable in case of schema evolution, where someone added a new column, and want to force the consuming segment to restart, so that the new values are seen in the consuming segment. While consumption can be restarted even by restarting the server that contains that segment, that is often more expensive (multiple tables, multiple consumers on that server) and hence folks don't like that option.
Calling a reset will take the segment to OFFLINE and back to ONLINE. If there are multiple replicas, all of them will get reset at once. This will cause downtime, even though we have replication. There is no way to make the reset happen once replica at a time.
A noDowntime option would be nice.

**Comment by npawar** [comment]
Another way to solve the same usecase, is an API to force commit (as suggested by @Jackie-Jiang )

**Comment by mcvsubbu** [comment]
If force commit will do, then we should do that. See Issue #6302

**Comment by sajjad-moradi** [comment]
ForceCommit endpoint - that was introduced in https://github.com/apache/pinot/pull/9197 - addresses the  requirement of this issue.
