### ISSUE TITLE
PinotAdminCommand throws exception 

### ISSUE THREAD

**Issue by mcvsubbu** [apache/pinot#7290]
2021/08/12 11:51:35.794 INFO [PinotAdministrator] [main] Usage: pinot-admin.sh <subCommand>
2021/08/12 11:51:35.794 INFO [PinotAdministrator] [main] Valid subCommands are:
2021/08/12 11:51:35.807 INFO [PinotAdministrator] [main] 	QuickStart	<Run Pinot QuickStart.>
2021/08/12 11:51:35.808 INFO [PinotAdministrator] [main] 	OperateClusterConfig	<Operate Pinot Cluster Config. Sample usage: `pinot-admin.sh OperateClusterConfig -operation DELETE -config pinot.broker.enable.query.limit.override`>
2021/08/12 11:51:35.809 INFO [PinotAdministrator] [main] 	GenerateData	<Generate random data as per the provided schema>
2021/08/12 11:51:35.810 INFO [PinotAdministrator] [main] 	LaunchDataIngestionJob	<Launch a data ingestion job.>
2021/08/12 11:51:35.811 INFO [PinotAdministrator] [main] 	CreateSegment	<Create pinot segments from the provided data files.>
2021/08/12 11:51:35.816 INFO [PinotAdministrator] [main] 	ImportData	<Insert data into Pinot cluster.>
2021/08/12 11:51:35.821 INFO [PinotAdministrator] [main] 	StartZookeeper	<Start the Zookeeper process at the specified port.>
2021/08/12 11:51:35.831 INFO [PinotAdministrator] [main] 	StartKafka	<Start Kafka at the specified port.>
2021/08/12 11:51:35.835 INFO [PinotAdministrator] [main] 	StreamAvroIntoKafka	<Stream the specified Avro file into a Kafka topic, which can be read by Pinot
by using org.apache.pinot.plugin.stream.kafka.KafkaJSONMessageDecoder as the
message decoder class name (stream.kafka.decoder.class.name).>
2021/08/12 11:51:35.838 INFO [PinotAdministrator] [main] 	StartController	<Start the Pinot Controller Process at the specified port.>
2021/08/12 11:51:35.839 INFO [PinotAdministrator] [main] 	StartBroker	<Start the Pinot Broker process at the specified port>
2021/08/12 11:51:35.841 INFO [PinotAdministrator] [main] 	StartServer	<Start the Pinot Server process at the specified port.>
2021/08/12 11:51:35.842 INFO [PinotAdministrator] [main] 	StartMinion	<Start the Pinot Minion process at the specified port>
2021/08/12 11:51:35.843 INFO [PinotAdministrator] [main] 	StartServiceManager	<Start the Pinot Service Process at the specified port.>
2021/08/12 11:51:35.844 INFO [PinotAdministrator] [main] 	AddTable	<Create a Pinot table>
2021/08/12 11:51:35.845 INFO [PinotAdministrator] [main] 	ChangeTableState	<Change the state (enable|disable|drop) of Pinot table>
2021/08/12 11:51:35.846 INFO [PinotAdministrator] [main] 	AddTenant	<Add tenant as per the specification provided.>
2021/08/12 11:51:35.847 INFO [PinotAdministrator] [main] 	AddSchema	<Add schema specified in the schema file to the controller>
2021/08/12 11:51:35.847 INFO [PinotAdministrator] [main] 	UpdateSchema	<Add schema specified in the schema file to the controller>
2021/08/12 11:51:35.848 INFO [PinotAdministrator] [main] 	UploadSegment	<Upload the Pinot segments.>
2021/08/12 11:51:35.849 INFO [PinotAdministrator] [main] 	PostQuery	<Query the uploaded Pinot segments.>
2021/08/12 11:51:35.850 INFO [PinotAdministrator] [main] 	StopProcess	<Stop the specified processes.>
2021/08/12 11:51:35.851 INFO [PinotAdministrator] [main] 	DeleteCluster	<Remove the Pinot Cluster from Helix.>
2021/08/12 11:51:35.854 INFO [PinotAdministrator] [main] 	ShowClusterInfo	<Show Pinot Cluster information.>
2021/08/12 11:51:35.855 INFO [PinotAdministrator] [main] 	AvroSchemaToPinotSchema	<Extracting Pinot schema file from Avro schema or data file.>
2021/08/12 11:51:35.856 INFO [PinotAdministrator] [main] 	JsonToPinotSchema	<Extracting Pinot schema file from JSON data file.>
2021/08/12 11:51:35.857 INFO [PinotAdministrator] [main] 	RebalanceTable	<Reassign instances and segments for a table.>
2021/08/12 11:51:35.857 INFO [PinotAdministrator] [main] 	ChangeNumReplicas	<Re-writes idealState to reflect the value of numReplicas in table config>
2021/08/12 11:51:35.858 INFO [PinotAdministrator] [main] 	ValidateConfig	<Validate configs on the specified Zookeeper.>
2021/08/12 11:51:35.859 INFO [PinotAdministrator] [main] 	VerifySegmentState	<Compares helix IdealState and ExternalView for specified table prefixes>
2021/08/12 11:51:35.859 INFO [PinotAdministrator] [main] 	ConvertPinotSegment	<Convert Pinot segments to another format such as AVRO/CSV/JSON.>
2021/08/12 11:51:35.861 INFO [PinotAdministrator] [main] 	MoveReplicaGroup	<Move complete set of segment replica from source servers to tagged servers in cluster>
2021/08/12 11:51:35.862 INFO [PinotAdministrator] [main] 	VerifyClusterState	<Verify cluster's state after shutting down several nodes randomly.>
2021/08/12 11:51:35.864 INFO [PinotAdministrator] [main] 	RealtimeProvisioningHelper	<Given the table config, partitions, retention and a sample completed segment for a realtime table to be setup, this tool will provide memory used by each host and an optimal segment size for various combinations of hours to consume and hosts. Instead of a completed segment, if schema with characteristics of data is provided, a segment will be generated and used for memory estimation.>
2021/08/12 11:51:35.865 INFO [PinotAdministrator] [main] 	MergeSegments	<Create the merged segment using concatenation>
2021/08/12 11:51:35.866 INFO [PinotAdministrator] [main] 	CheckOfflineSegmentIntervals	<Prints out offline segments with invalid time intervals>
2021/08/12 11:51:35.868 INFO [PinotAdministrator] [main] 	AnonymizeData	<Tool to anonymize a given Pinot table data while preserving data characteristics and query patterns>
2021/08/12 11:51:35.868 INFO [PinotAdministrator] [main] 	GitHubEventsQuickStart	<Runs the GitHubEventsQuickstart>
2021/08/12 11:51:35.868 INFO [PinotAdministrator] [main] 	StreamGitHubEvents	<Streams GitHubEvents into a Kafka topic>
2021/08/12 11:51:35.870 INFO [PinotAdministrator] [main] 	BootstrapTable	<Run Pinot Bootstrap Table.>
2021/08/12 11:51:35.872 INFO [PinotAdministrator] [main] 	SegmentProcessorFramework	<Runs the SegmentProcessorFramework>
2021/08/12 11:51:35.872 INFO [PinotAdministrator] [main] For other crud operations, please refer to ${ControllerAddress}/help.
Exception in thread "Thread-13" java.lang.NullPointerException
	at org.apache.pinot.tools.admin.command.StartServiceManagerCommand.cleanup(StartServiceManagerCommand.java:152)
	at org.apache.pinot.tools.AbstractBaseCommand$1.run(AbstractBaseCommand.java:34)

**Comment by Jackie-Jiang** [comment]
@xiangfu0 ^^
We can add a `null` check to avoid the NPE, but trying to understand why `_pinotServiceManager` is `null` in the first place.
@mcvsubbu Can you please provide more context on how to reproduce the issue?

**Comment by mcvsubbu** [comment]
Just run admin command with --help

**Comment by xiangfu0** [comment]
sure I will take a look
