### ISSUE TITLE
Documentation broken script links to gitbook from enterprise environments

### ISSUE THREAD

**Issue by pjpringle** [apache/pinot#7303]
Documentation is broken inside enterprises which block gitbook.com

For example

https://docs.pinot.apache.org/basics/getting-started/running-pinot-locally

All tabs are broken I.e. clicking download the release tab doesn't update to display the tab. 

May may sense to host the scripts and images on the same domain as the documentation.

**Comment by kishoreg** [comment]
We were not able to do that unfortunately.. ASF did not allow it.

**Comment by pjpringle** [comment]
Docs seem to work better these days.  Closing.
