### ISSUE TITLE
ZK PUT API doesn't support large payload

### ISSUE THREAD

**Issue by xiangfu0** [apache/pinot#7305]
Seems that we set the payload as a query param in PUT API, which makes it part or URL. The large payload will easily exceed the URL length limit, which prevents updating a large payload.

@mayankshriv @kishoreg

**Comment by Jackie-Jiang** [comment]
It should be a payload instead of a query param.
We can make `data` optional, and add a payload to this API. If payload is not available, use the `data` for backward-compatibility

**Comment by xiangfu0** [comment]
yes, we can make the backend change then fix the UI.
@shahsank3t

**Comment by shahsank3t** [comment]
Yes, I can make the UI side changes once we have backend changes done.

**Comment by galalen** [comment]
I would love to work on it, please point me to the class

**Comment by Jackie-Jiang** [comment]
@galalen Thanks for volunteering. Please take a look at `ZookeeperResource.java` and add payload to the `putData()` method
