### ISSUE TITLE
LAST aggregate function support

### ISSUE THREAD

**Issue by lakshmanan-v** [apache/pinot#7315]
In some of the tie bucket group by situations, having an aggregation function to get the last or latest value would be great.

**Comment by kishoreg** [comment]
+1 

someone else asked for the first and last functions recently on slack as well. Do you want to take this up?

**Comment by lakshmanan-v** [comment]
> +1
> 
> someone else asked for the first and last functions recently on slack as well. Do you want to take this up?

Would love to contribute. Currently working on these two tasks ([7212](https://github.com/apache/pinot/issues/7212)  & [7014](https://github.com/apache/pinot/issues/7014)) to add aggregate functions to support upgraded HLL and Raw percentile (EST and TDigest) functions. Will get to this after wrapping them up.

**Comment by pjpringle** [comment]
any updates on this one,  I can give it a go.

**Comment by lakshmanan-v** [comment]
> any updates on this one, I can give it a go.

@weixiangsun is working with @Jackie-Jiang on this already. PR would be out soon.

**Comment by Jackie-Jiang** [comment]
Added the support in #7584
