### ISSUE TITLE
Pinot UI doesn't set correct Auth header for queries

### ISSUE THREAD

**Issue by xiangfu0** [apache/pinot#7323]
Try with 0.8.0 release(https://downloads.apache.org/pinot/apache-pinot-0.8.0/apache-pinot-0.8.0-bin.tar.gz) quickstart:

```
bin/quick-start-auth.sh
```

Once it's up, go to `http://localhost:9000/`
Try out user credential: `user/secret`
Then click on table name `baseballStats`:
![image](https://user-images.githubusercontent.com/1202120/129957570-c0f60360-78c7-442a-92aa-efef62014ddb.png)
This also happens when click `RUN QUERY` button.

Schema call has the `Authorization` header, but seems not verified:
![image](https://user-images.githubusercontent.com/1202120/129958307-62c24980-d1b7-49b2-97f5-155630d057de.png)

Query call has no header:
![image](https://user-images.githubusercontent.com/1202120/129958390-66a62a4b-bb6c-42fc-a981-3682ab12c512.png)

Tried with admin permission: `admin/verysecret`
Then click on table name `baseballStats`:
Schema call is ok, but the query is still missing auth header.
![image](https://user-images.githubusercontent.com/1202120/129958584-d3ca2822-0731-4f97-83f4-5619e460d1f2.png)

Schema call has the `Authorization` header, and verified:
![image](https://user-images.githubusercontent.com/1202120/129958615-6c15ecbf-f8a2-4b55-a83b-c663abab8acf.png)

Query call has no header:
![image](https://user-images.githubusercontent.com/1202120/129958669-58f3d217-4d90-41ac-9d8d-35118951719f.png)

**Comment by xiangfu0** [comment]
@shahsank3t

**Comment by xiangfu0** [comment]
@apucher

**Comment by shahsank3t** [comment]
@xiangfu0 
`/sql` call issue has been fixed on master branch by @joshigaurava in https://github.com/apache/pinot/pull/7230
We need to cherry-pick in 0.8.0 release or will be part of the next release.

`/schema` call issue with user credentials that doesn't verify the user needs to be checked by @apucher.

**Comment by xiangfu0** [comment]
I fixed the user permission validation for /schema calls
So it should be ok now.
Thanks @shahsank3t !
