### ISSUE TITLE
Metadata push does not honor controllers configured dataDir to store pushed segments

### ISSUE THREAD

**Issue by ksnijjer** [apache/pinot#7328]
As part of offline ingestion job's yaml config, you need to define a **outputDir** which in theory can be any S3 bucket location that the compute cluster(running the ingestion job) would have access to. Now when we do a segment metadata push(for e.g `jobType: SegmentCreationAndMetadataPush` )as part of the job execution we list all files in this output directory/download segment tar.gz and extract metadata. This metadata and other related information is then sent to the controller, which updates the ZK metadata for the table/segment and subsequently pushes the segment download URI to Pinot Server which actually downloads these files to the local disk. 

There are few issues with current design:

1)Since outputDir path can be a different location it can bypass the controller data dir path configured for deep storage
2)Currently there is no data copied from outputDIR to controller dataDir, if for any reason output data bucket is purged/deleted then **Pinot servers will have data loss**
3)Additionally user/Pinot admin needs to ensure that Pinot cluster has access to the S3 output bucket, in environments where for e.g IAM role/user is used to access S3(or any other object store) by Pinot server, there is a strong possibility that access is limited to specific locations/buckets only.

Pros in current design:
-Allows clean separation between ETL output vs. controller data dir, preventing issues like partial data generated due to job failures etc. being propagated to end user queries.

Can we have some background task or processing on controller end which auto triggers copy of data to Deep store, when there is a difference between segment download URI vs. configured deep store UI ? In addition if for any reason Controller/server doesn't have required access to the download location, bubble it up as an error in the Pinot Console. Doing these would address 1,2,3 above and also retain existing separation between ingestion job and data storage.

**Comment by mayankshriv** [comment]
+1, we need to make this more user friendly. Apart from the issues mentioned above, it is also confusing to the users who are trying to push to multiple tables, as to which outDir should correspond to the controller's dataDir (recently asked in the slack community). Currently it is optimized for push-time.

One proposal could be as follows:
- For general case, the controller trigger a background copy of data from outDir to under controller's dataDir/<tableName>.
- For advanced users who know what they are doing and have the right permissions, the outDir (<tableName>) can directly be under the controller's dataDir. This would avoid any redundant copy and make the data push fast.

**Comment by mayankshriv** [comment]
cc @yupeng9

**Comment by ksnijjer** [comment]
@npawar FYI ^
