### ISSUE TITLE
Allow reloading segments with multiple threads

### ISSUE THREAD

**Issue by Jackie-Jiang** [apache/pinot#7338]
Currently when reloading the segments for a table, the segments are reloaded sequentially (single threaded). This is intentional because segment reload usually needs to generate new indexes on the fly, which can consume resources while server still need to serve queries.
In certain cases, users might want to use multiple threads to reload the segments, and we can add an option of parallelism in the reload message and make it default to 1.
Note that there is another semaphore to control the parallelism, and we should still comply with the semaphore.

The logic resides in `SegmentMessageHandlerFactory` class

**Comment by mcvsubbu** [comment]
Another reason this is reloaded one at a time is because the memory needed is doubled per segment. Both segments are in memory while query from the old segment is drained and new queries are routed to the new segment. We have often seen query performance slip SLAs during segment reload on a host. 

The number of parallel reload is a helix cluster-wide setting, however. I don't think there is any need to touch the message hander factory?

**Comment by Jackie-Jiang** [comment]
@mcvsubbu We have a `maxParallelRefreshThreads` configured within the `SegmentMessageHandlerFactory` to guard on the issue you described, and that's the reason why I mentioned we should still follow that config even reloading using multiple threads.

The table reload is modeled as one helix message, so only one message will be sent for multiple segments. The helix config won't enable parallel reloading

**Comment by mcvsubbu** [comment]
For some reason I thought there is a helix config that sets the number of parallel threads in the server. I remember we configured something like that for our internal cluster to support faster time for servers to come up. But then I cannot find that now in the cluster setting

**Comment by Jackie-Jiang** [comment]
@mcvsubbu It should be part of the cluster config in ZK. By default the server uses 40 threads to handle the messages.

**Comment by shreelakshmijoshi** [comment]
Hi @Jackie-Jiang !
I am a new open source contributor and would like to solve this issue, could you help me understand the issue better by providing some extra references ? 
Is this is issue open to contribute ?

**Comment by Jackie-Jiang** [comment]
@shreelakshmijoshi Yes, this issue is open to contribute. Pinot allows reloading segments of a given table by sending a custom Helix message (see `SegmentReloadMessage` class). We want to add an extra parameter to it to control the parallelism of the reload. The message is handled within the `SegmentMessageHandlerFactory` class

**Comment by suddendust** [comment]
@Jackie-Jiang Have raised a preliminary [PR](https://github.com/apache/pinot/pull/7893) for this. One question - Will it be a good idea to limit this factor? If the parallelism is too high, then there might be a severe resource crunch.

**Comment by Jackie-Jiang** [comment]
@suddendust Thanks for taking this up. Instead of allowing user to specify the parallelism through the query parameters, I would suggest passing the `_refreshThreadSemaphore` into the `reloadAllSegments` so we won't bring down the server

**Comment by suddendust** [comment]
@Jackie-Jiang Reload already piggybacks on the refresh semaphore to control the number of parallel `SegmentReloadMessage` it is processing:

```
      HelixTaskResult helixTaskResult = new HelixTaskResult();
      _logger.info("Handling message: {}", _message);
      try {
        if (_segmentName.equals("")) {
          acquireSema("ALL", _logger);
          // NOTE: the method aborts if any segment reload encounters an unhandled exception,
          // and can lead to inconsistent state across segments
          _instanceDataManager.reloadAllSegments(_tableNameWithType, _forceDownload, _reloadParallelism);
        } else {
          // Reload one segment
          acquireSema(_segmentName, _logger);
          _instanceDataManager.reloadSegment(_tableNameWithType, _segmentName, _forceDownload);
        }
```

So my understanding is that we're trying to parallelise the actual reloading of segments in `reloadAllSegments` which currently is sequential. As you proposed, the parallelism factor can be a part of the `SegmentReloadMessage` but how will the user configure it? Are we planning to add a new configuration?

**Comment by Jackie-Jiang** [comment]
@suddendust Currently we only acquire one semaphore for `reloadAllSegments()` because internally it will load segments in sequential. When we make it using multiple threads, we should also acquire more semaphores.

`reload` and `refresh` are essentially doing the same thing, where we need to keep 2 copies of segment loaded at the same time, so we should use the same semaphore to control both of them to avoid taking too much resource

**Comment by suddendust** [comment]
@Jackie-Jiang Shouldn't max reload threads be a server config instead of a param in the segment reload message, much like`max.parallel.refresh.threads`? So essentially the factory uses the same number of max. threads to handle every reload message.

Also, "By default the server uses 40 threads to handle the messages." - I couldn't find any doc for this anywhere, could you point me to it? Thanks!

**Comment by Jackie-Jiang** [comment]
@Jackie-Jiang I was suggesting to directly use the `_refreshThreadSemaphore` for the reload because `reload` and `refresh` are essentially the same, and we should not have 2 different threshold for them.

The 40 threads is a Helix default setting (didn't find the documentation, but the value is in `HelixTaskExecutor.DEFAULT_PARALLEL_TASKS`), which is not really related to this discussion.

**Comment by suddendust** [comment]
@Jackie-Jiang This was merged, can we close the issue?

**Comment by Jackie-Jiang** [comment]
@suddendust Thanks for the contribution! Closing the ticket
