### ISSUE TITLE
Pinot console UI keeps on spinning if there is a syntax error

### ISSUE THREAD

**Issue by ksnijjer** [apache/pinot#7344]
Firing a query with syntax error provides no feedback to the end user and UI continues to show the spinning icon while underlying API has already returned an error response.
For e.g running something like `select * from <tablename>;` generates below error response from Parser

`Uncaught (in promise) 
Object { name: "SyntaxError", message: "Unexpected 'P'", at: 1, text: "ProcessingException(errorCode:150, message:PQLParsingError:\norg.apache.pinot.sql.parsers.SqlCompilationException: Caught exception while parsing query: select * from tableA limit 10;\n\tat org.apache.pinot.sql.parsers.CalciteSqlParser.compileCalciteSqlToPinotQuery(CalciteSqlParser.java:324)\n\tat org.apache.pinot.sql.parsers.CalciteSqlParser.compileToPinotQuery(CalciteSqlParser.java:108)\n\tat org.apache.pinot.sql.parsers.CalciteSqlCompiler.compileToBrokerRequest(CalciteSqlCompiler.java:35)\n\tat org.apache.pinot.controller.api.resources.PinotQueryResource.getQueryResponse(PinotQueryResource.java:166)\n\tat org.apache.pinot.controller.api.resources.PinotQueryResource.handlePostSql(PinotQueryResource.java:137)\n\tat jdk.internal.reflect.GeneratedMethodAccessor406.invoke(Unknown Source)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:566)\n\tat org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)\n\tat org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)\n\tat org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)\n\tat org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219)\n\tat org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)\n\tat org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469))" }`

but UI doesn't update.
​
@shahsank3t

**Comment by mayankshriv** [comment]
Yes, this seems to be a common issue recently recently. User gets no feedback that the query failed due to syntax error, and they keep waiting for the spinning wheel in the UI assuming the query is running.

**Comment by Jackie-Jiang** [comment]
Duplicate with #7161. Can you please try with the latest master? The UI fix #7165 has been merged

**Comment by mayankshriv** [comment]
Tried a simple query with latest master `select * from <table>;` (note semi-colon), and seems to work. @ksnijjer please also verify at your end.

**Comment by ksnijjer** [comment]
@mayankshriv I don't have a setup to verify on my end but if you tested then we should be good to go. Marking this one as resolved.
