### ISSUE TITLE
Non quoted boolean complex identifier is handling correct?

### ISSUE THREAD

**Issue by xiangfu0** [apache/pinot#7345]
Tried
`bin/quick-start-complex-type-handling-offline.sh`
```
select id, "payload.commits.distinct" from githubEvents limit 10
```
works
but not
```
select id, payload.commits.distinct from githubEvents limit 10
```

Also checked that both 
```select id, payload.commits.author.name, payload.commits.author.email from githubEvents limit 10```
 and
```select id, "payload.commits.author.name", "payload.commits.author.email" from githubEvents limit 10```
 work.
![image](https://user-images.githubusercontent.com/1202120/130285872-088bd12c-8a27-484b-8494-a40b599b8ed5.png)

is this specific to boolean type or because of that `distinct` is a keyword?

**Comment by Jackie-Jiang** [comment]
What error did you get? Since `select id, "payload.commits.distinct" from githubEvents limit 10` work, it should be caused by the `distinct` keyword.
