### ISSUE TITLE
Atomic Batch Ingestion: Add an api to replace multiple segments

### ISSUE THREAD

**Issue by elonazoulay** [apache/pinot#7390]
When uploading offline segments it would be useful to have an api that can take a list of old segments and replace them with a list of new segments. This can be useful for lambda architecture where data for an entire day/hour is replaced atomically.

**Comment by Jackie-Jiang** [comment]
This can be done with the segment lineage feature contributed by @snleee. Do we have some user doc for this @snleee?

**Comment by snleee** [comment]
Added #7813. Let's move the discussion there.
