### ISSUE TITLE
[k8s] Remove chart from matchLabels in helper templates

### ISSUE THREAD

**Issue by ddcprg** [apache/pinot#7441]
This line will be prevent doing upgrades of the StatfulSet when a new version needs to be deployed

https://github.com/apache/pinot/blob/master/kubernetes/helm/pinot/templates/_helpers.tpl#L58

Kubernetes will fail with error

```
spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
```

**Comment by ivanvy-wix** [comment]
I think this issues refers to this line: https://github.com/apache/pinot/blob/bb2519494a15a3125dd509286d60ffd124f91c37/kubernetes/helm/pinot/templates/_helpers.tpl#L58

The line has been removed in #7177 (with a way to keep compatibility with already deployed charts) and so the issue can be closed?
