### ISSUE TITLE
Consider migrating joda-time to `java.time`

### ISSUE THREAD

**Issue by richardstartin** [apache/pinot#7499]
Joda-time was superseded by `java.time` when JDK8 was released and there is a straightforward migration path.

**Comment by ddcprg** [comment]
@richardstartin  @xiangfu0 I might be able to look into this one if no one else has picked it up

**Comment by richardstartin** [comment]
@ddcprg that would be awesome! As part of the effort, I would suggest building some unit testing around `DateTimeFunctions` to be sure there aren't any regressions. 

There is a blog post from the author of both libraries on performing the migration (from 2014) [here](https://blog.joda.org/2014/11/converting-from-joda-time-to-javatime.html). Don't miss the comment here:

> One more "odds and ends" which is important to be aware of:
>
> the Joda DateTimeFormat (http://www.joda.org/joda-time/apidocs/org/joda/time/format/DateTimeFormat.html) uses "Y" for "year of era", and "y" for "year". The Java 8 DateTimeFormatter (https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html) uses "Y" for "week based year", and "y" for "year of era". If you're currently using a Joda DateTimeFormat object with "Y" as part of the pattern, this may introduce an off-by-one error (https://stackoverflow.com/questions/26431882/difference-between-year-of-era-and-week-based-year) if you change it to a Java 8 DateTimeFormatter without also replacing "Y" with "y" in the pattern string.

**Comment by ddcprg** [comment]
Cool, Thank you for the suggestions!

**Comment by camac** [comment]
@ddcprg Excellent! we are hoping to publish these Joda-Time to java.time migration recipes tomorrow. After they are published I can give you a demo on how to use them? I'm in Sydney, Australia so if the time zone doesn't suit I can do a blog post / video demonstrating how to use Sensei and these recipes to perform a large part of the migration.

**Comment by camac** [comment]
> @ddcprg no worries! I'm working on the blog post this week. I'll post here when it's published

For anyone interested here is the aforementioned blog post which gives a bit of an overview of the kinds of Joda-Time to java.time transformations we are covering in our Sensei migration cookbook for Joda-time to java.time
: https://www.securecodewarrior.com/blog/migrating-joda-time-to-java-time

We have quite a few more recipes to publish over the next month so the cookbook should start to cover more of the Joda-Time classes.

Classes like `org.joda.time.Interval` (which are not included in java.time) will be covered in a separate cookbook for people who are happy to include [Threeten-extra](https://www.threeten.org/threeten-extra/) as a new dependency (in place of Joda-Time)

**Comment by richardstartin** [comment]
On #8397 I noticed that java.time can be quite a lot slower than JODA time, so this migration would be difficult to justify.
