### ISSUE TITLE
Querying JSON-type columns that are arrays at the top level doesn't work with dot notation.

### ISSUE THREAD

**Issue by dd-willgan** [apache/pinot#7504]
We are using Pinot 0.8.0 and have a JSON-type column with a JsonIndex on it. The top-level of the JSON is an array, and from https://docs.pinot.apache.org/users/user-guide-query/json-queries, it seems like we should be able to query it like
```
select feedback_issues_json[0] from test_table limit 10
```
```
select feedback_issues_json[0].value from test_table limit 10
```
but this doesn't return any rows. From the broker response it seems like `feedback_issues_json[0]` is being interpreted as the column name.

cc: @Jackie-Jiang

**Comment by Jackie-Jiang** [comment]
@amrishlal Could you please take a look?

**Comment by amrishlal** [comment]
I have created a PR to fix this issue. Please see #7511. Also, it seems like a similar fix is needed in `JsonIndex / JSON_MATCH` as well to allow for running queries such as:

```
SELECT *
  FROM testTable
WHERE JSON_MATCH(jsonColumn, '\"$.[2]\" IS NOT NULL') AND JSON_MATCH(jsonColumn, '\"$.[2]\" = ''test''')
```

I am assuming that you can take a look at `JsonIndex / JSON_MATCH` changes?

**Comment by Jackie-Jiang** [comment]
@amrishlal Thanks for working on this issue
The `JSON_MATCH` should already support it, and the correct syntax is `JSON_MATCH(jsonColumn, '"$[2]" IS NOT NULL')` (No escape for double quote & no `.` for array access)
