### ISSUE TITLE
FILTER Clause Support

### ISSUE THREAD

**Issue by atris** [apache/pinot#7519]
FILTER clause (SELECT COUNT(*) FILTER (WHERE foo > bar) FROM fooBar) allows complex reports to be generated efficiently without recomputation of the core predicate and rescans of the original data set.

https://docs.google.com/document/d/1qJzG1CmyVZpLN6rdI8V0zUWEaIjQ86hDL9XwrcPKcTs/edit?usp=sharing

**Comment by Jackie-Jiang** [comment]
Reference to the query syntax: https://modern-sql.com/feature/filter
Postgres supports it: https://medium.com/little-programming-joys/the-filter-clause-in-postgres-9-4-3dd327d3c852

**Comment by Jackie-Jiang** [comment]
The aggregation only support is merged #7916

We should support group-by as the next step

**Comment by egalpin** [comment]
Is there a known path/existing plan for how to implement group-by support? Seems interesting to work on if it were Pinot-dev-beginner friendly

**Comment by atris** [comment]
I am currently working on a PR for the same (Side note - it is not a
beginner friendly PR)

**Comment by egalpin** [comment]
@atris Any update on the progress of a PR to support GROUP BY?  Would be a very exciting feature to see 😊

**Comment by egalpin** [comment]
I wanted to mention that I'm currently exploring/investigating GROUP BY support with FILTER expressions.  As best as I can tell so far, GroupByPlanNode will need to have similar modifications as those made to AggregationPlanNode in @atris [original PR](https://github.com/apache/pinot/pull/7916/files#diff-83f495afef4b7f71270317579d50f0e3be8f773c6cbc61b54041cdf618854bdb) (plus all implicated changes).  I realize it's been advised that this is not a beginner-friendly PR but support for FILTER + GROUP BY will be high impact for my use of Pinot, so it's worth a shot.

I welcome any collaboration!
