### ISSUE TITLE
Sorting tables by number of segments is broken

### ISSUE THREAD

**Issue by hristo-stripe** [apache/pinot#7539]
The Controller UI does not sort the list of tables properly by the column `Number of Segments`.

**Comment by Jackie-Jiang** [comment]
@hristo-stripe Can you please share more context on the ask here? Are you suggesting adding a feature to sort the tables within the cluster manager UI?

**Comment by shahsank3t** [comment]
@Jackie-Jiang Fixed this issue and create a PR: https://github.com/apache/pinot/pull/7564
