### ISSUE TITLE
Column alias with same name as column causes pinot to hang

### ISSUE THREAD

**Issue by elonazoulay** [apache/pinot#7545]
If you have a function on a column and then alias that to the same column name pinot hangs.
To reproduce start the quick start batch and run the following query:
```
select cast(runs as long) as runs from baseballStats limit 10
```

This query works:
```
select cast(runs as long) as runs2 from baseballStats limit 10
```

**Comment by SandishKumarHN** [comment]
working on it

**Comment by SandishKumarHN** [comment]
this issue is fixed as part of this PR https://github.com/apache/pinot/pull/7576/, just verified it.

**Comment by Jackie-Jiang** [comment]
@xiangfu0 @elonazoulay Can you please verify the fix and close the issue if the issue is fixed?

**Comment by elonazoulay** [comment]
Apologies for the delay. This is fixed! Thanks @SandishKumarHN , @Jackie-Jiang @xiangfu0 !
