### ISSUE TITLE
Throw exception when queries containing non-existence column

### ISSUE THREAD

**Issue by xiangfu0** [apache/pinot#7577]
Pinot doesn't give error when users' queries contain non-existence column in schema, but give empty result.
It's also misleading when users aggregation query is bad but Pinot gives 0.

For certain queries, Pinot should just throw exceptions with messages like `Columns [A, B, C] don't exist in schema of table myTable`, instead of giving empty results.

**Comment by xiangfu0** [comment]
@yupeng9 @Jackie-Jiang

**Comment by Jackie-Jiang** [comment]
It's for historic reason, and we use DataSchemaSegmentPruner to keep the old behavior. We don't force schema for tables, and it is possible that the table consists of segments of different schema. Once we force the schema (which we should do), we can always reject the bad queries on broker side and remove the pruner.
