### ISSUE TITLE
Can avro data be transformed from hdfs path?

### ISSUE THREAD

**Issue by xuyang2** [apache/pinot#76]
According to [wiki/How-To-Use-Pinot](https://github.com/linkedin/pinot/wiki/How-To-Use-Pinot) 

Setting up the Hadoop workflow:

```
hadoop jar pinot-hadoop-0.016.jar SegmentCreation job.properties 
```

the `path.to.input` and `path.to.input` both are local path.

I think it will be helpful if hdfs path is supported.

**Comment by sbourke** [comment]
👍
