### ISSUE TITLE
Support NOT operator

### ISSUE THREAD

**Issue by ashishkf** [apache/pinot#7701]
Filing this issue based on slack discussion with @Jackie-Jiang.

Pinot does not support REGEXP_NOT_LIKE - w/o NOT operator it is hard to write queries that filter out rows that match a given REGEXP.

**Comment by atris** [comment]
We should not target specific operators for NOT -- rather, have a generic NOT operator which can apply the inverse predicate.

@Jackie-Jiang Does that make sense?

**Comment by Jackie-Jiang** [comment]
@atris Yes. I think the purpose of this issue is to add the generic NOT operator (similar to AND/OR). The lack of REGEXP_NOT_LIKE is the trigger of the issue.

**Comment by atris** [comment]
Ack. Shall I take a shot at this?

**Comment by mcvsubbu** [comment]
With support for text index, does it make sense for adding more features to the regexp functionality?

**Comment by atris** [comment]
I don't think this is specific to regexp indices

**Comment by mcvsubbu** [comment]
> I don't think this is specific to regexp indices

Ah ok

**Comment by atris** [comment]
JFYI, I will be working on this

**Comment by ashishkf** [comment]
> JFYI, I will be working on this

Any timeline for this?

**Comment by atris** [comment]
https://github.com/apache/pinot/pull/8148
