### ISSUE TITLE
Don't throw exception when query ends with semicolon

### ISSUE THREAD

**Issue by xiangfu0** [apache/pinot#7713]
Semicolon is the standard way to separate each SQL statement in database systems that allow more than one SQL statement to be executed in the same call to the server.

Though Pinot doesn't support multiple statements right now, we shouldn't throw exception when query ends with semicolon.

**Comment by jadireddi** [comment]
Would like to pick up this ticket.

**Comment by jerrinot** [comment]
this appears to be fixed by https://github.com/apache/pinot/pull/7861
