### ISSUE TITLE
Ignore query option from the commented out queries

### ISSUE THREAD

**Issue by Jackie-Jiang** [apache/pinot#7714]
Currently query option is processed as a regex (see `CalciteSqlParser.java` for details). This behavior will cause options being picked up from commented out queries. E.g.

```
SELECT * FROM table
-- SELECT * FROM table OPTION(...)
```

To fix this issue, we can consider switching to the standard SQL option syntax supported by Calcite

**Comment by kriti-sc** [comment]
@Jackie-Jiang added a possible fix. Introduced a regex for detecting commented-out queries. If a commented-out query is detected, the regex matching for query options is bypassed.

**Comment by kriti-sc** [comment]
>we can consider switching to the standard SQL option syntax supported by Calcite

I tried looking this up but seems to me that specifying query options is not a part of the ANSI SQL standard, they differ on a vendor to vendor basis.

There is also this comment in the code: https://github.com/apache/pinot/blob/9a61b491da01afa23d5788dd42a6ee579bcb118e/pinot-common/src/main/java/org/apache/pinot/sql/parsers/CalciteSqlParser.java#L106
