### ISSUE TITLE
Make broker segment unavailable exception configurable on Pinot Java client

### ISSUE THREAD

**Issue by dang-stripe** [apache/pinot#7770]
We're currently using the pinot java client for queries. With the introduction of https://github.com/apache/pinot/pull/7397, we're seeing more query exceptions since the java client currently raises an exception when there are any exceptions in the response: https://github.com/apache/pinot/blob/6611ff82f46ea837e6bd8edefd46ccc16d4e2002/pinot-clients/pinot-java-client/src/main/java/org/apache/pinot/client/Connection.java#L126-L128

Can we make this behavior configurable on the client?

**Comment by Jackie-Jiang** [comment]
2 options I can think of:
1. Add a flag to not fail the query, but log the exceptions as response metadata
2. Configure certain error codes to be ignored

**Comment by Jackie-Jiang** [comment]
@xiangfu0 ^^

**Comment by dang-stripe** [comment]
@Jackie-Jiang @xiangfu0 I think we have a preference for option 1 since it'll give us more control over what consistency guarantees we need which may very per query.

**Comment by xiangfu0** [comment]
Agreed, here we should provide some options for client side to config when to fail and how the exceptions are thrown.

**Comment by dang-stripe** [comment]
Thanks for addressing this! The fix is much appreciated.
