### ISSUE TITLE
JDBC client : Headers should be passed in PinotControllerTransport while creating instance of PinotConnetion 

### ISSUE THREAD

**Issue by kautshukla** [apache/pinot#7773]
https://github.com/apache/pinot/blob/d1606cd0f3877c1a8ec08255d003ef104a94c500/pinot-clients/pinot-jdbc-client/src/main/java/org/apache/pinot/client/PinotDriver.java#L71

Prerequisite: https://github.com/apache/pinot/blob/d1606cd0f3877c1a8ec08255d003ef104a94c500/pinot-clients/pinot-jdbc-client/src/main/java/org/apache/pinot/client/PinotDriver.java#L60 : headers map is not empty {JDBC with headers for Auth enabled client}

As of now:
              return new PinotConnection(controllerUrl, pinotClientTransport, tenant);

It should be:
             if(!headers.isEmpty)
                 return new PinotConnection(controllerUrl, pinotClientTransport, tenant, new PinotControllerTransport(headers));
             return new PinotConnection(controllerUrl, pinotClientTransport, tenant);

**Comment by xiangfu0** [comment]
0.9.0 is already cut and about to release, we may include this in 0.10.0 release.

**Comment by xiangfu0** [comment]
@kautshukla  Please file a PR for the change  :)
Thanks!

**Comment by kautshukla** [comment]
> 
@xiangfu0 : Already raised it. 

https://github.com/apache/pinot/pull/7774
