### ISSUE TITLE
/query/sql silently returns when all servers are down

### ISSUE THREAD

**Issue by bowen-stripe** [apache/pinot#7811]
Problem Statement:
Need a reliable way to tell if query result is valid to use when all servers are down.

Repro steps:
1. Take down all servers (I did "svc -d /etc/service/pinot-server")
2. Execute a query via broker ("select * from MyTable limit 10" via /query/sql)

Expected Results:
HTTP response has a non-200 status code, or "exceptions" field in response content shows error message about no server available.

Actual Results:
HTTP response status code = 200
Response:
{"exceptions":[],"numServersQueried":0,"numServersResponded":0,"numSegmentsQueried":0,"numSegmentsProcessed":0,"numSegmentsMatched":0,"numConsumingSegmentsQueried":0,"numDocsScanned":0,"numEntriesScannedInFilter":0,"numEntriesScannedPostFilter":0,"numGroupsLimitReached":false,"totalDocs":0,"timeUsedMs":0,"offlineThreadCpuTimeNs":0,"realtimeThreadCpuTimeNs":0,"segmentStatistics":[],"traceInfo":{},"numRowsResultSet":0,"minConsumingFreshnessTimeMs":0}

Questions:
I see in this case, "resultTable" is not present and "numServersQueried" is 0. Are those the recommended way to tell is query result is valid? Or do we think some more explicit way (status code ideally?) should be implemented?

**Comment by Jackie-Jiang** [comment]
This issue should be fixed by #7397 under the condition `numUnavailableSegments != 0`

**Comment by bowen-stripe** [comment]
Ah, that should be sufficient. Thanks!
