### ISSUE TITLE
Upgrade Kafka Lib to 2.4+

### ISSUE THREAD

**Issue by mapshen** [apache/pinot#7834]
Currently, Pinot is built using 2.0 by default. One feature we are looking at with 2.4+ is the capability to consume from follower replicas of a topic instead of the leader one. Are we considering an upgrade?

**Comment by xiangfu0** [comment]
Thanks for bringing this up!

Just wanna check the compatibility of using Kafka 2.4 consumer to consume Kafka broker from 2.0+.

If things are fine, we can safely just bump up the version number in pom file.

**Comment by xiangfu0** [comment]
From this wiki: https://cwiki.apache.org/confluence/display/KAFKA/Compatibility+Matrix

Seems that we can safely upgrade kafka consumer to consume older broker verisons.

**Comment by xiangfu0** [comment]
Do you want to file a PR to test the version upgrade?
https://github.com/apache/pinot/blob/master/pinot-plugins/pinot-stream-ingestion/pinot-kafka-2.0/pom.xml
