### ISSUE TITLE
Add error messages on the UI

### ISSUE THREAD

**Issue by Sangarshanan** [apache/pinot#7914]
Currently making any bad updates i,e backward-incompatible schema changes just returns an error
![image](https://user-images.githubusercontent.com/21971847/146323787-0df2d8c4-97bd-4692-b6d6-221c26ba2045.png)
An error clear message here instead would help a lot

**Comment by Jackie-Jiang** [comment]
@jadami10 Do you want to help with this UI enhancement?

**Comment by jadami10** [comment]
yes! I can help here

**Comment by jadami10** [comment]
@Sangarshanan, can you tell me exactly what you were trying to do? Trying to make a bad schema change locally gives me
![image](https://user-images.githubusercontent.com/4760722/146492444-b9402399-76e1-4196-945c-585aecc2ce3b.png)

**Comment by jadami10** [comment]
also
![image](https://user-images.githubusercontent.com/4760722/146492479-53c72954-7091-47dc-8006-ec5a64e33541.png)

**Comment by Sangarshanan** [comment]
You can reproduce this by updating the Datatype of `yearID` in the example `baseballStats` dataset from `INT` to `LONG`, not sure how you get the Backward incompatible schema error on your side tho I am on version `0.9.2`

**Comment by jadami10** [comment]
how are you running pinot? The code to block these updates was added in April in #6737 and the code to surface the errors in the UI has been even longer since October 2020 #6198.

I am running the quickstart locally and 0.9.0 in production and both show the error.

**Comment by Sangarshanan** [comment]
I am running Pinot with quickstart using this command https://docs.pinot.apache.org/basics/getting-started/running-pinot-locally#quick-start

**Comment by jadami10** [comment]
oh interesting... when i run it from the downloaded release, the responses all have `_error` and `_code`
![image](https://user-images.githubusercontent.com/4760722/146615583-197e7cfa-fd3f-4a0f-ad13-2a5879418894.png)
but running it from source I get
![image](https://user-images.githubusercontent.com/4760722/146615610-864500ca-df28-4948-aa19-95a935685074.png)

@Jackie-Jiang, I can modify the frontend to handle this, but I can't seem to find why jersey or jax-rs is returning _code or _error when run from release like this. Do you have any insight?

**Comment by Jackie-Jiang** [comment]
@jadami10 @Sangarshanan  This issue is fixed recently in #7812, but not included in the release yet. It should be included in the next release

**Comment by jadami10** [comment]
good catch. that one even links to 2 more PRs fixing it. Should we close this issue then or wait for the next release?

**Comment by Jackie-Jiang** [comment]
I think we can close this issue as it is already fixed in the latest master. What do you think @Sangarshanan?

**Comment by Sangarshanan** [comment]
Got it ! Yep can close this now
