### ISSUE TITLE
Pinot JDBC Client Connection Exception

### ISSUE THREAD

**Issue by Arpita030125** [apache/pinot#7987]
I have been trying to connect to authenticated Pinot Controller : sample only
final String dB_URL = "jdbc:pinot://hostname:port";
through JDBC Client with the following set of properties:samples only
properties.setProperty("username", "user");
properties.setProperty("password", "pass");

When I am trying to access the controller URL directly with the same set of credentials I am able to do so.
But when I am trying to connect to URL through JDBC client in my code  it is throwing the below exception:
PinotClientException: Pinot returned HTTP status 403, expected 200

I have tried the same code and was able to connect  to  local Pinot and execute queries which does not contain any authentication.

Expectation: I want to connect to authenticated pinot UI through JDBC client in my code and execute queries and fetch results.

**Comment by Jackie-Jiang** [comment]
@apucher Can you please take a look?

**Comment by kbastani** [comment]
Here is the issue when using basic authentication to lock down the controller.

https://github.com/apache/pinot/blob/bfe64b55460986135c6931e96e0cfc6ff178ad8c/pinot-clients/pinot-jdbc-client/src/main/java/org/apache/pinot/client/utils/DriverUtils.java#L75

**Comment by kbastani** [comment]
@Arpita030125 Can you try the following in your JDBC client? (not recommended for production code)

```java
final String username = "user";
final String password = "password";

// Concatenate username and password and use base64 to encode the concatenated string
String plainCredentials = username + ":" + password;
String base64Credentials = new String(Base64.getEncoder().encode(plainCredentials.getBytes()));

// Create authorization header
String authorizationHeader = "Basic " + base64Credentials;
Properties connectionProperties = new Properties();
connectionProperties.setProperty("headers.Authorization", authorizationHeader);

// Register new Pinot JDBC driver
DriverManager.registerDriver(new PinotDriver());

// Get a client connection and set the encoded authorization header
Connection connection = DriverManager.getConnection(DB_URL, connectionProperties);

// Test that your query successfully authenticates
Statement statement = connection.createStatement();
ResultSet rs = statement.executeQuery("SELECT count(*) FROM baseballStats LIMIT 1;");

while (rs.next()) {
    String result = rs.getString("count(*)");
    System.out.println(result);
}
```

**Comment by kbastani** [comment]
The fix for this issue is here: https://github.com/apache/pinot/commit/fcccf1b5a15847c541f5cf6d96a05bb0d15c98df

Previously, no headers would have been passed along to the controller which would cause a 403 unauthorized response when attempting to select an available broker to query.

**Comment by kbastani** [comment]
I've updated the Pinot docs with the relevant details on how to securely connect and query with JDBC. https://docs.pinot.apache.org/users/clients/java#authentication
