### ISSUE TITLE
Enhance Pinot Streaming Consumer Interface

### ISSUE THREAD

**Issue by navina** [apache/pinot#7988]
There are streaming systems which require additional client-initiated operations to guarantee the availability of data for replay. For example, Google Pubsub does **not** expose any notion of `offsets` for messages. It only delivers the messages that were published after a consumer is created. In order to replay or rewind, the client has to manually create/manage `snapshots` (aka checkpoints), which serves as an alternate mechanism to replay messages from a particular point in the stream.  

Pinot's realtime streaming ingestion is very closely modeled to kafka's semantics. In order to accommodate other streaming systems, it would be useful to expand the existing `PartitionGroupConsumer`. 
Proposal is to provide a mechanism to `commit` the state to the streaming source. For details on the proposal, please see - https://docs.google.com/document/d/17eywG2zYHv72ye3nBwVSdxlF7JIcTlqcNkov2TCqaGs/edit?usp=sharing

**Comment by npawar** [comment]
FYI @mcvsubbu @snleee @sajjad-moradi .

Thanks @navina . This will be certainly useful for streams like PubSub.

From your doc I see ``commit` will be invoked whenever the controller requests the server to commit a segment`. More specifically, will the commit be invoked before server gets back to the controller for metadata commit or after?
If it's the latter, some server failure scenarios might get tricky? If the former, any gotcha failure scenarios to consider?

**Comment by navina** [comment]
@npawar :  The commit will be invoked *before* the server gets back to the controller. Basically, when the server enters `COMMIT` state, it will first checkpoint to the stream, followed by building a segment and responding to the controller with metadata.  
Checkpoint is used as a "marker" in the stream. So, even if the server fails or enters commit state again, it should re-create (or use the existing) checkpoint and return the new metadata to the controller. 
I can't think of a gotcha failure scenarios as of now.

**Comment by mcvsubbu** [comment]
I hope we are discussing in the design document. As of now, it is very minimal. I have left some comments there. Please address them, thanks.
