### ISSUE TITLE
Pinot Dashboard tenant view shows incorrect amount of servers and brokers

### ISSUE THREAD

**Issue by lksvenoy-r7** [apache/pinot#7998]
**Current behaviour**
The homepage of the Pinot Dashboard (locally http://localhost:9000/#/) does not show the correct amount of servers and brokers on the tenant view.

(Screen from http://localhost:9000/)
![image](https://user-images.githubusercontent.com/46895578/149098824-11095196-4717-4993-8f69-20fb6d4af889.png)

However, when clicking on the link for the tenant, the correct amount of brokers and servers is displayed

(Screenshot from http://localhost:9000/Tenant1)
![image](https://user-images.githubusercontent.com/46895578/149099233-e55a4d0d-7bff-49df-9361-0c877f06b0df.png)

Screenshot from http://localhost:9000/Tenant2)
![image](https://user-images.githubusercontent.com/46895578/149099477-a8a97b92-28bb-4ead-ac4a-bfe6659e2ce6.png)

**Expected behavior**
The homepage of the Pinot Dashboard should correctly display the amount of servers and brokers for a tenant

**Comment by Jackie-Jiang** [comment]
@shahsank3t Can you please help take a look at this issue?
