### ISSUE TITLE
Enhancements to documentation about moving completed segments to different hosts

### ISSUE THREAD

**Issue by lksvenoy-r7** [apache/pinot#7999]
The documentation detailing how completed segments may be moved to a different host is described here: https://docs.pinot.apache.org/operators/operating-pinot/tuning/realtime#moving-completed-segments-to-different-hosts

This documentation mentions that segments may be hosted on a different host using the tagOverrideConfig, but there is no mention of it being possible to use the instanceAssignmentConfigMap to move completed segments.

As described in the [tag based instance assignment](https://docs.pinot.apache.org/operators/operating-pinot/instance-assignment#tag-based-instance-assignment) section of the documentation, using the instanceAssignmentConfigMap is the recommended approach, as it allows you more granular control over how segments are stored on hosts (using replica groups), but there is no mention of the fact that this can be used for moving completed segments as well.

We should update the [moving completed segments to different hosts](https://docs.pinot.apache.org/operators/operating-pinot/tuning/realtime#moving-completed-segments-to-different-hosts) section to include the recommended approach for moving segments.

**Comment by Jackie-Jiang** [comment]
Good catch! Could you please help update the documentation? You can find them under this repo: https://github.com/pinot-contrib/pinot-docs

**Comment by lksvenoy-r7** [comment]
PR opened: https://github.com/pinot-contrib/pinot-docs/pull/72/files

**Comment by Jackie-Jiang** [comment]
Thanks for helping enhance the documentation. The PR has been merged
