### ISSUE TITLE
Can not open new tabs from Pinot Dashboard

### ISSUE THREAD

**Issue by lksvenoy-r7** [apache/pinot#8000]
**Current behavior**
Currently when navigating the Pinot Dashboard, it is not possible to right click and open a new tab on the various links to resources (such as tables, tenants, and other links). I am not entirely sure, but I seem to remember that this used to be possible in a previous version of Pinot. In any case, it would be a huge user experience improvement for developers if we could open new tabs directly from the dashboard.

Below are screenshots to explain the problem.

Screenshot right clicking "Tenant1" (Should give ability to open new tab)
![image](https://user-images.githubusercontent.com/46895578/149107470-421eff31-032a-4bae-95b5-2be7b6d614e2.png)

This behavior is the same for Tenants, Controllers, Servers, Minions, and Brokers. This also happens when right clicking any element within the table/server/broker/controller overview. It also happens when right clicking segments within a table.

Screenshot 

Screenshot right clicking the top tabs (Tenants, Controllers, Brokers, Servers, Tables) (Works as expected)
![image](https://user-images.githubusercontent.com/46895578/149109564-d8e8ae9a-7b71-4137-96a3-6b7ce8a9366b.png)

**Expected behavior**
Right clicking any element within the Pinot Dashboard allows us to open a new tab pointing to that resource.

**Comment by mayankshriv** [comment]
cc: @shahsank3t
