### ISSUE TITLE
Performance: HTTP connection pooling could be used to reduce client latency

### ISSUE THREAD

**Issue by jonathanl-telenav** [apache/pinot#8007]
The time to set up and tear down HTTP broker connections to execute queries has a negative impact on query latency. A simple connection pool could keep established connections alive for reuse. See c3p0 and dbcp for some details on connection pooling. This optimization should have no effect on threading or transactions. It's just a way of reusing a live connection instead of opening a new connection for each query from the client. The client and the broker would both need to be changed to make this work, as neither should close pooled connections that are live until they expire from lack of use.

The discussion in Slack #general on January 12, 2022 gives more details.

**Comment by Jackie-Jiang** [comment]
Which connection are you referring to? The connections between broker and servers are async (non-blocking) and reused for multiple queries. We maintain one connection between each broker and server pair.

**Comment by jonathanl-telenav** [comment]
Ah, that is the information I was looking for. Thanks @Jackie-Jiang!
