### ISSUE TITLE
Here is typo in document

### ISSUE THREAD

**Issue by Lvnszn** [apache/pinot#8044]
Looks like `Returns the ISO week of the year from the given epoch millis and timezone id. The value ranges from 1 to 53` 

![image](https://user-images.githubusercontent.com/12541438/150310520-84137575-1839-4810-b58a-4a04faf166ff.png)

https://docs.pinot.apache.org/users/user-guide-query/supported-transformations#datetime-functions

**Comment by Jackie-Jiang** [comment]
Good catch! Updated the doc
