### ISSUE TITLE
Pinot GCS write fails to GCS bucket WITH CMEK enabled

### ISSUE THREAD

**Issue by AkshathPatkar** [apache/pinot#8075]
If we enable deep storage on GCS bucket with CMEK enabled some times GCS segment upload is failing with error.

`{
  "error": {
    "code": 400,
    "message": "Bad Cloud KMS crypto key: projects/atomic-sled-797/locations/us/keyRings/tst-gcs-key-us-01/cryptoKeys/gcs-01/cryptoKeyVersions/4",
    "errors": [
      {
        "message": "Bad Cloud KMS crypto key: projects/atomic-sled-797/locations/us/keyRings/tst-gcs-key-us-01/cryptoKeys/gcs-01/cryptoKeyVersions/4",
        "domain": "global",
        "reason": "invalid"
      }
    ]
  }
}`

After discussing further it looks like bug in OLD version of api being used 
https://github.com/apache/pinot/blob/d789ae70eec7ebafe0a688017c78c70d8caef798/pinot-plugins/pinot-file-system/pinot-gcs/pom.xml#L48-L49

This issue is fixed in later versions of google api 
https://github.com/googleapis/java-storage/issues/502

Can we get this upgraded

**Comment by Jackie-Jiang** [comment]
Thanks for investigating into the issue. Would you mind helping contribute a fix for this?

**Comment by AkshathPatkar** [comment]
Thanks I have sent a PR over https://github.com/apache/pinot/pull/8121. Let me know if you need more information on this

**Comment by Jackie-Jiang** [comment]
Thanks for submitting the fix. The fix has been merged, and closing this issue
