### ISSUE TITLE
Min identified as aggregation function instead of transform function

### ISSUE THREAD

**Issue by mneedham** [apache/pinot#8084]
When I try to use the `min`  scalar function e.g.

```
select min(distance, 5) 
from courses limit 10
```

It instead uses the aggregation function. i.e. it finds the minimum value across all rows, rather than computing the minimum value of `distance`  and `5` per row

<img src="https://user-images.githubusercontent.com/13220/151518911-3648beb1-af4d-4753-afb4-d89eff5c9bf6.png" alt="image" width="500"/>

If I would use the function with some hardcoded values then it does pick the correct function:

```
select min(7, 5) 
from courses limit 10
```

![image](https://user-images.githubusercontent.com/13220/151520261-6de03402-695a-4d93-901a-f5b0342cff59.png)

The same issue is there for the `max` function as well.

**Comment by richardstartin** [comment]
`min` _is_ an aggregation function in SQL. I think you're trying to use it like `least` (`max`: `greatest`) which isn't implemented in Pinot.

**Comment by mneedham** [comment]
Pinot has two different `min` functions. There's the aggregation function that you mention, but there is also a scalar function defined here - https://github.com/apache/pinot/blob/master/pinot-common/src/main/java/org/apache/pinot/common/function/scalar/ArithmeticFunctions.java#L57

```
  @ScalarFunction
  public static double min(double a, double b) {
    return Double.min(a, b);
  }

  @ScalarFunction
  public static double max(double a, double b) {
    return Double.max(a, b);
  }
```

So I wanted to call this `min` function in my query, but it calls the other one. So is your suggestion that the scalar functions should have different names?

**Comment by richardstartin** [comment]
> Pinot has two different `min` functions. There's the aggregation function that you mention, but there is also a scalar function defined here - https://github.com/apache/pinot/blob/master/pinot-common/src/main/java/org/apache/pinot/common/function/scalar/ArithmeticFunctions.java#L57
> 
> ```
>   @ScalarFunction
>   public static double min(double a, double b) {
>     return Double.min(a, b);
>   }
> 
>   @ScalarFunction
>   public static double max(double a, double b) {
>     return Double.max(a, b);
>   }
> ```
> 
> So I wanted to call this `min` function in my query, but it calls the other one. So is your suggestion that the scalar functions should have different names?

I’m aware of the scalar arithmetic functions. In SQL this function, which operates on tuples, not sets, is called least, not min. min is an aggregation over a set. I experimented with adding least and greatest scalar functions, and it works, but I would prefer to implement this as a TransformFunction for efficiency reasons (vectorisation).

**Comment by mneedham** [comment]
Got it, thanks!
