### ISSUE TITLE
Add `least` and `greatest` functions

### ISSUE THREAD

**Issue by richardstartin** [apache/pinot#8085]
`least(1,2,3,4,5);` yields 1
`greatest(1,2,3,4,5);` yields 5

|  foo | bar |
| ---- | --- |
| 1     |  0   |
| 2     |  1   |
| 5     |  4   |
| 6     |  7   |

`least(foo,bar,3) as min_ceiling;` yields 

| min_ceiling |
| ----------- |
|   0               |
|   1               |
|   3              |
|   3              |

`greatest(foo,bar,3) as max_floor;` yields 

| max_floor |
| ---------- |
|   3             |
|   3              |
|   5             |
|   7             |

**Comment by Jackie-Jiang** [comment]
We should replace the scalar function `min` with `least` and `max` with `greatest` (in `ArithmeticFunctions.java`). Currently we don't support arbitrary number of arguments in scalar function, but we can add different versions (e.g. 2 arguments, 3 arguments etc.). If user has more arguments, they can use nested `least` and `greatest`.
We can also add transform function for them, which can take arbitrary number of arguments.

**Comment by richardstartin** [comment]
I would prefer to implement this as a transform function so we can operate on arbitrary tuples. I already experimented with adding `least` and `greatest` to `ArithmeticFunctions` and the results were unsatisfactory (strictly binary, does not hand null well).

**Comment by Jackie-Jiang** [comment]
We might want both because transform function cannot be applied to ingestion transforms and post-aggregation transforms. Performance wise, transform function version is definitely better.
