### ISSUE TITLE
table creation shouldn't be allowed if table delete is happening async in background

### ISSUE THREAD

**Issue by walterddr** [apache/pinot#8091]
Currently table is deleted first and the segments were deleted async behind the scene. 

however if the controller died during the async deletion and got restarted. User can call the API to create an exact same name table without any issue. This should not be allowed since there's still left-over segments. 

I am not sure what's the right way to fix it. but some thoughts:
1. create a soft delete state for a table marking it as deleting, and not allow same name table to be recreated until the segment deletion is done. 
2. check the property store as well as table config store to make sure no left over segments exist, otherwise reject the table config creation request. 

Thoughts?

**Comment by mcvsubbu** [comment]
Related to Issue #7711

**Comment by mcvsubbu** [comment]
During deletion:
- Start the deletion process and wait until the table goes away from EXTRERNALVIEW

During table creation:
- Verify that the table does not exist in IDEALSTATE or EXTERLAVIEW

**Comment by walterddr** [comment]
sweet. thanks for referring to #7711. is it a duplicate entirely? i think we can close this one if it is

**Comment by ksnijjer** [comment]
For the user issue that we saw, table information was gone from EV/IS however entries were still left(controller seemed to die/restart in the middle) in ZK>PropertyStore(Table def. and Segments). Now table creation was still going through returning a 200 response but table didn't get created, so only checking IS/EV to allow table creation won't help.

**Comment by walterddr** [comment]
Observation
===

The issue is whether EXTERNAL VIEW for a table goes away before or after the PropertyStore remove entries for the associated segments. 

Upon checking the code in https://github.com/apache/pinot/blob/dd73ee7de1d8e8439e71b34d24627db48e06990e/pinot-controller/src/main/java/org/apache/pinot/controller/helix/core/PinotHelixResourceManager.java#L1624 the order for deleting offline table is 
* DropResource --> RemoveSegments --> RemovePropertyStore --> RemoveTableConfig --> RemoveInstanceAssignment

and in https://github.com/apache/pinot/blob/dd73ee7de1d8e8439e71b34d24627db48e06990e/pinot-controller/src/main/java/org/apache/pinot/controller/helix/core/PinotHelixResourceManager.java#L1259
* AddResource --> AddTableConfig --> AddInstanceAssignment

ProblemStatement
===
So the problem I think is

1. addTable does't check segment info and see if there's already existing segments for this table (with the same name i asusme)
2. deleteTable shouldn't delete the helix resource first before all the segments are remove (which is the only thing addTable checks for before raising TableAlreadyExistException)

Proposal
===
Looking at the above 2 problem, my proposal is to either 
1. check for segment in property store as well as Helix resource for duplicate table name
2. deleteTable should not delete the helix resource before all the table config and the segment info in property store were deleted.

Thoughts?



Reference
===

relates to #8092. Similar issue on the ordering - whether deep store file were deleted **before / after** property store segment deletion;

**Comment by Jackie-Jiang** [comment]
When creating the table, we should check all the related entries for the table is already removed. Per the sequence of entry deletion, we should check table config, instance partitions, segment lineage, task related metadata.
EV should not matter because Helix is able to handle it properly when the new IS is created

**Comment by walterddr** [comment]
I have the same observation as @Jackie-Jiang and also lean towards the 1st solution.
