### ISSUE TITLE
[UI] Query console cannot show query result when multiple columns have the same name

### ISSUE THREAD

**Issue by Jackie-Jiang** [apache/pinot#8123]
![Screen Shot 2022-02-03 at 3 55 21 PM](https://user-images.githubusercontent.com/17555551/152448913-646e9132-ee30-486b-864b-6e1b78b93a35.png)
![Screen Shot 2022-02-03 at 3 55 49 PM](https://user-images.githubusercontent.com/17555551/152448953-25197cd0-de0c-42df-9ecf-f4a8957b85e9.png)

**Comment by Jackie-Jiang** [comment]
@shahsank3t Can you please help take a look?

**Comment by shahsank3t** [comment]
@Jackie-Jiang Fixed in PR: https://github.com/apache/pinot/pull/8131
