### ISSUE TITLE
Support pushFileNamePattern job conf option

### ISSUE THREAD

**Issue by kkrugler** [apache/pinot#8141]
We do daily builds of offline segments using Hadoop, and then store the results in HDFS in the directory that is configured as our Pinot cluster’s deep store. Our build generates 35 new (or more typically updated) per-month segments each day, which we then deploy to our Pinot cluster via a metadata push.

What this means is that we’ve got a deep store directory in HDFS with ≈ 1200 segments (representing 3 years of data) for a table. When we do the metadata push every segment is downloaded, metadata is extracted, and that metadata tarball is sent to the controller. This takes about 3 hours currently. But we only want to send the 35 new segments.

It seems like a simple solution would be to support a new, optional `pushFileNamePattern` parameter in the job conf, which could be used to filter down to only the segments we care about. The format could be the same as the existing `includeFileNamePattern` pattern.

**Comment by mayankshriv** [comment]
I am curious why does metadata push take 3 hours? Are you not using the metadtata + uri push?

**Comment by kkrugler** [comment]
I don't know of any `metadtata + uri push` option - just `metadata` or `uri` (or `tar`). We're using the metadata push, which should be most efficient.

**Comment by mayankshriv** [comment]
Ah yes `metadata` push internally pushes `uri + metadata`. I am still unsure on why it takes 3 hours. When you say every segment is downloaded and metadata is extracted, are you referring to the push job, or the controller download. If former, the segment generation part could provide the metadata as well (to avoid download and extract). If latter, controller should not be downloading, that would be a bug.

**Comment by kkrugler** [comment]
Re segment download & metadata extraction, yes that's happening where the push job is running. I've got a separate (in progress) PR that does a streaming extract of just the two files needed for metadata (and ensures these files are first in the segment tarball), which does speed things up, but not as much as I'd expected.

So there might very well be a bug where the controller, or some other part of the system, is doing unneeded work...or there's a bottleneck. I guess I could run our controller w/trace level logging and then do the push job to get an idea of where the time is going.

**Comment by mayankshriv** [comment]
Thanks for confirming @kkrugler, and also for the fixes. Yeah, it would be great if we can identify the bottleneck, so we can fix that too.

**Comment by kkrugler** [comment]
Closed via https://github.com/apache/pinot/commit/f12e62522b8d09c8525a7482c92141042e3155c2
