### ISSUE TITLE
New broker boxes are not auto added to existed tenant to serve tables.

### ISSUE THREAD

**Issue by xiangfu0** [apache/pinot#82]
I assign 4 boxes as broker(defaultTenant), then add a table. 
Then  I add 4 more boxes to the same tenants.

Since the new 4 boxes are added as the same tenant name with old 4 boxes, so I assume new brokers should be added to the brokerResources idealstates, but they are not.

**Comment by kishoreg** [comment]
If we create broker resource in Auto mode, we can probably rely on Helix to
achieve this functionality.

**Comment by fx19880617** [comment]
For now we have one brokerResource in IdealStates, if we want to use full-auto, then we may need to create idealStates per brokerTenants I think.
