### ISSUE TITLE
MergeRollupMinionClusterIntegrationTest is flaky

### ISSUE THREAD

**Issue by richardstartin** [apache/pinot#8218]
https://github.com/apache/pinot/runs/5234008775?check_suite_focus=true

**Comment by Jackie-Jiang** [comment]
I have seen multiple integration test failures caused by `uploadSegment()`, so we might want to check that. That is common for all integration tests

**Comment by Jackie-Jiang** [comment]
The root cause is the same as #8265. Closing this one
