### ISSUE TITLE
Scalar Functions should be able to support multiple names

### ISSUE THREAD

**Issue by KKcorps** [apache/pinot#8236]
Currently, functions annotated with `@ScalarFunction` annotation take the name of the java method as the Query function name OR you can provide an alternative name. 
But there are scenarios, where we may need multiple names for the same function to support third-party tools such as Tableau, Looker etc. . e.g. (CEIL, CEILING), (LOGN, LN) etc. 

Currently we can do this by copying the method and just changing the name but that is not a good approach. We should make a small change in the Annotation Processor so that we can specify alternate names as part of annotation itself.

Suggested Changes - 

```
  @ScalarFunction(alias = {"ceil", "ceiling"})
  public static double ceil(double a) {
    return Math.ceil(a);
  }
```

**Comment by xiangfu0** [comment]
+1
