### ISSUE TITLE
Transform function with Groovy return wrong value in REALTIME table

### ISSUE THREAD

**Issue by fritzb** [apache/pinot#8245]
I have a transformFunction which rename a column from `name` to `name_match`. Apparently, the Groovy transform function generates wrong value from other rows, occasionally ( 6000 out of 52000 have wrong value ).
This happened on REALTIME table and not OFFLINE.

`  "fieldConfigList": [
    {
      "name": "name_match",
      "encodingType": "RAW",
      "indexType": "TEXT"
    }
  ],
  "ingestionConfig": {
    "transformConfigs": [{
      "columnName": "name_match",
      "transformFunction": "Groovy({name}, name)"
    }]
  },
`

**Comment by Jackie-Jiang** [comment]
Can you give some example of the wrong values generated (both the input and output)?

FYI, this renaming does not need groovy, `"transformConfigs": [{ "columnName": "name_match", "transformFunction":  "name" }]` should work
