### ISSUE TITLE
Add COALESCE or NULL value functions

### ISSUE THREAD

**Issue by lakshmanan-v** [apache/pinot#8251]
This is done in a  bunch of ways by different databases: https://www.w3schools.com/sql/sql_isnull.asp

It would be nice if pinot can support this capability. Right now this can only be done using CASE statement.

`CASE when expr([cols]) is 'null' THEN fallback_value ELSE expr([cols]) END`

**Comment by Jackie-Jiang** [comment]
This can be modeled as a scalar function (or transform function for better performance)

**Comment by KKcorps** [comment]
@Jackie-Jiang This is also a requirement to support Tableau completely from our end. Is there a way we can implement this?
Currentl, `WHERE column IS NULL` is supported when we set `nullHandlingEnabled` to `true`. But `CASE WHEN col IS NULL THEN a ELSE b` throws parsing exception.

**Comment by pjpringle** [comment]
> @Jackie-Jiang This is also a requirement to support Tableau completely from our end. Is there a way we can implement this? Currentl, `WHERE column IS NULL` is supported when we set `nullHandlingEnabled` to `true`. But `CASE WHEN col IS NULL THEN a ELSE b` throws parsing exception.

Did you miss the END in the case statement?
