### ISSUE TITLE
MergeRollupTask and RealtimeToOfflineSegmentsTask don't clean up old segments

### ISSUE THREAD

**Issue by GXM2333** [apache/pinot#8258]
In terms of  MergeRollupTask task, from the [design docs](https://docs.google.com/document/d/1gcRBibLvyu4jPQLthVeyhrK68PqqHnC6gpiaSEkYlx0/edit#), 

I see old segments should be deleted by configuring ` “oldSegmentCleanup”:"true"` in offline table config, and this config is default to be `true`. But I couldn't find this config from source codes and my offline table didn't delete old segments, either.

The picture below is offline table segment's names, which end timestamp is later than 1645603740000 ( 2022-02-23 16:09:00).

![offline table segment](https://user-images.githubusercontent.com/24871202/155941703-f1d0a35d-fb41-4dec-8f47-57f5bd5290d4.png)

my offline table segments are first generated by RealtimeToOfflineSegmentsTask, and then merged segments are generated by MergeRollupTask.

And same thing happened to RealtimeToOfflineSegmentsTask task which didn't delete old realtime segments after the task finished.

The picture below is realtime table segment's names, 
![realtime table segment](https://user-images.githubusercontent.com/24871202/155941765-ed0cc023-177a-468f-bdd0-c6467ebf70a5.png)

And here is my table config:

```
{
  "OFFLINE": {
    "tableName": "transcripts_OFFLINE",
    "tableType": "OFFLINE",
    "segmentsConfig": {
      "timeType": "MILLISECONDS",
      "schemaName": "transcripts",
      "retentionTimeUnit": "HOURS",
      "retentionTimeValue": "2",
      "replication": "1",
      "timeColumnName": "timestampInEpoch",
      "allowNullTimeValue": false,
      "replicaGroupStrategyConfig": {
        "partitionColumn": "studentID",
        "numInstancesPerPartition": 2
      }
    },
    "tenants": {
      "broker": "DefaultTenant",
      "server": "DefaultTenant"
    },
    "tableIndexConfig": {
      "invertedIndexColumns": [
        "lastName"
      ],
      "sortedColumn": [
        "firstName"
      ],
      "bloomFilterColumns": [
        "score"
      ],
      "loadMode": "MMAP",
      "enableDefaultStarTree": false,
      "enableDynamicStarTreeCreation": false,
      "segmentPartitionConfig": {
        "columnPartitionMap": {
          "studentID": {
            "functionName": "HashCode",
            "numPartitions": 4
          }
        }
      },
      "aggregateMetrics": false,
      "nullHandlingEnabled": false,
      "rangeIndexColumns": [
        "score"
      ],
      "rangeIndexVersion": 1,
      "autoGeneratedInvertedIndex": false,
      "createInvertedIndexDuringSegmentGeneration": false
    },
    "metadata": {
      "customConfigs": {}
    },
    "task": {
      "taskTypeConfigsMap": {
        "MergeRollupTask": {
          "1hour.mergeType": "rollup",
          "1hour.bucketTimePeriod": "1h",
          "1hour.bufferTimePeriod": "3h",
          "1hour.maxNumRecordsPerSegment": "1000000",
          "1hour.maxNumRecordsPerTask": "5000000",
          "1hour.maxNumParallelBuckets": "5",
          "1day.mergeType": "rollup",
          "1day.bucketTimePeriod": "1d",
          "1day.bufferTimePeriod": "1d",
          "1day.roundBucketTimePeriod": "1d",
          "1day.maxNumRecordsPerSegment": "1000000",
          "1day.maxNumRecordsPerTask": "5000000",
          "score.aggregationType": "sum"
        }
      }
    },
    "routing": {
      "segmentPrunerTypes": [
        "partition"
      ],
      "instanceSelectorType": "replicaGroup"
    },
    "isDimTable": false
  },
  "REALTIME": {
    "tableName": "transcripts_REALTIME",
    "tableType": "REALTIME",
    "segmentsConfig": {
      "timeType": "MILLISECONDS",
      "schemaName": "transcripts",
      "timeColumnName": "timestampInEpoch",
      "allowNullTimeValue": false,
      "replicasPerPartition": "2",
      "replicaGroupStrategyConfig": {
        "partitionColumn": "studentID",
        "numInstancesPerPartition": 2
      }
    },
    "tenants": {
      "broker": "DefaultTenant",
      "server": "DefaultTenant"
    },
    "tableIndexConfig": {
      "invertedIndexColumns": [
        "lastName"
      ],
      "streamConfigs": {
        "streamType": "kafka",
        "stream.kafka.consumer.type": "lowlevel",
        "stream.kafka.topic.name": "transcript-topic_1",
        "stream.kafka.decoder.class.name": "org.apache.pinot.plugin.stream.kafka.KafkaJSONMessageDecoder",
        "stream.kafka.consumer.factory.class.name": "org.apache.pinot.plugin.stream.kafka20.KafkaConsumerFactory",
        "stream.kafka.broker.list": "aptssd1.safe.lycc.qihoo.net:19092",
        "realtime.segment.flush.threshold.rows": "0",
        "realtime.segment.flush.threshold.time": "3m",
        "realtime.segment.flush.threshold.segment.size": "50M",
        "stream.kafka.consumer.prop.auto.offset.reset": "smallest"
      },
      "sortedColumn": [
        "firstName"
      ],
      "bloomFilterColumns": [
        "score"
      ],
      "loadMode": "MMAP",
      "enableDefaultStarTree": false,
      "enableDynamicStarTreeCreation": false,
      "segmentPartitionConfig": {
        "columnPartitionMap": {
          "studentID": {
            "functionName": "HashCode",
            "numPartitions": 4
          }
        }
      },
      "aggregateMetrics": false,
      "nullHandlingEnabled": false,
      "rangeIndexColumns": [
        "score"
      ],
      "rangeIndexVersion": 1,
      "autoGeneratedInvertedIndex": false,
      "createInvertedIndexDuringSegmentGeneration": false
    },
    "metadata": {
      "customConfigs": {}
    },
    "task": {
      "taskTypeConfigsMap": {
        "RealtimeToOfflineSegmentsTask": {
          "bucketTimePeriod": "6h",
          "bufferTimePeriod": "1d",
          "roundBucketTimePeriod": "1m",
          "mergeType": "rollup",
          "score.aggregationType": "max",
          "maxNumRecordsPerSegment": "100000"
        }
      }
    },
    "routing": {
      "segmentPrunerTypes": [
        "partition"
      ],
      "instanceSelectorType": "replicaGroup"
    },
    "instanceAssignmentConfigMap": {
      "CONSUMING": {
        "tagPoolConfig": {
          "tag": "DefaultTenant_REALTIME",
          "poolBased": false,
          "numPools": 0
        },
        "replicaGroupPartitionConfig": {
          "replicaGroupBased": true,
          "numInstances": 0,
          "numReplicaGroups": 2,
          "numInstancesPerReplicaGroup": 2,
          "numPartitions": 0,
          "numInstancesPerPartition": 0
        }
      }
    },
    "isDimTable": false
  }
}

```

Could you help me how to clean up old segments for MergeRollupTasks and RealtimeToOfflineSegmentsTasks? Thanks a lot.

**Comment by klsince** [comment]
I think those two minion tasks don't remove the segments directly. For segments in RT table, they should be removed based on table retention. For segments in OFFLINE table, in addition to table retention, they also should be removed based on segment lineage. As you may have noticed in the design doc, segment lineage is used by MergeRollup task for atomic segment swap. 

So, did you see any logs from [this manageSegmentLineageCleanupForTable method](https://github.com/apache/pinot/blob/master/pinot-controller/src/main/java/org/apache/pinot/controller/helix/core/retention/RetentionManager.java#L196) and [this manageRetentionForTable method](https://github.com/apache/pinot/blob/master/pinot-controller/src/main/java/org/apache/pinot/controller/helix/core/retention/RetentionManager.java#L100) at the controller side?  to see if deletion kicked in or not.

**Comment by GXM2333** [comment]
> I think those two minion tasks don't remove the segments directly. For segments in RT table, they should be removed based on table retention. For segments in OFFLINE table, in addition to table retention, they also should be removed based on segment lineage. As you may have noticed in the design doc, segment lineage is used by MergeRollup task for atomic segment swap.
> 
> So, did you see any logs from [this manageSegmentLineageCleanupForTable method](https://github.com/apache/pinot/blob/master/pinot-controller/src/main/java/org/apache/pinot/controller/helix/core/retention/RetentionManager.java#L196) and [this manageRetentionForTable method](https://github.com/apache/pinot/blob/master/pinot-controller/src/main/java/org/apache/pinot/controller/helix/core/retention/RetentionManager.java#L100) at the controller side? to see if deletion kicked in or not.

Thanks a lot. I see my logs, it was because my MergeRollupTask's mergeType for offline table is `rollup`. So table retention and segment lineage are not worked. Is there any way to delete old segments for rollup offline tables?

**Comment by klsince** [comment]
hmm.. interesting. do you have logs to help me locate the code where the deletion logic skips rollup segments?

**Comment by klsince** [comment]
from your logs, I spotted a few lines like ([thrown from code](https://github.com/apache/pinot/blob/master/pinot-controller/src/main/java/org/apache/pinot/controller/helix/core/retention/RetentionManager.java#L118))
```
2022/03/02 11:02:51.289 WARN [RetentionManager] [pool-6-thread-3] Invalid retention time: null null for table: transcriptss_OFFLINE, skip
```

**Comment by GXM2333** [comment]
Yes. For `transcriptss_OFFLINE` table ,I didn't configure a retention strategy.I guess the old segments of this table were deleted based on segment lineage, cause there are indeed a few old segments that have been deleted based on segments' screenshots above.

 I guess the reason that I didn't see these old segments name from [this log](https://github.com/apache/pinot/blob/b8fecb9d5a8fe524c42e29ce99ccf5012a2ebd49/pinot-controller/src/main/java/org/apache/pinot/controller/helix/core/retention/RetentionManager.java#L258) is log manager has deleted the log file.I found the default log configuration only maintain 10 log gzip files.
![](https://user-images.githubusercontent.com/24871202/156491910-7cb511ef-ae4b-4683-b33f-dca0d30f7952.png)

Thanks for helping me again,I will just close this issue :)
