### ISSUE TITLE
Failures during service startup leave process running in an inconsistent state

### ISSUE THREAD

**Issue by mikecdavis-dd** [apache/pinot#8267]
The `StartServiceManagerCommand` that handles asynchronous startup of services can leave the main process running even when part of the startup sequence has failed. In many scenarios `StartServiceManagerCommand#execute` catches general exceptions and will return `false`, but that return value is ignored by the respective callers:

* [StartServerCommand](https://github.com/apache/pinot/blob/c77c2c3e034d0cbe107142f62a2c89d29c566dbb/pinot-tools/src/main/java/org/apache/pinot/tools/admin/command/StartServerCommand.java#L195)
* [StartBrokerCommand](https://github.com/apache/pinot/blob/c77c2c3e034d0cbe107142f62a2c89d29c566dbb/pinot-tools/src/main/java/org/apache/pinot/tools/admin/command/StartBrokerCommand.java#L152)
* [StartControllerCommand](https://github.com/apache/pinot/blob/c77c2c3e034d0cbe107142f62a2c89d29c566dbb/pinot-tools/src/main/java/org/apache/pinot/tools/admin/command/StartControllerCommand.java#L187)
* [StartMinionCommand](https://github.com/apache/pinot/blob/master/pinot-tools/src/main/java/org/apache/pinot/tools/admin/command/StartMinionCommand.java#L127)

Option 1: Modify the callers to respect the return value from execute and shutdown accordingly
Option 2: Modify StartServiceManagerCommand#execute and throw an exception to be handled by the callers
Option 3: Exit immediately from `StartServiceManagerCommand`

Relates to: https://github.com/apache/pinot/issues/7271 where a Server fails to fully start up leaving it open to service queries, but unavailable to process helix messages.

**Comment by Jackie-Jiang** [comment]
Add @xiangfu0 to take a look

**Comment by xiangfu0** [comment]
I think we can fail the process if any  bootstrap service got failed
