### ISSUE TITLE
Filter out NULLS in aggregation function

### ISSUE THREAD

**Issue by KKcorps** [apache/pinot#8276]
The queries like `COUNT(columnA)` should only count rows which have non-null values. 
e.g.
A column `int0` has 17 rows out of which 6 have nulls
in pinot COUNT(column) will return 17
but it should ideally return 11.

**Comment by richardstartin** [comment]
This is supported by filter clauses which will be released in 0.10.0. Making it the default behaviour is another question.

**Comment by KKcorps** [comment]
Just saw it. https://github.com/apache/pinot/pull/7916 has these changes. I think that should suffice for now.
