### ISSUE TITLE
Indicate what fields are getting ignored when adding configs

### ISSUE THREAD

**Issue by npawar** [apache/pinot#8318]
Often users add schema or table config, and have gotten the position of a particular config wrong in the json. For example, `transformConfigs` put as top level field instead of inside `ingestionConfig`, or `enableDynamicStarTree` inside startree configs instead of top level. In such cases, Pinot simply ignores the unknown json fields that are not in their expected positions. 
This creates much confusion, as users are expecting the config to have some effect, but instead they see no effect. For example, putting transformConfigs as top level, will result in no transformations happening, making one think that the function is not working or there's some bug.

If we could find the delta of what has been saved and what was in the request config and display it to the user, that would help. This should definitely be part of the logs, but also in the response returned from the POST/PUT apis and validate apis

**Comment by navina** [comment]
I will pick this one up @npawar !

**Comment by saurabhd336** [comment]
These PRs add this functionality
https://github.com/apache/pinot/pull/8514
https://github.com/apache/pinot/pull/8606
