### ISSUE TITLE
Add support for building bloom filters in batch jobs for offline segments

### ISSUE THREAD

**Issue by dang-stripe** [apache/pinot#8334]
We're noticing that building bloom filters takes a considerable amount of time when loading segments on offline Pinot servers, specifically in rebalancing and replacing servers. We'd ideally like to perform this in our Spark offline pipeline instead similar to `createInvertedIndexDuringSegmentGeneration`.

**Comment by richardstartin** [comment]
Do you have any profiles you could share? We shouldn't rule out making it much faster to build bloom filters.
