### ISSUE TITLE
0.10.0 vulnerability in datatables.net

### ISSUE THREAD

**Issue by pjpringle** [apache/pinot#8429]
Enterprise vulnerability scanners flag the following preventing use of the 0.10.0 version

datatables:1.10.5-dev as sonatype-2020-0988 

Please can someone upgrade this to a latest version which is patched.

**Comment by timsants** [comment]
Can't seem to find this specific dependency in the project anymore? Has it been removed?

Regardless, we are in the process of upgrading some old NPM packages.

**Comment by pjpringle** [comment]
no longer an issue
