### ISSUE TITLE
Query regarding deep storage

### ISSUE THREAD

**Issue by mathewjpallan** [apache/pinot#8438]
Hi,

I am evaluating Apache Pinot and wanted to understand the deep storage options while deploying on Azure. From the docs, it seems like Azure blob is not supported and Azure Data Lake Storage has to be used as the deep storage. Can you please confirm on the same. 

Also is PinotFS the abstraction used for deep storage as well. The docs mention PinotFS in the context of importing data and hence this query.

**Comment by kkrugler** [comment]
Hi @mathewjpallan - these are really good questions for the `#general` channel in the Pinot Slack workspace.

**Comment by mathewjpallan** [comment]
@kkrugler I have raised it on slack and got responses. Will close this issue.
