### ISSUE TITLE
helm chart and tpl for extras config.

### ISSUE THREAD

**Issue by fcomte** [apache/pinot#8439]
Im a trying to configure a pinot cluster with an admin account with this helm chart.
It seems that I can't do it with a simple way by using only one value somewhere.
- There is no username and password on this chart 
- The extra.configs of all components are not evaluate by tpl function so i must precalculate all good values before which is not very practical.

Am I missing something ?

**Comment by Jackie-Jiang** [comment]
@walterddr @xiangfu0 Could you please take a look?

**Comment by xiangfu0** [comment]
we can model users' credentials as a list then loop and add them into controller/broker/server/minion extraConfigs.

**Comment by xiangfu0** [comment]
@fcomte Please take a look if there this PR what you are looking for: #8816
