### ISSUE TITLE
Airline dataset from the talk about the Star-Tree Index

### ISSUE THREAD

**Issue by ClouddJR** [apache/pinot#8477]
Hi, I couldn't find a better place to ask this question, so I decided to create this issue here.

Is the dataset used [in this talk](https://youtu.be/bwO0HSXguFA?t=519) (Airline data from 1987-2008) available somewhere? I would like to run my own experiments and it would be very valuable.

Thanks.

**Comment by Jackie-Jiang** [comment]
The data is available here: https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/HG7NV7

**Comment by kkrugler** [comment]
Hi @ClouddJR - the best place to ask questions like this is in the [Pinot Slack workspace](https://apache-pinot.slack.com/), e.g. via the general channel. You could maybe use this invite link to join: https://join.slack.com/t/apache-pinot/shared_invite/zt-5z7pav2f-yYtjZdVA~EDmrGkho87Vzw

**Comment by ClouddJR** [comment]
@kkrugler Thank you. I found out about the Slack channel after opening this issue. I will put my questions there from now on.

**Comment by Jackie-Jiang** [comment]
The data is available here:
https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/HG7NV7
