### ISSUE TITLE
Add startOffset and endOffset into segment metadata.properties file

### ISSUE THREAD

**Issue by npawar** [apache/pinot#8489]
And any other props that are missing.
Goal: every property in segment zk metadata should be in the metadata file on the segment.

**Comment by npawar** [comment]
cc: @mayankshriv

**Comment by Jackie-Jiang** [comment]
Certain fields should be in ZK metadata only though. Checked the ZK metadata, and adding start/end offset for debugging purpose should be good enough. The missing fields are `segment.flush.threshold.size`, `segment.flush.threshold.time`, `segment.realtime.download.url`, `segment.realtime.status`, `segment.realtime.numReplicas`

**Comment by saurabhd336** [comment]
@npawar Please review https://github.com/apache/pinot/pull/8502/files which aims to add the offset and potentially other ZK properties into segment's metadata.properties
