### ISSUE TITLE
Pinot minion doesn't have a healthcheck endpoint.

### ISSUE THREAD

**Issue by lfernandez93** [apache/pinot#8515]
all the other pinot components offer a healtcheck endpoint but not the minion, even-though the helm chart references to it  https://github.com/apache/pinot/blob/master/kubernetes/helm/pinot/templates/minion/statefulset.yml#L80 but it's disabled by default, it would be cool add a health check for this component as well so that we can have livenessProbes around it with kubernetes.

**Comment by Jackie-Jiang** [comment]
@lfernandez93 Good catch! Do you want to help contribute this? We can add a `PinotMinionHealthCheck` similar to `PinotBrokerHealthCheck` and add `LifecycleServiceStatusCallback` to the `ServiceStatus`

**Comment by saurabhd336** [comment]
This has been enabled with https://github.com/apache/pinot/pull/8574 and https://github.com/apache/pinot/pull/8593
