### ISSUE TITLE
[Bug]Pinot broker routes queries to servers while they are still downloading segments 

### ISSUE THREAD

**Issue by chenboat** [apache/pinot#8519]
Today if an empty box Pinot server joins the cluster to replace an existing server (i.e., the two servers share the same id), it can take 10s of minutes for Helix to instruct the new server to download all the segments and get them online. During the above process, Pinot brokers still route queries to the new server, this behavior results in partial and incorrect query results.

We should fix this bug by not routing the query to the server until it loads all the segments.

**Comment by mcvsubbu** [comment]
But then only those segments that are already loaded (and are ONLINE or CONSUMING in externalview on the new server) should get queries right? Is it a performance issue that you are facing?

**Comment by Jackie-Jiang** [comment]
@mcvsubbu The issue here is that for new servers, the `shutdownInProgress` flag is not set, and broker will start routing queries to it whenever the segment becomes ONLINE/CONSUMING in the external view. We should set the flag if it is not set yet when a server starts, so that all the servers (new server, existing server that encounters hard failure etc.) have the same behavior.

**Comment by chenboat** [comment]
@mcvsubbu This is not a performance issue but rather a query correctness issue. I also prefer to use the ExternalView as the single place to control the query routing decision rather using an additional flag. However, today it is possible that a Pinot segment is in ONLINE/CONSUMING state but the segment is still yet fully downloaded to the server during the segment replacement process I mentioned above. To me it is a bug as well. cc @Jackie-Jiang

**Comment by mcvsubbu** [comment]
One thing that can be done is as a part of new server workflow, set the `queriesDisabled` flag in Helix to true. This flag behaves the same as `shutdownInProgress`, except that the server does not change the flag back any time. It is used purely for admin purpose.
