### ISSUE TITLE
Make Pinot compatible with Spark 3.x

### ISSUE THREAD

**Issue by KKcorps** [apache/pinot#8526]
Current pinot used Apache spark 2.4.0 for running Spark Ingestion tasks. We need to upgrade it to Spark 3.x so that the latest spark version can be supported.

We will also need to make a lot of dependencies provided or add versions which don't conflict with spark.

Shading existing dependencies is also another option.

**Comment by suddendust** [comment]
Duplicate: https://github.com/apache/pinot/issues/7771
