### ISSUE TITLE
Support JDK17

### ISSUE THREAD

**Issue by richardstartin** [apache/pinot#8529]
Pinot doesn’t run on JDK17 out of the box and various illegal reflective accesses must be removed to improve new user experience. JDK17 support can be improved gradually by removing illegal reflective access in a piecemeal fashion.

**Comment by richardstartin** [comment]
Remaining blockers to running on JDK17 are:

* illegal reflective access in `FunctionInvoker` which blindly makes discovered methods accessible. This could be easily replaced with `MethodHandle`s and simply refuse to discover private methods from outside the module.
* Pinot currently cannot run on JDK17 with any combination of --add-opens/--add-exports because of the larray library which uses JDK internals which no longer exist in JDK17.

**Comment by gortiz** [comment]
Should we close this issue?
