### ISSUE TITLE
TEXT_MATCH query not working as described in documentation

### ISSUE THREAD

**Issue by taohu18** [apache/pinot#8595]
Based on the documentation, the above query should return all records containing "Boston Red" as is, however, records such as Boston Americans and Boston Doves are also in the query result. Looks like this match phrase query is not working as expected
![Screenshot from 2021-12-28 16-38-43](https://user-images.githubusercontent.com/85309206/165405599-f0af3ebb-576c-4a3b-bb11-3e977852f02c.png)
![Screenshot from 2021-12-28 16-37-54](https://user-images.githubusercontent.com/85309206/165405644-5206079f-1954-47cc-989b-29f548be4d46.png)

**Comment by Jackie-Jiang** [comment]
Can you please try removing the escape character? I believe that is used to escape the double quotes within a java string, and should not be added to the query.
cc @siddharthteotia

**Comment by taohu18** [comment]
@Jackie-Jiang Thanks for replying, I removed the double quotes but the result still looks incorrect. Some records only have "Boston" and some only have "Reds". Not all records contain "Boston Red" as is. 
cc @siddharthteotia

**Comment by Jackie-Jiang** [comment]
@taohu18 Not removing the double quotes, but just the backslash. I just updated the documentation page, please take a look.

**Comment by taohu18** [comment]
Thanks, it works! I will close this issue. Thanks again!
