### ISSUE TITLE
Add CSV Decoder for realtime

### ISSUE THREAD

**Issue by npawar** [apache/pinot#8617]
We only have JSON and Avro. Add support for CSV

**Comment by suddendust** [comment]
@npawar Can take this up, working on a very similar [feature](https://github.com/apache/pinot/issues/8399).

**Comment by npawar** [comment]
Thanks Prashant!

**Comment by suddendust** [comment]
PR: https://github.com/apache/pinot/pull/8658

**Comment by suddendust** [comment]
❤️ thanks everyone :)
