### ISSUE TITLE
Re-design the date time format

### ISSUE THREAD

**Issue by Jackie-Jiang** [apache/pinot#8632]
Currently the date time format is of the format:
- `<size>:<timeUnit>:<timeFormat>(:<pattern>( tz(<timezone>))`

E.g.
- `1:SECONDS:EPOCH`
- `1:DAYS:SIMPLE_DATE_FORMAT:yyyy-MM-dd tz(America/Chicago)`
- `1:MILLISECONDS:TIMESTAMP`

The problem of this format is that for certain time format, the size and time unit is implicit, and will cause confusion.

The proposal is to change the time format to:
- `EPOCH|<timeUnit>(|<size>)`
  - `EPOCH|SECONDS`
  - `EPOCH|MINUTES|5`
- `SDF|<timeFormat>(|<timezone>)`
  - `SDF|yyyy-MM-dd`
  - `SDF|yyyy-MM-dd'T'HH:mm:ss'Z'|America/Chicago`
- `TIMESTAMP`

We want to change the delimiter so that it won't be mixed with the character in the time format

**Comment by KKcorps** [comment]
I feel both if these formats cause a lot of confusion for new users. What each value represents is not implicit and requires going through the doc to change every time.
I propose a better way to handle this is to just keep this whole field as JSON.
e.g.

```json
{
      "size":1,
      "timeUnit":"DAYS",
      "timeFormat":"SIMPLE_DATE_FORMAT",
      "pattern":"yyyy-MM-dd",
      "timeZone":"PST"
}
```

**Comment by Jackie-Jiang** [comment]
@KKcorps Agree that keeping it as JSON would be easier to use. We still need a single string representation though which can be used as the argument of the `DATE_TIME_CONVERT` function. The changes proposed here is for the existing `DateTimeFieldSpec` and `DATE_TIME_CONVERT` function, and we should do it in a backward compatible way.
The long term solution should be to introduce the `DATE_TIME` data type, which can take extra properties (e.g. `pattern`, `timeZone`).

**Comment by stym06** [comment]
Created initial PR: #8727

**Comment by Jackie-Jiang** [comment]
> @Jackie-Jiang For `EPOCH|<timeUnit>(|<size>)` will this `size` be not there for MILLISECONDS and SECONDS, as you've mentioned:
> 
> ```
> EPOCH|SECONDS
> EPOCH|MINUTES|5
> ```

This size is optional for all the time units. If it is not provided, the default size is 1

**Comment by stym06** [comment]
@Jackie-Jiang In case of `1:HOURS:SIMPLE_DATE_FORMAT:yyyy-MM-dd tz(America/Chicago)` what will be equivalent in the new format?

**Comment by Jackie-Jiang** [comment]
@stym06 It should be `SDF|yyyy-MM-dd|America/Chicago`. Note that `1:HOURS` does not apply to SDF
