### ISSUE TITLE
PulsarConsumerTest.testPartitionLevelConsumer is flaky

### ISSUE THREAD

**Issue by richardstartin** [apache/pinot#8690]
https://github.com/apache/pinot/runs/6412121833?check_suite_focus=true

**Comment by Jackie-Jiang** [comment]
@KKcorps Can you please take a look? I also got this failure in #8677, not sure if they are related (not likely related though)

**Comment by xiangfu0** [comment]
Another try: https://github.com/apache/pinot/pull/8691

**Comment by KKcorps** [comment]
Looking into it. I am still not able to understand why this error occurs at randomly and is impossible to produce in local.

**Comment by Jackie-Jiang** [comment]
Usually the test failure that is hard to reproduce locally is due to the slowness of the CI machines. We may use `TestUtils.waitForCondition()` if the condition is not guaranteed to be met at the first place

**Comment by Jackie-Jiang** [comment]
Duplicate of #8537
