### ISSUE TITLE
Is it possible to configure realtime servers to directly upload to deep store?

### ISSUE THREAD

**Issue by dang-stripe** [apache/pinot#8692]
It seems that the peer download feature allows uploading segments from realtime servers directly to the deep store (in our case S3). Is it possible to enable uploading directly from servers to S3 instead of through the controllers?

https://docs.pinot.apache.org/operators/operating-pinot/decoupling-controller-from-the-data-path

cc @Jackie-Jiang

**Comment by Jackie-Jiang** [comment]
Currently directly uploading to deep store is coupled with the peer download feature, so you can just follow the doc to configure the table.
We can consider decoupling these 2 features, but enabling peer download just adds extra availability to the cluster in case the deep store is down for some reason and server is not able to upload the segment.

**Comment by dang-stripe** [comment]
Does that mean there's a potential risk of data loss? If the realtime servers are unable to upload their segment to deep store, they can continue to commit segments via the controller. What happens if they get replaced before other replica servers are able to download the segment?

**Comment by Jackie-Jiang** [comment]
@dang-stripe Good point. So we should decouple these 2 features, and if peer-download is not enabled, we should still allow server to directly upload the segment to the deep store, but abort the segment commit if the upload failed

**Comment by icefury71** [comment]
+1 on decoupling this : we shouldn't be forcing people to use peer download to use this feature.

**Comment by dang-stripe** [comment]
Fixed by https://github.com/apache/pinot/pull/10136 

https://docs.pinot.apache.org/operators/operating-pinot/decoupling-controller-from-the-data-path#upload-completed-segment-to-deep-store-directly
