### ISSUE TITLE
For performance considerations ， Can I create "roll up" table for query?

### ISSUE THREAD

**Issue by superwood** [apache/pinot#87]
For performance considerations ， Can I create "roll up" table for query?

The   big table  A have some dimensions ,

dimension1  dimension2  dimension3  dimensions4   .....  metrics
dimension1  dimension2  dimension3  dimensions4   .....  metrics

And the   frequent  query   "select  sum(metrics)  from  A where dimension1= and dimension2=  " will scan all the table for sum metrics.  
if  there is  a "roll up " table for A  name A1:
dimension1  dimension2  metrics
dimension1  dimension2  metrics

The query  "select  sum(metrics)  from  A where dimension1= and dimension2=  "  will search data from A1 which is aggregated from A.

**Comment by kishoreg** [comment]
We have something equivalent called star tree index. This can be enabled
while generating the segment by setting -enableStarTreeIndex=true

By default, it will create roll up for all dimensions. Note: this creates
roll up only if required, which can be controlled by setting maxLeafRecords.

Try it out and let us know. We will provide detailed instructions on a
github page today.

**Comment by mayankshriv** [comment]
I have updated the "Quick-Start" document on how to generate star tree
segments in Pinot. Once generated, the segments can be uploaded/queried as
regular segments. Please refer to the "Star Tree" segment in the link below.

https://github.com/linkedin/pinot/wiki/Quick-Start-Guide

Thanks,
Mayank
