### ISSUE TITLE
BaseChunkSVForwardIndexWriter's default version can end up storing the overflowed chunkOffset in the header

### ISSUE THREAD

**Issue by snleee** [apache/pinot#8701]
BaseChunkSVForwardIndexWriter's default version is V2. V2 uses 4bytes to store chunkOffset. When there are a lot of rows for "noDictionaryColumn", it can actually store overflowed int value for chunkOffset in the header. From V3, we store long value so we won't face this issue.

![image](https://user-images.githubusercontent.com/27253407/168405217-0c5cd4a5-857d-4cba-bd88-5fda645b903a.png)

The correct behavior should be throwing the exception when we generate the segment if we face the int overflow for chunk Offset.

**Comment by richardstartin** [comment]
V4 would also avoid this, has some other advantages discussed [here](https://docs.google.com/document/d/1Y7MyQGmDD2fI7brOOFQtToxd8ML837qRuc3IlNYFvCw/edit) but has a size limit of 4GiB.
