### ISSUE TITLE
Make Pinot minion stateless service 

### ISSUE THREAD

**Issue by xiangfu0** [apache/pinot#8723]
Ideally minion should be a K8s deployment instead of statefulset.
We may want to implement the auto cleanup feature for zk garbage for minion instances as well.

**Comment by xiangfu0** [comment]
The auto cleanup minion is already implemented, so I guess we can directly move the the deployment side

**Comment by Jackie-Jiang** [comment]
@xiangfu0 Can you share the PR of auto-cleanup the minion? I lost track of it

**Comment by xiangfu0** [comment]
There was an old issue : https://github.com/apache/pinot/issues/6526 and corresponding PR: https://github.com/apache/pinot/pull/6543

So the only thing left is the k8s changes which I can do it very soon.

**Comment by xiangfu0** [comment]
https://github.com/apache/pinot/pull/8936
