### ISSUE TITLE
Support raw index for multi-valued columns

### ISSUE THREAD

**Issue by Jackie-Jiang** [apache/pinot#8755]
Related issues: #6473, #8750

**Comment by siddharthteotia** [comment]
hey @Jackie-Jiang - there is another related issue here https://github.com/apache/pinot/issues/7870

I had discussed the point (4) in that issue with @somandal  and we are planning to do it in one of the two ways:

- Support for general purpose compression on dictionary encoded columns. So, for a dictionary encoded column it is not absolutely necessary to dictionary encode the forward index as well. The raw data in forward index can be compressed using LZ4 / SNAPPY etc just like we would have done for a noDictionary column
- The other way we are thinking is to also add support for no forward index.

I think both approaches can be implemented and will benefit the case where forward index can be huge (like the MV column example in my issue) and the column is only used in filtering so ok to have the forward index compressed or not have it at all.

**Comment by suddendust** [comment]
@siddharthteotia Any update on this?

**Comment by Jackie-Jiang** [comment]
Don't remember the intention for this issue, but the raw index for MV columns is already supported with #7595

**Comment by suddendust** [comment]
@Jackie-Jiang IIRC, we have a very high cardinality MV column on which we want to turn off dict encoding. However, do so does not let us define inverted index on these columns. So we want to be able to have the inverted index WHILE having the option to turn off the dictionary for this column. The dictionary ends up occupying around 50% of the segment size.

**Comment by suddendust** [comment]
@Jackie-Jiang Further description [here](https://github.com/apache/pinot/issues/8750).

**Comment by Jackie-Jiang** [comment]
Since the topic of this issue is already supported, closing this one and use other issues to track the specific feature request
