### ISSUE TITLE
Pagination on Selection not working as expected

### ISSUE THREAD

**Issue by darktaiga01** [apache/pinot#8770]
I have some problem about using LIMIT clause for paginating.  I query this statement
`select * from baseballStats order by yearID desc limit 0, 20`
It returns first 20 rows of the result. And it's fine. But when I want to query this statement
`select * from baseballStats order by yearID desc limit 200,300`
![image](https://user-images.githubusercontent.com/22326202/170205476-9b4e7fae-9852-4106-8c0f-4816fc1fc586.png)
It return first 300 rows of the result (0 to 300) but I want it return from offset 200 to 300
I've tried some statement as following
`select * from baseballStats order by yearID desc limit 87000,88000`
![image](https://user-images.githubusercontent.com/22326202/170206069-87e5da50-61aa-43e4-9ee7-40435b4fe135.png)
And it return last 10889 rows (from offset 87000 to 97889 and 97889 is number of rows in my table)

Did I use it incorrectly, or is this feature not working as I understand?
Thanks for reading.

**Comment by Jackie-Jiang** [comment]
Hi, when you use `limit` with 2 arguments:
The first argument: `offset`
The second argument: `limit` (number of rows to return)

So if you use `limit 200, 300`, Pinot will return rows of index `200-500`. If you want to get rows of index `200-300`, you may use `limit 200, 100`

**Comment by darktaiga01** [comment]
Oh, my bad. Thanks @Jackie-Jiang .
