### ISSUE TITLE
Allow adding a unique suffix to segment name during batch ingestion

### ISSUE THREAD

**Issue by KKcorps** [apache/pinot#8782]
Currently, if a user creates segments from the batch data that 
* contains either no time column or 
* contains same time for all the records (e.g. Current data in `yyyy-MM-dd` format)

the generated segments have same names. This creates issue because the segments end up replacing each other even when the push type is set to `APPEND`

The solution is to either add a current timestamp column in the table or provide a config in `SegmentNameGenerationSpec` to append `currentTimestamp`, `uuid` or something else at the end of the segment name

**Comment by KKcorps** [comment]
`InputFileSegmentNameGenerator` handles only one scenario whereby it can create a unique segment per file. But if file names are same in subsequent runs of the Generation job, it can still create issues.

**Comment by xiangfu0** [comment]
This makes sense, I think we can add a config to append creation time or random sequence_id to make the segment name unique.
