### ISSUE TITLE
PQL query endpoint deprecation drops support for Presto-Pinot with older dependency

### ISSUE THREAD

**Issue by cliandy** [apache/pinot#8793]
The Presto-Pinot driver using `PinotScatterGatherQueryClient.java` for version 0.10.0 is incompatible with changes introduced in #7430 for handling Presto direct-to-server internal Pinot API calls.

This seems to be intentional, as things are marked as non backward compatible, but **we are currently unable to take advantage of newer Pinot builds due to this dependency mismatch** of 0.10.0 driver and 0.11.0 Pinot w/PQL deprecation due to missing `pinotQuery` field.

**Comment by Jackie-Jiang** [comment]
@xiangfu0 Can you please help here?
