### ISSUE TITLE
includeFileNamePattern not working as expected

### ISSUE THREAD

**Issue by diogobaeder** [apache/pinot#8805]
Hi folks,

This seems to be a bug to me, so I'm opening an issue here right away (instead of bringing this to Slack first).

What I want to do is to be able to run a batch job that uses just one file as the input; Suppose that I have a directory, `/some/dir`, and then I have a segment data file there, `foo.json`. So I have `inputDirURI` set to `/some/dir`. But then, if I set `includeFileNamePattern` to any of:
* `regex:foo.json`
* `regex:foo\.json`
* `glob:foo.json`
* `glob:*/foo.json`

neither of them work.

The only way I can ever get this to work is by using `glob:**/foo.json`, which is counter-intuitive and probably inefficient - I really only need to process one file per batch in my case. Sure, it works, but I think this has some room for improvement, right? Or maybe there should at least be an alternative like `file:foo.json`?

Thanks!

**Comment by Jackie-Jiang** [comment]
cc @xiangfu0

**Comment by kkrugler** [comment]
@xiangfu0 is correct, you need to use `glob:**/foo.json`

See https://www.digitalocean.com/community/tools/glob?comments=true&glob=%2A%2A%2F%2A.json&matches=false&tests=%2Fsome%2Fdir%2Ffoo.json for a useful site to debug glob patterns.

**Comment by kkrugler** [comment]
@diogobaeder - why do you think `glob:**/foo.json` is inefficient? You are restricting the match space to what's at your `inputDirURI`.

**Comment by diogobaeder** [comment]
@kkrugler because it might have to traverse through all matching file paths according to the glob, and then filter in the ones that match `inputDirURI`, no? I mean, this is just speculation really, so I might be totally wrong as I don't know the implementation, but it's what my sense tells me the code is probably doing. Anyway, even if this is what happens, it's probably not a big deal (unless there's a case of traversing directories with too many paths, which depending on the implementation might be a bit slow).

**Comment by diogobaeder** [comment]
There you go, folks: https://github.com/pinot-contrib/pinot-docs/pull/101 - sorry I forgot to link to GitHub issues (and couldn't find out how to do this).

**Comment by Jackie-Jiang** [comment]
Thanks @diogobaeder Merged the change to the documentation repo

**Comment by diogobaeder** [comment]
Thanks @Jackie-Jiang :-)
