### ISSUE TITLE
Table selector won't work if table name is null

### ISSUE THREAD

**Issue by LaroLuo** [apache/pinot#8842]
https://github.com/apache/pinot/blob/d1d2ddbc116f6dddbefdf1e69dd409434eaae0e4/pinot-clients/pinot-java-client/src/main/java/org/apache/pinot/client/Connection.java#L86-L94

**Comment by Jackie-Jiang** [comment]
Thanks for reporting the issue.

If table name is not provided, we should parse the query and extract the table name from the query. This requires pulling in the `CalciteSqlParser` class, which is currently in `pinot-common` module.
We can either:
- Make `pinot-client` depend on `pinot-common`
- Pull `CalciteSqlParser` into `pinot-spi`

cc @xiangfu0

**Comment by npawar** [comment]
Assuming we are okay with these dependencies in pinot-client @xiangfu0 , labeling this as beginner as it looks straightforward enough to fix. Lmk if it is not.

**Comment by tanmesh** [comment]
I am planning to pick up this task.

**Comment by tanmesh** [comment]
I am planning to pick this up making the `pinot-client depend on pinot-common`.

**Comment by tanmesh** [comment]
Hey @npawar @Jackie-Jiang 👋 , can you please assign someone to review this PR 🙏

**Comment by xiangfu0** [comment]
The PR is on the right track.
One thing worth mentioning is that the get table name is the best effort.
And if the tableName is null, the brokerSelector should return any broker. E.g. `select 1` is usually used for testing the db connection by many external systems. This kind of query has no table name, but also a valid query.

**Comment by Jackie-Jiang** [comment]
Solved with #9902
