### ISSUE TITLE
Star-tree indexing a JSON key

### ISSUE THREAD

**Issue by tonykim-moloco** [apache/pinot#8851]
When creating a star-tree index, we would write a table config as follows.
``` JSON
"tableIndexConfig": {
  "starTreeIndexConfigs": [{
    "dimensionsSplitOrder": [
      "Country",
      "Browser",
      "Locale"
    ],
    "skipStarNodeCreationForDimensions": [
    ],
    "functionColumnPairs": [
      "SUM__Impressions"
    ],
    "maxLeafRecords": 1
  }],
  ...
}
```
Is there a way to specify a JSON column within the `dimensionSplitOrder`?
For example, if we have a column named `person`, having a JSON value such as `{
      "number" : 112,
      "street" : "main st",
      "country" : "us"
    }`, can we add `"country"` as one of the `dimensionsSplitOrder`?

**Comment by kkrugler** [comment]
Hi @tonykim-moloco - this is a great question for the #general channel on the Pinot Slack workspace (join [here](https://communityinviter.com/apps/apache-pinot/apache-pinot)).

**Comment by tonykim-moloco** [comment]
Thanks! I'll ask in the Slack workspace!
