### ISSUE TITLE
Allowing empty segments with kafka consumption

### ISSUE THREAD

**Issue by jadami10** [apache/pinot#8929]
We have a fairly unique consumption pattern that leads to consumption issues in Pinot.

- our Pinot table is set to consume topic T across P partitions.
- topic T has many different shapes of events, but at ingestion time we filter out any events that do not meet criteria C
- topic T has a high number of events per second
- for some Partitions P, there may be 0 events for days that match our criteria

What ends up happening is Pinot never seals those segments but continues extending their lease. When we go to restart Pinot servers, they then restart consuming from days ago. This leads to a huge amount of data being consumed just to be filtered out again, throttling from the kafka side, and waiting hours for the server to go healthy again.

I believe kinesis already has a way to seal "empty segments" that we would need here as well to get Pinot to continue advancing offsets correctly.

**Comment by Jackie-Jiang** [comment]
This is a fair ask. Since we introduced filtering during ingestion, if the offset moves but no record ingested, we should commit an empty segment and move the offset. cc @npawar @mcvsubbu
