### ISSUE TITLE
Setting progressively higher limits on groupBy queries causes query performance to degrade

### ISSUE THREAD

**Issue by jadami10** [apache/pinot#8930]
For bare "SELECT X FROM Y" queries, regardless of the "LIMIT", the query performs the same.

For "SELECT X, SUM(Z) FROM Y" queries, there's certain threshold for LIMIT, usually around 1-10 million, where every multiple of 10 you increase the limit by causes the query to take 10x longer to return results. It still returns the right result; it just takes a lot longer.

**Comment by Jackie-Jiang** [comment]
This is solved with #8921

**Comment by jadami10** [comment]
beat me to it. we'll pull this in, thank you!

**Comment by jadami10** [comment]
To follow up here. We pulled this change into 1 cluster today. Overall latencies are the same, but tail latencies have stabilized greatly. Their peaks are down an order of magnitude (from seconds to hundreds of millis).
