### ISSUE TITLE
Bug in 0.10.0, Incorrect result when using more than two CASE WHEN statement in group by query

### ISSUE THREAD

**Issue by taohu18** [apache/pinot#8996]
Here is an example query

SELECT DISTINCTCOUNT(name) count, CASE WHEN age < 2 THEN '0-2' WHEN age < 4 THEN '2-4'  ELSE '4+' END age_range FROM SAMPLE_TABLE WHERE age >= 0 GROUP BY age_range LIMIT 10

In the table, 3 people has age between 0 and 2, 2 people has age between 2-4, and 4 people has age above 4. But the result of the above query shows 0-2 has 0 people, 2-4 has 5 people and 4+ has 4 people. It adds up the count of first two case when and store the result in the case when before ELSE.

Above query is just a simple example, my production query has 7 CASE WHENs and the result adds up the count of all CASE WHENs and store the total in the last CASE WHEN group before ELSE

This bug only occurs in 0.10.0, in 0.9.3 it works as expected.

**Comment by mayankshriv** [comment]
Thanks for reporting, we will take a look. Is this a generic bug, or happens on a specific dataset?

**Comment by taohu18** [comment]
> 

This should be a generic bug. It occurs on all datasets

**Comment by taohu18** [comment]
@richardstartin I downloaded pinot from the official build, not sure if it's on master or not. I will try with the most recent official build to see if it's fixed

**Comment by ankitsultana** [comment]
Cherry picking https://github.com/apache/pinot/pull/8748 on v0.10.0 fixed it for us.
