### ISSUE TITLE
BadQueryRequestException when filtering on metric column first

### ISSUE THREAD

**Issue by jadami10** [apache/pinot#8998]
This is a weird one.

This query works fine
```
select currency, sum(amount)
from my table
where id = X
and amount > 0
group by currency
```

The following query fails
```
select currency, sum(amount)
from my table
where amount > 0
and id = X
group by currency
```

I get back
```
[
  {
    "errorCode": 200,
    "message": "QueryExecutionError:\norg.apache.pinot.spi.exception.BadQueryRequestException: Unsupported function: sum not found\n\tat org.apache.pinot.core.operator.transform.function.TransformFunctionFactory.get(TransformFunctionFactory.java:296)\n\tat org.apache.pinot.core.operator.transform.function.TransformFunctionFactory.get(TransformFunctionFactory.java:259)\n\tat org.apache.pinot.core.operator.filter.ExpressionFilterOperator.<init>(ExpressionFilterOperator.java:59)\n\tat org.apache.pinot.core.plan.FilterPlanNode.constructPhysicalOperator(FilterPlanNode.java:237)"
  },
  {
    "errorCode": 200,
    "message": "QueryExecutionError:\norg.apache.pinot.spi.exception.BadQueryRequestException: Unsupported function: sum not found\n\tat org.apache.pinot.core.operator.transform.function.TransformFunctionFactory.get(TransformFunctionFactory.java:296)\n\tat org.apache.pinot.core.operator.transform.function.TransformFunctionFactory.get(TransformFunctionFactory.java:259)\n\tat org.apache.pinot.core.operator.filter.ExpressionFilterOperator.<init>(ExpressionFilterOperator.java:59)\n\tat org.apache.pinot.core.plan.FilterPlanNode.constructPhysicalOperator(FilterPlanNode.java:237)"
  }
]
```
I've tried <, >, =, is null, is not null; but no matter what, if you filter on amount first, the query fails.

I can't repro with latest master and the meetupRsvp table, so it might already be fixed.

**Comment by Jackie-Jiang** [comment]
The query is missing the `group by currency` though. What is the response with the latest master?

**Comment by jadami10** [comment]
i just missed typing it. I've updated the description. I will be updating to latest master early next week so can check again.

**Comment by jadami10** [comment]
It seems even after moving the filter condition around and updating to latest master, this is still happening

**Comment by Jackie-Jiang** [comment]
Based on the exception message, the engine is processing `sum(amount)` in the filter clause. Do you have alias in the query? Based on the query I don't know how is that possible though..

**Comment by jadami10** [comment]
Ohhh you're totally right and this is a result of our confusing column names. 

Because we pre-aggregate, we name the column 'sum_amount'. And then when we query we do 'sum(sum_amount) as amount'. So filtering by 'amount' is wrong and only looks like it should work because of the alias. In reality the column is 'sum_amount'

Cc @noon-stripe
