### ISSUE TITLE
Reload Status Showing Inconsistent Result on UI

### ISSUE THREAD

**Issue by Harnoor-se7en** [apache/pinot#9007]
Hi Folks. For checking indexes, config applied, etc we have to exec into the pod to verify the table config.
For example in the below attached image, we do not have any inverted index on `tenant_id`: 
<img width="1280" alt="Screenshot 2022-07-01 at 4 17 53 PM" src="https://user-images.githubusercontent.com/100941492/176883126-25963af5-5d56-46b3-a315-ee99d294c498.png">

Expected result:
we only have dictionary encoding and forward index for this column:
<img width="320" alt="Screenshot 2022-07-01 at 4 18 05 PM" src="https://user-images.githubusercontent.com/100941492/176883179-929b2928-1bc4-4b9f-a891-d841741a8baa.png">

**Comment by Jackie-Jiang** [comment]
Is `tenant_id` sorted? If the column is sorted, the sorted index can be used as both forward index and inverted index, and that might be the reason why the inverted-index is checked here

**Comment by npawar** [comment]
@Harnoor-se7en did you get a chance to check? It seems the endpoint is working as expected, and that the metadata might be returing such info based on the column characteristics. Can you check the response of the endpoint invoked (the segments metadata endpoint).
Closing this issue, please reopen if your checks reveal that it is indeed incorrect or inconsistent.
