### ISSUE TITLE
Allowing empty segments for all stream consumers

### ISSUE THREAD

**Issue by jadami10** [apache/pinot#9014]
In this part of the code, https://github.com/apache/pinot/blob/2b82366c369cf668175695605f0b77d7105f4aff/pinot-core/src/main/java/org/apache/pinot/core/data/manager/realtime/LLRealtimeSegmentDataManager.java#L301-L304, we extend the segment build time by 1 hour if no rows were consumed. We have some common cases where certain partitions may never have data. We are either filtering out a lot of the data or there's a temporary error in our ingestion plugin. We also use a custom ingestion plugin.

But by forever extending the lease like this, whenever we restart the server, the server attempts to consume going back days or weeks and causes high CPU usage and throttling for both the server and kafka.

**Comment by KKcorps** [comment]
Hi, what I am not able to understand is, why is server consuming days/weeks back data? The consumer only deals with the offsets. It just starts consuming after the last offset that was consumed. If there was no data published, then it shouldn't be an issue imo. The rest of the partitions which had data should have already committed and so they shouldn't be getting consumed from start as well.
Can you add you table config here.

**Comment by jadami10** [comment]
The problem is that there is data published, and it's quite high volume. We are just filtering it all out in our decoder. So in this case, the server never actually commits the segment to advance the offsets. So a restart will cause it to go all the way back to the last time it saw a message it didn't filter out which can be hours or days.

Our table config is has a bunch of custom keys for our internal stream ingestion plugin, so i'm not sure it would be helpful.

**Comment by KKcorps** [comment]
@jadami10 Yeah, in your scenario it makes sense. Yep, we can take it up.
