### ISSUE TITLE
Support extract syntax

### ISSUE THREAD

**Issue by gortiz** [apache/pinot#9075]
SQL defines the [extract expression](https://modern-sql.com/feature/extract) that can be used to access components of temporal datatypes. Calcite already supports it, so when an expression includes an extract function it parses. But once Pinot tries to convert it to its own expression AST, it fails with:
```
ProcessingException(errorCode:150, message:PQLParsingError:
java.lang.ClassCastException: class org.apache.calcite.sql.SqlIntervalQualifier cannot be cast to class org.apache.calcite.sql.SqlBasicCall (org.apache.calcite.sql.SqlIntervalQualifier and org.apache.calcite.sql.SqlBasicCall are in unnamed module of loader 'app')
	at org.apache.pinot.sql.parsers.CalciteSqlParser.toExpression(CalciteSqlParser.java:682)
	at org.apache.pinot.sql.parsers.CalciteSqlParser.compileFunctionExpression(CalciteSqlParser.java:737)
	at org.apache.pinot.sql.parsers.CalciteSqlParser.toExpression(CalciteSqlParser.java:682)
	at org.apache.pinot.sql.parsers.CalciteSqlParser.toExpression(CalciteSqlParser.java:619))
```

Pinot already have functions like `minute`, `year`, etc so this seems to be a matter of syntax.

**Comment by tanmesh** [comment]
I am planning to pick this up.

**Comment by tanmesh** [comment]
I have added the progress so far in the above PR. May I get some eyes on this, to ensure that I am on the right track?###

**Comment by tanmesh** [comment]
@npawar Update -- PR is merged.

**Comment by tanmesh** [comment]
I have added the documentation in the PR above ^. Please review it.

**Comment by Jackie-Jiang** [comment]
Merged. Thank you so much for your contribution!
