### ISSUE TITLE
Support REGEXP_REPLACE

### ISSUE THREAD

**Issue by gortiz** [apache/pinot#9079]
Most SQL databases support `REGEXP_REPLACE` function ([Oracle](https://docs.oracle.com/cd/B19306_01/server.102/b14200/functions130.htm), [Postgres](https://www.postgresql.org/docs/current/functions-matching.html), [Vertica](https://www.vertica.com/docs/9.2.x/HTML/Content/Authoring/SQLReferenceManual/Functions/RegularExpressions/REGEXP_REPLACE.htm), [MySQL](https://dev.mysql.com/doc/refman/8.0/en/regexp.html#function_regexp-replace)). Pinot instead supports `REPLACE`, which just looks for exact string matches and replace them with another simple string.

It shouldn't be very difficult to support this operation in Pinot. Current implementation of `ltrim` and `rtrim` already uses Java regex. The main difference is that, for performance reasons, the pattern should be stored somewhere in the AST to be compiled only once.

**Comment by gortiz** [comment]
IMHO this ticket should be labeled as `beginner-task`

**Comment by vvivekiyer** [comment]
I'll pick this up.

**Comment by siddharthteotia** [comment]
Completed with PR https://github.com/apache/pinot/pull/9123
