### ISSUE TITLE
gitbook url unavailable

### ISSUE THREAD

**Issue by 0ZhangJc0** [apache/pinot#9080]
https://docs.pinot.apache.org/

![image](https://user-images.githubusercontent.com/48285423/180149636-78c3caf3-0da5-4c7f-9f35-ea2df9328d40.png)

**Comment by xiangfu0** [comment]
Thanks for reporting, we are experiencing some DNS issue with apache.org website. Please use : https://apache-pinot.gitbook.io/latest instead until the DNS record is resolved.

https://issues.apache.org/jira/browse/INFRA-23494

**Comment by xiangfu0** [comment]
This is fixed.
