### ISSUE TITLE
Issue with documentation for M1 Mac Support

### ISSUE THREAD

**Issue by jugomezv** [apache/pinot#9107]
I was going through the set up for M1 and found that [this ](https://docs.pinot.apache.org/basics/getting-started/running-pinot-locally#m1-mac-support)section seems to have an issue:

The provided settings.xml file as shown there, causes a failure due to parsing issues:

```
<activeProfiles>
  <activeProfile>
    apple-silicon
  </activeProfile>
</activeProfiles>
<profiles>
  <profile>
    <id>apple-silicon</id>
    <properties>
      <os.detected.classifier>osx-x86_64</os.detected.classifier>
    </properties>
  </profile>
</profiles>
```

Seems like the proper syntax is to include the full content of the file within the activeProfiles tag:

```
<activeProfiles>
  <activeProfile>
    apple-silicon
  </activeProfile>
  <profiles>
    <profile>
      <id>apple-silicon</id>
      <properties>
        <os.detected.classifier>osx-x86_64</os.detected.classifier>
      </properties>
    </profile>
  </profiles>
</activeProfiles>
```

**Comment by snleee** [comment]
@jugomezv https://github.com/pinot-contrib/pinot-docs/

The documentation can be updated in the above repository. Can you update the change and file the PR?

**Comment by jugomezv** [comment]
Sure, let me try that

**Comment by snleee** [comment]
https://github.com/pinot-contrib/pinot-docs/pull/107

**Comment by jugomezv** [comment]
Merged.
