### ISSUE TITLE
Ability to change logging levels at a component level dynamically

### ISSUE THREAD

**Issue by amol-mathur** [apache/pinot#9108]
Hi,

i want the ability to change log levels at a pinot component level (controller, broker etc) dynamically without requiring a restarts
this is a pretty useful feature for anyone running pinot in production
ideally i would like this to be saved as some config in ZK and some buttons on the pinot ui to toggle between different levels

**Comment by Jackie-Jiang** [comment]
This is a great feature! Do you want to help contribute this?

**Comment by xiangfu0** [comment]
Submitted a PR: https://github.com/apache/pinot/pull/9180
