### ISSUE TITLE
SegmentGenerationJobRunner.submitSegmentGenTask should catch all Throwables

### ISSUE THREAD

**Issue by gortiz** [apache/pinot#9113]
SegmentGenerationJobRunner.submitSegmentGenTask submits tasks to an executor. Each task has a try-catch that logs the problem and stops the execution in case a subclass of Exception is thrown. But this code does not log the problem if an Error is thrown. For example, if the JVM that executes SegmentGenerationJobRunner does not have enough heap memory to apply the generation, then Java will throw an OutOfMemoryError that will not be catched by SegmentGenerationJobRunner.submitSegmentGenTask. As a result, no log is printed to the user and the JVM continues to work. Eventually there is enough memory to sucessfully create the other segments and the process finish with a correct status but without generating some segments.

This behavior is very misleading, as the user thinks that his data is correctly stored in Pinot, when in fact some segments have been ignored.

**Comment by Jackie-Jiang** [comment]
Good catch! We should change the code to catch all `Throwable`

**Comment by rino-kadijk** [comment]
It can be hard to recover from a JVM Error. Are you sure you want to catch and retry ALL JVM Errors including LinkageError, StackOverFlowError, IOError, etc?

**Comment by Jackie-Jiang** [comment]
@rino-kadijk It's a global catch and we are not trying to recover from it. Currently we will miss the error and the thread just died without properly propagate the error back.

Closing the issue as the fix is merged
