### ISSUE TITLE
Bug: isArray should not be accepting byte array. 

### ISSUE THREAD

**Issue by JasonLeeWeiHern** [apache/pinot#9146]
the method isArray in the class [ComplexTypeTransformer.java](https://github.com/apache/pinot/blob/master/pinot-segment-local/src/main/java/org/apache/pinot/segment/local/recordtransformer/ComplexTypeTransformer.java) is accepting byte array which shouldn't be the case.

**Comment by KKcorps** [comment]
The issue is although it returns true in  `isArray` in case of byte[], at the next step we try to cast this byte[] to Object[] which breaks stuff

**Comment by Jackie-Jiang** [comment]
Good catch! We may just do `instanceOf Object[]` instead. Basically all primitive arrays are treated as single entry
