### ISSUE TITLE
Support to merge the existing column value and the incoming event

### ISSUE THREAD

**Issue by huaheh** [apache/pinot#9188]
In a partial upsert table, we can define an upsert strategy for each column, for example, OVERWRITE. This leads to the column's value always being overwritten by the next incoming event. The suggestion is to have control over merging the existing column value and the field value of the incoming event. 

For example, a table has two columns, col1 and col2, both having OVERWRITE upsert strategy. With incoming event {"f1":"v1",  "f2": null}, the expected transformation is like

```
      {
        "columnName": "col1",
        "transformFunction": "OVERWRITE_IF(f1 != null,  f1, col1)"
      },
      {
        "columnName": "col2",
        "transformFunction": "OVERWRITE_IF(f2 != null,  f2, col2)"
      },
```

This way col1 will be updated with v1 while col2 will remain its old value. This flexibility allows us to ingest some fields of an event and drop the other fields, and not have to drop the whole event if we merely don't want some columns to be overwritten.

**Comment by Jackie-Jiang** [comment]
Partial upsert will always ignore the `null` values, so for your use case, if the new record has {"col1": "v1", "col2": null} with OVERRIDE strategy, it should achieve what you want.

cc @deemoliu seems this behavior is not clearly documented

**Comment by huaheh** [comment]
Not just null, also apply the merge on non-null values.

**Comment by huaheh** [comment]
Hi @Jackie-Jiang, do you mean `null` is always ignored regardless of the column's partialUpsertStrategies?

**Comment by Jackie-Jiang** [comment]
@huaheh Yes. The `partialUpsertStrategies` will only be applied when the existing and new values are both non-null.

**Comment by huaheh** [comment]
Thanks, the "null ignoring" behavior is very useful and currently satisfies our needs.

**Comment by Jackie-Jiang** [comment]
I'll close the issue for now. @huaheh Let me know if you run into issues when trying it out
