### ISSUE TITLE
[multistage] Query Doesn't Return Schema When Result Set is Empty

### ISSUE THREAD

**Issue by ankitsultana** [apache/pinot#9189]
You can run this query with the MULTI_STAGE quickstart for reproducing this:

```
SELECT
a.playerID, a.runs, a.yearID, b.runs, b.yearID FROM baseballStats_OFFLINE AS a JOIN baseballStats_OFFLINE AS b ON a.playerID = b.playerID WHERE a.runs > 160 AND b.runs < 0
```

cc: @walterddr 

<img width="1222" alt="image" src="https://user-images.githubusercontent.com/8644710/183790352-4f76dec3-4d25-4d17-bdc5-520709934319.png">

**Comment by walterddr** [comment]
close with #9222
