### ISSUE TITLE
RealtimeNonReplicaGroupSegmentAssignmentTest is flaky

### ISSUE THREAD

**Issue by Jackie-Jiang** [apache/pinot#9253]
```
Error:    RealtimeNonReplicaGroupSegmentAssignmentTest.testRelocateCompletedSegments:231 expected [true] but found [false]
```

It tests the behavior of Helix auto rebalance strategy (`SegmentAssignmentUtils.rebalanceTableWithHelixAutoRebalanceStrategy()`), which might not perfectly balance the segments.

**Comment by npawar** [comment]
Seeing linked PRs already merged. Closing this and we can reopen if issue still persists
