### ISSUE TITLE
SERVER ISN'T PROPERLY STARTING WHILE CONFIGURING HDFS AS DEEP STORAGE 

### ISSUE THREAD

**Issue by DDeena007** [apache/pinot#9283]
![image (1)](https://user-images.githubusercontent.com/104492757/186843179-5ab9075d-86e4-4677-a6a3-f9d0584514a5.png)
![image (2)](https://user-images.githubusercontent.com/104492757/186843189-1f8c72dd-fc29-4bd2-a566-ac37ecd7fef9.png)

**Comment by kkrugler** [comment]
Hi @DDeena007 - this is a good question for the #troubleshooting channel on the Pinot Slack workspace. We try to use GitHub issues for things which have first been discussed on Slack, and identified as likely bugs or useful enhancements.

**Comment by Jackie-Jiang** [comment]
cc @KKcorps @xiangfu0

**Comment by npawar** [comment]
Since this is more than a month old, and I believe Deena since asked this on slack, closing this issue.
