### ISSUE TITLE
RealtimeToOfflineSegmentsTask does not add file extension to segment files in Deep Store

### ISSUE THREAD

**Issue by aw381246** [apache/pinot#9307]
The segment files are .tar.gz, but don't include that extension if they're created through a RealtimeToOfflineSegmentsTask 

We ran into this while trying to run a SegmentMetadataPush job to restore segment metadata in a DR situation where we still had the Segment files in a GCS bucket.

The SegmentMetadataPush job calls SegmentPushUtils.sendSegmentUriAndMetadata which filters the specified folder for only files with .tar.gz extensions (which in our case the files had no extensions.

We worked around the issue by renaming the files with the extensions manually and that worked.

**Comment by aw381246** [comment]
This problem is actually not specific to just the RealtimeToOfflineSegmentsTask.  Completed segments that had not run through the task also have no file extensions

**Comment by Jackie-Jiang** [comment]
Thanks for reporting the issue. Would you like to help contribute a fix?

**Comment by galalen** [comment]
If its still available please assign it to me

**Comment by bobby-richard-sed** [comment]
Would it be better to just remove the .tar.gz extension check from the SegmentMetadataPush job?

**Comment by bobby-richard** [comment]
Would it be better to remove the .tar.gz extension check from the SegmentMetadataPush job?

**Comment by robertzych** [comment]
This can now be closed as #9359 updated SegmentPushUtils to support segments without the .tar.gz extension.
