### ISSUE TITLE
Segments Deleted Due to Retention Can Cause Query Failures with ServerSegmentMissing Error

### ISSUE THREAD

**Issue by ankitsultana** [apache/pinot#9371]
We recently enabled the feature to return exceptions for cases when some segments are missing (as opposed to returning partial results).

This feature was rolled out in #7823.

After enabling it we have started seeing the following error occasionally for our Realtime tables. On digging a bit we found that this error comes when a segment is deleted due to retention.

```
ServerSegmentMissing:1 segments [<segment-name>] missing on server: <server-name>, errorCode:235
```

**Comment by chenboat** [comment]
@Jackie-Jiang @mcvsubbu How does Pinot handle the case after the broker gets the external view segment to server mapping, the segments get deleted right after that?

**Comment by mcvsubbu** [comment]
routing table is re-built when the external view notification comes in. That means any segment that is there now (and was not there before) is deleted, and any segment that was not there before (and is there now) are added. Also, if segments are moved, then that is included in the routing reconstruction as well

**Comment by Jackie-Jiang** [comment]
Hmm, this means server processes the callbacks faster than the broker. We have #7818 trying to address the similar issue, but if the version you are running already includes this PR, that means broker is too slow, and before it processes the IS change, server already deleted the segment.
In that case, one possible solution is to introduce a delay on the server before dropping the segment.

**Comment by ankitsultana** [comment]
Another solution may be to extend TimeSegmentPruner or create a new Pruner to prune segments which are older than the configured retention.

**Comment by Jackie-Jiang** [comment]
This can happen when segment is manually deleted as well, so I feel we want a more general solution

**Comment by ankitsultana** [comment]
@Jackie-Jiang suggested that we can keep a cache of the deleted segments in Pinot Servers and ignore this error if the missing segment is a recently deleted segment. We can try this approach out.
