### ISSUE TITLE
Connection with Kafka successfully but the query is not showing the topic data

### ISSUE THREAD

**Issue by pedrov-santos98** [apache/pinot#9417]
Hi guys, I'm having a problem with Apache Pinot.
I'm testing the tool and I would like to create a table with data from a kafka topic.

For the environment I'm using a docker-compose with kafka confluent community + apache pinot.

I am following the following official tutorial -> [https://docs.pinot.apache.org/basics/data-import/pinot-stream-ingestion/import-from-apache-kafka](url)

All connection is successful, I create the "transcript" schema and the "transcript_realtime" table.

![Apache Pinot 1](https://user-images.githubusercontent.com/47081066/190830469-ed5f06c7-c075-44cf-ba97-79627aa7adb1.jpg)
![Apache Pinot 2](https://user-images.githubusercontent.com/47081066/190830473-db14c035-06ea-49c5-ba6d-32c2144b3180.jpg)

I know the connection is correct because Apache Pinot creates the topic in kafka if it doesn't exist

![Apache Pinot 3](https://user-images.githubusercontent.com/47081066/190830558-14ea6d17-dde5-4a30-9a71-f3b73074d9d2.jpg)

The problem is that when generating the messages in the kafka topic

![Control Center - Google Chrome](https://user-images.githubusercontent.com/47081066/190830645-0474e966-9cbe-4c3d-8f2d-a1b033b4f750.jpg)

When doing the select on the table nothing happens.

![Apache Pinot - Google Chrome](https://user-images.githubusercontent.com/47081066/190830734-ccbbe145-5bf5-45a7-ae47-a56a2a0fb743.jpg)

Do you know what could be happening?
Thank you very much!

**Comment by Jackie-Jiang** [comment]
Do you see any exception logged on the servers?
cc @npawar @navina to take a look

**Comment by navina** [comment]
@pedrov-santos98 can you check the logs in the server directory for any exceptions that is happening during ingestion? 

Based on your description, it looks like ingestion is silently failing or dropping the records. Here are some possible ways in which you can verify that the ingestion is still progressing:
1. Using the Rest APIs via the Swagger UI:
a. `/getTableStatus` and verify that the state is `HEALTHY`
b. `/debug/tables/{tableName}` to view the debug information for the table. You can increase the verbosity to see more details.
c. `/consumingSegmentsInfo` -> if this doesn't return any segments, it means there are no consuming segments and ideally, you would have caught this "error" state in the previous 2 queries
2. Look at the metrics, if you have them exported somewhere:
a. if `LLC_PARTITION_CONSUMING` is non-zero, there is an ingestion issue
3. Look at the ZK status - make sure that the ideal state (IS) and external view (EV) for that table match and each partition has a consuming segment. 
4. Search the server logs for any error or exception.

Happy to connect on the Apache Pinot slack and troubleshoot as well. My id is `navina`

**Comment by npawar** [comment]
Hello @pedrov-santos98 , were you able to resolve the issue?

**Comment by npawar** [comment]
Closing this issue for now. Please reopen if issue persists and debugging steps provided by @navina don't help
