### ISSUE TITLE
Issue on Histogram with condition

### ISSUE THREAD

**Issue by wynet321** [apache/pinot#9421]
query as
`select HISTOGRAM(duration,0,1858,3) as histogram_data from signal_data where  doc_type='Paid'`
When tried to use histogram with the condition where-clause, pinot report 
`  {
    "message": "QueryExecutionError:\njava.lang.NullPointerException\n\tat org.apache.pinot.core.query.aggregation.function.HistogramAggregationFunction.extractAggregationResult(HistogramAggregationFunction.java:156)\n\tat org.apache.pinot.core.query.aggregation.function.HistogramAggregationFunction.extractAggregationResult(HistogramAggregationFunction.java:42)\n\tat org.apache.pinot.core.query.aggregation.DefaultAggregationExecutor.getResult(DefaultAggregationExecutor.java:57)\n\tat org.apache.pinot.core.operator.query.AggregationOperator.getNextBlock(AggregationOperator.java:73)",
    "errorCode": 200
}`

**Comment by siddharthteotia** [comment]
cc @jasperjiaguo
