### ISSUE TITLE
Do we need `-XX:ActiveProcessorCount=2` in jvmOpts?

### ISSUE THREAD

**Issue by sudo6si** [apache/pinot#9491]
Currently helm chart's [`values.yaml` file](https://github.com/apache/pinot/blob/dc84310077765ce367d380c97aa67f9e4caeb0bf/kubernetes/helm/pinot/values.yaml#L102) contains following option:

```
  jvmOpts: "-XX:ActiveProcessorCount=2 -Xms256M -Xmx1G -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -Xlog:gc*:file=/opt/pinot/gc-pinot-controller.log"
```

As per my [understanding](https://stackoverflow.com/a/59882645)

> Overrides the number of CPUs that the VM will use to calculate the size of thread pools it will use for various operations such as Garbage Collection and ForkJoinPool.

Do we need this option and if yes should this be configured to be equal to container's CPU?

**Comment by xiangfu0** [comment]
This is usually be configured when try users started with a very small VM. We do see problems that some users configure <1 CPU for pinot and that might cause unexpected behavior of the program, as the java system gives you that you have 0 CPU. 

For advanced users, definitely modify it as you needed or just remove this option.

**Comment by sudo6si** [comment]
@xiangfu0 thanks for the quick revert. We have removed this option entirely and assuming that pinot's JVM is smart enough to figure out how much CPU is available for it?

If that is not the case, let me know and we will set the value to be equal to container's CPU.

**Comment by xiangfu0** [comment]
> ave removed this option entirely and assuming that pinot's JVM is smart enough to figure out how much CPU is available for it?

Feel free to remove, this is the safeguard for extreme low resources users.

**Comment by sudo6si** [comment]
Thanks for the explanation. Closing this as resolved.

**Comment by ksnijjer** [comment]
@xiangfu0 I would suggest that we get rid of this flag in default settings in first place, and simply add a highlighted note which recommends users to explicitly set this config as and when needed. WDYT ?

**Comment by xiangfu0** [comment]
I think we can have a reasonable default one and meanwhile prepare a few `values.yaml` recipes for different usages, e.g. values-dev.yaml or values-small,yaml, etc.

**Comment by ksnijjer** [comment]
That seems like a better approach, thanks @xiangfu0!
