### ISSUE TITLE
Add API for checking table rebalance status

### ISSUE THREAD

**Issue by dang-stripe** [apache/pinot#9558]
It'd be great to have an API to check rebalance status programmatically so we can automate rebalances. Currently the API always returns in-progress and requires checking the controller logs for status or checking external view / ideal state. https://github.com/apache/pinot/blob/master/pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotTableRestletResource.java#L677

**Comment by Jackie-Jiang** [comment]
One workaround for this is to run the rebalance in dry-run mode and check the response. If the response is no-op, that means the ideal state is already reaching the end state (external view might not converge yet).
We can add an API to apply similar idea, and also add extra check on whether the external view matches the ideal state.

**Comment by antwigambrah** [comment]
Hi @Jackie-Jiang please assign this to me . By the way , per the discussions  above running rebalance  returns IN_PROGRESS for the first time , when you run again in dry-mode=false , it should return no-op and when the idealstate=external view the status should be returned as done .

**Comment by Jackie-Jiang** [comment]
Thank @antwigambrah for volunteering. We should not run the rebalance in regular (non-dry) mode again when a previous one is in progress. If you run the dry-run mode again, it should return no-op when the rebalance already reach the end state.

**Comment by Jackie-Jiang** [comment]
Done with #10359
