### ISSUE TITLE
Add support for DISTINCTSUM and DISTINCTAVERAGE functions

### ISSUE THREAD

**Issue by vvivekiyer** [apache/pinot#9574]
Currently, pinot only supports using `COUNT` aggregation function on `DISTINCT`. This is supported in two ways:
1. DISTINCTCOUNT
2. COUNT(DISTINCT colA) 

https://github.com/apache/pinot/blob/e813867985746e916c8e898a530002551b661496/pinot-common/src/main/java/org/apache/pinot/sql/parsers/CalciteSqlParser.java#L788-L789

The ask in this issue to make pinot also support `SUM` and 'AVG' aggregation functions on `DISTINCT`. As mentioned above, this can be supported using two ways:
1. SUM(DISTINCT colA)  or AVG(DISTINCT colA)  ---> SQL friendly way
2. DISTINCTSUM or DISTINCTAVG

Similar support is offered by MySQL - https://dev.mysql.com/doc/refman/8.0/en/aggregate-functions.html#function_sum

**Comment by vvivekiyer** [comment]
I'm currently working on this.

**Comment by siddharthteotia** [comment]
cc @walterddr @Jackie-Jiang

**Comment by walterddr** [comment]
this is not something postgres supports (which is much closer following SQL standard) 
- only `COUNT(DISTINCT( colA [, colB]*)`

however given we already support DISTINCTCOUNT, it seems ok to support DISTINCTSUM as a dialect sugar to me

**Comment by siddharthteotia** [comment]
@vvivekiyer is working on this.

**Comment by siddharthteotia** [comment]
Support has been merged for `DISTINCTSUM` and `DISTINCTAVG` for SV columns. Support for MV columns will be done in a follow-up PR.

**Comment by vvivekiyer** [comment]
OSS issue for extending this support to MV columns https://github.com/apache/pinot/issues/10109
