### ISSUE TITLE
[multi-stage] Table join order

### ISSUE THREAD

**Issue by 61yao** [apache/pinot#9590]
The join table order has to be in the order of table size. i.e. table from the right hand side has to be smaller. 

@walterddr FYI.

**Comment by nizarhejazi** [comment]
@walterddr @61yao Any update on this task?

**Comment by walterddr** [comment]
i dont think this ticket is valid anymore. we have multiple ways to control the ordering of joins in SQL syntax (explicitly or implicitly) do you have any specific SQL situation in mind? please feel free to create a new ticket with details.
