### ISSUE TITLE
[multi-stage] NPE during nested loop joins

### ISSUE THREAD

**Issue by agavra** [apache/pinot#9592]
There's a bug where singletonInstance may be null in the case of a JOIN where one side is BROADCAST and the other is SINGLETON (this is the case with nested loop joins for inequality conditions). This causes NPEs in the logs, but actually works because the side that hits the NPE doesn't expect to get any data anyway (that's the side that gets the broadcast from one side but nothing from the SINGLETON)

https://github.com/apache/pinot/blob/d22b4678f5e4a0436f03ff7b0927ecaeaa7dc2c1/pinot-query-runtime/src/main/java/org/apache/pinot/query/runtime/operator/MailboxReceiveOperator.java#L75-L82

**Comment by walterddr** [comment]
this should be mitigated by https://github.com/apache/pinot/pull/9582#discussion_r996227427 and should eventually be fixed systematically by addressing this issue: https://github.com/apache/pinot/issues/9611
