### ISSUE TITLE
Missing information in pinot-realtime-quickstart.yml

### ISSUE THREAD

**Issue by jnorinder** [apache/pinot#9606]
Hi,

The file pinot-realtime-quickstart.yml needs to be updated. See attached file

As you can see I've added a copy of the schema (as airlineStatsAvro) and modified the definition of  airlineStatsAvro_realtime_table_config.json with schemaName: "airlineStatsAvro".

Also, I needed to change the following in the kubernetes/helm documentation:

```
kubectl -n pinot-quickstart exec kafka-0 -- kafka-topics --zookeeper kafka-zookeeper:2181 --topic flights-realtime --create --partitions 1 --replication-factor 1
kubectl -n pinot-quickstart exec kafka-0 -- kafka-topics --zookeeper kafka-zookeeper:2181 --topic flights-realtime-avro --create --partitions 1 --replication-factor 1
```

To:

```
kubectl -n pinot-quickstart exec kafka-0 -- kafka-topics.sh --bootstrap-server kafka-0:9092 --topic flights-realtime --create --partitions 1 --replication-factor 1
kubectl -n pinot-quickstart exec kafka-0 -- kafka-topics.sh --bootstrap-server kafka-0:9092 --topic flights-realtime-avro --create --partitions 1 --replication-factor 1
```

This made pinot a lot happier and no craschbackoffloop anymore. :-)

Hope this helps!

Regards,
Julius Norinder

[pinot-realtime-quickstart.txt](https://github.com/apache/pinot/files/9795280/pinot-realtime-quickstart.txt)

**Comment by Jackie-Jiang** [comment]
Thanks for reporting the issue and proposing the fix. Could you help create a PR and contribute this fix?

**Comment by jnorinder** [comment]
Hi,

Sure! I can give it a try.

Regards,
Julius
________________________________
Från: Xiaotian (Jackie) Jiang ***@***.***>
Skickat: den 18 oktober 2022 01:23
Till: apache/pinot ***@***.***>
Kopia: Julius Norinder ***@***.***>; Author ***@***.***>
Ämne: Re: [apache/pinot] Missing information in pinot-realtime-quickstart.yml (Issue #9606)


Thanks for reporting the issue and proposing the fix. Could you help create a PR and contribute this fix?
