### ISSUE TITLE
[multi-stage] [bug] aggregate node with group by key hash collision may produce wrong result

### ISSUE THREAD

**Issue by 61yao** [apache/pinot#9675]
AggregateNode is using hashcode as key for _groupByResultHolders and _groupByKeyHolder map. 
If > 1 keys have hashcode collision, only one will be used to produce results. 

@walterddr FYI

**Comment by walterddr** [comment]
yes this is possible. we need something similar to the `GroupKeyGenerator` used in leaf stage aggregate group by executor
