### ISSUE TITLE
Can we add compression configuration for functionColumnPairs to StartreeIndexConfigs?

### ISSUE THREAD

**Issue by priyen** [apache/pinot#9694]
I notice right now the Startree builder will not use any compression for metric columns. There is also no way to configure it, while in non-startree, you can do so via `noDictionaryConfig` field in the table config. 

I would like the ability to configure this for startree because when a `functionColumnPairs` has a output type of bytes, such as when you use `distinctcountrawhll`, the size is big.  For example, my test segment goes from 77 mb -> 3.3 GB if I add a startree, and it's because the bytes field output of that functionColumnPair is not compressed. In this case, I want the compression but right now there is no way to configure it

**Comment by t0mpere** [comment]
Hey I'm interested in this too. Did anyone look into this? It would be a game changer for us.

**Comment by Jackie-Jiang** [comment]
@priyen Have you started working on this? @t0mpere is volunteering to work on this

**Comment by jadami10** [comment]
we haven't prioritized work on this. Internally, we've changed this to always lz4 compress any byte columns. @t0mpere, feel free to take!

**Comment by t0mpere** [comment]
I'll prioritise this with my team. Probably picking it up in the upcoming weeks.
