### ISSUE TITLE
[flakytest] LLCRealtimeClusterIntegrationTest.testInvertedIndexTriggering

### ISSUE THREAD

**Issue by walterddr** [apache/pinot#9761]
https://github.com/apache/pinot/actions/runs/3419762999/jobs/5693691165
https://github.com/apache/pinot/actions/runs/3416093989/jobs/5685886707
https://github.com/apache/pinot/actions/runs/3390452918/jobs/5634615231

**Comment by Jackie-Jiang** [comment]
This is caused by a bug (or undesired behavior) in real-time freshness calculation: when a new consuming segment is created without consuming records from upstream, the freshness value will be reset to 0. This fails the check in the test
