### ISSUE TITLE
API for checking status of forceCommit for realtime tables

### ISSUE THREAD

**Issue by dang-stripe** [apache/pinot#9783]
We've leveraged the forceCommit API to minimize data ingestion lag before rebalances and other operations. It currently has no way of measuring status, aside from checking that external view + ideal state have converged on the realtime table after some timeframe.

@Jackie-Jiang suggested we can create a stateless API by exposing the earliest creation time of all consuming segments and poll that periodically.

**Comment by piyushchauhan** [comment]
I haven't used the forceCommit feature. But IMO forceCommit should trigger a job and job id should be returned. You can periodically check for the status of the job and decide accordingly.

**Comment by jadami10** [comment]
@Jackie-Jiang, I believe #10088 closes this
