### ISSUE TITLE
Logging Limit

### ISSUE THREAD

**Issue by abhs50** [apache/pinot#9788]
Currently 1 log on the broker is followed by N logs (1 per server). So every query gets N + 1 logs. For a high QPS system, this can turn into a lot of data. 

Reduce amount of logging in broker, server using a config. 

In addition to capping Log Rate at Query time, have a config to control Log Volume for segment ingestion as below

Consider exposing these as config : https://github.com/apache/pinot/blob/dcc496f63b4488989808ec144a7e2ffcc4697c75/pinot-core/src/main/java/org/apache/pinot/core/data/manager/realtime/LLRealtimeSegmentDataManager.java#L212

https://github.com/apache/pinot/blob/dcc496f63b4488989808ec144a7e2ffcc4697c75/pinot-core/src/main/java/org/apache/pinot/core/data/manager/realtime/LLRealtimeSegmentDataManager.java#L210

**Comment by Jackie-Jiang** [comment]
We already have some rate limit config, see `QueryLogger` class for details. Do you think we need to add more configs?

cc @agavra

**Comment by bagipriyank** [comment]
@Jackie-Jiang rate limiting option in `QueryLogger` is very helpful to limit the logs from broker. However right now, there is a log per query from each server that is involved in responding to the query. We are looking at options to reduce logging on the server side, and not just broker. 

We also want to look at reducing log volume from ingestion from kafka. Looks like options for controlling that are hard coded in the code right now as shared by @abhs50 above. It would be helpful to have them configurable.

**Comment by Jackie-Jiang** [comment]
On the server side, we have `pinot.query.scheduler.query.log.maxRatePerSecond` which is similar to the config on the broker side. More configs can be found here: https://docs.pinot.apache.org/configuration-reference/server

**Comment by abhs50** [comment]
Apologies for delay. @Jackie-Jiang : Is there a config which controls this : https://github.com/apache/pinot/blob/dcc496f63b4488989808ec144a7e2ffcc4697c75/pinot-core/src/main/java/org/apache/pinot/core/data/manager/realtime/LLRealtimeSegmentDataManager.java#L212

We see a bunch of logs in our server pods due to this [line](https://github.com/apache/pinot/blob/dcc496f63b4488989808ec144a7e2ffcc4697c75/pinot-core/src/main/java/org/apache/pinot/core/data/manager/realtime/LLRealtimeSegmentDataManager.java#L1575) :

**Comment by abhs50** [comment]
Additionally is there way to keep Pinot Server in Error logging mode instead of `info` by default. We are using helm installation way of deploying Pinot.

**Comment by Jackie-Jiang** [comment]
> Apologies for delay. @Jackie-Jiang : Is there a config which controls this :
> 
> https://github.com/apache/pinot/blob/dcc496f63b4488989808ec144a7e2ffcc4697c75/pinot-core/src/main/java/org/apache/pinot/core/data/manager/realtime/LLRealtimeSegmentDataManager.java#L212
> 
> We see a bunch of logs in our server pods due to this [line](https://github.com/apache/pinot/blob/dcc496f63b4488989808ec144a7e2ffcc4697c75/pinot-core/src/main/java/org/apache/pinot/core/data/manager/realtime/LLRealtimeSegmentDataManager.java#L1575) . We want to limit it to a lower value

Seems it is not configurable as of now. Do you want to help contribute a PR to make it configurable?

> Additionally is there way to keep Pinot Server in ERROR logging mode instead of INFO by default. We are using helm installation way of deploying Pinot.

@xiangfu0 do you know how to change the default logging level with helm installation? I think it is doable with a customized log4j config file?

**Comment by abhs50** [comment]
@Jackie-Jiang : Yes, I can work on an PR to make it configurable.

I will research more on logging config with helm installation.

**Comment by abhs50** [comment]
@Jackie-Jiang : This can be controlled via Helm envs as here : https://github.com/apache/pinot/blob/master/kubernetes/helm/pinot/values.yaml#L167

In that case we wont this MR and we are moving to ERROR logging only in production.
