### ISSUE TITLE
Add the support for DefaultAzureCredential for ADLSGen2PinotFS

### ISSUE THREAD

**Issue by snleee** [apache/pinot#9805]
Currently, S3PinotFS implementation falls back to initialize credential using `DefaultCredentialsProvider` when the access key and secret is not provided by the pinot config. In this way, we allow users to set env variables like `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`.

For ADLS Gen2 Pinot FS, we expect users to pass `accessKey` and `accountName` via pinot config. We should use default credential provider when those information is not given.

Some references to look:

https://learn.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-java?tabs=powershell%2Cmanaged-identity%2Croles-azure-portal%2Csign-in-azure-cli
https://blog.jongallant.com/2021/08/azure-identity-101/

**Comment by snleee** [comment]
@xiangfu0

**Comment by ceekay47** [comment]
Hi @snleee, is this still a valid issue? If so, can I pick this up?

**Comment by Jackie-Jiang** [comment]
I think this is supported with #9855. @snleee Can you please verify?

**Comment by wisercoder** [comment]
It appears to be supported, [see here](https://github.com/apache/pinot/blob/2ca35da2e6ebc12375471939a466c2e98131c2eb/pinot-plugins/pinot-file-system/pinot-adls/src/main/java/org/apache/pinot/plugin/filesystem/ADLSGen2PinotFS.java#L194C75-L194C104).

But it is not documented, [see here](https://docs.pinot.apache.org/basics/data-import/pinot-file-system/import-from-adls-azure).

**Comment by Jackie-Jiang** [comment]
@wisercoder Thanks for looking it up! Do you want to help contribute the documentation?
