### ISSUE TITLE
Improve the documentation on the new Date Time Formats

### ISSUE THREAD

**Issue by snleee** [apache/pinot#9809]
From 0.11.0, we have adopted the new date time formats (https://github.com/apache/pinot/pull/9378). We do have the documentations regarding to the new format; however, our schema (`flights-schema.json`) examples are using the old format. It would be great if we can add some more data time field with the new date time format in the example schema:

Document needs to be edited:
https://docs.pinot.apache.org/configuration-reference/schema
https://docs.pinot.apache.org/basics/components/schema

**Comment by snleee** [comment]
@KKcorps Can you take a look into this?

**Comment by KKcorps** [comment]
Cool, Will do that.

**Comment by KKcorps** [comment]
Updated 
https://app.gitbook.com/o/-LtRX9NwSr7Ga7zA4piL/s/-LtH6nl58DdnZnelPdTc-887967055/~/changes/eyzG3orTd7QY8YaUOtGe/basics/components/schema

https://app.gitbook.com/o/-LtRX9NwSr7Ga7zA4piL/s/-LtH6nl58DdnZnelPdTc-887967055/~/changes/eyzG3orTd7QY8YaUOtGe/configuration-reference/schema
