### ISSUE TITLE
Add gz compressed file support for `ORCRecordReader` and `ParquetAvroRecordReader`

### ISSUE THREAD

**Issue by snleee** [apache/pinot#9847]
Currently, many record reader implementation supports to read either raw file or gzip file as an input. For instance, csv record reader can understand both `data.csv` and `data.csv.gz`. 

Here are the list of record readers that we don't support `gz` compressed files :

1. ORCRecordReader
2. ParquetAvroRecordReader

**Comment by etolbakov** [comment]
hi @snleee 
happy to give this ticket a go if no one else is working on it.
