### ISSUE TITLE
[multistage] Add Support for Not-In Operator

### ISSUE THREAD

**Issue by ankitsultana** [apache/pinot#9867]
At present the following query doesn't work:

```
SELECT
  teamID
FROM
  baseballStats
WHERE
  teamID NOT IN (
    SELECT
      teamID
    FROM
      baseballStats
    WHERE
      hits > 10
  )
```

This gets converted to a left-join which is correct. However there a couple of issues:

1. The FilterOperand doesn't recognize the "IS NOT TRUE" function.
2. Projection for the table-scan is not pushed down, so the join ends up pulling in data for all the columns.

re: 2, it also hits a bug where the mailbox send operator receives a block which has 1 less column (teamID0 column) than expected.

This query can also benefit from colocated joins.

cc: @walterddr

**Comment by walterddr** [comment]
CC @agavra for the 1 less column - i believe this has to do with how the current pinot-broker reducers expects vs. how calcite expects. thus pinot-server instance response operator returns something not compatible.
