### ISSUE TITLE
Switching from raw index to dictionary encoding breaks REALTIME segments

### ISSUE THREAD

**Issue by Jackie-Jiang** [apache/pinot#9874]
#9454 introduces the feature to switch from raw index to dictionary encoding during segment reload. But for REALTIME table, the cardinality info is not available for raw index columns during stats collection, so we put Integer.MIN_VALUE as the cardinality in the segment metadata.
When switching from raw index to dictionary, the cardinality is not updated in the segment metadata, but it is required when loading the dictionary (see `BaseImmutableDictionary` for details). This is breaking the REALTIME segments.

**Comment by Jackie-Jiang** [comment]
@vvivekiyer Can you please take a look at this issue and see if my analysis is correct. cc @siddharthteotia

**Comment by vvivekiyer** [comment]
Looking into this.

**Comment by nizarhejazi** [comment]
@Jackie-Jiang @vvivekiyer any ETA for this fix?

**Comment by vvivekiyer** [comment]
I should be able to get this fix merged in the next couple of days.

**Comment by vvivekiyer** [comment]
This issue is fixed in PR #9875 @nizarhejazi 
@siddharthteotia can you please close this issue?

**Comment by siddharthteotia** [comment]
Thanks for the timely fix @vvivekiyer

**Comment by nizarhejazi** [comment]
Thanks @vvivekiyer
