### ISSUE TITLE
[Flaky-test] ZKOperatorTest.testMetadataUploadType

### ISSUE THREAD

**Issue by Jackie-Jiang** [apache/pinot#9897]
Error:  Failures: 
Error:    ZKOperatorTest.testMetadataUploadType:178 Failed to meet condition in 30000ms, error message: Failed to delete segmentZkMetadata.

Example run:
https://github.com/apache/pinot/actions/runs/3597915154/jobs/6060171582

**Comment by walterddr** [comment]
+1. another [INFO] org.apache.pinot.controller.helix.PinotControllerModeStatelessTest.testDualModeController  Time elapsed: 10.205 s
[INFO] org.apache.pinot.controller.helix.PinotControllerModeStatelessTest.testHelixOnlyController  Time elapsed: 3.716 s
[INFO] org.apache.pinot.controller.helix.PinotControllerModeStatelessTest.testPinotOnlyController  Time elapsed: 5.242 s
[INFO] 
[INFO] Results:
[INFO] 
Error:  Failures: 
Error:    ZKOperatorTest.testMetadataUploadType:178 Failed to meet condition in 30000ms, error message: Failed to delete segmentZkMetadata.

**Comment by Jackie-Jiang** [comment]
Reproduced and saw different IS and EV, but controller didn't schedule a message to drop the segment in EV.
This should be the same Helix bug as in https://github.com/apache/helix/issues/331, which is claimed to be fixed, so we removed the workaround in the test in #9634
