### ISSUE TITLE
[feature] Support coalesce for literals 

### ISSUE THREAD

**Issue by 61yao** [apache/pinot#9931]
Currently, coalesce only works for columns names. 

We can add literal support for this if we can tell whether a literal is null or not. 

@Jackie-Jiang

**Comment by etadelta222** [comment]
Hi @61yao , for our use case the literal would not be null. ex: coalesce([column],'string literal') if the [column] is null, use the 'string literal'. Purpose of the coalesce for us is to pass in a string literal when the actual column value is null.

**Comment by 61yao** [comment]
https://github.com/apache/pinot/pull/9958 Sent out the PR here.

**Comment by 61yao** [comment]
https://github.com/apache/pinot/pull/9958 got merged
