### ISSUE TITLE
[multistage] default group limit unable to override

### ISSUE THREAD

**Issue by walterddr** [apache/pinot#9970]
when InstancePlanMakerImplV2 makes query plan it puts 
```
_numGroupsLimit = config.getProperty(NUM_GROUPS_LIMIT_KEY, DEFAULT_NUM_GROUPS_LIMIT);
```
which is 100_000 by default. however this option is cluster-wide and cannot be overwritten by leaf-stage only on v2. This results in some high-cardinality group by queries produce incorrect results;
propose to create options for these static cluster-wide settings to be overwritten via query option:
CC @61yao also #9957

**Comment by snleee** [comment]
@walterddr Is https://github.com/apache/pinot/pull/9978 addressing this issue?

**Comment by walterddr** [comment]
not really. we also want to configure this on the fly using QueryOptions. not just cluster config.

**Comment by walterddr** [comment]
I think it is related to #9957
