### ISSUE TITLE
Auto clean up the dead broker and server instances if possible

### ISSUE THREAD

**Issue by xiangfu0** [apache/pinot#9992]
It's safe to delete a dead instance if no table/segment assigned.

So we can proactively clean up broker/server instances once it's dead for a while, could be one hour or one day

**Comment by xiangfu0** [comment]
https://github.com/apache/pinot/pull/10027

**Comment by jadami10** [comment]
@xiangfu0, any reason we didn't cleanup controllers in here as well?
